[workspace]
members = [
    "crates/dynwinrt",
    "bindings/js",
    "benchmarks/js/static-rust",
    "bindings/py",
    "tools/dynwinrt-codegen",
]
resolver = "2"

[workspace.package]
license = "MIT"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[profile.coverage]
inherits = "dev"
incremental = false
lto = false
codegen-units = 1
debug = 2
