// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! Pure JavaScript and declaration rendering for validated Classic-COM IR.

use std::collections::BTreeMap;

#[cfg(test)]
use super::super::ir::ProjectedComEnumMember;
use super::super::ir::{
    ActivationPlan, ComEnumUnderlying, ComParamDirection, ComReturnConvention, ComType,
    PointerAliasKind, ProjectedComEnum, ProjectedComInterface, ProjectedComMethod,
    ProjectedComMethodKind, ProjectedComParam, ProjectedEnumValue, ResultConversion,
    StringEncoding,
};
use super::naming::js_param_name;
use super::types::{
    abi_type_js, input_type_dts, result_type_dts, scalar_type_dts, unwrap_result_js, wrap_arg_js,
};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ComGeneratedOutput {
    pub js: String,
    pub dts: String,
    pub extra_files: Vec<(String, String)>,
}

pub(in crate::codegen::com) fn render_com_interface(
    meta: &ProjectedComInterface,
) -> ComGeneratedOutput {
    let js = render_js(meta);
    let dts = render_dts(meta);
    let mut extra_files = Vec::new();
    for en in &meta.referenced_enums {
        let (enum_js, enum_dts) = render_enum_files(en);
        extra_files.push((format!("{}.js", en.name), enum_js));
        extra_files.push((format!("{}.d.ts", en.name), enum_dts));
    }
    extra_files.sort_by(|a, b| a.0.cmp(&b.0));
    ComGeneratedOutput {
        js,
        dts,
        extra_files,
    }
}

fn render_js(meta: &ProjectedComInterface) -> String {
    let mut out = String::new();
    out.push_str("// Generated by dynwinrt-codegen — do not edit\n");
    let runtime_imports = if matches!(meta.activation, ActivationPlan::WinRtFactory { .. }) {
        "DynCom, DynComMethodSig, DynWinRtValue, WinGuid"
    } else {
        "DynCom, DynComMethodSig, WinGuid"
    };
    out.push_str(&format!(
        "import {{ {runtime_imports} }} from '{}';\n",
        com_runtime_import_name()
    ));
    for en in &meta.referenced_enums {
        out.push_str(&format!(
            "import {{ {} }} from './{}.js';\n",
            en.name, en.name
        ));
    }
    out.push('\n');
    if meta
        .methods
        .iter()
        .any(|method| method.string_buffer.is_some())
    {
        out.push_str("function _normalizeStringBufferCount(value, name) {\n");
        out.push_str("    if (!Number.isInteger(value) || value <= 0) throw new TypeError(`${name} must be a positive integer`);\n");
        out.push_str("    return value;\n}\n");
        out.push_str("function _decodeWideString(buffer) {\n    let end = 0;\n");
        out.push_str(
            "    while (end + 1 < buffer.length && buffer.readUInt16LE(end) !== 0) end += 2;\n",
        );
        out.push_str("    return buffer.subarray(0, end).toString('utf16le');\n}\n\n");
    }
    out.push_str(&format!(
        "export const IID_{} = WinGuid.parse('{}');\n",
        meta.name, meta.iid
    ));
    if let ActivationPlan::WinRtFactory {
        class_name,
        target_iid,
        ..
    } = &meta.activation
    {
        out.push_str(&format!(
            "const IID_{class_name}_default = WinGuid.parse('{target_iid}');\n"
        ));
    }
    out.push('\n');
    let register_fn = if meta.is_iunknown_rooted {
        "registerIUnknownInterface"
    } else {
        "registerIInspectableInterface"
    };
    let cache_var = format!("_{}Cache", meta.name);
    let iface_var = format!("_{}", meta.name);
    out.push_str(&format!("let {cache_var};\n"));
    out.push_str(&format!(
        "const {iface_var} = new Proxy({{}}, {{\n    get(_target, prop) {{\n        {cache_var} ??= DynCom.{register_fn}('{}.{}', IID_{})\n",
        meta.namespace, meta.name, meta.name
    ));
    for method in &meta.methods {
        out.push_str(&format!(
            "            .addMethod('{}', {})\n",
            method.name,
            build_method_sig_js(method)
        ));
    }
    if out.ends_with('\n') {
        out.pop();
    }
    out.push_str(";\n");
    out.push_str(&format!("        const value = {cache_var}[prop];\n        return typeof value === 'function' ? value.bind({cache_var}) : value;\n    }},\n}});\n\n"));
    out.push_str(&format!("export class {} {{\n", meta.name));
    out.push_str("    _obj;\n    constructor(obj) { this._obj = obj; }\n");
    out.push_str(&format!(
        "    static _fromNative(obj) {{ return new {}(obj); }}\n",
        meta.name
    ));
    match &meta.activation {
        ActivationPlan::None => {}
        ActivationPlan::Coclass {
            clsid,
            coclass_name,
        } => {
            out.push_str(&format!(
                "    /** Create a new `{}` via `CoCreateInstance` on `CLSID_{coclass_name}`. */\n",
                meta.name
            ));
            out.push_str(&format!("    static create() {{\n        const _obj = DynCom.coCreateInstance('{clsid}', IID_{});\n        return new {}(_obj);\n    }}\n", meta.name, meta.name));
        }
        ActivationPlan::WinRtFactory {
            class_name,
            class_namespace,
            ..
        } => {
            let full = format!("{class_namespace}.{class_name}");
            out.push_str(&format!("    /** Create a new `{}` by activating the `{full}` factory and QI'ing to the interop. */\n", meta.name));
            out.push_str(&format!("    static create() {{\n        const factory = DynWinRtValue.activationFactory('{full}');\n        const _obj = factory.cast(IID_{});\n        return new {}(_obj);\n    }}\n", meta.name, meta.name));
        }
    }
    for method in &meta.methods {
        match method.kind {
            ProjectedComMethodKind::Normal => emit_method_js(&mut out, method, &iface_var),
            ProjectedComMethodKind::CallerSuppliedDynamicIid {
                natural_param_count,
            } => emit_dynamic_iid_method_js(&mut out, method, natural_param_count, &iface_var),
            ProjectedComMethodKind::SynthesizedGetForWindow {
                natural_param_count,
                ref target_iid,
            } => emit_synthesized_interop_method_js(
                &mut out,
                method,
                natural_param_count,
                target_iid,
                &iface_var,
                meta,
            ),
        }
    }
    out.push_str("}\n");
    out
}

fn build_method_sig_js(method: &ProjectedComMethod) -> String {
    let mut parts = Vec::new();
    for (index, param) in method.params.iter().enumerate() {
        match param.direction {
            ComParamDirection::In => parts.push(format!(".addIn({})", abi_type_js(&param.typ))),
            ComParamDirection::InOut => {
                parts.push(format!(".addInOut({})", abi_type_js(&param.typ)))
            }
            ComParamDirection::OutStringBuffer => parts.push(".addIn(DynCom.pointerType())".into()),
            ComParamDirection::Out => {
                if method.string_buffer.as_ref().is_some_and(|plan| {
                    index > plan.count_param_index && plan.optional_param_indices.contains(&index)
                }) {
                    parts.push(".addIn(DynCom.pointerType())".into());
                } else {
                    parts.push(format!(".addOut({})", abi_type_js(&param.typ)));
                }
            }
        }
    }
    match &method.return_convention {
        ComReturnConvention::HResult => {}
        ComReturnConvention::SemanticHResult => parts.push(".preserveHresult()".into()),
        ComReturnConvention::Void => parts.push(".returnsVoid()".into()),
        ComReturnConvention::Direct(typ) => parts.push(format!(".returns({})", abi_type_js(typ))),
    }
    if parts.is_empty() {
        "new DynComMethodSig()".into()
    } else {
        format!("new DynComMethodSig(){}", parts.join(""))
    }
}

fn input_params(method: &ProjectedComMethod) -> Vec<(usize, &ProjectedComParam)> {
    method
        .params
        .iter()
        .enumerate()
        .filter(|(_, param)| param.direction.is_input())
        .collect()
}

fn emit_method_js(out: &mut String, method: &ProjectedComMethod, iface_var: &str) {
    let inputs = input_params(method);
    let params = inputs
        .iter()
        .enumerate()
        .map(|(surface, (index, param))| {
            let name = js_param_name(&param.name, surface);
            if let Some(plan) = &method.string_buffer {
                if plan.optional_param_indices.contains(index) {
                    return if *index == plan.count_param_index {
                        format!("{name} = 260")
                    } else {
                        format!("{name} = 0")
                    };
                }
            }
            name
        })
        .collect::<Vec<_>>();
    out.push_str(&format!(
        "    {}({}) {{\n",
        method.camel_name,
        params.join(", ")
    ));
    if let Some(plan) = &method.string_buffer {
        emit_string_buffer_method_body(out, method, plan, &inputs, iface_var);
        out.push_str("    }\n");
        return;
    }
    let args = inputs
        .iter()
        .enumerate()
        .map(|(surface, (_, param))| wrap_arg_js(&param.typ, &js_param_name(&param.name, surface)))
        .collect::<Vec<_>>();
    emit_invocation_and_results(out, method, iface_var, &args);
    out.push_str("    }\n");
}

fn emit_string_buffer_method_body(
    out: &mut String,
    method: &ProjectedComMethod,
    plan: &super::super::ir::StringBufferPlan,
    inputs: &[(usize, &ProjectedComParam)],
    iface_var: &str,
) {
    let count_surface = inputs
        .iter()
        .position(|(index, _)| *index == plan.count_param_index)
        .expect("validated count input");
    let count_name = js_param_name(&method.params[plan.count_param_index].name, count_surface);
    if plan.encoding == StringEncoding::Ansi {
        out.push_str("        throw new Error('PSTR out buffers are not yet decoded safely');\n");
        return;
    }
    let args = method
        .params
        .iter()
        .enumerate()
        .filter_map(|(index, param)| {
            if index == plan.buffer_param_index {
                Some("DynCom.pointer(_buffer)".into())
            } else if param.direction.is_input() {
                let surface = inputs
                    .iter()
                    .position(|(input_index, _)| *input_index == index)
                    .expect("validated input");
                Some(wrap_arg_js(
                    &param.typ,
                    &js_param_name(&param.name, surface),
                ))
            } else if index > plan.count_param_index && plan.optional_param_indices.contains(&index)
            {
                Some("DynCom.pointer(0n)".into())
            } else {
                None
            }
        })
        .collect::<Vec<_>>();
    out.push_str(&format!(
        "        {count_name} = _normalizeStringBufferCount({count_name}, '{count_name}');\n"
    ));
    out.push_str(&format!(
        "        const _buffer = Buffer.alloc({count_name} * 2);\n"
    ));
    match method.results.len() {
        0 => out.push_str(&format!(
            "        {iface_var}.method({}).invoke(this._obj, [{}]);\n",
            method.vtable_index,
            args.join(", ")
        )),
        1 => out.push_str(&format!(
            "        const _out = {iface_var}.method({}).invoke(this._obj, [{}]);\n",
            method.vtable_index,
            args.join(", ")
        )),
        _ => out.push_str(&format!(
            "        const _out = {iface_var}.method({}).invokeAll(this._obj, [{}]);\n",
            method.vtable_index,
            args.join(", ")
        )),
    }
    out.push_str("        const _text = _decodeWideString(_buffer);\n");
    match method.results.len() {
        0 => out.push_str("        return _text;\n"),
        1 => out.push_str(&format!(
            "        return [_text, {}];\n",
            unwrap_result_js(&method.results[0], "_out")
        )),
        _ => {
            let values = method
                .results
                .iter()
                .enumerate()
                .map(|(index, result)| unwrap_result_js(result, &format!("_out[{index}]")))
                .collect::<Vec<_>>();
            out.push_str(&format!("        return [_text, {}];\n", values.join(", ")));
        }
    }
}

fn emit_invocation_and_results(
    out: &mut String,
    method: &ProjectedComMethod,
    iface_var: &str,
    args: &[String],
) {
    match method.results.len() {
        0 => out.push_str(&format!(
            "        {iface_var}.method({}).invoke(this._obj, [{}]);\n",
            method.vtable_index,
            args.join(", ")
        )),
        1 => {
            out.push_str(&format!(
                "        const _out = {iface_var}.method({}).invoke(this._obj, [{}]);\n",
                method.vtable_index,
                args.join(", ")
            ));
            out.push_str(&format!(
                "        return {};\n",
                unwrap_result_js(&method.results[0], "_out")
            ));
        }
        _ => {
            out.push_str(&format!(
                "        const _r = {iface_var}.method({}).invokeAll(this._obj, [{}]);\n",
                method.vtable_index,
                args.join(", ")
            ));
            let values = method
                .results
                .iter()
                .enumerate()
                .map(|(index, result)| unwrap_result_js(result, &format!("_r[{index}]")))
                .collect::<Vec<_>>();
            out.push_str(&format!("        return [{}];\n", values.join(", ")));
        }
    }
}

fn emit_dynamic_iid_method_js(
    out: &mut String,
    method: &ProjectedComMethod,
    natural_count: usize,
    iface_var: &str,
) {
    let natural = &method.params[..natural_count];
    let mut surface = natural
        .iter()
        .enumerate()
        .map(|(index, param)| js_param_name(&param.name, index))
        .collect::<Vec<_>>();
    surface.push("iid".into());
    let mut args = natural
        .iter()
        .enumerate()
        .map(|(index, param)| wrap_arg_js(&param.typ, &js_param_name(&param.name, index)))
        .collect::<Vec<_>>();
    args.push("DynCom.iidPointer(_iid)".into());
    out.push_str(&format!(
        "    {}({}) {{\n        const _iid = WinGuid.parse(iid);\n",
        method.camel_name,
        surface.join(", ")
    ));
    out.push_str(&format!(
        "        const _raw = {iface_var}.method({}).invoke(this._obj, [{}]);\n",
        method.vtable_index,
        args.join(", ")
    ));
    out.push_str("        return DynCom.adoptComPointer(_raw, _iid);\n    }\n");
}

fn emit_synthesized_interop_method_js(
    out: &mut String,
    method: &ProjectedComMethod,
    natural_count: usize,
    _target_iid: &str,
    iface_var: &str,
    meta: &ProjectedComInterface,
) {
    let natural = &method.params[..natural_count];
    let params = natural
        .iter()
        .enumerate()
        .map(|(index, param)| js_param_name(&param.name, index))
        .collect::<Vec<_>>();
    let mut args = natural
        .iter()
        .enumerate()
        .map(|(index, param)| wrap_arg_js(&param.typ, &js_param_name(&param.name, index)))
        .collect::<Vec<_>>();
    let class_name = match &meta.activation {
        ActivationPlan::WinRtFactory { class_name, .. } => class_name,
        _ => unreachable!("validated interop activation"),
    };
    args.push(format!("DynCom.iidPointer(IID_{class_name}_default)"));
    out.push_str(&format!(
        "    {}({}) {{\n",
        method.camel_name,
        params.join(", ")
    ));
    out.push_str(&format!(
        "        const _raw = {iface_var}.method({}).invoke(this._obj, [{}]);\n",
        method.vtable_index,
        args.join(", ")
    ));
    out.push_str(&format!("        const _out = DynCom.adoptComPointer(_raw, IID_{class_name}_default);\n        return _out;\n    }}\n"));
}

fn render_dts(meta: &ProjectedComInterface) -> String {
    let mut out = String::new();
    out.push_str("// Generated by dynwinrt-codegen — do not edit\n");
    for en in &meta.referenced_enums {
        out.push_str(&format!(
            "import {{ {} }} from './{}.js';\n",
            en.name, en.name
        ));
    }
    if needs_bridge_import(meta) {
        out.push_str(&format!(
            "import type {{ DynWinRtValue }} from '{}';\n",
            com_runtime_import_name()
        ));
    }
    out.push('\n');
    for (name, underlying) in collect_scalar_aliases(meta) {
        out.push_str(&format!(
            "/** Transparent Win32 scalar typedef. */\nexport type {name} = {};\n",
            scalar_type_dts(underlying)
        ));
    }
    if !collect_scalar_aliases(meta).is_empty() {
        out.push('\n');
    }
    for (name, kind) in collect_pointer_aliases(meta) {
        match kind {
            PointerAliasKind::HandleValue => out.push_str(&format!("/** Opaque Win32 handle value. Pass a raw pointer value as a `bigint` (full pointer width) or `number` (safe integer). */\nexport type {name} = bigint | number;\n")),
            PointerAliasKind::DataPointer => out.push_str(&format!("/** Opaque native data address. Inputs may also use a `Buffer`/`Uint8Array`, whose backing-store address is passed and retained for the call. */\nexport type {name} = bigint | number;\n")),
            PointerAliasKind::StringPointer => out.push_str(&format!("/** Win32 NUL-terminated string pointer. Pass a `Buffer` holding the string bytes (including the NUL terminator), or pass a raw pointer as `bigint`. */\nexport type {name} = bigint | Buffer;\n")),
        }
    }
    if !collect_pointer_aliases(meta).is_empty() {
        out.push('\n');
    }
    out.push_str(&format!(
        "export declare const IID_{}: unknown;\n\nexport declare class {} {{\n",
        meta.name, meta.name
    ));
    match &meta.activation {
        ActivationPlan::None => {}
        ActivationPlan::Coclass { .. } => out.push_str(&format!(
            "    /** Create a new instance via the coclass activation path. */\n    static create(): {};\n",
            meta.name
        )),
        ActivationPlan::WinRtFactory { .. } => out.push_str(&format!(
            "    /** Activate the projected WinRT class and QI to the interop. */\n    static create(): {};\n",
            meta.name
        )),
    }
    out.push_str(&format!("    /** Wrap an existing native COM pointer (for QueryInterface bridging). */\n    static _fromNative(obj: unknown): {};\n", meta.name));
    for method in &meta.methods {
        let (params, ret) = match method.kind {
            ProjectedComMethodKind::Normal => (dts_params(method), dts_return_type(method)),
            ProjectedComMethodKind::CallerSuppliedDynamicIid {
                natural_param_count,
            } => {
                let mut params = dts_natural_params(method, natural_param_count);
                params.push("iid: string".into());
                (params, "DynWinRtValue".into())
            }
            ProjectedComMethodKind::SynthesizedGetForWindow {
                natural_param_count,
                ..
            } => (
                dts_natural_params(method, natural_param_count),
                "DynWinRtValue".into(),
            ),
        };
        out.push_str(&format!(
            "    {}({}): {};\n",
            method.camel_name,
            params.join(", "),
            ret
        ));
    }
    out.push_str("}\n");
    out
}

fn dts_natural_params(method: &ProjectedComMethod, count: usize) -> Vec<String> {
    method.params[..count]
        .iter()
        .enumerate()
        .map(|(index, param)| {
            format!(
                "{}: {}",
                js_param_name(&param.name, index),
                input_type_dts(&param.typ)
            )
        })
        .collect()
}

fn dts_params(method: &ProjectedComMethod) -> Vec<String> {
    method
        .params
        .iter()
        .enumerate()
        .filter(|(_, param)| param.direction.is_input())
        .enumerate()
        .map(|(surface, (index, param))| {
            let mut name = js_param_name(&param.name, surface);
            if method
                .string_buffer
                .as_ref()
                .is_some_and(|plan| plan.optional_param_indices.contains(&index))
            {
                name.push('?');
            }
            format!("{name}: {}", input_type_dts(&param.typ))
        })
        .collect()
}

fn dts_return_type(method: &ProjectedComMethod) -> String {
    if method.string_buffer.is_some() {
        return if method.results.is_empty() {
            "string".into()
        } else {
            format!(
                "[string, {}]",
                method
                    .results
                    .iter()
                    .map(result_type_dts)
                    .collect::<Vec<_>>()
                    .join(", ")
            )
        };
    }
    match method.results.len() {
        0 => "void".into(),
        1 => result_type_dts(&method.results[0]),
        _ => format!(
            "[{}]",
            method
                .results
                .iter()
                .map(result_type_dts)
                .collect::<Vec<_>>()
                .join(", ")
        ),
    }
}

fn collect_pointer_aliases(meta: &ProjectedComInterface) -> Vec<(String, PointerAliasKind)> {
    let mut aliases = BTreeMap::new();
    for method in &meta.methods {
        for typ in
            method
                .params
                .iter()
                .map(|param| &param.typ)
                .chain(match &method.return_convention {
                    ComReturnConvention::Direct(typ) => Some(typ),
                    _ => None,
                })
        {
            match typ {
                ComType::PointerAlias { name, kind } => {
                    aliases.insert(name.clone(), *kind);
                }
                ComType::Bstr => {
                    aliases.insert("BSTR".into(), PointerAliasKind::HandleValue);
                }
                ComType::Primitive(_)
                | ComType::NativeIsize
                | ComType::NativeUsize
                | ComType::Win32Bool
                | ComType::HResult
                | ComType::Guid
                | ComType::HString
                | ComType::Enum { .. }
                | ComType::ScalarAlias { .. }
                | ComType::RawPointer
                | ComType::ManagedInterface { .. } => {}
            }
        }
    }
    aliases.into_iter().collect()
}

fn collect_scalar_aliases(
    meta: &ProjectedComInterface,
) -> Vec<(String, super::super::ir::ComScalarRepr)> {
    let mut aliases = BTreeMap::new();
    for method in &meta.methods {
        for typ in
            method
                .params
                .iter()
                .map(|param| &param.typ)
                .chain(match &method.return_convention {
                    ComReturnConvention::Direct(typ) => Some(typ),
                    _ => None,
                })
        {
            if let ComType::ScalarAlias { name, underlying } = typ {
                aliases.insert(name.clone(), *underlying);
            }
        }
    }
    aliases.into_iter().collect()
}

fn needs_bridge_import(meta: &ProjectedComInterface) -> bool {
    matches!(meta.activation, ActivationPlan::WinRtFactory { .. })
        || meta.methods.iter().any(|method| {
            !matches!(method.kind, ProjectedComMethodKind::Normal)
                || method
                    .params
                    .iter()
                    .any(|param| matches!(param.typ, ComType::ManagedInterface { .. }))
                || method.results.iter().any(|result| {
                    matches!(
                        result.conversion,
                        ResultConversion::ManagedCom
                            | ResultConversion::CoTaskMemData
                            | ResultConversion::DynamicIidAdoption
                    )
                })
        })
}

fn com_runtime_import_name() -> String {
    let import_name = crate::codegen::project::get_import_name();
    if import_name == "@microsoft/dynwinrt" {
        format!("{import_name}/com")
    } else {
        import_name
    }
}

fn render_enum_files(en: &ProjectedComEnum) -> (String, String) {
    let mut js = String::from("// Generated by dynwinrt-codegen — do not edit\n");
    js.push_str(&format!("export const {} = Object.freeze({{\n", en.name));
    for member in &en.members {
        js.push_str(&format!(
            "    {}: {},\n",
            member.name,
            render_enum_value(&member.value, en.underlying)
        ));
    }
    js.push_str("});\n");
    let mut dts = String::from("// Generated by dynwinrt-codegen — do not edit\n");
    dts.push_str(&format!(
        "export type {} = (typeof {})[keyof typeof {}];\n",
        en.name, en.name, en.name
    ));
    dts.push_str(&format!("export declare const {}: {{\n", en.name));
    for member in &en.members {
        dts.push_str(&format!(
            "    readonly {}: {};\n",
            member.name,
            render_enum_value(&member.value, en.underlying)
        ));
    }
    dts.push_str("};\n");
    (js, dts)
}

fn render_enum_value(value: &ProjectedEnumValue, underlying: ComEnumUnderlying) -> String {
    let suffix = if matches!(underlying, ComEnumUnderlying::I64 | ComEnumUnderlying::U64) {
        "n"
    } else {
        ""
    };
    match value {
        ProjectedEnumValue::Signed(value) => format!("{value}{suffix}"),
        ProjectedEnumValue::Unsigned(value) => format!("{value}{suffix}"),
    }
}

#[cfg(test)]
#[path = "render_tests.rs"]
mod tests;
