// Generated by dynwinrt-codegen — do not edit
import type { WinGuid } from '@microsoft/dynwinrt/com';
import { SHOW_WINDOW_CMD } from '../windows-and-messaging/SHOW_WINDOW_CMD.js';
import type { DynWinRtValue } from '@microsoft/dynwinrt/com';
import type { DynComNativeStruct } from '@microsoft/dynwinrt/com';

/** Opaque Win32 handle value. Pass a raw pointer value as a `bigint` (full pointer width) or `number` (safe integer). */
export type HWND = bigint | number;
/** Win32 NUL-terminated string pointer. Pass a JS `string` (encoded automatically), or a `Buffer`/`Uint8Array` holding UTF-16LE bytes including the NUL terminator. Arbitrary numeric addresses require the explicit unsafe runtime. */
export type PWSTR = string | Buffer | Uint8Array;

/** Validated native POD bytes (Windows.Win32.Storage.FileSystem-specific size selected at runtime). */
export type WIN32_FIND_DATAW = DynComNativeStruct & { readonly __dynComNativeStructLayout: 'Windows.Win32.Storage.FileSystem.WIN32_FIND_DATAW' };
export declare function createWIN32_FIND_DATAW(bytes?: Buffer): WIN32_FIND_DATAW;

export declare const IID_IShellLinkW: WinGuid;

export declare class IShellLinkW {
    static readonly IID: typeof IID_IShellLinkW;
    protected constructor(obj: unknown);
    /** Wrap an existing native COM pointer (for QueryInterface bridging). */
    static _fromNative(obj: unknown): IShellLinkW;
    /** Release the underlying native COM reference. Safe to call more than once. */
    release(): void;
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-ishelllinkw-getpath} */
    getPath(cch: number, pfd: WIN32_FIND_DATAW | null, fFlags: number): [string, WIN32_FIND_DATAW | null];
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-ishelllinkw-getidlist} */
    getIDList(): DynWinRtValue;
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-ishelllinkw-setidlist} */
    setIDList(pidl: Buffer | Uint8Array): void;
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-ishelllinkw-getdescription} */
    getDescription(cch?: number): string;
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-ishelllinkw-setdescription} */
    setDescription(name: PWSTR): void;
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-ishelllinkw-getworkingdirectory} */
    getWorkingDirectory(cch?: number): string;
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-ishelllinkw-setworkingdirectory} */
    setWorkingDirectory(dir: PWSTR): void;
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-ishelllinkw-getarguments} */
    getArguments(cch?: number): string;
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-ishelllinkw-setarguments} */
    setArguments(args: PWSTR): void;
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-ishelllinkw-gethotkey} */
    getHotkey(): number;
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-ishelllinkw-sethotkey} */
    setHotkey(wHotkey: number): void;
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-ishelllinkw-getshowcmd} */
    getShowCmd(): SHOW_WINDOW_CMD;
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-ishelllinkw-setshowcmd} */
    setShowCmd(iShowCmd: SHOW_WINDOW_CMD): void;
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-ishelllinkw-geticonlocation} */
    getIconLocation(cch?: number): [string, number];
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-ishelllinkw-seticonlocation} */
    setIconLocation(iconPath: PWSTR, iIcon: number): void;
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-ishelllinkw-setrelativepath} */
    setRelativePath(pathRel: PWSTR, reserved: number): void;
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-ishelllinkw-resolve} */
    resolve(hwnd: HWND | Buffer | Uint8Array, fFlags: number): void;
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-ishelllinkw-setpath} */
    setPath(file: PWSTR): void;
}
