// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! Classic-COM (option A) code generation.
//!
//! This module generates natural TypeScript/JS wrappers for IUnknown-rooted
//! Win32 COM interfaces described in Windows.Win32.winmd. It intentionally
//! keeps a **separate pipeline** from the WinRT projection: classic COM has
//! meaningfully different semantics (IUnknown base offset of 3 vs 6, HRESULT
//! throw-on-failure, `CoCreateInstance` activation, no IReference/async
//! projection) so mixing them into the existing IR would obscure both paths.
//!
//! What we emit today (phase 1):
//! - `<InterfaceName>.js`: registration via `DynWinRtType.registerInterfaceUnknown`
//!   + a natural class with camelCase methods and static `create()` /
//!   `_fromNative()`.
//! - `<InterfaceName>.d.ts`: PascalCase class, camelCase methods, opaque
//!   handle typedefs (HWND etc.) as `bigint | Buffer`, HRESULT returns
//!   projected to `void` (throwing on failure via the runtime).
//! - Per-enum sibling files for each enum referenced by any method parameter.

use std::collections::BTreeSet;

use crate::meta::{ComInterfaceMeta, MethodMeta, ParamDirection, ParamMeta};
use crate::types::TypeMeta;

/// A rendered classic-COM output: primary `.js` + `.d.ts` for the interface,
/// plus zero or more sibling files (one `.js` + `.d.ts` per referenced enum).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ComGeneratedOutput {
    pub js: String,
    pub dts: String,
    /// Additional files (filename → content). Includes each enum's `.js` and
    /// `.d.ts`. Stable-sorted by filename for deterministic output.
    pub extra_files: Vec<(String, String)>,
}

// ---------------------------------------------------------------------------
// Public entry
// ---------------------------------------------------------------------------

/// Generate the `.js` + `.d.ts` for a classic-COM interface.
///
/// `winmd_paths` is retained (rather than removed) so that a follow-up phase
/// can resolve additional deeply nested dependencies (structs, delegate
/// interfaces) without a signature churn. For phase 1, only direct enum
/// references discovered during `parse_com_interface` are emitted.
pub fn generate_com_interface_files(
    meta: &ComInterfaceMeta,
    _winmd_paths: &str,
) -> ComGeneratedOutput {
    let js = render_js(meta);
    let dts = render_dts(meta);

    // Per-enum sibling files (referenced by parameter types).
    let mut extra_files: Vec<(String, String)> = Vec::new();
    for en in &meta.referenced_enums {
        if let TypeMeta::Enum { name, .. } = en {
            let (enum_js, enum_dts) = render_enum_files(en);
            extra_files.push((format!("{}.js", name), enum_js));
            extra_files.push((format!("{}.d.ts", name), enum_dts));
        }
    }
    extra_files.sort_by(|a, b| a.0.cmp(&b.0));

    ComGeneratedOutput { js, dts, extra_files }
}

// ---------------------------------------------------------------------------
// .js rendering
// ---------------------------------------------------------------------------

fn render_js(meta: &ComInterfaceMeta) -> String {
    let iface = &meta.interface;
    let iid = &iface.iid;
    let name = &iface.name;

    let mut out = String::new();
    out.push_str("// Generated by dynwinrt-codegen — do not edit\n");

    // Imports (runtime + any referenced enums)
    out.push_str("import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, WinGuid } from '@microsoft/dynwinrt';\n");
    for en in enum_import_names(meta) {
        out.push_str(&format!("import {{ {} }} from './{}.js';\n", en, en));
    }
    out.push('\n');

    out.push_str(&format!(
        "export const IID_{name} = WinGuid.parse('{iid}');\n",
        name = name,
        iid = iid
    ));
    out.push('\n');

    // Interface registration (lazy)
    let cache_var = format!("_{name}Cache", name = name);
    let iface_var = format!("_{name}", name = name);
    out.push_str(&format!("let {cache_var};\n", cache_var = cache_var));
    out.push_str(&format!(
        "const {iface_var} = new Proxy({{}}, {{\n    get(_target, prop) {{\n        {cache_var} ??= DynWinRtType.registerInterfaceUnknown('{name}', IID_{name})\n",
        iface_var = iface_var,
        cache_var = cache_var,
        name = name,
    ));
    for m in &iface.methods {
        out.push_str(&format!(
            "            .addMethod('{}', {})\n",
            m.name,
            build_method_sig_js(m)
        ));
    }
    // Trim trailing newline before closing the block, then close.
    if out.ends_with('\n') {
        out.truncate(out.len() - 1);
    }
    out.push_str(";\n");
    out.push_str(&format!(
        "        const value = {cache_var}[prop];\n        return typeof value === 'function' ? value.bind({cache_var}) : value;\n    }},\n}});\n",
        cache_var = cache_var,
    ));
    out.push('\n');

    // Class body
    out.push_str(&format!("export class {name} {{\n", name = name));
    out.push_str("    _obj;\n");
    out.push_str("    constructor(obj) { this._obj = obj; }\n");
    out.push_str(&format!(
        "    static _fromNative(obj) {{ return new {name}(obj); }}\n",
        name = name
    ));

    if let Some(ref clsid) = meta.coclass_clsid {
        // static create()
        out.push_str(&format!(
            "    /** Create a new `{name}` via `CoCreateInstance` on `CLSID_{cc}`. */\n",
            name = name,
            cc = meta.coclass_name.as_deref().unwrap_or("Coclass")
        ));
        out.push_str(&format!(
            "    static create() {{\n        const _obj = DynWinRtValue.coCreateInstance('{clsid}', IID_{name});\n        return new {name}(_obj);\n    }}\n",
            clsid = clsid,
            name = name,
        ));
    }

    for m in &iface.methods {
        emit_method_js(&mut out, m, &iface_var);
    }
    out.push_str("}\n");
    out
}

fn build_method_sig_js(m: &MethodMeta) -> String {
    let mut parts = Vec::new();
    for p in &m.params {
        if p.direction == ParamDirection::In {
            parts.push(format!(".addIn({})", ts_type_expr_js(&p.typ)));
        } else if p.direction == ParamDirection::Out {
            parts.push(format!(".addOut({})", ts_type_expr_js(&p.typ)));
        } else if p.direction == ParamDirection::OutFill {
            parts.push(format!(".addOutFill({})", ts_type_expr_js(&p.typ)));
        }
    }
    // Return type of a classic-COM HRESULT method is NOT part of the sig —
    // the runtime swallows HRESULT and throws on failure. Only non-HRESULT
    // returns are recorded (rare; e.g. IClassFactory::CreateInstance uses
    // HRESULT, so most Win32 methods land here).
    if let Some(ref rt) = m.return_type {
        if !is_hresult(rt) {
            parts.push(format!(".addOut({})", ts_type_expr_js(rt)));
        }
    }
    if parts.is_empty() {
        "new DynWinRtMethodSig()".to_string()
    } else {
        format!("new DynWinRtMethodSig(){}", parts.join(""))
    }
}

fn emit_method_js(out: &mut String, m: &MethodMeta, iface_var: &str) {
    let camel = camel_case(&m.name);
    let in_params: Vec<&ParamMeta> = m
        .params
        .iter()
        .filter(|p| p.direction == ParamDirection::In)
        .collect();
    let param_list: Vec<String> = in_params
        .iter()
        .enumerate()
        .map(|(i, p)| js_param_name(&p.name, i))
        .collect();

    let args_exprs: Vec<String> = in_params
        .iter()
        .enumerate()
        .map(|(i, p)| wrap_arg_js(&p.typ, &js_param_name(&p.name, i)))
        .collect();

    out.push_str(&format!(
        "    {camel}({params}) {{\n",
        camel = camel,
        params = param_list.join(", ")
    ));
    out.push_str(&format!(
        "        {iface_var}.method({slot}).invoke(this._obj, [{args}]);\n",
        iface_var = iface_var,
        slot = m.vtable_index,
        args = args_exprs.join(", ")
    ));
    out.push_str("    }\n");
}

// ---------------------------------------------------------------------------
// .d.ts rendering
// ---------------------------------------------------------------------------

fn render_dts(meta: &ComInterfaceMeta) -> String {
    let iface = &meta.interface;
    let name = &iface.name;

    let mut out = String::new();
    out.push_str("// Generated by dynwinrt-codegen — do not edit\n");
    // Import Buffer type hint via `import type` from Node ambient — HWND uses `Buffer`.
    // Node.js `Buffer` is a global type; no import needed. We DO import enum types.
    for en in enum_import_names(meta) {
        out.push_str(&format!("import {{ {} }} from './{}.js';\n", en, en));
    }
    out.push('\n');

    // Emit typedef aliases for handles seen in method parameters.
    let handle_aliases = collect_handle_aliases(meta);
    for h in &handle_aliases {
        out.push_str(&format!(
            "/** Opaque Win32 handle. Accepts either a raw pointer as `bigint` or a `Buffer`. */\nexport type {h} = bigint | Buffer;\n",
            h = h
        ));
    }
    if !handle_aliases.is_empty() {
        out.push('\n');
    }

    out.push_str(&format!("export declare const IID_{name}: unknown;\n\n", name = name));

    out.push_str(&format!("export declare class {name} {{\n", name = name));
    if meta.coclass_clsid.is_some() {
        out.push_str("    /** Create a new instance via the coclass activation path. */\n");
        out.push_str(&format!("    static create(): {name};\n", name = name));
    }
    out.push_str(&format!(
        "    /** Wrap an existing native COM pointer (for QueryInterface bridging). */\n    static _fromNative(obj: unknown): {name};\n",
        name = name
    ));

    for m in &iface.methods {
        let camel = camel_case(&m.name);
        let in_params: Vec<&ParamMeta> = m
            .params
            .iter()
            .filter(|p| p.direction == ParamDirection::In)
            .collect();
        let ts_params: Vec<String> = in_params
            .iter()
            .enumerate()
            .map(|(i, p)| {
                format!("{}: {}", js_param_name(&p.name, i), ts_type_expr_dts(&p.typ))
            })
            .collect();
        let ret = match &m.return_type {
            None => "void".to_string(),
            Some(t) if is_hresult(t) => "void".to_string(),
            Some(t) => ts_type_expr_dts(t),
        };
        out.push_str(&format!(
            "    {camel}({params}): {ret};\n",
            camel = camel,
            params = ts_params.join(", "),
            ret = ret,
        ));
    }
    out.push_str("}\n");
    out
}

fn collect_handle_aliases(meta: &ComInterfaceMeta) -> Vec<String> {
    let mut set = BTreeSet::new();
    for m in &meta.interface.methods {
        for p in &m.params {
            if let Some(h) = handle_type_name(&p.typ) {
                set.insert(h);
            }
        }
    }
    set.into_iter().collect()
}

// ---------------------------------------------------------------------------
// Enum sibling files
// ---------------------------------------------------------------------------

fn render_enum_files(en: &TypeMeta) -> (String, String) {
    let (name, members) = match en {
        TypeMeta::Enum { name, members, .. } => (name.as_str(), members),
        _ => unreachable!(),
    };

    // .js: a frozen object.
    let mut js = String::new();
    js.push_str("// Generated by dynwinrt-codegen — do not edit\n");
    js.push_str(&format!("export const {name} = Object.freeze({{\n", name = name));
    for m in members {
        js.push_str(&format!("    {}: {},\n", m.name, m.value));
    }
    js.push_str("});\n");

    // .d.ts: a proper enum declaration.
    let mut dts = String::new();
    dts.push_str("// Generated by dynwinrt-codegen — do not edit\n");
    dts.push_str(&format!("export declare const enum {name} {{\n", name = name));
    for m in members {
        dts.push_str(&format!("    {} = {},\n", m.name, m.value));
    }
    dts.push_str("}\n");

    (js, dts)
}

fn enum_import_names(meta: &ComInterfaceMeta) -> Vec<String> {
    meta.referenced_enums
        .iter()
        .filter_map(|e| match e {
            TypeMeta::Enum { name, .. } => Some(name.clone()),
            _ => None,
        })
        .collect()
}

// ---------------------------------------------------------------------------
// Type mapping helpers
// ---------------------------------------------------------------------------

/// TS type expression for the `.d.ts` surface.
fn ts_type_expr_dts(t: &TypeMeta) -> String {
    if let Some(h) = handle_type_name(t) {
        return h;
    }
    match t {
        TypeMeta::Bool => "boolean".into(),
        TypeMeta::I8 | TypeMeta::U8 | TypeMeta::I16 | TypeMeta::U16 | TypeMeta::I32 | TypeMeta::U32
            | TypeMeta::F32 | TypeMeta::F64 | TypeMeta::Char16 => "number".into(),
        TypeMeta::I64 | TypeMeta::U64 => "bigint".into(),
        TypeMeta::String => "string".into(),
        TypeMeta::Guid => "string".into(),
        TypeMeta::Enum { name, .. } => name.clone(),
        TypeMeta::Struct { name, .. } => name.clone(),
        // Pointer-to-struct or unknown — opaque bigint|Buffer at the surface.
        _ => "bigint | Buffer".into(),
    }
}

/// Runtime type expression for `DynWinRtMethodSig` calls in `.js`.
fn ts_type_expr_js(t: &TypeMeta) -> String {
    if handle_type_name(t).is_some() {
        return "DynWinRtType.pointer()".into();
    }
    match t {
        TypeMeta::Bool => "DynWinRtType.boolType()".into(),
        TypeMeta::I8 => "DynWinRtType.i8Type()".into(),
        TypeMeta::U8 => "DynWinRtType.u8Type()".into(),
        TypeMeta::I16 => "DynWinRtType.i16Type()".into(),
        TypeMeta::U16 => "DynWinRtType.u16Type()".into(),
        TypeMeta::I32 => "DynWinRtType.i32Type()".into(),
        TypeMeta::U32 => "DynWinRtType.u32Type()".into(),
        TypeMeta::I64 => "DynWinRtType.i64Type()".into(),
        TypeMeta::U64 => "DynWinRtType.u64Type()".into(),
        TypeMeta::F32 => "DynWinRtType.f32Type()".into(),
        TypeMeta::F64 => "DynWinRtType.f64Type()".into(),
        TypeMeta::Char16 => "DynWinRtType.char16()".into(),
        TypeMeta::String => "DynWinRtType.pointer()".into(), // PCWSTR/PWSTR → opaque
        TypeMeta::Guid => "DynWinRtType.guid()".into(),
        TypeMeta::Enum { underlying, .. } => ts_type_expr_js(underlying),
        _ => "DynWinRtType.pointer()".into(),
    }
}

fn wrap_arg_js(t: &TypeMeta, var: &str) -> String {
    if handle_type_name(t).is_some() {
        return format!("DynWinRtValue.pointer({var})", var = var);
    }
    match t {
        TypeMeta::Bool => format!("DynWinRtValue.boolValue({var})", var = var),
        TypeMeta::I8 => format!("DynWinRtValue.i8Value({var})", var = var),
        TypeMeta::U8 => format!("DynWinRtValue.u8Value({var})", var = var),
        TypeMeta::I16 => format!("DynWinRtValue.i16Value({var})", var = var),
        TypeMeta::U16 => format!("DynWinRtValue.u16Value({var})", var = var),
        TypeMeta::I32 => format!("DynWinRtValue.i32({var})", var = var),
        TypeMeta::U32 => format!("DynWinRtValue.u32({var})", var = var),
        TypeMeta::I64 => format!("DynWinRtValue.i64(BigInt({var}))", var = var),
        TypeMeta::U64 => format!("DynWinRtValue.u64(BigInt({var}))", var = var),
        TypeMeta::F32 => format!("DynWinRtValue.f32({var})", var = var),
        TypeMeta::F64 => format!("DynWinRtValue.f64({var})", var = var),
        TypeMeta::Char16 => format!("DynWinRtValue.char16({var})", var = var),
        TypeMeta::String => format!("DynWinRtValue.pointer({var})", var = var),
        TypeMeta::Guid => format!("DynWinRtValue.guid({var})", var = var),
        TypeMeta::Enum { underlying, .. } => wrap_arg_js(underlying, var),
        _ => format!("DynWinRtValue.pointer({var})", var = var),
    }
}

/// Returns `Some("HWND")` etc. when the given type is a Win32 opaque handle
/// (a struct in `Windows.Win32.Foundation` or similar handle-namespace with a
/// single pointer-shaped `Value` field). Also returns handle names for
/// PWSTR/PCWSTR/HRESULT-family types encountered as parameters (except
/// HRESULT itself which is treated as `void`).
fn handle_type_name(t: &TypeMeta) -> Option<String> {
    match t {
        TypeMeta::Struct { namespace, name, fields } => {
            if !is_win32_handle_namespace(namespace) {
                return None;
            }
            if is_hresult_by_name(namespace, name) {
                return None; // HRESULT is not a "handle" — never surface it as one
            }
            // Handle heuristic: exactly one field named `Value`, of pointer/int type.
            if fields.len() == 1
                && fields[0].name == "Value"
                && matches!(
                    fields[0].typ,
                    TypeMeta::Object
                        | TypeMeta::U64
                        | TypeMeta::I64
                        | TypeMeta::U32
                        | TypeMeta::I32
                )
            {
                return Some(name.clone());
            }
            None
        }
        _ => None,
    }
}

fn is_win32_handle_namespace(ns: &str) -> bool {
    ns.starts_with("Windows.Win32.")
}

fn is_hresult(t: &TypeMeta) -> bool {
    matches!(
        t,
        TypeMeta::Struct { namespace, name, .. }
            if is_hresult_by_name(namespace, name)
    )
}

fn is_hresult_by_name(ns: &str, name: &str) -> bool {
    ns == "Windows.Win32.Foundation" && name == "HRESULT"
}

// ---------------------------------------------------------------------------
// Naming helpers
// ---------------------------------------------------------------------------

fn camel_case(name: &str) -> String {
    if name.is_empty() {
        return String::new();
    }
    let chars: Vec<char> = name.chars().collect();
    // Count the leading uppercase run.
    let mut run = 0usize;
    while run < chars.len() && chars[run].is_ascii_uppercase() {
        run += 1;
    }
    let mut result = String::with_capacity(name.len());
    if run == 0 {
        // Already starts lowercase — return unchanged.
        return name.to_string();
    }
    if run == chars.len() {
        // Fully uppercase (e.g. "URL") — lowercase everything.
        for c in &chars {
            result.push(c.to_ascii_lowercase());
        }
        return result;
    }
    if run == 1 {
        // Simple case: lowercase first char, keep the rest.
        result.push(chars[0].to_ascii_lowercase());
        for c in &chars[1..] {
            result.push(*c);
        }
        return result;
    }
    // Multi-char uppercase run followed by lowercase: last uppercase char is
    // the start of the next word. E.g. "IOHandle" -> "ioHandle".
    for c in &chars[..run - 1] {
        result.push(c.to_ascii_lowercase());
    }
    for c in &chars[run - 1..] {
        result.push(*c);
    }
    result
}

fn js_param_name(raw: &str, index: usize) -> String {
    let base = if raw.is_empty() {
        format!("arg{}", index)
    } else {
        raw.to_string()
    };
    // Camelize (strip common Hungarian prefixes lightly for prettier surface):
    // dwFoo -> foo, pFoo -> foo, lpszFoo -> foo, cbFoo -> foo, iFoo -> foo, hFoo -> foo, hwndFoo -> foo.
    let stripped = strip_hungarian(&base);
    let mut out = String::with_capacity(stripped.len());
    let mut chars = stripped.chars();
    if let Some(first) = chars.next() {
        out.push(first.to_ascii_lowercase());
    }
    for c in chars {
        out.push(c);
    }
    // Guard against JS reserved words.
    match out.as_str() {
        "class" | "return" | "function" | "default" | "this" | "new" | "delete"
        | "let" | "const" | "var" | "if" | "else" | "for" | "while" | "do" | "switch"
        | "case" | "break" | "continue" | "true" | "false" | "null" | "undefined"
        | "in" | "of" | "typeof" | "instanceof" | "throw" | "try" | "catch" | "finally"
        | "yield" | "async" | "await" | "with" | "void" | "public" | "private" | "protected"
        | "package" | "static" | "import" | "export" | "extends" | "super" | "arguments" => {
            format!("{}_", out)
        }
        _ => out,
    }
}

fn strip_hungarian(s: &str) -> &str {
    // Only strip common **multi-character** Hungarian prefixes, and only when
    // followed by an uppercase letter (word boundary). Single-letter prefixes
    // like `h`, `p`, `i` cause too many false positives on real method-param
    // names (e.g. `hwnd` starts with `h` but isn't Hungarian; `pButton` is).
    let prefixes = [
        "lpwsz", "pwsz", "lpsz", "psz", "lpsz", "pwstr", "pcwstr",
        "hwnd", "dw", "sz", "cb", "cx", "cy", "cw", "ch", "cn", "cc",
        "lp", "np", "ph", "pd", "pf", "pv", "ppv", "pp", "wsz",
    ];
    for p in prefixes {
        if let Some(rest) = s.strip_prefix(p) {
            if rest
                .chars()
                .next()
                .map(|c| c.is_ascii_uppercase())
                .unwrap_or(false)
            {
                return rest;
            }
        }
    }
    s
}

// ---------------------------------------------------------------------------
// Unit tests (fast, no winmd — pure logic)
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn camel_case_basic() {
        assert_eq!(camel_case("HrInit"), "hrInit");
        assert_eq!(camel_case("SetProgressValue"), "setProgressValue");
        assert_eq!(camel_case("AddTab"), "addTab");
        assert_eq!(camel_case("URL"), "url");
        assert_eq!(camel_case("IOHandle"), "ioHandle");
    }

    #[test]
    fn strip_hungarian_only_at_word_boundary() {
        assert_eq!(strip_hungarian("dwReserved"), "Reserved");
        assert_eq!(strip_hungarian("hwndTab"), "Tab");
        // "hwnd" alone must NOT be stripped (no uppercase follow-up).
        assert_eq!(strip_hungarian("hwnd"), "hwnd");
    }

    #[test]
    fn handle_type_name_recognizes_hwnd_shape() {
        let hwnd = TypeMeta::Struct {
            namespace: "Windows.Win32.Foundation".into(),
            name: "HWND".into(),
            fields: vec![crate::types::FieldMeta {
                name: "Value".into(),
                typ: TypeMeta::Object,
            }],
        };
        assert_eq!(handle_type_name(&hwnd).as_deref(), Some("HWND"));
    }

    #[test]
    fn hresult_is_not_a_handle() {
        let hr = TypeMeta::Struct {
            namespace: "Windows.Win32.Foundation".into(),
            name: "HRESULT".into(),
            fields: vec![crate::types::FieldMeta {
                name: "Value".into(),
                typ: TypeMeta::I32,
            }],
        };
        assert!(handle_type_name(&hr).is_none());
        assert!(is_hresult(&hr));
    }

    #[test]
    fn non_win32_struct_is_not_a_handle() {
        let rect = TypeMeta::Struct {
            namespace: "Windows.Foundation".into(),
            name: "Rect".into(),
            fields: vec![
                crate::types::FieldMeta { name: "X".into(), typ: TypeMeta::F32 },
                crate::types::FieldMeta { name: "Y".into(), typ: TypeMeta::F32 },
                crate::types::FieldMeta { name: "Width".into(), typ: TypeMeta::F32 },
                crate::types::FieldMeta { name: "Height".into(), typ: TypeMeta::F32 },
            ],
        };
        assert!(handle_type_name(&rect).is_none());
    }
}
