// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '../../dist/index.js';
import { IBuffer } from './IBuffer.js';
import { InputStreamOptions } from './InputStreamOptions.js';

/**
 * A WinRT async operation that supports progress reporting and cancellation.
 *
 * - `await op` — wait for the final result
 * - `op.progress(cb)` — receive incremental progress updates (chainable)
 * - `op.cancel()` — cancel the underlying WinRT operation
 */
type WinRTAsyncWithProgress<T, P = unknown> = Promise<T> & {
    /** Register a callback for progress updates. Returns `this` for chaining. */
    progress(cb: (value: P) => void): WinRTAsyncWithProgress<T, P>;
    /** Get the underlying Promise (equivalent to awaiting directly). */
    toPromise(): Promise<T>;
    /** Cancel the underlying WinRT async operation. */
    cancel(): void;
};

export declare const IID_IInputStream: WinGuid;

export declare class IInputStream {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IInputStream;

    readAsync(buffer: IBuffer, count: number, options: InputStreamOptions, signal?: AbortSignal): WinRTAsyncWithProgress<IBuffer, number>;
}
