// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '../../dist/index.js';

export declare const IID_IMapView_String_Object: WinGuid;

export declare class IMapView_String_Object {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IMapView_String_Object;

    lookup(key: string): unknown;

    get size(): number;

    hasKey(key: string): boolean;

    /**
     * Get the value for `key`. Alias for `lookup()`.
     */
    get(key: string): unknown | undefined;

    /**
     * Check if the map contains `key`. Alias for `hasKey()`.
     */
    has(key: string): boolean;


    get length(): number;
}
