// Generated by dynwinrt-codegen — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('../../dist/index.js');
let __m_IMapView_String_Object;
const __load_IMapView_String_Object = () => (__m_IMapView_String_Object ??= require('./IMapView_String_Object.js'));
const __get_IMapView_String_Object = () => __load_IMapView_String_Object().IMapView_String_Object;
const { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } = require('./StreamedFileDataRequestedHandler.js');
const { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } = require('./TypedEventHandler_IStorageQueryResultBase_Object.js');
const { IID_TypedEventHandler_SystemMediaTransportControls_AutoRepeatModeChangeRequestedEventArgs, TypedEventHandler_SystemMediaTransportControls_AutoRepeatModeChangeRequestedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_SystemMediaTransportControls_AutoRepeatModeChangeRequestedEventArgs.js');
const { IID_TypedEventHandler_SystemMediaTransportControls_PlaybackPositionChangeRequestedEventArgs, TypedEventHandler_SystemMediaTransportControls_PlaybackPositionChangeRequestedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_SystemMediaTransportControls_PlaybackPositionChangeRequestedEventArgs.js');
const { IID_TypedEventHandler_SystemMediaTransportControls_PlaybackRateChangeRequestedEventArgs, TypedEventHandler_SystemMediaTransportControls_PlaybackRateChangeRequestedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_SystemMediaTransportControls_PlaybackRateChangeRequestedEventArgs.js');
const { IID_TypedEventHandler_SystemMediaTransportControls_ShuffleEnabledChangeRequestedEventArgs, TypedEventHandler_SystemMediaTransportControls_ShuffleEnabledChangeRequestedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_SystemMediaTransportControls_ShuffleEnabledChangeRequestedEventArgs.js');
const { IID_TypedEventHandler_SystemMediaTransportControls_SystemMediaTransportControlsButtonPressedEventArgs, TypedEventHandler_SystemMediaTransportControls_SystemMediaTransportControlsButtonPressedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_SystemMediaTransportControls_SystemMediaTransportControlsButtonPressedEventArgs.js');
const { IID_TypedEventHandler_SystemMediaTransportControls_SystemMediaTransportControlsPropertyChangedEventArgs, TypedEventHandler_SystemMediaTransportControls_SystemMediaTransportControlsPropertyChangedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_SystemMediaTransportControls_SystemMediaTransportControlsPropertyChangedEventArgs.js');
const { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_Object.js');
const { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs.js');
const { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserChangedEventArgs.js');
let __m_StreamedFileDataRequest;
const __load_StreamedFileDataRequest = () => (__m_StreamedFileDataRequest ??= require('./StreamedFileDataRequest.js'));
const __get_StreamedFileDataRequest = () => __load_StreamedFileDataRequest().StreamedFileDataRequest;
let __m_IStorageQueryResultBase;
const __load_IStorageQueryResultBase = () => (__m_IStorageQueryResultBase ??= require('./IStorageQueryResultBase.js'));
const __get_IStorageQueryResultBase = () => __load_IStorageQueryResultBase().IStorageQueryResultBase;
let __m_SystemMediaTransportControls;
const __load_SystemMediaTransportControls = () => (__m_SystemMediaTransportControls ??= require('./SystemMediaTransportControls.js'));
const __get_SystemMediaTransportControls = () => __load_SystemMediaTransportControls().SystemMediaTransportControls;
let __m_AutoRepeatModeChangeRequestedEventArgs;
const __load_AutoRepeatModeChangeRequestedEventArgs = () => (__m_AutoRepeatModeChangeRequestedEventArgs ??= require('./AutoRepeatModeChangeRequestedEventArgs.js'));
const __get_AutoRepeatModeChangeRequestedEventArgs = () => __load_AutoRepeatModeChangeRequestedEventArgs().AutoRepeatModeChangeRequestedEventArgs;
let __m_PlaybackPositionChangeRequestedEventArgs;
const __load_PlaybackPositionChangeRequestedEventArgs = () => (__m_PlaybackPositionChangeRequestedEventArgs ??= require('./PlaybackPositionChangeRequestedEventArgs.js'));
const __get_PlaybackPositionChangeRequestedEventArgs = () => __load_PlaybackPositionChangeRequestedEventArgs().PlaybackPositionChangeRequestedEventArgs;
let __m_PlaybackRateChangeRequestedEventArgs;
const __load_PlaybackRateChangeRequestedEventArgs = () => (__m_PlaybackRateChangeRequestedEventArgs ??= require('./PlaybackRateChangeRequestedEventArgs.js'));
const __get_PlaybackRateChangeRequestedEventArgs = () => __load_PlaybackRateChangeRequestedEventArgs().PlaybackRateChangeRequestedEventArgs;
let __m_ShuffleEnabledChangeRequestedEventArgs;
const __load_ShuffleEnabledChangeRequestedEventArgs = () => (__m_ShuffleEnabledChangeRequestedEventArgs ??= require('./ShuffleEnabledChangeRequestedEventArgs.js'));
const __get_ShuffleEnabledChangeRequestedEventArgs = () => __load_ShuffleEnabledChangeRequestedEventArgs().ShuffleEnabledChangeRequestedEventArgs;
let __m_SystemMediaTransportControlsButtonPressedEventArgs;
const __load_SystemMediaTransportControlsButtonPressedEventArgs = () => (__m_SystemMediaTransportControlsButtonPressedEventArgs ??= require('./SystemMediaTransportControlsButtonPressedEventArgs.js'));
const __get_SystemMediaTransportControlsButtonPressedEventArgs = () => __load_SystemMediaTransportControlsButtonPressedEventArgs().SystemMediaTransportControlsButtonPressedEventArgs;
let __m_SystemMediaTransportControlsPropertyChangedEventArgs;
const __load_SystemMediaTransportControlsPropertyChangedEventArgs = () => (__m_SystemMediaTransportControlsPropertyChangedEventArgs ??= require('./SystemMediaTransportControlsPropertyChangedEventArgs.js'));
const __get_SystemMediaTransportControlsPropertyChangedEventArgs = () => __load_SystemMediaTransportControlsPropertyChangedEventArgs().SystemMediaTransportControlsPropertyChangedEventArgs;
let __m_UserWatcher;
const __load_UserWatcher = () => (__m_UserWatcher ??= require('./UserWatcher.js'));
const __get_UserWatcher = () => __load_UserWatcher().UserWatcher;
let __m_UserAuthenticationStatusChangingEventArgs;
const __load_UserAuthenticationStatusChangingEventArgs = () => (__m_UserAuthenticationStatusChangingEventArgs ??= require('./UserAuthenticationStatusChangingEventArgs.js'));
const __get_UserAuthenticationStatusChangingEventArgs = () => __load_UserAuthenticationStatusChangingEventArgs().UserAuthenticationStatusChangingEventArgs;
let __m_UserChangedEventArgs;
const __load_UserChangedEventArgs = () => (__m_UserChangedEventArgs ??= require('./UserChangedEventArgs.js'));
const __get_UserChangedEventArgs = () => __load_UserChangedEventArgs().UserChangedEventArgs;

const _unwrap = (x) => x?._obj ?? x;

const IID_IMap_String_Object = DynWinRtType.parameterized(WinGuid.parse('3c2925fe-8519-45c1-aa79-197b6718c1c1'), [DynWinRtType.hstring(), DynWinRtType.object()]).iid();

let _IMap_String_ObjectCache;
const _IMap_String_Object = new Proxy({}, {
    get(_target, prop) {
        _IMap_String_ObjectCache ??= DynWinRtType.registerInterface(
        "IMap_String_Object", IID_IMap_String_Object)
        .addMethod("Lookup", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.object()))
        .addMethod("get_Size", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
        .addMethod("HasKey", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.boolType()))
        .addMethod("GetView", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('e480ce40-a338-4ada-adcf-272272e48cb9'), [DynWinRtType.hstring(), DynWinRtType.object()])))
        .addMethod("Insert", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addIn(DynWinRtType.object()).addOut(DynWinRtType.boolType()))
        .addMethod("Remove", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()))
        .addMethod("Clear", new DynWinRtMethodSig());
        const value = _IMap_String_ObjectCache[prop];
        return typeof value === 'function' ? value.bind(_IMap_String_ObjectCache) : value;
    }
});

class IMap_String_Object {
    _obj;

    constructor(obj) {
        this._obj = obj.cast(IID_IMap_String_Object);
    }

    static from(obj) {
        return new IMap_String_Object(obj.cast(IID_IMap_String_Object));
    }

    lookup(key) {
        return ((v) => v.isNull() ? null : v)(_IMap_String_Object.method(6).invoke(this._obj, [DynWinRtValue.hstring(key)]));
    }

    get size() {
        return _IMap_String_Object.method(7).invoke(this._obj, []).toNumber();
    }

    hasKey(key) {
        return _IMap_String_Object.method(8).invoke(this._obj, [DynWinRtValue.hstring(key)]).toBool();
    }

    getView() {
        return ((v) => v.isNull() ? null : new (__get_IMapView_String_Object())(v))(_IMap_String_Object.method(9).invoke(this._obj, []));
    }

    insert(key, value) {
        return _IMap_String_Object.method(10).invoke(this._obj, [DynWinRtValue.hstring(key), (value == null ? DynWinRtValue.nullValue() : _unwrap(value))]).toBool();
    }

    remove(key) {
        _IMap_String_Object.method(11).invoke(this._obj, [DynWinRtValue.hstring(key)]);
    }

    clear() {
        _IMap_String_Object.method(12).invoke(this._obj, []);
    }

    /**
     * Get the value for `key`. Alias for `lookup()`.
     */
    get(key) {
        return (() => { try { return ((v) => v.isNull() ? null : v)(_IMap_String_Object.method(6).invoke(this._obj, [DynWinRtValue.hstring(key)])); } catch { return undefined; } })();
    }

    /**
     * Check if the map contains `key`. Alias for `hasKey()`.
     */
    has(key) {
        return _IMap_String_Object.method(8).invoke(this._obj, [DynWinRtValue.hstring(key)]).toBool();
    }

    /**
     * Set a key-value pair. Alias for `insert()`.
     */
    set(key, value) {
        _IMap_String_Object.method(10).invoke(this._obj, [DynWinRtValue.hstring(key), (value == null ? DynWinRtValue.nullValue() : _unwrap(value))]);
    }

    /**
     * Remove entry by key. Alias for `remove()`.
     */
    delete(key) {
        _IMap_String_Object.method(11).invoke(this._obj, [DynWinRtValue.hstring(key)]);
    }

    /** Number of entries. Alias for `size`. */
    get length() { return this.size; }

    /**
     * Create a new IMap from parallel arrays of keys and values.
     */
    static create(keys, values) {
        return new IMap_String_Object(DynWinRtValue.createMap(keys.map(k => _unwrap(k)), values.map(v => _unwrap(v)), DynWinRtType.hstring(), DynWinRtType.object()));
    }
}
exports.IID_IMap_String_Object = IID_IMap_String_Object;
exports.IMap_String_Object = IMap_String_Object;
