// Generated by dynwinrt-codegen — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('../../dist/index.js');
const { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } = require('./StreamedFileDataRequestedHandler.js');
const { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } = require('./TypedEventHandler_IStorageQueryResultBase_Object.js');
const { IID_TypedEventHandler_SystemMediaTransportControls_AutoRepeatModeChangeRequestedEventArgs, TypedEventHandler_SystemMediaTransportControls_AutoRepeatModeChangeRequestedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_SystemMediaTransportControls_AutoRepeatModeChangeRequestedEventArgs.js');
const { IID_TypedEventHandler_SystemMediaTransportControls_PlaybackPositionChangeRequestedEventArgs, TypedEventHandler_SystemMediaTransportControls_PlaybackPositionChangeRequestedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_SystemMediaTransportControls_PlaybackPositionChangeRequestedEventArgs.js');
const { IID_TypedEventHandler_SystemMediaTransportControls_PlaybackRateChangeRequestedEventArgs, TypedEventHandler_SystemMediaTransportControls_PlaybackRateChangeRequestedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_SystemMediaTransportControls_PlaybackRateChangeRequestedEventArgs.js');
const { IID_TypedEventHandler_SystemMediaTransportControls_ShuffleEnabledChangeRequestedEventArgs, TypedEventHandler_SystemMediaTransportControls_ShuffleEnabledChangeRequestedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_SystemMediaTransportControls_ShuffleEnabledChangeRequestedEventArgs.js');
const { IID_TypedEventHandler_SystemMediaTransportControls_SystemMediaTransportControlsButtonPressedEventArgs, TypedEventHandler_SystemMediaTransportControls_SystemMediaTransportControlsButtonPressedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_SystemMediaTransportControls_SystemMediaTransportControlsButtonPressedEventArgs.js');
const { IID_TypedEventHandler_SystemMediaTransportControls_SystemMediaTransportControlsPropertyChangedEventArgs, TypedEventHandler_SystemMediaTransportControls_SystemMediaTransportControlsPropertyChangedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_SystemMediaTransportControls_SystemMediaTransportControlsPropertyChangedEventArgs.js');
const { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_Object.js');
const { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs.js');
const { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserChangedEventArgs.js');
let __m_StreamedFileDataRequest;
const __load_StreamedFileDataRequest = () => (__m_StreamedFileDataRequest ??= require('./StreamedFileDataRequest.js'));
const __get_StreamedFileDataRequest = () => __load_StreamedFileDataRequest().StreamedFileDataRequest;
let __m_IStorageQueryResultBase;
const __load_IStorageQueryResultBase = () => (__m_IStorageQueryResultBase ??= require('./IStorageQueryResultBase.js'));
const __get_IStorageQueryResultBase = () => __load_IStorageQueryResultBase().IStorageQueryResultBase;
let __m_SystemMediaTransportControls;
const __load_SystemMediaTransportControls = () => (__m_SystemMediaTransportControls ??= require('./SystemMediaTransportControls.js'));
const __get_SystemMediaTransportControls = () => __load_SystemMediaTransportControls().SystemMediaTransportControls;
let __m_AutoRepeatModeChangeRequestedEventArgs;
const __load_AutoRepeatModeChangeRequestedEventArgs = () => (__m_AutoRepeatModeChangeRequestedEventArgs ??= require('./AutoRepeatModeChangeRequestedEventArgs.js'));
const __get_AutoRepeatModeChangeRequestedEventArgs = () => __load_AutoRepeatModeChangeRequestedEventArgs().AutoRepeatModeChangeRequestedEventArgs;
let __m_PlaybackPositionChangeRequestedEventArgs;
const __load_PlaybackPositionChangeRequestedEventArgs = () => (__m_PlaybackPositionChangeRequestedEventArgs ??= require('./PlaybackPositionChangeRequestedEventArgs.js'));
const __get_PlaybackPositionChangeRequestedEventArgs = () => __load_PlaybackPositionChangeRequestedEventArgs().PlaybackPositionChangeRequestedEventArgs;
let __m_PlaybackRateChangeRequestedEventArgs;
const __load_PlaybackRateChangeRequestedEventArgs = () => (__m_PlaybackRateChangeRequestedEventArgs ??= require('./PlaybackRateChangeRequestedEventArgs.js'));
const __get_PlaybackRateChangeRequestedEventArgs = () => __load_PlaybackRateChangeRequestedEventArgs().PlaybackRateChangeRequestedEventArgs;
let __m_ShuffleEnabledChangeRequestedEventArgs;
const __load_ShuffleEnabledChangeRequestedEventArgs = () => (__m_ShuffleEnabledChangeRequestedEventArgs ??= require('./ShuffleEnabledChangeRequestedEventArgs.js'));
const __get_ShuffleEnabledChangeRequestedEventArgs = () => __load_ShuffleEnabledChangeRequestedEventArgs().ShuffleEnabledChangeRequestedEventArgs;
let __m_SystemMediaTransportControlsButtonPressedEventArgs;
const __load_SystemMediaTransportControlsButtonPressedEventArgs = () => (__m_SystemMediaTransportControlsButtonPressedEventArgs ??= require('./SystemMediaTransportControlsButtonPressedEventArgs.js'));
const __get_SystemMediaTransportControlsButtonPressedEventArgs = () => __load_SystemMediaTransportControlsButtonPressedEventArgs().SystemMediaTransportControlsButtonPressedEventArgs;
let __m_SystemMediaTransportControlsPropertyChangedEventArgs;
const __load_SystemMediaTransportControlsPropertyChangedEventArgs = () => (__m_SystemMediaTransportControlsPropertyChangedEventArgs ??= require('./SystemMediaTransportControlsPropertyChangedEventArgs.js'));
const __get_SystemMediaTransportControlsPropertyChangedEventArgs = () => __load_SystemMediaTransportControlsPropertyChangedEventArgs().SystemMediaTransportControlsPropertyChangedEventArgs;
let __m_UserWatcher;
const __load_UserWatcher = () => (__m_UserWatcher ??= require('./UserWatcher.js'));
const __get_UserWatcher = () => __load_UserWatcher().UserWatcher;
let __m_UserAuthenticationStatusChangingEventArgs;
const __load_UserAuthenticationStatusChangingEventArgs = () => (__m_UserAuthenticationStatusChangingEventArgs ??= require('./UserAuthenticationStatusChangingEventArgs.js'));
const __get_UserAuthenticationStatusChangingEventArgs = () => __load_UserAuthenticationStatusChangingEventArgs().UserAuthenticationStatusChangingEventArgs;
let __m_UserChangedEventArgs;
const __load_UserChangedEventArgs = () => (__m_UserChangedEventArgs ??= require('./UserChangedEventArgs.js'));
const __get_UserChangedEventArgs = () => __load_UserChangedEventArgs().UserChangedEventArgs;

const IID_IMusicDisplayProperties3 = WinGuid.parse('4db51ac1-0681-4e8c-9401-b8159d9eefc7');

let _IMusicDisplayProperties3Cache;
const _IMusicDisplayProperties3 = new Proxy({}, {
    get(_target, prop) {
        _IMusicDisplayProperties3Cache ??= DynWinRtType.registerInterface(
        "IMusicDisplayProperties3", IID_IMusicDisplayProperties3)
        .addMethod("get_AlbumTrackCount", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
        .addMethod("put_AlbumTrackCount", new DynWinRtMethodSig().addIn(DynWinRtType.u32()));
        const value = _IMusicDisplayProperties3Cache[prop];
        return typeof value === 'function' ? value.bind(_IMusicDisplayProperties3Cache) : value;
    }
});

class IMusicDisplayProperties3 {
    _obj;

    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IMusicDisplayProperties3(obj.cast(IID_IMusicDisplayProperties3));
    }

    get albumTrackCount() {
        return _IMusicDisplayProperties3.method(6).invoke(this._obj, []).toNumber();
    }
    set albumTrackCount(value) {
        _IMusicDisplayProperties3.method(7).invoke(this._obj, [DynWinRtValue.u32(value)]);
    }
}
exports.IID_IMusicDisplayProperties3 = IID_IMusicDisplayProperties3;
exports.IMusicDisplayProperties3 = IMusicDisplayProperties3;
