// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '../../dist/index.js';

export declare const IID_IMusicDisplayProperties3: WinGuid;

export declare class IMusicDisplayProperties3 {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IMusicDisplayProperties3;

    get albumTrackCount(): number;
    set albumTrackCount(value: number);
}
