// Generated by dynwinrt-codegen — do not edit
export type IndexedState = (typeof IndexedState)[keyof typeof IndexedState];
export declare const IndexedState: {
    readonly Unknown: 0;
    readonly NotIndexed: 1;
    readonly PartiallyIndexed: 2;
    readonly FullyIndexed: 3;
};
