// Generated by dynwinrt-codegen — do not edit
const __exportLazy = (name, path) => {
    let mod;
    Object.defineProperty(exports, name, {
        enumerable: true,
        configurable: true,
        get() { return (mod ??= require(path))[name]; },
    });
};
__exportLazy('AutoRepeatModeChangeRequestedEventArgs', './AutoRepeatModeChangeRequestedEventArgs.js');
__exportLazy('BasicProperties', './BasicProperties.js');
__exportLazy('packDateTime', './BasicProperties.js');
__exportLazy('unpackDateTime', './BasicProperties.js');
__exportLazy('CommonFileQuery', './CommonFileQuery.js');
__exportLazy('CommonFolderQuery', './CommonFolderQuery.js');
__exportLazy('CreationCollisionOption', './CreationCollisionOption.js');
__exportLazy('DateStackOption', './DateStackOption.js');
__exportLazy('DocumentProperties', './DocumentProperties.js');
__exportLazy('FileAccessMode', './FileAccessMode.js');
__exportLazy('FileAttributes', './FileAttributes.js');
__exportLazy('FolderDepth', './FolderDepth.js');
__exportLazy('IBuffer', './IBuffer.js');
__exportLazy('IClosable', './IClosable.js');
__exportLazy('IContentTypeProvider', './IContentTypeProvider.js');
__exportLazy('IInputStream', './IInputStream.js');
__exportLazy('IInputStreamReference', './IInputStreamReference.js');
__exportLazy('IIterable_IKeyValuePair_String_Object', './IIterable_IKeyValuePair_String_Object.js');
__exportLazy('IIterable_String', './IIterable_String.js');
__exportLazy('IIterator_IWwwFormUrlDecoderEntry', './IIterator_IWwwFormUrlDecoderEntry.js');
__exportLazy('IIterator_Object', './IIterator_Object.js');
__exportLazy('IIterator_String', './IIterator_String.js');
__exportLazy('IKeyValuePair_String_Object', './IKeyValuePair_String_Object.js');
__exportLazy('IMapView_String_Object', './IMapView_String_Object.js');
__exportLazy('IMap_String_IVectorView_TextSegment', './IMap_String_IVectorView_TextSegment.js');
__exportLazy('IMap_String_Object', './IMap_String_Object.js');
__exportLazy('IMusicDisplayProperties2', './IMusicDisplayProperties2.js');
__exportLazy('IMusicDisplayProperties3', './IMusicDisplayProperties3.js');
__exportLazy('IOutputStream', './IOutputStream.js');
__exportLazy('IPropertySet', './IPropertySet.js');
__exportLazy('IQueryOptionsAdditionalSearchSources', './IQueryOptionsAdditionalSearchSources.js');
__exportLazy('IQueryOptionsWithProviderFilter', './IQueryOptionsWithProviderFilter.js');
__exportLazy('IRandomAccessStream', './IRandomAccessStream.js');
__exportLazy('IRandomAccessStreamReference', './IRandomAccessStreamReference.js');
__exportLazy('IRandomAccessStreamWithContentType', './IRandomAccessStreamWithContentType.js');
__exportLazy('IReference_Double', './IReference_Double.js');
__exportLazy('IStorageFile', './IStorageFile.js');
__exportLazy('IStorageFile2', './IStorageFile2.js');
__exportLazy('IStorageFilePropertiesWithAvailability', './IStorageFilePropertiesWithAvailability.js');
__exportLazy('IStorageFileQueryResult2', './IStorageFileQueryResult2.js');
__exportLazy('packTextSegment', './IStorageFileQueryResult2.js');
__exportLazy('unpackTextSegment', './IStorageFileQueryResult2.js');
__exportLazy('IStorageFolder', './IStorageFolder.js');
__exportLazy('IStorageFolder2', './IStorageFolder2.js');
__exportLazy('IStorageFolder3', './IStorageFolder3.js');
__exportLazy('IStorageFolderQueryOperations', './IStorageFolderQueryOperations.js');
__exportLazy('IStorageItem', './IStorageItem.js');
__exportLazy('IStorageItem2', './IStorageItem2.js');
__exportLazy('IStorageItemExtraProperties', './IStorageItemExtraProperties.js');
__exportLazy('IStorageItemProperties', './IStorageItemProperties.js');
__exportLazy('IStorageItemProperties2', './IStorageItemProperties2.js');
__exportLazy('IStorageItemPropertiesWithProvider', './IStorageItemPropertiesWithProvider.js');
__exportLazy('IStorageLibraryChangeReader2', './IStorageLibraryChangeReader2.js');
__exportLazy('IStorageLibraryChangeTracker2', './IStorageLibraryChangeTracker2.js');
__exportLazy('IStorageProvider2', './IStorageProvider2.js');
__exportLazy('IStorageQueryResultBase', './IStorageQueryResultBase.js');
__exportLazy('packEventRegistrationToken', './IStorageQueryResultBase.js');
__exportLazy('unpackEventRegistrationToken', './IStorageQueryResultBase.js');
__exportLazy('IStreamedFileDataRequest', './IStreamedFileDataRequest.js');
__exportLazy('IStringable', './IStringable.js');
__exportLazy('ISystemMediaTransportControls2', './ISystemMediaTransportControls2.js');
__exportLazy('IThumbnailProperties', './IThumbnailProperties.js');
__exportLazy('IUriRuntimeClassWithAbsoluteCanonicalUri', './IUriRuntimeClassWithAbsoluteCanonicalUri.js');
__exportLazy('IUser2', './IUser2.js');
__exportLazy('IUserChangedEventArgs2', './IUserChangedEventArgs2.js');
__exportLazy('IVectorView_IStorageItem', './IVectorView_IStorageItem.js');
__exportLazy('IVectorView_SortEntry', './IVectorView_SortEntry.js');
__exportLazy('packSortEntry', './IVectorView_SortEntry.js');
__exportLazy('unpackSortEntry', './IVectorView_SortEntry.js');
__exportLazy('IVectorView_StorageFile', './IVectorView_StorageFile.js');
__exportLazy('IVectorView_StorageFolder', './IVectorView_StorageFolder.js');
__exportLazy('IVectorView_StorageLibraryChange', './IVectorView_StorageLibraryChange.js');
__exportLazy('IVectorView_String', './IVectorView_String.js');
__exportLazy('IVectorView_TextSegment', './IVectorView_TextSegment.js');
__exportLazy('IVectorView_User', './IVectorView_User.js');
__exportLazy('IVectorView_UserWatcherUpdateKind', './IVectorView_UserWatcherUpdateKind.js');
__exportLazy('IVector_SortEntry', './IVector_SortEntry.js');
__exportLazy('IVector_String', './IVector_String.js');
__exportLazy('IVideoDisplayProperties2', './IVideoDisplayProperties2.js');
__exportLazy('IWwwFormUrlDecoderEntry', './IWwwFormUrlDecoderEntry.js');
__exportLazy('ImageDisplayProperties', './ImageDisplayProperties.js');
__exportLazy('ImageProperties', './ImageProperties.js');
__exportLazy('IndexedState', './IndexedState.js');
__exportLazy('IndexerOption', './IndexerOption.js');
__exportLazy('InputStreamOptions', './InputStreamOptions.js');
__exportLazy('MediaPlaybackAutoRepeatMode', './MediaPlaybackAutoRepeatMode.js');
__exportLazy('MediaPlaybackStatus', './MediaPlaybackStatus.js');
__exportLazy('MediaPlaybackType', './MediaPlaybackType.js');
__exportLazy('MusicDisplayProperties', './MusicDisplayProperties.js');
__exportLazy('MusicProperties', './MusicProperties.js');
__exportLazy('packTimeSpan', './MusicProperties.js');
__exportLazy('unpackTimeSpan', './MusicProperties.js');
__exportLazy('NameCollisionOption', './NameCollisionOption.js');
__exportLazy('PhotoOrientation', './PhotoOrientation.js');
__exportLazy('PlaybackPositionChangeRequestedEventArgs', './PlaybackPositionChangeRequestedEventArgs.js');
__exportLazy('PlaybackRateChangeRequestedEventArgs', './PlaybackRateChangeRequestedEventArgs.js');
__exportLazy('PropertyPrefetchOptions', './PropertyPrefetchOptions.js');
__exportLazy('QueryOptions', './QueryOptions.js');
__exportLazy('RandomAccessStreamReference', './RandomAccessStreamReference.js');
__exportLazy('ShuffleEnabledChangeRequestedEventArgs', './ShuffleEnabledChangeRequestedEventArgs.js');
__exportLazy('SoundLevel', './SoundLevel.js');
__exportLazy('StorageDeleteOption', './StorageDeleteOption.js');
__exportLazy('StorageFile', './StorageFile.js');
__exportLazy('StorageFileQueryResult', './StorageFileQueryResult.js');
__exportLazy('StorageFolder', './StorageFolder.js');
__exportLazy('StorageFolderQueryResult', './StorageFolderQueryResult.js');
__exportLazy('StorageItemContentProperties', './StorageItemContentProperties.js');
__exportLazy('StorageItemQueryResult', './StorageItemQueryResult.js');
__exportLazy('StorageItemThumbnail', './StorageItemThumbnail.js');
__exportLazy('StorageItemTypes', './StorageItemTypes.js');
__exportLazy('StorageLibraryChange', './StorageLibraryChange.js');
__exportLazy('StorageLibraryChangeReader', './StorageLibraryChangeReader.js');
__exportLazy('StorageLibraryChangeTracker', './StorageLibraryChangeTracker.js');
__exportLazy('StorageLibraryChangeTrackerOptions', './StorageLibraryChangeTrackerOptions.js');
__exportLazy('StorageLibraryChangeType', './StorageLibraryChangeType.js');
__exportLazy('StorageOpenOptions', './StorageOpenOptions.js');
__exportLazy('StorageProvider', './StorageProvider.js');
__exportLazy('StorageStreamTransaction', './StorageStreamTransaction.js');
__exportLazy('StreamedFileDataRequest', './StreamedFileDataRequest.js');
__exportLazy('StreamedFileFailureMode', './StreamedFileFailureMode.js');
__exportLazy('SystemMediaTransportControls', './SystemMediaTransportControls.js');
__exportLazy('SystemMediaTransportControlsButton', './SystemMediaTransportControlsButton.js');
__exportLazy('SystemMediaTransportControlsButtonPressedEventArgs', './SystemMediaTransportControlsButtonPressedEventArgs.js');
__exportLazy('SystemMediaTransportControlsDisplayUpdater', './SystemMediaTransportControlsDisplayUpdater.js');
__exportLazy('SystemMediaTransportControlsProperty', './SystemMediaTransportControlsProperty.js');
__exportLazy('SystemMediaTransportControlsPropertyChangedEventArgs', './SystemMediaTransportControlsPropertyChangedEventArgs.js');
__exportLazy('SystemMediaTransportControlsTimelineProperties', './SystemMediaTransportControlsTimelineProperties.js');
__exportLazy('ThumbnailMode', './ThumbnailMode.js');
__exportLazy('ThumbnailOptions', './ThumbnailOptions.js');
__exportLazy('ThumbnailType', './ThumbnailType.js');
__exportLazy('Uri', './Uri.js');
__exportLazy('User', './User.js');
__exportLazy('UserAgeConsentGroup', './UserAgeConsentGroup.js');
__exportLazy('UserAgeConsentResult', './UserAgeConsentResult.js');
__exportLazy('UserAuthenticationStatus', './UserAuthenticationStatus.js');
__exportLazy('UserAuthenticationStatusChangeDeferral', './UserAuthenticationStatusChangeDeferral.js');
__exportLazy('UserAuthenticationStatusChangingEventArgs', './UserAuthenticationStatusChangingEventArgs.js');
__exportLazy('UserChangedEventArgs', './UserChangedEventArgs.js');
__exportLazy('UserPictureSize', './UserPictureSize.js');
__exportLazy('UserType', './UserType.js');
__exportLazy('UserWatcher', './UserWatcher.js');
__exportLazy('UserWatcherStatus', './UserWatcherStatus.js');
__exportLazy('UserWatcherUpdateKind', './UserWatcherUpdateKind.js');
__exportLazy('VideoDisplayProperties', './VideoDisplayProperties.js');
__exportLazy('VideoOrientation', './VideoOrientation.js');
__exportLazy('VideoProperties', './VideoProperties.js');
__exportLazy('IIterable_IWwwFormUrlDecoderEntry', './WwwFormUrlDecoder.js');
__exportLazy('IVectorView_IWwwFormUrlDecoderEntry', './WwwFormUrlDecoder.js');
__exportLazy('WwwFormUrlDecoder', './WwwFormUrlDecoder.js');
__exportLazy('createProjectedLifetimeScope', './lifetime.js');
0 && (module.exports = {
    AutoRepeatModeChangeRequestedEventArgs,
    BasicProperties,
    packDateTime,
    unpackDateTime,
    CommonFileQuery,
    CommonFolderQuery,
    CreationCollisionOption,
    DateStackOption,
    DocumentProperties,
    FileAccessMode,
    FileAttributes,
    FolderDepth,
    IBuffer,
    IClosable,
    IContentTypeProvider,
    IInputStream,
    IInputStreamReference,
    IIterable_IKeyValuePair_String_Object,
    IIterable_String,
    IIterator_IWwwFormUrlDecoderEntry,
    IIterator_Object,
    IIterator_String,
    IKeyValuePair_String_Object,
    IMapView_String_Object,
    IMap_String_IVectorView_TextSegment,
    IMap_String_Object,
    IMusicDisplayProperties2,
    IMusicDisplayProperties3,
    IOutputStream,
    IPropertySet,
    IQueryOptionsAdditionalSearchSources,
    IQueryOptionsWithProviderFilter,
    IRandomAccessStream,
    IRandomAccessStreamReference,
    IRandomAccessStreamWithContentType,
    IReference_Double,
    IStorageFile,
    IStorageFile2,
    IStorageFilePropertiesWithAvailability,
    IStorageFileQueryResult2,
    packTextSegment,
    unpackTextSegment,
    IStorageFolder,
    IStorageFolder2,
    IStorageFolder3,
    IStorageFolderQueryOperations,
    IStorageItem,
    IStorageItem2,
    IStorageItemExtraProperties,
    IStorageItemProperties,
    IStorageItemProperties2,
    IStorageItemPropertiesWithProvider,
    IStorageLibraryChangeReader2,
    IStorageLibraryChangeTracker2,
    IStorageProvider2,
    IStorageQueryResultBase,
    packEventRegistrationToken,
    unpackEventRegistrationToken,
    IStreamedFileDataRequest,
    IStringable,
    ISystemMediaTransportControls2,
    IThumbnailProperties,
    IUriRuntimeClassWithAbsoluteCanonicalUri,
    IUser2,
    IUserChangedEventArgs2,
    IVectorView_IStorageItem,
    IVectorView_SortEntry,
    packSortEntry,
    unpackSortEntry,
    IVectorView_StorageFile,
    IVectorView_StorageFolder,
    IVectorView_StorageLibraryChange,
    IVectorView_String,
    IVectorView_TextSegment,
    IVectorView_User,
    IVectorView_UserWatcherUpdateKind,
    IVector_SortEntry,
    IVector_String,
    IVideoDisplayProperties2,
    IWwwFormUrlDecoderEntry,
    ImageDisplayProperties,
    ImageProperties,
    IndexedState,
    IndexerOption,
    InputStreamOptions,
    MediaPlaybackAutoRepeatMode,
    MediaPlaybackStatus,
    MediaPlaybackType,
    MusicDisplayProperties,
    MusicProperties,
    packTimeSpan,
    unpackTimeSpan,
    NameCollisionOption,
    PhotoOrientation,
    PlaybackPositionChangeRequestedEventArgs,
    PlaybackRateChangeRequestedEventArgs,
    PropertyPrefetchOptions,
    QueryOptions,
    RandomAccessStreamReference,
    ShuffleEnabledChangeRequestedEventArgs,
    SoundLevel,
    StorageDeleteOption,
    StorageFile,
    StorageFileQueryResult,
    StorageFolder,
    StorageFolderQueryResult,
    StorageItemContentProperties,
    StorageItemQueryResult,
    StorageItemThumbnail,
    StorageItemTypes,
    StorageLibraryChange,
    StorageLibraryChangeReader,
    StorageLibraryChangeTracker,
    StorageLibraryChangeTrackerOptions,
    StorageLibraryChangeType,
    StorageOpenOptions,
    StorageProvider,
    StorageStreamTransaction,
    StreamedFileDataRequest,
    StreamedFileFailureMode,
    SystemMediaTransportControls,
    SystemMediaTransportControlsButton,
    SystemMediaTransportControlsButtonPressedEventArgs,
    SystemMediaTransportControlsDisplayUpdater,
    SystemMediaTransportControlsProperty,
    SystemMediaTransportControlsPropertyChangedEventArgs,
    SystemMediaTransportControlsTimelineProperties,
    ThumbnailMode,
    ThumbnailOptions,
    ThumbnailType,
    Uri,
    User,
    UserAgeConsentGroup,
    UserAgeConsentResult,
    UserAuthenticationStatus,
    UserAuthenticationStatusChangeDeferral,
    UserAuthenticationStatusChangingEventArgs,
    UserChangedEventArgs,
    UserPictureSize,
    UserType,
    UserWatcher,
    UserWatcherStatus,
    UserWatcherUpdateKind,
    VideoDisplayProperties,
    VideoOrientation,
    VideoProperties,
    IIterable_IWwwFormUrlDecoderEntry,
    IVectorView_IWwwFormUrlDecoderEntry,
    WwwFormUrlDecoder,
    createProjectedLifetimeScope,
});
