// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '../../dist/index.js';

export declare const IID_IQueryOptionsAdditionalSearchSources: WinGuid;

export declare class IQueryOptionsAdditionalSearchSources {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IQueryOptionsAdditionalSearchSources;

    get includeLocalSemanticIndex(): boolean;
    set includeLocalSemanticIndex(value: boolean);

    get includeCloudProviders(): boolean;
    set includeCloudProviders(value: boolean);
}
