// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '../../dist/index.js';
import { IVector_String } from './IVector_String.js';

export declare const IID_IQueryOptionsWithProviderFilter: WinGuid;

export declare class IQueryOptionsWithProviderFilter {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IQueryOptionsWithProviderFilter;

    get storageProviderIdFilter(): IVector_String;
}
