// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '../../dist/index.js';
import { FileAccessMode } from './FileAccessMode.js';
import { IStorageFolder } from './IStorageFolder.js';
import { NameCollisionOption } from './NameCollisionOption.js';
import { StorageFile } from './StorageFile.js';
import { StorageStreamTransaction } from './StorageStreamTransaction.js';
import { IRandomAccessStream } from './IRandomAccessStream.js';

export declare const IID_IStorageFile: WinGuid;

export declare class IStorageFile {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IStorageFile;

    get fileType(): string;

    get contentType(): string;

    openAsync(accessMode: FileAccessMode, signal?: AbortSignal): Promise<IRandomAccessStream>;

    openTransactedWriteAsync(signal?: AbortSignal): Promise<StorageStreamTransaction>;

    /**
     * Overload of `copy` with default name, options.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     */
    copyOverloadDefaultNameAndOptions(destinationFolder: IStorageFolder, signal?: AbortSignal): Promise<StorageFile>;

    /**
     * Overload of `copy` with default options.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     */
    copyOverloadDefaultOptions(destinationFolder: IStorageFolder, desiredNewName: string, signal?: AbortSignal): Promise<StorageFile>;

    /**
     * Parameterless overload of `copy`.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     */
    copyOverload(destinationFolder: IStorageFolder, desiredNewName: string, option: NameCollisionOption, signal?: AbortSignal): Promise<StorageFile>;

    copyAndReplaceAsync(fileToReplace: IStorageFile, signal?: AbortSignal): Promise<void>;

    /**
     * Overload of `move` with default name, options.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     */
    moveOverloadDefaultNameAndOptions(destinationFolder: IStorageFolder, signal?: AbortSignal): Promise<void>;

    /**
     * Overload of `move` with default options.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     */
    moveOverloadDefaultOptions(destinationFolder: IStorageFolder, desiredNewName: string, signal?: AbortSignal): Promise<void>;

    /**
     * Parameterless overload of `move`.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     */
    moveOverload(destinationFolder: IStorageFolder, desiredNewName: string, option: NameCollisionOption, signal?: AbortSignal): Promise<void>;

    moveAndReplaceAsync(fileToReplace: IStorageFile, signal?: AbortSignal): Promise<void>;
}
