// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '../../dist/index.js';

export declare const IID_IStorageLibraryChangeReader2: WinGuid;

export declare class IStorageLibraryChangeReader2 {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IStorageLibraryChangeReader2;

    getLastChangeId(): bigint;
}
