// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '../../dist/index.js';
import { IStorageItem } from './IStorageItem.js';

export declare const IID_IStorageFolder2: WinGuid;

export declare class IStorageFolder2 {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IStorageFolder2;

    tryGetItemAsync(name: string, signal?: AbortSignal): Promise<IStorageItem>;
}
