// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '../../dist/index.js';

export declare const IID_IStorageProvider2: WinGuid;

export declare class IStorageProvider2 {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IStorageProvider2;

    isPropertySupportedForPartialFileAsync(propertyCanonicalName: string, signal?: AbortSignal): Promise<boolean>;
}
