// Generated by dynwinrt-codegen — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } = require('../../dist/index.js');
const { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } = require('./StreamedFileDataRequestedHandler.js');
const { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } = require('./TypedEventHandler_IStorageQueryResultBase_Object.js');
const { IID_TypedEventHandler_SystemMediaTransportControls_AutoRepeatModeChangeRequestedEventArgs, TypedEventHandler_SystemMediaTransportControls_AutoRepeatModeChangeRequestedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_SystemMediaTransportControls_AutoRepeatModeChangeRequestedEventArgs.js');
const { IID_TypedEventHandler_SystemMediaTransportControls_PlaybackPositionChangeRequestedEventArgs, TypedEventHandler_SystemMediaTransportControls_PlaybackPositionChangeRequestedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_SystemMediaTransportControls_PlaybackPositionChangeRequestedEventArgs.js');
const { IID_TypedEventHandler_SystemMediaTransportControls_PlaybackRateChangeRequestedEventArgs, TypedEventHandler_SystemMediaTransportControls_PlaybackRateChangeRequestedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_SystemMediaTransportControls_PlaybackRateChangeRequestedEventArgs.js');
const { IID_TypedEventHandler_SystemMediaTransportControls_ShuffleEnabledChangeRequestedEventArgs, TypedEventHandler_SystemMediaTransportControls_ShuffleEnabledChangeRequestedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_SystemMediaTransportControls_ShuffleEnabledChangeRequestedEventArgs.js');
const { IID_TypedEventHandler_SystemMediaTransportControls_SystemMediaTransportControlsButtonPressedEventArgs, TypedEventHandler_SystemMediaTransportControls_SystemMediaTransportControlsButtonPressedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_SystemMediaTransportControls_SystemMediaTransportControlsButtonPressedEventArgs.js');
const { IID_TypedEventHandler_SystemMediaTransportControls_SystemMediaTransportControlsPropertyChangedEventArgs, TypedEventHandler_SystemMediaTransportControls_SystemMediaTransportControlsPropertyChangedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_SystemMediaTransportControls_SystemMediaTransportControlsPropertyChangedEventArgs.js');
const { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_Object.js');
const { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs.js');
const { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserChangedEventArgs.js');
let __m_StorageFolder;
const __load_StorageFolder = () => (__m_StorageFolder ??= require('./StorageFolder.js'));
const __get_StorageFolder = () => __load_StorageFolder().StorageFolder;
let __m_QueryOptions;
const __load_QueryOptions = () => (__m_QueryOptions ??= require('./QueryOptions.js'));
const __get_QueryOptions = () => __load_QueryOptions().QueryOptions;
let __m_StreamedFileDataRequest;
const __load_StreamedFileDataRequest = () => (__m_StreamedFileDataRequest ??= require('./StreamedFileDataRequest.js'));
const __get_StreamedFileDataRequest = () => __load_StreamedFileDataRequest().StreamedFileDataRequest;
let __m_SystemMediaTransportControls;
const __load_SystemMediaTransportControls = () => (__m_SystemMediaTransportControls ??= require('./SystemMediaTransportControls.js'));
const __get_SystemMediaTransportControls = () => __load_SystemMediaTransportControls().SystemMediaTransportControls;
let __m_AutoRepeatModeChangeRequestedEventArgs;
const __load_AutoRepeatModeChangeRequestedEventArgs = () => (__m_AutoRepeatModeChangeRequestedEventArgs ??= require('./AutoRepeatModeChangeRequestedEventArgs.js'));
const __get_AutoRepeatModeChangeRequestedEventArgs = () => __load_AutoRepeatModeChangeRequestedEventArgs().AutoRepeatModeChangeRequestedEventArgs;
let __m_PlaybackPositionChangeRequestedEventArgs;
const __load_PlaybackPositionChangeRequestedEventArgs = () => (__m_PlaybackPositionChangeRequestedEventArgs ??= require('./PlaybackPositionChangeRequestedEventArgs.js'));
const __get_PlaybackPositionChangeRequestedEventArgs = () => __load_PlaybackPositionChangeRequestedEventArgs().PlaybackPositionChangeRequestedEventArgs;
let __m_PlaybackRateChangeRequestedEventArgs;
const __load_PlaybackRateChangeRequestedEventArgs = () => (__m_PlaybackRateChangeRequestedEventArgs ??= require('./PlaybackRateChangeRequestedEventArgs.js'));
const __get_PlaybackRateChangeRequestedEventArgs = () => __load_PlaybackRateChangeRequestedEventArgs().PlaybackRateChangeRequestedEventArgs;
let __m_ShuffleEnabledChangeRequestedEventArgs;
const __load_ShuffleEnabledChangeRequestedEventArgs = () => (__m_ShuffleEnabledChangeRequestedEventArgs ??= require('./ShuffleEnabledChangeRequestedEventArgs.js'));
const __get_ShuffleEnabledChangeRequestedEventArgs = () => __load_ShuffleEnabledChangeRequestedEventArgs().ShuffleEnabledChangeRequestedEventArgs;
let __m_SystemMediaTransportControlsButtonPressedEventArgs;
const __load_SystemMediaTransportControlsButtonPressedEventArgs = () => (__m_SystemMediaTransportControlsButtonPressedEventArgs ??= require('./SystemMediaTransportControlsButtonPressedEventArgs.js'));
const __get_SystemMediaTransportControlsButtonPressedEventArgs = () => __load_SystemMediaTransportControlsButtonPressedEventArgs().SystemMediaTransportControlsButtonPressedEventArgs;
let __m_SystemMediaTransportControlsPropertyChangedEventArgs;
const __load_SystemMediaTransportControlsPropertyChangedEventArgs = () => (__m_SystemMediaTransportControlsPropertyChangedEventArgs ??= require('./SystemMediaTransportControlsPropertyChangedEventArgs.js'));
const __get_SystemMediaTransportControlsPropertyChangedEventArgs = () => __load_SystemMediaTransportControlsPropertyChangedEventArgs().SystemMediaTransportControlsPropertyChangedEventArgs;
let __m_UserWatcher;
const __load_UserWatcher = () => (__m_UserWatcher ??= require('./UserWatcher.js'));
const __get_UserWatcher = () => __load_UserWatcher().UserWatcher;
let __m_UserAuthenticationStatusChangingEventArgs;
const __load_UserAuthenticationStatusChangingEventArgs = () => (__m_UserAuthenticationStatusChangingEventArgs ??= require('./UserAuthenticationStatusChangingEventArgs.js'));
const __get_UserAuthenticationStatusChangingEventArgs = () => __load_UserAuthenticationStatusChangingEventArgs().UserAuthenticationStatusChangingEventArgs;
let __m_UserChangedEventArgs;
const __load_UserChangedEventArgs = () => (__m_UserChangedEventArgs ??= require('./UserChangedEventArgs.js'));
const __get_UserChangedEventArgs = () => __load_UserChangedEventArgs().UserChangedEventArgs;

const _unwrap = (x) => x?._obj ?? x;

const IID_IStorageQueryResultBase = WinGuid.parse('c297d70d-7353-47ab-ba58-8c61425dc54b');

let _IStorageQueryResultBaseCache;
const _IStorageQueryResultBase = new Proxy({}, {
    get(_target, prop) {
        _IStorageQueryResultBaseCache ??= DynWinRtType.registerInterface(
        "IStorageQueryResultBase", IID_IStorageQueryResultBase)
        .addMethod("GetItemCountAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.u32())))
        .addMethod("get_Folder", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.Storage.StorageFolder', WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b'))))
        .addMethod("add_ContentsChanged", new DynWinRtMethodSig().addIn(DynWinRtType.parameterized(WinGuid.parse('9de1c534-6ae1-11e0-84e1-18a905bcc53f'), [DynWinRtType.interface(WinGuid.parse('c297d70d-7353-47ab-ba58-8c61425dc54b')), DynWinRtType.object()])).addOut(DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()])))
        .addMethod("remove_ContentsChanged", new DynWinRtMethodSig().addIn(DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()])))
        .addMethod("add_OptionsChanged", new DynWinRtMethodSig().addIn(DynWinRtType.parameterized(WinGuid.parse('9de1c534-6ae1-11e0-84e1-18a905bcc53f'), [DynWinRtType.interface(WinGuid.parse('c297d70d-7353-47ab-ba58-8c61425dc54b')), DynWinRtType.object()])).addOut(DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()])))
        .addMethod("remove_OptionsChanged", new DynWinRtMethodSig().addIn(DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()])))
        .addMethod("FindStartIndexAsync", new DynWinRtMethodSig().addIn(DynWinRtType.object()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.u32())))
        .addMethod("GetCurrentQueryOptions", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.Storage.Search.QueryOptions', WinGuid.parse('1e5e46ee-0f45-4838-a8e9-d0479d446c30'))))
        .addMethod("ApplyNewQueryOptions", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Windows.Storage.Search.QueryOptions', WinGuid.parse('1e5e46ee-0f45-4838-a8e9-d0479d446c30'))));
        const value = _IStorageQueryResultBaseCache[prop];
        return typeof value === 'function' ? value.bind(_IStorageQueryResultBaseCache) : value;
    }
});

function unpackEventRegistrationToken(v) {
    const s = v.asStruct();
    return { value: s.getI64(0) };
}
const _unpackEventRegistrationToken = unpackEventRegistrationToken;
const EventRegistrationToken_Type = DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()]);
const _EventRegistrationToken_Type = EventRegistrationToken_Type;
function packEventRegistrationToken(v) {
    const s = DynWinRtStruct.create(EventRegistrationToken_Type);
    s.setI64(0, v.value);
    return s;
}
const _packEventRegistrationToken = packEventRegistrationToken;

class IStorageQueryResultBase {
    _obj;

    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IStorageQueryResultBase(obj.cast(IID_IStorageQueryResultBase));
    }

    async getItemCountAsync(signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageQueryResultBase.method(6).invoke(this._obj, []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return _v.toNumber();
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }

    get folder() {
        return ((v) => v.isNull() ? null : (__get_StorageFolder())._fromNative(v))(_IStorageQueryResultBase.method(7).invoke(this._obj, []));
    }

    onContentsChanged(callback) {
        const wrapped = (__a0__, __a1__) => callback(((v) => v.isNull() ? null : new IStorageQueryResultBase(v))(__a0__), ((v) => v.isNull() ? null : v)(__a1__));
        const handler = DynWinRtDelegate.create(IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES, wrapped);
        const __token = _IStorageQueryResultBase.method(8).invoke(this._obj, [handler.toValue()]);
        return () => { void handler; _IStorageQueryResultBase.method(9).invoke(this._obj, [__token]); };
    }
    onceContentsChanged(callback) {
        const unsub = this.onContentsChanged((...args) => { unsub(); callback(...args); });
        return unsub;
    }
    offContentsChanged(token) {
        _IStorageQueryResultBase.method(9).invoke(this._obj, [token]);
    }

    offContentsChanged(token) {
        _IStorageQueryResultBase.method(9).invoke(this._obj, [token]);
    }

    onOptionsChanged(callback) {
        const wrapped = (__a0__, __a1__) => callback(((v) => v.isNull() ? null : new IStorageQueryResultBase(v))(__a0__), ((v) => v.isNull() ? null : v)(__a1__));
        const handler = DynWinRtDelegate.create(IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES, wrapped);
        const __token = _IStorageQueryResultBase.method(10).invoke(this._obj, [handler.toValue()]);
        return () => { void handler; _IStorageQueryResultBase.method(11).invoke(this._obj, [__token]); };
    }
    onceOptionsChanged(callback) {
        const unsub = this.onOptionsChanged((...args) => { unsub(); callback(...args); });
        return unsub;
    }
    offOptionsChanged(token) {
        _IStorageQueryResultBase.method(11).invoke(this._obj, [token]);
    }

    offOptionsChanged(token) {
        _IStorageQueryResultBase.method(11).invoke(this._obj, [token]);
    }

    async findStartIndexAsync(value, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageQueryResultBase.method(12).invoke(this._obj, [(value == null ? DynWinRtValue.nullValue() : _unwrap(value))]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return _v.toNumber();
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }

    getCurrentQueryOptions() {
        return ((v) => v.isNull() ? null : (__get_QueryOptions())._fromNative(v))(_IStorageQueryResultBase.method(13).invoke(this._obj, []));
    }

    applyNewQueryOptions(newQueryOptions) {
        _IStorageQueryResultBase.method(14).invoke(this._obj, [(newQueryOptions == null ? DynWinRtValue.nullValue() : _unwrap(newQueryOptions))]);
    }
}
exports.IID_IStorageQueryResultBase = IID_IStorageQueryResultBase;
exports.unpackEventRegistrationToken = unpackEventRegistrationToken;
exports.EventRegistrationToken_Type = EventRegistrationToken_Type;
exports.packEventRegistrationToken = packEventRegistrationToken;
exports.IStorageQueryResultBase = IStorageQueryResultBase;
