// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '../../dist/index.js';
import { StorageFile } from './StorageFile.js';

export declare const IID_IVectorView_StorageFile: WinGuid;

export declare class IVectorView_StorageFile {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IVectorView_StorageFile;

    getAt(index: number): StorageFile;

    get size(): number;

    getMany(startIndex: number, items: StorageFile[]): StorageFile[];


    get length(): number;


    at(index: number): StorageFile | undefined;


    toArray(): StorageFile[];


    [Symbol.iterator](): IterableIterator<StorageFile>;

    /**
     * Return the index of `value`, or -1 if not found.
     */
    indexOf(value: StorageFile): number;
}
