// Generated by dynwinrt-codegen — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('../../dist/index.js');
let __m_IVectorView_String;
const __load_IVectorView_String = () => (__m_IVectorView_String ??= require('./IVectorView_String.js'));
const __get_IVectorView_String = () => __load_IVectorView_String().IVectorView_String;
const { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } = require('./StreamedFileDataRequestedHandler.js');
const { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } = require('./TypedEventHandler_IStorageQueryResultBase_Object.js');
const { IID_TypedEventHandler_SystemMediaTransportControls_AutoRepeatModeChangeRequestedEventArgs, TypedEventHandler_SystemMediaTransportControls_AutoRepeatModeChangeRequestedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_SystemMediaTransportControls_AutoRepeatModeChangeRequestedEventArgs.js');
const { IID_TypedEventHandler_SystemMediaTransportControls_PlaybackPositionChangeRequestedEventArgs, TypedEventHandler_SystemMediaTransportControls_PlaybackPositionChangeRequestedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_SystemMediaTransportControls_PlaybackPositionChangeRequestedEventArgs.js');
const { IID_TypedEventHandler_SystemMediaTransportControls_PlaybackRateChangeRequestedEventArgs, TypedEventHandler_SystemMediaTransportControls_PlaybackRateChangeRequestedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_SystemMediaTransportControls_PlaybackRateChangeRequestedEventArgs.js');
const { IID_TypedEventHandler_SystemMediaTransportControls_ShuffleEnabledChangeRequestedEventArgs, TypedEventHandler_SystemMediaTransportControls_ShuffleEnabledChangeRequestedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_SystemMediaTransportControls_ShuffleEnabledChangeRequestedEventArgs.js');
const { IID_TypedEventHandler_SystemMediaTransportControls_SystemMediaTransportControlsButtonPressedEventArgs, TypedEventHandler_SystemMediaTransportControls_SystemMediaTransportControlsButtonPressedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_SystemMediaTransportControls_SystemMediaTransportControlsButtonPressedEventArgs.js');
const { IID_TypedEventHandler_SystemMediaTransportControls_SystemMediaTransportControlsPropertyChangedEventArgs, TypedEventHandler_SystemMediaTransportControls_SystemMediaTransportControlsPropertyChangedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_SystemMediaTransportControls_SystemMediaTransportControlsPropertyChangedEventArgs.js');
const { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_Object.js');
const { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs.js');
const { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserChangedEventArgs.js');
let __m_StreamedFileDataRequest;
const __load_StreamedFileDataRequest = () => (__m_StreamedFileDataRequest ??= require('./StreamedFileDataRequest.js'));
const __get_StreamedFileDataRequest = () => __load_StreamedFileDataRequest().StreamedFileDataRequest;
let __m_IStorageQueryResultBase;
const __load_IStorageQueryResultBase = () => (__m_IStorageQueryResultBase ??= require('./IStorageQueryResultBase.js'));
const __get_IStorageQueryResultBase = () => __load_IStorageQueryResultBase().IStorageQueryResultBase;
let __m_SystemMediaTransportControls;
const __load_SystemMediaTransportControls = () => (__m_SystemMediaTransportControls ??= require('./SystemMediaTransportControls.js'));
const __get_SystemMediaTransportControls = () => __load_SystemMediaTransportControls().SystemMediaTransportControls;
let __m_AutoRepeatModeChangeRequestedEventArgs;
const __load_AutoRepeatModeChangeRequestedEventArgs = () => (__m_AutoRepeatModeChangeRequestedEventArgs ??= require('./AutoRepeatModeChangeRequestedEventArgs.js'));
const __get_AutoRepeatModeChangeRequestedEventArgs = () => __load_AutoRepeatModeChangeRequestedEventArgs().AutoRepeatModeChangeRequestedEventArgs;
let __m_PlaybackPositionChangeRequestedEventArgs;
const __load_PlaybackPositionChangeRequestedEventArgs = () => (__m_PlaybackPositionChangeRequestedEventArgs ??= require('./PlaybackPositionChangeRequestedEventArgs.js'));
const __get_PlaybackPositionChangeRequestedEventArgs = () => __load_PlaybackPositionChangeRequestedEventArgs().PlaybackPositionChangeRequestedEventArgs;
let __m_PlaybackRateChangeRequestedEventArgs;
const __load_PlaybackRateChangeRequestedEventArgs = () => (__m_PlaybackRateChangeRequestedEventArgs ??= require('./PlaybackRateChangeRequestedEventArgs.js'));
const __get_PlaybackRateChangeRequestedEventArgs = () => __load_PlaybackRateChangeRequestedEventArgs().PlaybackRateChangeRequestedEventArgs;
let __m_ShuffleEnabledChangeRequestedEventArgs;
const __load_ShuffleEnabledChangeRequestedEventArgs = () => (__m_ShuffleEnabledChangeRequestedEventArgs ??= require('./ShuffleEnabledChangeRequestedEventArgs.js'));
const __get_ShuffleEnabledChangeRequestedEventArgs = () => __load_ShuffleEnabledChangeRequestedEventArgs().ShuffleEnabledChangeRequestedEventArgs;
let __m_SystemMediaTransportControlsButtonPressedEventArgs;
const __load_SystemMediaTransportControlsButtonPressedEventArgs = () => (__m_SystemMediaTransportControlsButtonPressedEventArgs ??= require('./SystemMediaTransportControlsButtonPressedEventArgs.js'));
const __get_SystemMediaTransportControlsButtonPressedEventArgs = () => __load_SystemMediaTransportControlsButtonPressedEventArgs().SystemMediaTransportControlsButtonPressedEventArgs;
let __m_SystemMediaTransportControlsPropertyChangedEventArgs;
const __load_SystemMediaTransportControlsPropertyChangedEventArgs = () => (__m_SystemMediaTransportControlsPropertyChangedEventArgs ??= require('./SystemMediaTransportControlsPropertyChangedEventArgs.js'));
const __get_SystemMediaTransportControlsPropertyChangedEventArgs = () => __load_SystemMediaTransportControlsPropertyChangedEventArgs().SystemMediaTransportControlsPropertyChangedEventArgs;
let __m_UserWatcher;
const __load_UserWatcher = () => (__m_UserWatcher ??= require('./UserWatcher.js'));
const __get_UserWatcher = () => __load_UserWatcher().UserWatcher;
let __m_UserAuthenticationStatusChangingEventArgs;
const __load_UserAuthenticationStatusChangingEventArgs = () => (__m_UserAuthenticationStatusChangingEventArgs ??= require('./UserAuthenticationStatusChangingEventArgs.js'));
const __get_UserAuthenticationStatusChangingEventArgs = () => __load_UserAuthenticationStatusChangingEventArgs().UserAuthenticationStatusChangingEventArgs;
let __m_UserChangedEventArgs;
const __load_UserChangedEventArgs = () => (__m_UserChangedEventArgs ??= require('./UserChangedEventArgs.js'));
const __get_UserChangedEventArgs = () => __load_UserChangedEventArgs().UserChangedEventArgs;

const _unwrap = (x) => x?._obj ?? x;

const IID_IVector_String = DynWinRtType.parameterized(WinGuid.parse('913337e9-11a1-4345-a3a2-4e7f956e222d'), [DynWinRtType.hstring()]).iid();

let _IVector_StringCache;
const _IVector_String = new Proxy({}, {
    get(_target, prop) {
        _IVector_StringCache ??= DynWinRtType.registerInterface(
        "IVector_String", IID_IVector_String)
        .addMethod("GetAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addOut(DynWinRtType.hstring()))
        .addMethod("get_Size", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
        .addMethod("GetView", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.hstring()])))
        .addMethod("IndexOf", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.u32()).addOut(DynWinRtType.boolType()))
        .addMethod("SetAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addIn(DynWinRtType.hstring()))
        .addMethod("InsertAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addIn(DynWinRtType.hstring()))
        .addMethod("RemoveAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()))
        .addMethod("Append", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()))
        .addMethod("RemoveAtEnd", new DynWinRtMethodSig())
        .addMethod("Clear", new DynWinRtMethodSig())
        .addMethod("GetMany", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addOutFill(DynWinRtType.arrayType(DynWinRtType.hstring())).addOut(DynWinRtType.u32()))
        .addMethod("ReplaceAll", new DynWinRtMethodSig().addIn(DynWinRtType.arrayType(DynWinRtType.hstring())));
        const value = _IVector_StringCache[prop];
        return typeof value === 'function' ? value.bind(_IVector_StringCache) : value;
    }
});

class IVector_String {
    _obj;

    constructor(obj) {
        this._obj = obj.cast(IID_IVector_String);
    }

    static from(obj) {
        return new IVector_String(obj.cast(IID_IVector_String));
    }

    getAt(index) {
        return _IVector_String.method(6).invoke(this._obj, [DynWinRtValue.u32(index)]).toString();
    }

    get size() {
        return _IVector_String.method(7).invoke(this._obj, []).toNumber();
    }

    getView() {
        return ((v) => v.isNull() ? null : new (__get_IVectorView_String())(v))(_IVector_String.method(8).invoke(this._obj, []));
    }

    setAt(index, value) {
        _IVector_String.method(10).invoke(this._obj, [DynWinRtValue.u32(index), DynWinRtValue.hstring(value)]);
    }

    insertAt(index, value) {
        _IVector_String.method(11).invoke(this._obj, [DynWinRtValue.u32(index), DynWinRtValue.hstring(value)]);
    }

    removeAt(index) {
        _IVector_String.method(12).invoke(this._obj, [DynWinRtValue.u32(index)]);
    }

    append(value) {
        _IVector_String.method(13).invoke(this._obj, [DynWinRtValue.hstring(value)]);
    }

    removeAtEnd() {
        _IVector_String.method(14).invoke(this._obj, []);
    }

    clear() {
        _IVector_String.method(15).invoke(this._obj, []);
    }

    /** Alias for {@link size}; matches Array.length / TypedArray.length. */
    get length() { return this.size; }

    /** Element at `index`. Negative indices count from the end (Array.prototype.at semantics). */
    at(index) {
        const n = this.size;
        const i = index < 0 ? n + index : index;
        if (i < 0 || i >= n) return undefined;
        return this.getAt(i);
    }

    /** Materialize as a plain JS array. */
    toArray() {
        const n = this.size;
        const out = new Array(n);
        for (let i = 0; i < n; i++) out[i] = this.getAt(i);
        return out;
    }

    *[Symbol.iterator]() {
        const n = this.size;
        for (let i = 0; i < n; i++) yield this.getAt(i);
    }

    /**
     * Return the index of `value`, or -1 if not found.
     */
    indexOf(value) {
        return (() => { const _r = _IVector_String.method(9).invokeAll(this._obj, [DynWinRtValue.hstring(value)]); return _r[1].toBool() ? _r[0].toNumber() : -1; })();
    }

    /**
     * Copy elements starting at `startIndex` into a new array of length `count`.
     */
    getMany(startIndex, count) {
        return (() => { const _a = DynWinRtArray.fromStringValues(new Array(count).fill('')); const _r = _IVector_String.method(16).invokeAll(this._obj, [DynWinRtValue.u32(startIndex), _a.toValue()]); return _r[0].asArray().toStringVec().slice(0, _r[1].toNumber()); })();
    }

    /**
     * Replace all elements in the vector with the provided items.
     */
    replaceAll(items) {
        _IVector_String.method(17).invoke(this._obj, [DynWinRtArray.fromStringValues(items).toValue()]);
    }

    /**
     * Create a new IVector from an array of items.
     */
    static create(items) {
        return new IVector_String(DynWinRtValue.createVector(items.map(i => _unwrap(i)), DynWinRtType.hstring()));
    }
}
exports.IID_IVector_String = IID_IVector_String;
exports.IVector_String = IVector_String;
