// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '../../dist/index.js';
import { IStorageItem } from './IStorageItem.js';

export declare const IID_IVectorView_IStorageItem: WinGuid;

export declare class IVectorView_IStorageItem {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IVectorView_IStorageItem;

    getAt(index: number): IStorageItem;

    get size(): number;

    getMany(startIndex: number, items: IStorageItem[]): IStorageItem[];


    get length(): number;


    at(index: number): IStorageItem | undefined;


    toArray(): IStorageItem[];


    [Symbol.iterator](): IterableIterator<IStorageItem>;

    /**
     * Return the index of `value`, or -1 if not found.
     */
    indexOf(value: IStorageItem): number;
}
