// Generated by dynwinrt-codegen — do not edit

const MediaPlaybackAutoRepeatMode = Object.freeze({
    None: 0,
    Track: 1,
    List: 2,
});
exports.MediaPlaybackAutoRepeatMode = MediaPlaybackAutoRepeatMode;
