// Generated by dynwinrt-codegen — do not edit
export type MediaPlaybackType = (typeof MediaPlaybackType)[keyof typeof MediaPlaybackType];
export declare const MediaPlaybackType: {
    readonly Unknown: 0;
    readonly Music: 1;
    readonly Video: 2;
    readonly Image: 3;
};
