// Generated by dynwinrt-codegen — do not edit

const PhotoOrientation = Object.freeze({
    Unspecified: 0,
    Normal: 1,
    FlipHorizontal: 2,
    Rotate180: 3,
    FlipVertical: 4,
    Transpose: 5,
    Rotate270: 6,
    Transverse: 7,
    Rotate90: 8,
});
exports.PhotoOrientation = PhotoOrientation;
