// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtValue, DynWinRtStruct, WinGuid } from '../../dist/index.js';

export interface TimeSpan {
    duration: bigint;
}
/** Convert a WinRT struct value into a `TimeSpan` object. */
export declare function unpackTimeSpan(v: DynWinRtValue): TimeSpan;
export declare const TimeSpan_Type: DynWinRtType;
/** Convert a `TimeSpan` object into a WinRT struct value. */
export declare function packTimeSpan(v: TimeSpan): DynWinRtStruct;

export declare const IID_PlaybackPositionChangeRequestedEventArgs: WinGuid;
export declare class PlaybackPositionChangeRequestedEventArgs {
    private constructor();
    get requestedPlaybackPosition(): TimeSpan;
}
