// Generated by dynwinrt-codegen — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('../../dist/index.js');
let __m_lifetime;
const __load_lifetime = () => (__m_lifetime ??= require('./lifetime.js'));
const __get_trackProjectedValue = () => __load_lifetime().trackProjectedValue;

const IID_IPlaybackRateChangeRequestedEventArgs = WinGuid.parse('2ce2c41f-3cd6-4f77-9ba7-eb27c26a2140');
const IID_PlaybackRateChangeRequestedEventArgs = WinGuid.parse('2ce2c41f-3cd6-4f77-9ba7-eb27c26a2140');

let _IPlaybackRateChangeRequestedEventArgsCache;
const _IPlaybackRateChangeRequestedEventArgs = new Proxy({}, {
    get(_target, prop) {
        _IPlaybackRateChangeRequestedEventArgsCache ??= DynWinRtType.registerInterface(
        "IPlaybackRateChangeRequestedEventArgs", IID_IPlaybackRateChangeRequestedEventArgs)
        .addMethod("get_RequestedPlaybackRate", new DynWinRtMethodSig().addOut(DynWinRtType.f64()));
        const value = _IPlaybackRateChangeRequestedEventArgsCache[prop];
        return typeof value === 'function' ? value.bind(_IPlaybackRateChangeRequestedEventArgsCache) : value;
    }
});

class PlaybackRateChangeRequestedEventArgs {
    _obj;

    constructor() {
        throw new TypeError('PlaybackRateChangeRequestedEventArgs cannot be constructed directly.');
    }
    static _fromNative(obj) {
        return Object.assign(Object.create(PlaybackRateChangeRequestedEventArgs.prototype), { _obj: (__get_trackProjectedValue())((__get_trackProjectedValue())(obj, 'PlaybackRateChangeRequestedEventArgs').cast(IID_IPlaybackRateChangeRequestedEventArgs), 'PlaybackRateChangeRequestedEventArgs') });
    }
    get requestedPlaybackRate() {
        return _IPlaybackRateChangeRequestedEventArgs.method(6).invoke(this._obj, []).toF64();
    }
}
exports.IID_PlaybackRateChangeRequestedEventArgs = IID_PlaybackRateChangeRequestedEventArgs;
exports.PlaybackRateChangeRequestedEventArgs = PlaybackRateChangeRequestedEventArgs;
