// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtValue, DynWinRtStruct, WinGuid } from '../../dist/index.js';
import { IIterable_String } from './IIterable_String.js';
import { IVector_SortEntry } from './IVector_SortEntry.js';
import { IVector_String } from './IVector_String.js';
import { PropertyPrefetchOptions } from './PropertyPrefetchOptions.js';
import { ThumbnailMode } from './ThumbnailMode.js';
import { ThumbnailOptions } from './ThumbnailOptions.js';
import { CommonFileQuery } from './CommonFileQuery.js';
import { CommonFolderQuery } from './CommonFolderQuery.js';
import { DateStackOption } from './DateStackOption.js';
import { FolderDepth } from './FolderDepth.js';
import { IndexerOption } from './IndexerOption.js';

export interface SortEntry {
    propertyName: string;
    ascendingOrder: boolean;
}
/** Convert a WinRT struct value into a `SortEntry` object. */
export declare function unpackSortEntry(v: DynWinRtValue): SortEntry;
export declare const SortEntry_Type: DynWinRtType;
/** Convert a `SortEntry` object into a WinRT struct value. */
export declare function packSortEntry(v: SortEntry): DynWinRtStruct;

export declare const IID_QueryOptions: WinGuid;
export declare class QueryOptions {
    constructor();
    constructor(query: CommonFolderQuery);
    constructor(query: CommonFileQuery, fileTypeFilter: IIterable_String | string[]);
    /**
     * Create a new `QueryOptions` instance.
     */
    static createDefault(): QueryOptions;
    static createCommonFileQuery(query: CommonFileQuery, fileTypeFilter: IIterable_String | string[]): QueryOptions;
    static createCommonFolderQuery(query: CommonFolderQuery): QueryOptions;
    get fileTypeFilter(): IVector_String;
    get folderDepth(): FolderDepth;
    set folderDepth(value: FolderDepth);
    get applicationSearchFilter(): string;
    set applicationSearchFilter(value: string);
    get userSearchFilter(): string;
    set userSearchFilter(value: string);
    get language(): string;
    set language(value: string);
    get indexerOption(): IndexerOption;
    set indexerOption(value: IndexerOption);
    get sortOrder(): IVector_SortEntry;
    get groupPropertyName(): string;
    get dateStackOption(): DateStackOption;
    saveToString(): string;
    loadFromString(value: string): void;
    setThumbnailPrefetch(mode: ThumbnailMode, requestedSize: number, options: ThumbnailOptions): void;
    setPropertyPrefetch(options: PropertyPrefetchOptions, propertiesToRetrieve: IIterable_String | string[]): void;
    /** Cast this object to another WinRT interface. */
    as<T>(InterfaceClass: { from(obj: any): T }): T;
    get storageProviderIdFilter(): IVector_String;
    get includeLocalSemanticIndex(): boolean;
    set includeLocalSemanticIndex(value: boolean);
    get includeCloudProviders(): boolean;
    set includeCloudProviders(value: boolean);
}

export declare class IQueryOptionsWithProviderFilter {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IQueryOptionsWithProviderFilter;

    get storageProviderIdFilter(): IVector_String;
}

export declare class IQueryOptionsAdditionalSearchSources {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IQueryOptionsAdditionalSearchSources;

    get includeLocalSemanticIndex(): boolean;
    set includeLocalSemanticIndex(value: boolean);

    get includeCloudProviders(): boolean;
    set includeCloudProviders(value: boolean);
}
