// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '../../dist/index.js';

export declare const IID_ShuffleEnabledChangeRequestedEventArgs: WinGuid;
export declare class ShuffleEnabledChangeRequestedEventArgs {
    private constructor();
    get requestedShuffleEnabled(): boolean;
}
