// Generated by dynwinrt-codegen — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('../../dist/index.js');
let __m_lifetime;
const __load_lifetime = () => (__m_lifetime ??= require('./lifetime.js'));
const __get_trackProjectedValue = () => __load_lifetime().trackProjectedValue;

const IID_IShuffleEnabledChangeRequestedEventArgs = WinGuid.parse('49b593fe-4fd0-4666-a314-c0e01940d302');
const IID_ShuffleEnabledChangeRequestedEventArgs = WinGuid.parse('49b593fe-4fd0-4666-a314-c0e01940d302');

let _IShuffleEnabledChangeRequestedEventArgsCache;
const _IShuffleEnabledChangeRequestedEventArgs = new Proxy({}, {
    get(_target, prop) {
        _IShuffleEnabledChangeRequestedEventArgsCache ??= DynWinRtType.registerInterface(
        "IShuffleEnabledChangeRequestedEventArgs", IID_IShuffleEnabledChangeRequestedEventArgs)
        .addMethod("get_RequestedShuffleEnabled", new DynWinRtMethodSig().addOut(DynWinRtType.boolType()));
        const value = _IShuffleEnabledChangeRequestedEventArgsCache[prop];
        return typeof value === 'function' ? value.bind(_IShuffleEnabledChangeRequestedEventArgsCache) : value;
    }
});

class ShuffleEnabledChangeRequestedEventArgs {
    _obj;

    constructor() {
        throw new TypeError('ShuffleEnabledChangeRequestedEventArgs cannot be constructed directly.');
    }
    static _fromNative(obj) {
        return Object.assign(Object.create(ShuffleEnabledChangeRequestedEventArgs.prototype), { _obj: (__get_trackProjectedValue())((__get_trackProjectedValue())(obj, 'ShuffleEnabledChangeRequestedEventArgs').cast(IID_IShuffleEnabledChangeRequestedEventArgs), 'ShuffleEnabledChangeRequestedEventArgs') });
    }
    get requestedShuffleEnabled() {
        return _IShuffleEnabledChangeRequestedEventArgs.method(6).invoke(this._obj, []).toBool();
    }
}
exports.IID_ShuffleEnabledChangeRequestedEventArgs = IID_ShuffleEnabledChangeRequestedEventArgs;
exports.ShuffleEnabledChangeRequestedEventArgs = ShuffleEnabledChangeRequestedEventArgs;
