// Generated by dynwinrt-codegen — do not edit
export type SoundLevel = (typeof SoundLevel)[keyof typeof SoundLevel];
export declare const SoundLevel: {
    readonly Muted: 0;
    readonly Low: 1;
    readonly Full: 2;
};
