// Generated by dynwinrt-codegen — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } = require('../../dist/index.js');
const { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } = require('./StreamedFileDataRequestedHandler.js');
let __m_Uri;
const __load_Uri = () => (__m_Uri ??= require('./Uri.js'));
const __get_Uri = () => __load_Uri().Uri;
let __m_FileAccessMode;
const __load_FileAccessMode = () => (__m_FileAccessMode ??= require('./FileAccessMode.js'));
const __get_FileAccessMode = () => __load_FileAccessMode().FileAccessMode;
let __m_FileAttributes;
const __load_FileAttributes = () => (__m_FileAttributes ??= require('./FileAttributes.js'));
const __get_FileAttributes = () => __load_FileAttributes().FileAttributes;
const { IID_IStorageFile } = require('./IStorageFile.js');
let __m_IStorageFile;
const __load_IStorageFile = () => (__m_IStorageFile ??= require('./IStorageFile.js'));
const __get_IStorageFile = () => __load_IStorageFile().IStorageFile;
const { IID_IStorageFolder } = require('./IStorageFolder.js');
let __m_IStorageFolder;
const __load_IStorageFolder = () => (__m_IStorageFolder ??= require('./IStorageFolder.js'));
const __get_IStorageFolder = () => __load_IStorageFolder().IStorageFolder;
const { IID_IStorageItem } = require('./IStorageItem.js');
let __m_IStorageItem;
const __load_IStorageItem = () => (__m_IStorageItem ??= require('./IStorageItem.js'));
const __get_IStorageItem = () => __load_IStorageItem().IStorageItem;
let __m_NameCollisionOption;
const __load_NameCollisionOption = () => (__m_NameCollisionOption ??= require('./NameCollisionOption.js'));
const __get_NameCollisionOption = () => __load_NameCollisionOption().NameCollisionOption;
let __m_StorageDeleteOption;
const __load_StorageDeleteOption = () => (__m_StorageDeleteOption ??= require('./StorageDeleteOption.js'));
const __get_StorageDeleteOption = () => __load_StorageDeleteOption().StorageDeleteOption;
let __m_StorageFolder;
const __load_StorageFolder = () => (__m_StorageFolder ??= require('./StorageFolder.js'));
const __get_StorageFolder = () => __load_StorageFolder().StorageFolder;
let __m_StorageItemTypes;
const __load_StorageItemTypes = () => (__m_StorageItemTypes ??= require('./StorageItemTypes.js'));
const __get_StorageItemTypes = () => __load_StorageItemTypes().StorageItemTypes;
let __m_StorageOpenOptions;
const __load_StorageOpenOptions = () => (__m_StorageOpenOptions ??= require('./StorageOpenOptions.js'));
const __get_StorageOpenOptions = () => __load_StorageOpenOptions().StorageOpenOptions;
let __m_StorageProvider;
const __load_StorageProvider = () => (__m_StorageProvider ??= require('./StorageProvider.js'));
const __get_StorageProvider = () => __load_StorageProvider().StorageProvider;
let __m_StorageStreamTransaction;
const __load_StorageStreamTransaction = () => (__m_StorageStreamTransaction ??= require('./StorageStreamTransaction.js'));
const __get_StorageStreamTransaction = () => __load_StorageStreamTransaction().StorageStreamTransaction;
let __m_BasicProperties;
const __load_BasicProperties = () => (__m_BasicProperties ??= require('./BasicProperties.js'));
const __get_BasicProperties = () => __load_BasicProperties().BasicProperties;
let __m_StorageItemContentProperties;
const __load_StorageItemContentProperties = () => (__m_StorageItemContentProperties ??= require('./StorageItemContentProperties.js'));
const __get_StorageItemContentProperties = () => __load_StorageItemContentProperties().StorageItemContentProperties;
let __m_StorageItemThumbnail;
const __load_StorageItemThumbnail = () => (__m_StorageItemThumbnail ??= require('./StorageItemThumbnail.js'));
const __get_StorageItemThumbnail = () => __load_StorageItemThumbnail().StorageItemThumbnail;
let __m_ThumbnailMode;
const __load_ThumbnailMode = () => (__m_ThumbnailMode ??= require('./ThumbnailMode.js'));
const __get_ThumbnailMode = () => __load_ThumbnailMode().ThumbnailMode;
let __m_ThumbnailOptions;
const __load_ThumbnailOptions = () => (__m_ThumbnailOptions ??= require('./ThumbnailOptions.js'));
const __get_ThumbnailOptions = () => __load_ThumbnailOptions().ThumbnailOptions;
const { IID_IInputStream } = require('./IInputStream.js');
let __m_IInputStream;
const __load_IInputStream = () => (__m_IInputStream ??= require('./IInputStream.js'));
const __get_IInputStream = () => __load_IInputStream().IInputStream;
const { IID_IRandomAccessStream } = require('./IRandomAccessStream.js');
let __m_IRandomAccessStream;
const __load_IRandomAccessStream = () => (__m_IRandomAccessStream ??= require('./IRandomAccessStream.js'));
const __get_IRandomAccessStream = () => __load_IRandomAccessStream().IRandomAccessStream;
const { IID_IRandomAccessStreamReference } = require('./IRandomAccessStreamReference.js');
let __m_IRandomAccessStreamReference;
const __load_IRandomAccessStreamReference = () => (__m_IRandomAccessStreamReference ??= require('./IRandomAccessStreamReference.js'));
const __get_IRandomAccessStreamReference = () => __load_IRandomAccessStreamReference().IRandomAccessStreamReference;
const { IID_IRandomAccessStreamWithContentType } = require('./IRandomAccessStreamWithContentType.js');
let __m_IRandomAccessStreamWithContentType;
const __load_IRandomAccessStreamWithContentType = () => (__m_IRandomAccessStreamWithContentType ??= require('./IRandomAccessStreamWithContentType.js'));
const __get_IRandomAccessStreamWithContentType = () => __load_IRandomAccessStreamWithContentType().IRandomAccessStreamWithContentType;
let __m_User;
const __load_User = () => (__m_User ??= require('./User.js'));
const __get_User = () => __load_User().User;
const { IID_IStorageItemProperties } = require('./IStorageItemProperties.js');
let __m_IStorageItemProperties;
const __load_IStorageItemProperties = () => (__m_IStorageItemProperties ??= require('./IStorageItemProperties.js'));
const __get_IStorageItemProperties = () => __load_IStorageItemProperties().IStorageItemProperties;
const { IID_IStorageItemProperties2 } = require('./IStorageItemProperties2.js');
let __m_IStorageItemProperties2;
const __load_IStorageItemProperties2 = () => (__m_IStorageItemProperties2 ??= require('./IStorageItemProperties2.js'));
const __get_IStorageItemProperties2 = () => __load_IStorageItemProperties2().IStorageItemProperties2;
const { IID_IStorageItem2 } = require('./IStorageItem2.js');
let __m_IStorageItem2;
const __load_IStorageItem2 = () => (__m_IStorageItem2 ??= require('./IStorageItem2.js'));
const __get_IStorageItem2 = () => __load_IStorageItem2().IStorageItem2;
const { IID_IStorageItemPropertiesWithProvider } = require('./IStorageItemPropertiesWithProvider.js');
let __m_IStorageItemPropertiesWithProvider;
const __load_IStorageItemPropertiesWithProvider = () => (__m_IStorageItemPropertiesWithProvider ??= require('./IStorageItemPropertiesWithProvider.js'));
const __get_IStorageItemPropertiesWithProvider = () => __load_IStorageItemPropertiesWithProvider().IStorageItemPropertiesWithProvider;
let __m_StreamedFileDataRequest;
const __load_StreamedFileDataRequest = () => (__m_StreamedFileDataRequest ??= require('./StreamedFileDataRequest.js'));
const __get_StreamedFileDataRequest = () => __load_StreamedFileDataRequest().StreamedFileDataRequest;
let __m_lifetime;
const __load_lifetime = () => (__m_lifetime ??= require('./lifetime.js'));
const __get_trackProjectedValue = () => __load_lifetime().trackProjectedValue;

const _unwrap = (x) => x?._obj ?? x;

const IID_IStorageFileStatics = WinGuid.parse('5984c710-daf2-43c8-8bb4-a4d3eacfd03f');
const IID_IStorageFileStatics2 = WinGuid.parse('5c76a781-212e-4af9-8f04-740cae108974');
const IID_IInputStreamReference = WinGuid.parse('43929d18-5ec9-4b5a-919c-4205b0c804b6');
const IID_IStorageFilePropertiesWithAvailability = WinGuid.parse('afcbbe9b-582b-4133-9648-e44ca46ee491');
const IID_IStorageFile2 = WinGuid.parse('954e4bcf-0a77-42fb-b777-c2ed58a52e44');
const IID_StorageFile = WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea');

let _IStorageFileCache;
const _IStorageFile = new Proxy({}, {
    get(_target, prop) {
        _IStorageFileCache ??= DynWinRtType.registerInterface(
        "IStorageFile", IID_IStorageFile)
        .addMethod("get_FileType", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
        .addMethod("get_ContentType", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
        .addMethod("OpenAsync", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.FileAccessMode', ['Read', 'ReadWrite'], [0, 1])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.interface(WinGuid.parse('905a0fe1-bc53-11df-8c49-001e4fc686da')))))
        .addMethod("OpenTransactedWriteAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageStreamTransaction', WinGuid.parse('f67cf363-a53d-4d94-ae2c-67232d93acdd')))))
        .addMethod("CopyOverloadDefaultNameAndOptions", new DynWinRtMethodSig().addIn(DynWinRtType.interface(WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b'))).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea')))))
        .addMethod("CopyOverloadDefaultOptions", new DynWinRtMethodSig().addIn(DynWinRtType.interface(WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b'))).addIn(DynWinRtType.hstring()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea')))))
        .addMethod("CopyOverload", new DynWinRtMethodSig().addIn(DynWinRtType.interface(WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b'))).addIn(DynWinRtType.hstring()).addIn(DynWinRtType.enumType('Windows.Storage.NameCollisionOption', ['GenerateUniqueName', 'ReplaceExisting', 'FailIfExists'], [0, 1, 2])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea')))))
        .addMethod("CopyAndReplaceAsync", new DynWinRtMethodSig().addIn(DynWinRtType.interface(WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea'))).addOut(DynWinRtType.iAsyncAction()))
        .addMethod("MoveOverloadDefaultNameAndOptions", new DynWinRtMethodSig().addIn(DynWinRtType.interface(WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b'))).addOut(DynWinRtType.iAsyncAction()))
        .addMethod("MoveOverloadDefaultOptions", new DynWinRtMethodSig().addIn(DynWinRtType.interface(WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b'))).addIn(DynWinRtType.hstring()).addOut(DynWinRtType.iAsyncAction()))
        .addMethod("MoveOverload", new DynWinRtMethodSig().addIn(DynWinRtType.interface(WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b'))).addIn(DynWinRtType.hstring()).addIn(DynWinRtType.enumType('Windows.Storage.NameCollisionOption', ['GenerateUniqueName', 'ReplaceExisting', 'FailIfExists'], [0, 1, 2])).addOut(DynWinRtType.iAsyncAction()))
        .addMethod("MoveAndReplaceAsync", new DynWinRtMethodSig().addIn(DynWinRtType.interface(WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea'))).addOut(DynWinRtType.iAsyncAction()));
        const value = _IStorageFileCache[prop];
        return typeof value === 'function' ? value.bind(_IStorageFileCache) : value;
    }
});

let _IStorageFileStaticsCache;
const _IStorageFileStatics = new Proxy({}, {
    get(_target, prop) {
        _IStorageFileStaticsCache ??= DynWinRtType.registerInterface(
        "IStorageFileStatics", IID_IStorageFileStatics)
        .addMethod("GetFileFromPathAsync", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea')))))
        .addMethod("GetFileFromApplicationUriAsync", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Windows.Foundation.Uri', WinGuid.parse('9e365e57-48b2-4160-956f-c7385120bbfc'))).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea')))))
        .addMethod("CreateStreamedFileAsync", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addIn(DynWinRtType.interface(WinGuid.parse('fef6a824-2fe1-4d07-a35b-b77c50b5f4cc'))).addIn(DynWinRtType.interface(WinGuid.parse('33ee3134-1dd6-4e3a-8067-d1c162e8642b'))).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea')))))
        .addMethod("ReplaceWithStreamedFileAsync", new DynWinRtMethodSig().addIn(DynWinRtType.interface(WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea'))).addIn(DynWinRtType.interface(WinGuid.parse('fef6a824-2fe1-4d07-a35b-b77c50b5f4cc'))).addIn(DynWinRtType.interface(WinGuid.parse('33ee3134-1dd6-4e3a-8067-d1c162e8642b'))).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea')))))
        .addMethod("CreateStreamedFileFromUriAsync", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addIn(DynWinRtType.runtimeClass('Windows.Foundation.Uri', WinGuid.parse('9e365e57-48b2-4160-956f-c7385120bbfc'))).addIn(DynWinRtType.interface(WinGuid.parse('33ee3134-1dd6-4e3a-8067-d1c162e8642b'))).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea')))))
        .addMethod("ReplaceWithStreamedFileFromUriAsync", new DynWinRtMethodSig().addIn(DynWinRtType.interface(WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea'))).addIn(DynWinRtType.runtimeClass('Windows.Foundation.Uri', WinGuid.parse('9e365e57-48b2-4160-956f-c7385120bbfc'))).addIn(DynWinRtType.interface(WinGuid.parse('33ee3134-1dd6-4e3a-8067-d1c162e8642b'))).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea')))));
        const value = _IStorageFileStaticsCache[prop];
        return typeof value === 'function' ? value.bind(_IStorageFileStaticsCache) : value;
    }
});

let _IStorageFileStatics2Cache;
const _IStorageFileStatics2 = new Proxy({}, {
    get(_target, prop) {
        _IStorageFileStatics2Cache ??= DynWinRtType.registerInterface(
        "IStorageFileStatics2", IID_IStorageFileStatics2)
        .addMethod("GetFileFromPathForUserAsync", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Windows.System.User', WinGuid.parse('df9a26c6-e746-4bcd-b5d4-120103c4209b'))).addIn(DynWinRtType.hstring()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea')))));
        const value = _IStorageFileStatics2Cache[prop];
        return typeof value === 'function' ? value.bind(_IStorageFileStatics2Cache) : value;
    }
});

let _IInputStreamReferenceCache;
const _IInputStreamReference = new Proxy({}, {
    get(_target, prop) {
        _IInputStreamReferenceCache ??= DynWinRtType.registerInterface(
        "IInputStreamReference", IID_IInputStreamReference)
        .addMethod("OpenSequentialReadAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.interface(WinGuid.parse('905a0fe2-bc53-11df-8c49-001e4fc686da')))));
        const value = _IInputStreamReferenceCache[prop];
        return typeof value === 'function' ? value.bind(_IInputStreamReferenceCache) : value;
    }
});

let _IRandomAccessStreamReferenceCache;
const _IRandomAccessStreamReference = new Proxy({}, {
    get(_target, prop) {
        _IRandomAccessStreamReferenceCache ??= DynWinRtType.registerInterface(
        "IRandomAccessStreamReference", IID_IRandomAccessStreamReference)
        .addMethod("OpenReadAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.interface(WinGuid.parse('cc254827-4b3d-438f-9232-10c76bc7e038')))));
        const value = _IRandomAccessStreamReferenceCache[prop];
        return typeof value === 'function' ? value.bind(_IRandomAccessStreamReferenceCache) : value;
    }
});

let _IStorageItemCache;
const _IStorageItem = new Proxy({}, {
    get(_target, prop) {
        _IStorageItemCache ??= DynWinRtType.registerInterface(
        "IStorageItem", IID_IStorageItem)
        .addMethod("RenameAsyncOverloadDefaultOptions", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.iAsyncAction()))
        .addMethod("RenameAsync", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addIn(DynWinRtType.enumType('Windows.Storage.NameCollisionOption', ['GenerateUniqueName', 'ReplaceExisting', 'FailIfExists'], [0, 1, 2])).addOut(DynWinRtType.iAsyncAction()))
        .addMethod("DeleteAsyncOverloadDefaultOptions", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncAction()))
        .addMethod("DeleteAsync", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.StorageDeleteOption', ['Default', 'PermanentDelete'], [0, 1])).addOut(DynWinRtType.iAsyncAction()))
        .addMethod("GetBasicPropertiesAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.FileProperties.BasicProperties', WinGuid.parse('d05d55db-785e-4a66-be02-9beec58aea81')))))
        .addMethod("get_Name", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
        .addMethod("get_Path", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
        .addMethod("get_Attributes", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Windows.Storage.FileAttributes', ['Normal', 'ReadOnly', 'Directory', 'Archive', 'Temporary', 'LocallyIncomplete'], [0, 1, 16, 32, 256, 512])))
        .addMethod("get_DateCreated", new DynWinRtMethodSig().addOut(DynWinRtType.structType('Windows.Foundation.DateTime', [DynWinRtType.i64()])))
        .addMethod("IsOfType", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.StorageItemTypes', ['None', 'File', 'Folder'], [0, 1, 2])).addOut(DynWinRtType.boolType()));
        const value = _IStorageItemCache[prop];
        return typeof value === 'function' ? value.bind(_IStorageItemCache) : value;
    }
});

let _IStorageItemPropertiesCache;
const _IStorageItemProperties = new Proxy({}, {
    get(_target, prop) {
        _IStorageItemPropertiesCache ??= DynWinRtType.registerInterface(
        "IStorageItemProperties", IID_IStorageItemProperties)
        .addMethod("GetThumbnailAsyncOverloadDefaultSizeDefaultOptions", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.FileProperties.ThumbnailMode', ['PicturesView', 'VideosView', 'MusicView', 'DocumentsView', 'ListView', 'SingleItem'], [0, 1, 2, 3, 4, 5])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.FileProperties.StorageItemThumbnail', WinGuid.parse('cc254827-4b3d-438f-9232-10c76bc7e038')))))
        .addMethod("GetThumbnailAsyncOverloadDefaultOptions", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.FileProperties.ThumbnailMode', ['PicturesView', 'VideosView', 'MusicView', 'DocumentsView', 'ListView', 'SingleItem'], [0, 1, 2, 3, 4, 5])).addIn(DynWinRtType.u32()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.FileProperties.StorageItemThumbnail', WinGuid.parse('cc254827-4b3d-438f-9232-10c76bc7e038')))))
        .addMethod("GetThumbnailAsync", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.FileProperties.ThumbnailMode', ['PicturesView', 'VideosView', 'MusicView', 'DocumentsView', 'ListView', 'SingleItem'], [0, 1, 2, 3, 4, 5])).addIn(DynWinRtType.u32()).addIn(DynWinRtType.enumType('Windows.Storage.FileProperties.ThumbnailOptions', ['None', 'ReturnOnlyIfCached', 'ResizeThumbnail', 'UseCurrentScale'], [0, 1, 2, 4])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.FileProperties.StorageItemThumbnail', WinGuid.parse('cc254827-4b3d-438f-9232-10c76bc7e038')))))
        .addMethod("get_DisplayName", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
        .addMethod("get_DisplayType", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
        .addMethod("get_FolderRelativeId", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
        .addMethod("get_Properties", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.Storage.FileProperties.StorageItemContentProperties', WinGuid.parse('05294bad-bc38-48bf-85d7-770e0e2ae0ba'))));
        const value = _IStorageItemPropertiesCache[prop];
        return typeof value === 'function' ? value.bind(_IStorageItemPropertiesCache) : value;
    }
});

let _IStorageItemProperties2Cache;
const _IStorageItemProperties2 = new Proxy({}, {
    get(_target, prop) {
        _IStorageItemProperties2Cache ??= DynWinRtType.registerInterface(
        "IStorageItemProperties2", IID_IStorageItemProperties2)
        .addMethod("GetScaledImageAsThumbnailAsyncOverloadDefaultSizeDefaultOptions", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.FileProperties.ThumbnailMode', ['PicturesView', 'VideosView', 'MusicView', 'DocumentsView', 'ListView', 'SingleItem'], [0, 1, 2, 3, 4, 5])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.FileProperties.StorageItemThumbnail', WinGuid.parse('cc254827-4b3d-438f-9232-10c76bc7e038')))))
        .addMethod("GetScaledImageAsThumbnailAsyncOverloadDefaultOptions", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.FileProperties.ThumbnailMode', ['PicturesView', 'VideosView', 'MusicView', 'DocumentsView', 'ListView', 'SingleItem'], [0, 1, 2, 3, 4, 5])).addIn(DynWinRtType.u32()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.FileProperties.StorageItemThumbnail', WinGuid.parse('cc254827-4b3d-438f-9232-10c76bc7e038')))))
        .addMethod("GetScaledImageAsThumbnailAsync", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.FileProperties.ThumbnailMode', ['PicturesView', 'VideosView', 'MusicView', 'DocumentsView', 'ListView', 'SingleItem'], [0, 1, 2, 3, 4, 5])).addIn(DynWinRtType.u32()).addIn(DynWinRtType.enumType('Windows.Storage.FileProperties.ThumbnailOptions', ['None', 'ReturnOnlyIfCached', 'ResizeThumbnail', 'UseCurrentScale'], [0, 1, 2, 4])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.FileProperties.StorageItemThumbnail', WinGuid.parse('cc254827-4b3d-438f-9232-10c76bc7e038')))));
        const value = _IStorageItemProperties2Cache[prop];
        return typeof value === 'function' ? value.bind(_IStorageItemProperties2Cache) : value;
    }
});

let _IStorageItem2Cache;
const _IStorageItem2 = new Proxy({}, {
    get(_target, prop) {
        _IStorageItem2Cache ??= DynWinRtType.registerInterface(
        "IStorageItem2", IID_IStorageItem2)
        .addMethod("GetParentAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFolder', WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b')))))
        .addMethod("IsEqual", new DynWinRtMethodSig().addIn(DynWinRtType.interface(WinGuid.parse('4207a996-ca2f-42f7-bde8-8b10457a7f30'))).addOut(DynWinRtType.boolType()));
        const value = _IStorageItem2Cache[prop];
        return typeof value === 'function' ? value.bind(_IStorageItem2Cache) : value;
    }
});

let _IStorageItemPropertiesWithProviderCache;
const _IStorageItemPropertiesWithProvider = new Proxy({}, {
    get(_target, prop) {
        _IStorageItemPropertiesWithProviderCache ??= DynWinRtType.registerInterface(
        "IStorageItemPropertiesWithProvider", IID_IStorageItemPropertiesWithProvider)
        .addMethod("get_Provider", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.Storage.StorageProvider', WinGuid.parse('e705eed4-d478-47d6-ba46-1a8ebe114a20'))));
        const value = _IStorageItemPropertiesWithProviderCache[prop];
        return typeof value === 'function' ? value.bind(_IStorageItemPropertiesWithProviderCache) : value;
    }
});

let _IStorageFilePropertiesWithAvailabilityCache;
const _IStorageFilePropertiesWithAvailability = new Proxy({}, {
    get(_target, prop) {
        _IStorageFilePropertiesWithAvailabilityCache ??= DynWinRtType.registerInterface(
        "IStorageFilePropertiesWithAvailability", IID_IStorageFilePropertiesWithAvailability)
        .addMethod("get_IsAvailable", new DynWinRtMethodSig().addOut(DynWinRtType.boolType()));
        const value = _IStorageFilePropertiesWithAvailabilityCache[prop];
        return typeof value === 'function' ? value.bind(_IStorageFilePropertiesWithAvailabilityCache) : value;
    }
});

let _IStorageFile2Cache;
const _IStorageFile2 = new Proxy({}, {
    get(_target, prop) {
        _IStorageFile2Cache ??= DynWinRtType.registerInterface(
        "IStorageFile2", IID_IStorageFile2)
        .addMethod("OpenWithOptionsAsync", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.FileAccessMode', ['Read', 'ReadWrite'], [0, 1])).addIn(DynWinRtType.enumType('Windows.Storage.StorageOpenOptions', ['None', 'AllowOnlyReaders', 'AllowReadersAndWriters'], [0, 1, 2])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.interface(WinGuid.parse('905a0fe1-bc53-11df-8c49-001e4fc686da')))))
        .addMethod("OpenTransactedWriteWithOptionsAsync", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.StorageOpenOptions', ['None', 'AllowOnlyReaders', 'AllowReadersAndWriters'], [0, 1, 2])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageStreamTransaction', WinGuid.parse('f67cf363-a53d-4d94-ae2c-67232d93acdd')))));
        const value = _IStorageFile2Cache[prop];
        return typeof value === 'function' ? value.bind(_IStorageFile2Cache) : value;
    }
});

function unpackDateTime(v) {
    const s = v.asStruct();
    return { universalTime: s.getI64(0) };
}
const _unpackDateTime = unpackDateTime;
const DateTime_Type = DynWinRtType.structType('Windows.Foundation.DateTime', [DynWinRtType.i64()]);
const _DateTime_Type = DateTime_Type;
function packDateTime(v) {
    const s = DynWinRtStruct.create(DateTime_Type);
    s.setI64(0, v.universalTime);
    return s;
}
const _packDateTime = packDateTime;

class StorageFile {
    _obj;
    static _s_IStorageFileStatics;
    static _s_IStorageFileStatics2;
    static s_IStorageFileStatics() { return StorageFile._s_IStorageFileStatics ??= DynWinRtValue.activationFactory('Windows.Storage.StorageFile').cast(IID_IStorageFileStatics); }
    static s_IStorageFileStatics2() { return StorageFile._s_IStorageFileStatics2 ??= DynWinRtValue.activationFactory('Windows.Storage.StorageFile').cast(IID_IStorageFileStatics2); }

    constructor() {
        throw new TypeError('StorageFile cannot be constructed directly.');
    }
    static _fromNative(obj) {
        return Object.assign(Object.create(StorageFile.prototype), { _obj: (__get_trackProjectedValue())((__get_trackProjectedValue())(obj, 'StorageFile').cast(IID_IStorageFile), 'StorageFile') });
    }
    static async getFileFromPathAsync(path, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFileStatics.method(6).invoke(StorageFile.s_IStorageFileStatics(), [DynWinRtValue.hstring(path)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : StorageFile._fromNative(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    static async getFileFromApplicationUriAsync(uri, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFileStatics.method(7).invoke(StorageFile.s_IStorageFileStatics(), [(uri == null ? DynWinRtValue.nullValue() : _unwrap(uri))]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : StorageFile._fromNative(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    static async createStreamedFileAsync(displayNameWithExtension, dataRequested, thumbnail, signal) {
        const _dataRequested_wrapped = (__a0__) => dataRequested(((v) => v.isNull() ? null : (__get_StreamedFileDataRequest())._fromNative(v))(__a0__));
        const _dataRequested_d = DynWinRtDelegate.create(IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES, _dataRequested_wrapped).toValue();
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFileStatics.method(8).invoke(StorageFile.s_IStorageFileStatics(), [DynWinRtValue.hstring(displayNameWithExtension), (dataRequested == null ? DynWinRtValue.nullValue() : _dataRequested_d), (thumbnail == null ? DynWinRtValue.nullValue() : _unwrap(thumbnail))]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : StorageFile._fromNative(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    static async replaceWithStreamedFileAsync(fileToReplace, dataRequested, thumbnail, signal) {
        const _dataRequested_wrapped = (__a0__) => dataRequested(((v) => v.isNull() ? null : (__get_StreamedFileDataRequest())._fromNative(v))(__a0__));
        const _dataRequested_d = DynWinRtDelegate.create(IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES, _dataRequested_wrapped).toValue();
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFileStatics.method(9).invoke(StorageFile.s_IStorageFileStatics(), [(fileToReplace == null ? DynWinRtValue.nullValue() : _unwrap(fileToReplace)), (dataRequested == null ? DynWinRtValue.nullValue() : _dataRequested_d), (thumbnail == null ? DynWinRtValue.nullValue() : _unwrap(thumbnail))]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : StorageFile._fromNative(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    static async createStreamedFileFromUriAsync(displayNameWithExtension, uri, thumbnail, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFileStatics.method(10).invoke(StorageFile.s_IStorageFileStatics(), [DynWinRtValue.hstring(displayNameWithExtension), (uri == null ? DynWinRtValue.nullValue() : _unwrap(uri)), (thumbnail == null ? DynWinRtValue.nullValue() : _unwrap(thumbnail))]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : StorageFile._fromNative(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    static async replaceWithStreamedFileFromUriAsync(fileToReplace, uri, thumbnail, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFileStatics.method(11).invoke(StorageFile.s_IStorageFileStatics(), [(fileToReplace == null ? DynWinRtValue.nullValue() : _unwrap(fileToReplace)), (uri == null ? DynWinRtValue.nullValue() : _unwrap(uri)), (thumbnail == null ? DynWinRtValue.nullValue() : _unwrap(thumbnail))]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : StorageFile._fromNative(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    static async getFileFromPathForUserAsync(user, path, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFileStatics2.method(6).invoke(StorageFile.s_IStorageFileStatics2(), [(user == null ? DynWinRtValue.nullValue() : _unwrap(user)), DynWinRtValue.hstring(path)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : StorageFile._fromNative(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    get fileType() {
        return _IStorageFile.method(6).invoke(this._obj, []).toString();
    }
    get contentType() {
        return _IStorageFile.method(7).invoke(this._obj, []).toString();
    }
    async openAsync(accessMode, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFile.method(8).invoke(this._obj, [DynWinRtValue.i32(accessMode)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : new (__get_IRandomAccessStream())(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    async openTransactedWriteAsync(signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFile.method(9).invoke(this._obj, []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : (__get_StorageStreamTransaction())._fromNative(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    async _copyAsync_1(destinationFolder, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFile.method(10).invoke(this._obj, [(destinationFolder == null ? DynWinRtValue.nullValue() : _unwrap(destinationFolder))]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : StorageFile._fromNative(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    async _copyAsync_2(destinationFolder, desiredNewName, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFile.method(11).invoke(this._obj, [(destinationFolder == null ? DynWinRtValue.nullValue() : _unwrap(destinationFolder)), DynWinRtValue.hstring(desiredNewName)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : StorageFile._fromNative(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    async _copyAsync_3(destinationFolder, desiredNewName, option, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFile.method(12).invoke(this._obj, [(destinationFolder == null ? DynWinRtValue.nullValue() : _unwrap(destinationFolder)), DynWinRtValue.hstring(desiredNewName), DynWinRtValue.i32(option)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : StorageFile._fromNative(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    /**
     * Overload of `copy` with default name, options.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     */
    copyAsync(...args) {
        if (args.length >= 3 && args[2] !== undefined && !(args[2] instanceof AbortSignal)) {
            return this._copyAsync_3(args[0], args[1], args[2], args[3]);
        }
        if (args.length >= 2 && args[1] !== undefined && !(args[1] instanceof AbortSignal)) {
            return this._copyAsync_2(args[0], args[1], args[2]);
        }
        return this._copyAsync_1(args[0], args[1]);
    }
    async copyAndReplaceAsync(fileToReplace, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFile.method(13).invoke(this._obj, [(fileToReplace == null ? DynWinRtValue.nullValue() : _unwrap(fileToReplace))]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            await _op.toPromise();
            return;
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    async _moveAsync_1(destinationFolder, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFile.method(14).invoke(this._obj, [(destinationFolder == null ? DynWinRtValue.nullValue() : _unwrap(destinationFolder))]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            await _op.toPromise();
            return;
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    async _moveAsync_2(destinationFolder, desiredNewName, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFile.method(15).invoke(this._obj, [(destinationFolder == null ? DynWinRtValue.nullValue() : _unwrap(destinationFolder)), DynWinRtValue.hstring(desiredNewName)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            await _op.toPromise();
            return;
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    async _moveAsync_3(destinationFolder, desiredNewName, option, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFile.method(16).invoke(this._obj, [(destinationFolder == null ? DynWinRtValue.nullValue() : _unwrap(destinationFolder)), DynWinRtValue.hstring(desiredNewName), DynWinRtValue.i32(option)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            await _op.toPromise();
            return;
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    /**
     * Overload of `move` with default name, options.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     */
    moveAsync(...args) {
        if (args.length >= 3 && args[2] !== undefined && !(args[2] instanceof AbortSignal)) {
            return this._moveAsync_3(args[0], args[1], args[2], args[3]);
        }
        if (args.length >= 2 && args[1] !== undefined && !(args[1] instanceof AbortSignal)) {
            return this._moveAsync_2(args[0], args[1], args[2]);
        }
        return this._moveAsync_1(args[0], args[1]);
    }
    async moveAndReplaceAsync(fileToReplace, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFile.method(17).invoke(this._obj, [(fileToReplace == null ? DynWinRtValue.nullValue() : _unwrap(fileToReplace))]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            await _op.toPromise();
            return;
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
    async openSequentialReadAsync(signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IInputStreamReference.method(6).invoke(this._obj.cast(IID_IInputStreamReference), []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : new (__get_IInputStream())(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    async openReadAsync(signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IRandomAccessStreamReference.method(6).invoke(this._obj.cast(IID_IRandomAccessStreamReference), []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : new (__get_IRandomAccessStreamWithContentType())(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    async _renameAsync_1(desiredName, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageItem.method(6).invoke(this._obj.cast(IID_IStorageItem), [DynWinRtValue.hstring(desiredName)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            await _op.toPromise();
            return;
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    async _renameAsync_2(desiredName, option, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageItem.method(7).invoke(this._obj.cast(IID_IStorageItem), [DynWinRtValue.hstring(desiredName), DynWinRtValue.i32(option)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            await _op.toPromise();
            return;
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    /**
     * Overload of `renameAsync` with default options.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     */
    renameAsync(...args) {
        if (args.length >= 2 && args[1] !== undefined && !(args[1] instanceof AbortSignal)) {
            return this._renameAsync_2(args[0], args[1], args[2]);
        }
        return this._renameAsync_1(args[0], args[1]);
    }
    async _deleteAsync_1(signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageItem.method(8).invoke(this._obj.cast(IID_IStorageItem), []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            await _op.toPromise();
            return;
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    async _deleteAsync_2(option, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageItem.method(9).invoke(this._obj.cast(IID_IStorageItem), [DynWinRtValue.i32(option)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            await _op.toPromise();
            return;
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    /**
     * Overload of `deleteAsync` with default options.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     */
    deleteAsync(...args) {
        if (args.length >= 1 && args[0] !== undefined && !(args[0] instanceof AbortSignal)) {
            return this._deleteAsync_2(args[0], args[1]);
        }
        return this._deleteAsync_1(args[0]);
    }
    async getBasicPropertiesAsync(signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageItem.method(10).invoke(this._obj.cast(IID_IStorageItem), []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : (__get_BasicProperties())._fromNative(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    get name() {
        return _IStorageItem.method(11).invoke(this._obj.cast(IID_IStorageItem), []).toString();
    }
    get path() {
        return _IStorageItem.method(12).invoke(this._obj.cast(IID_IStorageItem), []).toString();
    }
    get attributes() {
        return _IStorageItem.method(13).invoke(this._obj.cast(IID_IStorageItem), []).toNumber();
    }
    get dateCreated() {
        return _unpackDateTime(_IStorageItem.method(14).invoke(this._obj.cast(IID_IStorageItem), []));
    }
    isOfType(type) {
        return _IStorageItem.method(15).invoke(this._obj.cast(IID_IStorageItem), [DynWinRtValue.i32(type)]).toBool();
    }
    async _getThumbnailAsync_1(mode, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageItemProperties.method(6).invoke(this._obj.cast(IID_IStorageItemProperties), [DynWinRtValue.i32(mode)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : (__get_StorageItemThumbnail())._fromNative(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    async _getThumbnailAsync_2(mode, requestedSize, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageItemProperties.method(7).invoke(this._obj.cast(IID_IStorageItemProperties), [DynWinRtValue.i32(mode), DynWinRtValue.u32(requestedSize)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : (__get_StorageItemThumbnail())._fromNative(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    async _getThumbnailAsync_3(mode, requestedSize, options, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageItemProperties.method(8).invoke(this._obj.cast(IID_IStorageItemProperties), [DynWinRtValue.i32(mode), DynWinRtValue.u32(requestedSize), DynWinRtValue.i32(options)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : (__get_StorageItemThumbnail())._fromNative(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    /**
     * Overload of `getThumbnailAsync` with default size, default, options.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     */
    getThumbnailAsync(...args) {
        if (args.length >= 3 && args[2] !== undefined && !(args[2] instanceof AbortSignal)) {
            return this._getThumbnailAsync_3(args[0], args[1], args[2], args[3]);
        }
        if (args.length >= 2 && args[1] !== undefined && !(args[1] instanceof AbortSignal)) {
            return this._getThumbnailAsync_2(args[0], args[1], args[2]);
        }
        return this._getThumbnailAsync_1(args[0], args[1]);
    }
    get displayName() {
        return _IStorageItemProperties.method(9).invoke(this._obj.cast(IID_IStorageItemProperties), []).toString();
    }
    get displayType() {
        return _IStorageItemProperties.method(10).invoke(this._obj.cast(IID_IStorageItemProperties), []).toString();
    }
    get folderRelativeId() {
        return _IStorageItemProperties.method(11).invoke(this._obj.cast(IID_IStorageItemProperties), []).toString();
    }
    get properties() {
        return ((v) => v.isNull() ? null : (__get_StorageItemContentProperties())._fromNative(v))(_IStorageItemProperties.method(12).invoke(this._obj.cast(IID_IStorageItemProperties), []));
    }
    async _getScaledImageAsThumbnailAsync_1(mode, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageItemProperties2.method(6).invoke(this._obj.cast(IID_IStorageItemProperties2), [DynWinRtValue.i32(mode)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : (__get_StorageItemThumbnail())._fromNative(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    async _getScaledImageAsThumbnailAsync_2(mode, requestedSize, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageItemProperties2.method(7).invoke(this._obj.cast(IID_IStorageItemProperties2), [DynWinRtValue.i32(mode), DynWinRtValue.u32(requestedSize)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : (__get_StorageItemThumbnail())._fromNative(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    async _getScaledImageAsThumbnailAsync_3(mode, requestedSize, options, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageItemProperties2.method(8).invoke(this._obj.cast(IID_IStorageItemProperties2), [DynWinRtValue.i32(mode), DynWinRtValue.u32(requestedSize), DynWinRtValue.i32(options)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : (__get_StorageItemThumbnail())._fromNative(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    /**
     * Overload of `getScaledImageAsThumbnailAsync` with default size, default, options.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     */
    getScaledImageAsThumbnailAsync(...args) {
        if (args.length >= 3 && args[2] !== undefined && !(args[2] instanceof AbortSignal)) {
            return this._getScaledImageAsThumbnailAsync_3(args[0], args[1], args[2], args[3]);
        }
        if (args.length >= 2 && args[1] !== undefined && !(args[1] instanceof AbortSignal)) {
            return this._getScaledImageAsThumbnailAsync_2(args[0], args[1], args[2]);
        }
        return this._getScaledImageAsThumbnailAsync_1(args[0], args[1]);
    }
    async getParentAsync(signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageItem2.method(6).invoke(this._obj.cast(IID_IStorageItem2), []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : (__get_StorageFolder())._fromNative(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    isEqual(item) {
        return _IStorageItem2.method(7).invoke(this._obj.cast(IID_IStorageItem2), [(item == null ? DynWinRtValue.nullValue() : _unwrap(item))]).toBool();
    }
    get provider() {
        return ((v) => v.isNull() ? null : (__get_StorageProvider())._fromNative(v))(_IStorageItemPropertiesWithProvider.method(6).invoke(this._obj.cast(IID_IStorageItemPropertiesWithProvider), []));
    }
    get isAvailable() {
        return _IStorageFilePropertiesWithAvailability.method(6).invoke(this._obj.cast(IID_IStorageFilePropertiesWithAvailability), []).toBool();
    }
}

class IInputStreamReference {
    _obj;

    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IInputStreamReference(obj.cast(IID_IInputStreamReference));
    }

    async openSequentialReadAsync(signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IInputStreamReference.method(6).invoke(this._obj, []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : new (__get_IInputStream())(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
}

class IStorageFilePropertiesWithAvailability {
    _obj;

    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IStorageFilePropertiesWithAvailability(obj.cast(IID_IStorageFilePropertiesWithAvailability));
    }

    get isAvailable() {
        return _IStorageFilePropertiesWithAvailability.method(6).invoke(this._obj, []).toBool();
    }
}

class IStorageFile2 {
    _obj;

    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IStorageFile2(obj.cast(IID_IStorageFile2));
    }

    async openWithOptionsAsync(accessMode, options, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFile2.method(6).invoke(this._obj, [DynWinRtValue.i32(accessMode), DynWinRtValue.i32(options)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : new (__get_IRandomAccessStream())(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }

    async openTransactedWriteWithOptionsAsync(options, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFile2.method(7).invoke(this._obj, [DynWinRtValue.i32(options)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : (__get_StorageStreamTransaction())._fromNative(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
}
exports.IID_StorageFile = IID_StorageFile;
exports.unpackDateTime = unpackDateTime;
exports.DateTime_Type = DateTime_Type;
exports.packDateTime = packDateTime;
exports.StorageFile = StorageFile;
exports.IInputStreamReference = IInputStreamReference;
exports.IStorageFilePropertiesWithAvailability = IStorageFilePropertiesWithAvailability;
exports.IStorageFile2 = IStorageFile2;
