// Generated by dynwinrt-codegen — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } = require('../../dist/index.js');
let __m_IVectorView_IStorageItem;
const __load_IVectorView_IStorageItem = () => (__m_IVectorView_IStorageItem ??= require('./IVectorView_IStorageItem.js'));
const __get_IVectorView_IStorageItem = () => __load_IVectorView_IStorageItem().IVectorView_IStorageItem;
let __m_IVectorView_StorageFile;
const __load_IVectorView_StorageFile = () => (__m_IVectorView_StorageFile ??= require('./IVectorView_StorageFile.js'));
const __get_IVectorView_StorageFile = () => __load_IVectorView_StorageFile().IVectorView_StorageFile;
let __m_IVectorView_StorageFolder;
const __load_IVectorView_StorageFolder = () => (__m_IVectorView_StorageFolder ??= require('./IVectorView_StorageFolder.js'));
const __get_IVectorView_StorageFolder = () => __load_IVectorView_StorageFolder().IVectorView_StorageFolder;
let __m_CreationCollisionOption;
const __load_CreationCollisionOption = () => (__m_CreationCollisionOption ??= require('./CreationCollisionOption.js'));
const __get_CreationCollisionOption = () => __load_CreationCollisionOption().CreationCollisionOption;
let __m_FileAttributes;
const __load_FileAttributes = () => (__m_FileAttributes ??= require('./FileAttributes.js'));
const __get_FileAttributes = () => __load_FileAttributes().FileAttributes;
const { IID_IStorageItem } = require('./IStorageItem.js');
let __m_IStorageItem;
const __load_IStorageItem = () => (__m_IStorageItem ??= require('./IStorageItem.js'));
const __get_IStorageItem = () => __load_IStorageItem().IStorageItem;
let __m_NameCollisionOption;
const __load_NameCollisionOption = () => (__m_NameCollisionOption ??= require('./NameCollisionOption.js'));
const __get_NameCollisionOption = () => __load_NameCollisionOption().NameCollisionOption;
let __m_StorageDeleteOption;
const __load_StorageDeleteOption = () => (__m_StorageDeleteOption ??= require('./StorageDeleteOption.js'));
const __get_StorageDeleteOption = () => __load_StorageDeleteOption().StorageDeleteOption;
let __m_StorageFile;
const __load_StorageFile = () => (__m_StorageFile ??= require('./StorageFile.js'));
const __get_StorageFile = () => __load_StorageFile().StorageFile;
let __m_StorageItemTypes;
const __load_StorageItemTypes = () => (__m_StorageItemTypes ??= require('./StorageItemTypes.js'));
const __get_StorageItemTypes = () => __load_StorageItemTypes().StorageItemTypes;
let __m_StorageLibraryChangeTracker;
const __load_StorageLibraryChangeTracker = () => (__m_StorageLibraryChangeTracker ??= require('./StorageLibraryChangeTracker.js'));
const __get_StorageLibraryChangeTracker = () => __load_StorageLibraryChangeTracker().StorageLibraryChangeTracker;
let __m_StorageProvider;
const __load_StorageProvider = () => (__m_StorageProvider ??= require('./StorageProvider.js'));
const __get_StorageProvider = () => __load_StorageProvider().StorageProvider;
let __m_BasicProperties;
const __load_BasicProperties = () => (__m_BasicProperties ??= require('./BasicProperties.js'));
const __get_BasicProperties = () => __load_BasicProperties().BasicProperties;
let __m_StorageItemContentProperties;
const __load_StorageItemContentProperties = () => (__m_StorageItemContentProperties ??= require('./StorageItemContentProperties.js'));
const __get_StorageItemContentProperties = () => __load_StorageItemContentProperties().StorageItemContentProperties;
let __m_StorageItemThumbnail;
const __load_StorageItemThumbnail = () => (__m_StorageItemThumbnail ??= require('./StorageItemThumbnail.js'));
const __get_StorageItemThumbnail = () => __load_StorageItemThumbnail().StorageItemThumbnail;
let __m_ThumbnailMode;
const __load_ThumbnailMode = () => (__m_ThumbnailMode ??= require('./ThumbnailMode.js'));
const __get_ThumbnailMode = () => __load_ThumbnailMode().ThumbnailMode;
let __m_ThumbnailOptions;
const __load_ThumbnailOptions = () => (__m_ThumbnailOptions ??= require('./ThumbnailOptions.js'));
const __get_ThumbnailOptions = () => __load_ThumbnailOptions().ThumbnailOptions;
let __m_CommonFileQuery;
const __load_CommonFileQuery = () => (__m_CommonFileQuery ??= require('./CommonFileQuery.js'));
const __get_CommonFileQuery = () => __load_CommonFileQuery().CommonFileQuery;
let __m_CommonFolderQuery;
const __load_CommonFolderQuery = () => (__m_CommonFolderQuery ??= require('./CommonFolderQuery.js'));
const __get_CommonFolderQuery = () => __load_CommonFolderQuery().CommonFolderQuery;
let __m_IndexedState;
const __load_IndexedState = () => (__m_IndexedState ??= require('./IndexedState.js'));
const __get_IndexedState = () => __load_IndexedState().IndexedState;
let __m_QueryOptions;
const __load_QueryOptions = () => (__m_QueryOptions ??= require('./QueryOptions.js'));
const __get_QueryOptions = () => __load_QueryOptions().QueryOptions;
let __m_StorageFileQueryResult;
const __load_StorageFileQueryResult = () => (__m_StorageFileQueryResult ??= require('./StorageFileQueryResult.js'));
const __get_StorageFileQueryResult = () => __load_StorageFileQueryResult().StorageFileQueryResult;
let __m_StorageFolderQueryResult;
const __load_StorageFolderQueryResult = () => (__m_StorageFolderQueryResult ??= require('./StorageFolderQueryResult.js'));
const __get_StorageFolderQueryResult = () => __load_StorageFolderQueryResult().StorageFolderQueryResult;
let __m_StorageItemQueryResult;
const __load_StorageItemQueryResult = () => (__m_StorageItemQueryResult ??= require('./StorageItemQueryResult.js'));
const __get_StorageItemQueryResult = () => __load_StorageItemQueryResult().StorageItemQueryResult;
let __m_User;
const __load_User = () => (__m_User ??= require('./User.js'));
const __get_User = () => __load_User().User;
const { IID_IStorageItemProperties } = require('./IStorageItemProperties.js');
let __m_IStorageItemProperties;
const __load_IStorageItemProperties = () => (__m_IStorageItemProperties ??= require('./IStorageItemProperties.js'));
const __get_IStorageItemProperties = () => __load_IStorageItemProperties().IStorageItemProperties;
const { IID_IStorageItemProperties2 } = require('./IStorageItemProperties2.js');
let __m_IStorageItemProperties2;
const __load_IStorageItemProperties2 = () => (__m_IStorageItemProperties2 ??= require('./IStorageItemProperties2.js'));
const __get_IStorageItemProperties2 = () => __load_IStorageItemProperties2().IStorageItemProperties2;
const { IID_IStorageItem2 } = require('./IStorageItem2.js');
let __m_IStorageItem2;
const __load_IStorageItem2 = () => (__m_IStorageItem2 ??= require('./IStorageItem2.js'));
const __get_IStorageItem2 = () => __load_IStorageItem2().IStorageItem2;
const { IID_IStorageItemPropertiesWithProvider } = require('./IStorageItemPropertiesWithProvider.js');
let __m_IStorageItemPropertiesWithProvider;
const __load_IStorageItemPropertiesWithProvider = () => (__m_IStorageItemPropertiesWithProvider ??= require('./IStorageItemPropertiesWithProvider.js'));
const __get_IStorageItemPropertiesWithProvider = () => __load_IStorageItemPropertiesWithProvider().IStorageItemPropertiesWithProvider;
let __m_lifetime;
const __load_lifetime = () => (__m_lifetime ??= require('./lifetime.js'));
const __get_trackProjectedValue = () => __load_lifetime().trackProjectedValue;

const _unwrap = (x) => x?._obj ?? x;

const IID_IStorageFolder = WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b');
const IID_IStorageFolderStatics = WinGuid.parse('08f327ff-85d5-48b9-aee9-28511e339f9f');
const IID_IStorageFolderStatics2 = WinGuid.parse('b4656dc3-71d2-467d-8b29-371f0f62bf6f');
const IID_IStorageFolderQueryOperations = WinGuid.parse('cb43ccc9-446b-4a4f-be97-757771be5203');
const IID_IStorageFolder2 = WinGuid.parse('e827e8b9-08d9-4a8e-a0ac-fe5ed3cbbbd3');
const IID_IStorageFolder3 = WinGuid.parse('9f617899-bde1-4124-aeb3-b06ad96f98d4');
const IID_StorageFolder = WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b');

let _IStorageFolderCache;
const _IStorageFolder = new Proxy({}, {
    get(_target, prop) {
        _IStorageFolderCache ??= DynWinRtType.registerInterface(
        "IStorageFolder", IID_IStorageFolder)
        .addMethod("CreateFileAsyncOverloadDefaultOptions", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea')))))
        .addMethod("CreateFileAsync", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addIn(DynWinRtType.enumType('Windows.Storage.CreationCollisionOption', ['GenerateUniqueName', 'ReplaceExisting', 'FailIfExists', 'OpenIfExists'], [0, 1, 2, 3])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea')))))
        .addMethod("CreateFolderAsyncOverloadDefaultOptions", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFolder', WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b')))))
        .addMethod("CreateFolderAsync", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addIn(DynWinRtType.enumType('Windows.Storage.CreationCollisionOption', ['GenerateUniqueName', 'ReplaceExisting', 'FailIfExists', 'OpenIfExists'], [0, 1, 2, 3])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFolder', WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b')))))
        .addMethod("GetFileAsync", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea')))))
        .addMethod("GetFolderAsync", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFolder', WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b')))))
        .addMethod("GetItemAsync", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.interface(WinGuid.parse('4207a996-ca2f-42f7-bde8-8b10457a7f30')))))
        .addMethod("GetFilesAsyncOverloadDefaultOptionsStartAndCount", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea'))]))))
        .addMethod("GetFoldersAsyncOverloadDefaultOptionsStartAndCount", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.runtimeClass('Windows.Storage.StorageFolder', WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b'))]))))
        .addMethod("GetItemsAsyncOverloadDefaultStartAndCount", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.interface(WinGuid.parse('4207a996-ca2f-42f7-bde8-8b10457a7f30'))]))));
        const value = _IStorageFolderCache[prop];
        return typeof value === 'function' ? value.bind(_IStorageFolderCache) : value;
    }
});

let _IStorageFolderStaticsCache;
const _IStorageFolderStatics = new Proxy({}, {
    get(_target, prop) {
        _IStorageFolderStaticsCache ??= DynWinRtType.registerInterface(
        "IStorageFolderStatics", IID_IStorageFolderStatics)
        .addMethod("GetFolderFromPathAsync", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFolder', WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b')))));
        const value = _IStorageFolderStaticsCache[prop];
        return typeof value === 'function' ? value.bind(_IStorageFolderStaticsCache) : value;
    }
});

let _IStorageFolderStatics2Cache;
const _IStorageFolderStatics2 = new Proxy({}, {
    get(_target, prop) {
        _IStorageFolderStatics2Cache ??= DynWinRtType.registerInterface(
        "IStorageFolderStatics2", IID_IStorageFolderStatics2)
        .addMethod("GetFolderFromPathForUserAsync", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Windows.System.User', WinGuid.parse('df9a26c6-e746-4bcd-b5d4-120103c4209b'))).addIn(DynWinRtType.hstring()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFolder', WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b')))));
        const value = _IStorageFolderStatics2Cache[prop];
        return typeof value === 'function' ? value.bind(_IStorageFolderStatics2Cache) : value;
    }
});

let _IStorageItemCache;
const _IStorageItem = new Proxy({}, {
    get(_target, prop) {
        _IStorageItemCache ??= DynWinRtType.registerInterface(
        "IStorageItem", IID_IStorageItem)
        .addMethod("RenameAsyncOverloadDefaultOptions", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.iAsyncAction()))
        .addMethod("RenameAsync", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addIn(DynWinRtType.enumType('Windows.Storage.NameCollisionOption', ['GenerateUniqueName', 'ReplaceExisting', 'FailIfExists'], [0, 1, 2])).addOut(DynWinRtType.iAsyncAction()))
        .addMethod("DeleteAsyncOverloadDefaultOptions", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncAction()))
        .addMethod("DeleteAsync", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.StorageDeleteOption', ['Default', 'PermanentDelete'], [0, 1])).addOut(DynWinRtType.iAsyncAction()))
        .addMethod("GetBasicPropertiesAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.FileProperties.BasicProperties', WinGuid.parse('d05d55db-785e-4a66-be02-9beec58aea81')))))
        .addMethod("get_Name", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
        .addMethod("get_Path", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
        .addMethod("get_Attributes", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Windows.Storage.FileAttributes', ['Normal', 'ReadOnly', 'Directory', 'Archive', 'Temporary', 'LocallyIncomplete'], [0, 1, 16, 32, 256, 512])))
        .addMethod("get_DateCreated", new DynWinRtMethodSig().addOut(DynWinRtType.structType('Windows.Foundation.DateTime', [DynWinRtType.i64()])))
        .addMethod("IsOfType", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.StorageItemTypes', ['None', 'File', 'Folder'], [0, 1, 2])).addOut(DynWinRtType.boolType()));
        const value = _IStorageItemCache[prop];
        return typeof value === 'function' ? value.bind(_IStorageItemCache) : value;
    }
});

let _IStorageFolderQueryOperationsCache;
const _IStorageFolderQueryOperations = new Proxy({}, {
    get(_target, prop) {
        _IStorageFolderQueryOperationsCache ??= DynWinRtType.registerInterface(
        "IStorageFolderQueryOperations", IID_IStorageFolderQueryOperations)
        .addMethod("GetIndexedStateAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.enumType('Windows.Storage.Search.IndexedState', ['Unknown', 'NotIndexed', 'PartiallyIndexed', 'FullyIndexed'], [0, 1, 2, 3]))))
        .addMethod("CreateFileQueryOverloadDefault", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.Storage.Search.StorageFileQueryResult', WinGuid.parse('52fda447-2baa-412c-b29f-d4b1778efa1e'))))
        .addMethod("CreateFileQuery", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.Search.CommonFileQuery', ['DefaultQuery', 'OrderByName', 'OrderByTitle', 'OrderByMusicProperties', 'OrderBySearchRank', 'OrderByDate'], [0, 1, 2, 3, 4, 5])).addOut(DynWinRtType.runtimeClass('Windows.Storage.Search.StorageFileQueryResult', WinGuid.parse('52fda447-2baa-412c-b29f-d4b1778efa1e'))))
        .addMethod("CreateFileQueryWithOptions", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Windows.Storage.Search.QueryOptions', WinGuid.parse('1e5e46ee-0f45-4838-a8e9-d0479d446c30'))).addOut(DynWinRtType.runtimeClass('Windows.Storage.Search.StorageFileQueryResult', WinGuid.parse('52fda447-2baa-412c-b29f-d4b1778efa1e'))))
        .addMethod("CreateFolderQueryOverloadDefault", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.Storage.Search.StorageFolderQueryResult', WinGuid.parse('6654c911-7d66-46fa-aecf-e4a4baa93ab8'))))
        .addMethod("CreateFolderQuery", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.Search.CommonFolderQuery', ['DefaultQuery', 'GroupByYear', 'GroupByMonth', 'GroupByArtist', 'GroupByAlbum', 'GroupByAlbumArtist', 'GroupByComposer', 'GroupByGenre', 'GroupByPublishedYear', 'GroupByRating', 'GroupByTag', 'GroupByAuthor', 'GroupByType'], [0, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111])).addOut(DynWinRtType.runtimeClass('Windows.Storage.Search.StorageFolderQueryResult', WinGuid.parse('6654c911-7d66-46fa-aecf-e4a4baa93ab8'))))
        .addMethod("CreateFolderQueryWithOptions", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Windows.Storage.Search.QueryOptions', WinGuid.parse('1e5e46ee-0f45-4838-a8e9-d0479d446c30'))).addOut(DynWinRtType.runtimeClass('Windows.Storage.Search.StorageFolderQueryResult', WinGuid.parse('6654c911-7d66-46fa-aecf-e4a4baa93ab8'))))
        .addMethod("CreateItemQuery", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.Storage.Search.StorageItemQueryResult', WinGuid.parse('e8948079-9d58-47b8-b2b2-41b07f4795f9'))))
        .addMethod("CreateItemQueryWithOptions", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Windows.Storage.Search.QueryOptions', WinGuid.parse('1e5e46ee-0f45-4838-a8e9-d0479d446c30'))).addOut(DynWinRtType.runtimeClass('Windows.Storage.Search.StorageItemQueryResult', WinGuid.parse('e8948079-9d58-47b8-b2b2-41b07f4795f9'))))
        .addMethod("GetFilesAsync", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.Search.CommonFileQuery', ['DefaultQuery', 'OrderByName', 'OrderByTitle', 'OrderByMusicProperties', 'OrderBySearchRank', 'OrderByDate'], [0, 1, 2, 3, 4, 5])).addIn(DynWinRtType.u32()).addIn(DynWinRtType.u32()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea'))]))))
        .addMethod("GetFilesAsyncOverloadDefaultStartAndCount", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.Search.CommonFileQuery', ['DefaultQuery', 'OrderByName', 'OrderByTitle', 'OrderByMusicProperties', 'OrderBySearchRank', 'OrderByDate'], [0, 1, 2, 3, 4, 5])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea'))]))))
        .addMethod("GetFoldersAsync", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.Search.CommonFolderQuery', ['DefaultQuery', 'GroupByYear', 'GroupByMonth', 'GroupByArtist', 'GroupByAlbum', 'GroupByAlbumArtist', 'GroupByComposer', 'GroupByGenre', 'GroupByPublishedYear', 'GroupByRating', 'GroupByTag', 'GroupByAuthor', 'GroupByType'], [0, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111])).addIn(DynWinRtType.u32()).addIn(DynWinRtType.u32()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.runtimeClass('Windows.Storage.StorageFolder', WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b'))]))))
        .addMethod("GetFoldersAsyncOverloadDefaultStartAndCount", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.Search.CommonFolderQuery', ['DefaultQuery', 'GroupByYear', 'GroupByMonth', 'GroupByArtist', 'GroupByAlbum', 'GroupByAlbumArtist', 'GroupByComposer', 'GroupByGenre', 'GroupByPublishedYear', 'GroupByRating', 'GroupByTag', 'GroupByAuthor', 'GroupByType'], [0, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.runtimeClass('Windows.Storage.StorageFolder', WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b'))]))))
        .addMethod("GetItemsAsync", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addIn(DynWinRtType.u32()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.interface(WinGuid.parse('4207a996-ca2f-42f7-bde8-8b10457a7f30'))]))))
        .addMethod("AreQueryOptionsSupported", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Windows.Storage.Search.QueryOptions', WinGuid.parse('1e5e46ee-0f45-4838-a8e9-d0479d446c30'))).addOut(DynWinRtType.boolType()))
        .addMethod("IsCommonFolderQuerySupported", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.Search.CommonFolderQuery', ['DefaultQuery', 'GroupByYear', 'GroupByMonth', 'GroupByArtist', 'GroupByAlbum', 'GroupByAlbumArtist', 'GroupByComposer', 'GroupByGenre', 'GroupByPublishedYear', 'GroupByRating', 'GroupByTag', 'GroupByAuthor', 'GroupByType'], [0, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111])).addOut(DynWinRtType.boolType()))
        .addMethod("IsCommonFileQuerySupported", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.Search.CommonFileQuery', ['DefaultQuery', 'OrderByName', 'OrderByTitle', 'OrderByMusicProperties', 'OrderBySearchRank', 'OrderByDate'], [0, 1, 2, 3, 4, 5])).addOut(DynWinRtType.boolType()));
        const value = _IStorageFolderQueryOperationsCache[prop];
        return typeof value === 'function' ? value.bind(_IStorageFolderQueryOperationsCache) : value;
    }
});

let _IStorageItemPropertiesCache;
const _IStorageItemProperties = new Proxy({}, {
    get(_target, prop) {
        _IStorageItemPropertiesCache ??= DynWinRtType.registerInterface(
        "IStorageItemProperties", IID_IStorageItemProperties)
        .addMethod("GetThumbnailAsyncOverloadDefaultSizeDefaultOptions", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.FileProperties.ThumbnailMode', ['PicturesView', 'VideosView', 'MusicView', 'DocumentsView', 'ListView', 'SingleItem'], [0, 1, 2, 3, 4, 5])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.FileProperties.StorageItemThumbnail', WinGuid.parse('cc254827-4b3d-438f-9232-10c76bc7e038')))))
        .addMethod("GetThumbnailAsyncOverloadDefaultOptions", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.FileProperties.ThumbnailMode', ['PicturesView', 'VideosView', 'MusicView', 'DocumentsView', 'ListView', 'SingleItem'], [0, 1, 2, 3, 4, 5])).addIn(DynWinRtType.u32()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.FileProperties.StorageItemThumbnail', WinGuid.parse('cc254827-4b3d-438f-9232-10c76bc7e038')))))
        .addMethod("GetThumbnailAsync", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.FileProperties.ThumbnailMode', ['PicturesView', 'VideosView', 'MusicView', 'DocumentsView', 'ListView', 'SingleItem'], [0, 1, 2, 3, 4, 5])).addIn(DynWinRtType.u32()).addIn(DynWinRtType.enumType('Windows.Storage.FileProperties.ThumbnailOptions', ['None', 'ReturnOnlyIfCached', 'ResizeThumbnail', 'UseCurrentScale'], [0, 1, 2, 4])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.FileProperties.StorageItemThumbnail', WinGuid.parse('cc254827-4b3d-438f-9232-10c76bc7e038')))))
        .addMethod("get_DisplayName", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
        .addMethod("get_DisplayType", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
        .addMethod("get_FolderRelativeId", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
        .addMethod("get_Properties", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.Storage.FileProperties.StorageItemContentProperties', WinGuid.parse('05294bad-bc38-48bf-85d7-770e0e2ae0ba'))));
        const value = _IStorageItemPropertiesCache[prop];
        return typeof value === 'function' ? value.bind(_IStorageItemPropertiesCache) : value;
    }
});

let _IStorageItemProperties2Cache;
const _IStorageItemProperties2 = new Proxy({}, {
    get(_target, prop) {
        _IStorageItemProperties2Cache ??= DynWinRtType.registerInterface(
        "IStorageItemProperties2", IID_IStorageItemProperties2)
        .addMethod("GetScaledImageAsThumbnailAsyncOverloadDefaultSizeDefaultOptions", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.FileProperties.ThumbnailMode', ['PicturesView', 'VideosView', 'MusicView', 'DocumentsView', 'ListView', 'SingleItem'], [0, 1, 2, 3, 4, 5])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.FileProperties.StorageItemThumbnail', WinGuid.parse('cc254827-4b3d-438f-9232-10c76bc7e038')))))
        .addMethod("GetScaledImageAsThumbnailAsyncOverloadDefaultOptions", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.FileProperties.ThumbnailMode', ['PicturesView', 'VideosView', 'MusicView', 'DocumentsView', 'ListView', 'SingleItem'], [0, 1, 2, 3, 4, 5])).addIn(DynWinRtType.u32()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.FileProperties.StorageItemThumbnail', WinGuid.parse('cc254827-4b3d-438f-9232-10c76bc7e038')))))
        .addMethod("GetScaledImageAsThumbnailAsync", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.FileProperties.ThumbnailMode', ['PicturesView', 'VideosView', 'MusicView', 'DocumentsView', 'ListView', 'SingleItem'], [0, 1, 2, 3, 4, 5])).addIn(DynWinRtType.u32()).addIn(DynWinRtType.enumType('Windows.Storage.FileProperties.ThumbnailOptions', ['None', 'ReturnOnlyIfCached', 'ResizeThumbnail', 'UseCurrentScale'], [0, 1, 2, 4])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.FileProperties.StorageItemThumbnail', WinGuid.parse('cc254827-4b3d-438f-9232-10c76bc7e038')))));
        const value = _IStorageItemProperties2Cache[prop];
        return typeof value === 'function' ? value.bind(_IStorageItemProperties2Cache) : value;
    }
});

let _IStorageItem2Cache;
const _IStorageItem2 = new Proxy({}, {
    get(_target, prop) {
        _IStorageItem2Cache ??= DynWinRtType.registerInterface(
        "IStorageItem2", IID_IStorageItem2)
        .addMethod("GetParentAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFolder', WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b')))))
        .addMethod("IsEqual", new DynWinRtMethodSig().addIn(DynWinRtType.interface(WinGuid.parse('4207a996-ca2f-42f7-bde8-8b10457a7f30'))).addOut(DynWinRtType.boolType()));
        const value = _IStorageItem2Cache[prop];
        return typeof value === 'function' ? value.bind(_IStorageItem2Cache) : value;
    }
});

let _IStorageFolder2Cache;
const _IStorageFolder2 = new Proxy({}, {
    get(_target, prop) {
        _IStorageFolder2Cache ??= DynWinRtType.registerInterface(
        "IStorageFolder2", IID_IStorageFolder2)
        .addMethod("TryGetItemAsync", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.interface(WinGuid.parse('4207a996-ca2f-42f7-bde8-8b10457a7f30')))));
        const value = _IStorageFolder2Cache[prop];
        return typeof value === 'function' ? value.bind(_IStorageFolder2Cache) : value;
    }
});

let _IStorageItemPropertiesWithProviderCache;
const _IStorageItemPropertiesWithProvider = new Proxy({}, {
    get(_target, prop) {
        _IStorageItemPropertiesWithProviderCache ??= DynWinRtType.registerInterface(
        "IStorageItemPropertiesWithProvider", IID_IStorageItemPropertiesWithProvider)
        .addMethod("get_Provider", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.Storage.StorageProvider', WinGuid.parse('e705eed4-d478-47d6-ba46-1a8ebe114a20'))));
        const value = _IStorageItemPropertiesWithProviderCache[prop];
        return typeof value === 'function' ? value.bind(_IStorageItemPropertiesWithProviderCache) : value;
    }
});

let _IStorageFolder3Cache;
const _IStorageFolder3 = new Proxy({}, {
    get(_target, prop) {
        _IStorageFolder3Cache ??= DynWinRtType.registerInterface(
        "IStorageFolder3", IID_IStorageFolder3)
        .addMethod("TryGetChangeTracker", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.Storage.StorageLibraryChangeTracker', WinGuid.parse('9e157316-6073-44f6-9681-7492d1286c90'))));
        const value = _IStorageFolder3Cache[prop];
        return typeof value === 'function' ? value.bind(_IStorageFolder3Cache) : value;
    }
});

function unpackDateTime(v) {
    const s = v.asStruct();
    return { universalTime: s.getI64(0) };
}
const _unpackDateTime = unpackDateTime;
const DateTime_Type = DynWinRtType.structType('Windows.Foundation.DateTime', [DynWinRtType.i64()]);
const _DateTime_Type = DateTime_Type;
function packDateTime(v) {
    const s = DynWinRtStruct.create(DateTime_Type);
    s.setI64(0, v.universalTime);
    return s;
}
const _packDateTime = packDateTime;

class StorageFolder {
    _obj;
    static _s_IStorageFolderStatics;
    static _s_IStorageFolderStatics2;
    static s_IStorageFolderStatics() { return StorageFolder._s_IStorageFolderStatics ??= DynWinRtValue.activationFactory('Windows.Storage.StorageFolder').cast(IID_IStorageFolderStatics); }
    static s_IStorageFolderStatics2() { return StorageFolder._s_IStorageFolderStatics2 ??= DynWinRtValue.activationFactory('Windows.Storage.StorageFolder').cast(IID_IStorageFolderStatics2); }

    constructor() {
        throw new TypeError('StorageFolder cannot be constructed directly.');
    }
    static _fromNative(obj) {
        return Object.assign(Object.create(StorageFolder.prototype), { _obj: (__get_trackProjectedValue())((__get_trackProjectedValue())(obj, 'StorageFolder').cast(IID_IStorageFolder), 'StorageFolder') });
    }
    static async getFolderFromPathAsync(path, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolderStatics.method(6).invoke(StorageFolder.s_IStorageFolderStatics(), [DynWinRtValue.hstring(path)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : StorageFolder._fromNative(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    static async getFolderFromPathForUserAsync(user, path, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolderStatics2.method(6).invoke(StorageFolder.s_IStorageFolderStatics2(), [(user == null ? DynWinRtValue.nullValue() : _unwrap(user)), DynWinRtValue.hstring(path)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : StorageFolder._fromNative(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    async _createFileAsync_1(desiredName, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolder.method(6).invoke(this._obj, [DynWinRtValue.hstring(desiredName)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : (__get_StorageFile())._fromNative(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    async _createFileAsync_2(desiredName, options, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolder.method(7).invoke(this._obj, [DynWinRtValue.hstring(desiredName), DynWinRtValue.i32(options)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : (__get_StorageFile())._fromNative(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    /**
     * Overload of `createFileAsync` with default options.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     */
    createFileAsync(...args) {
        if (args.length >= 2 && args[1] !== undefined && !(args[1] instanceof AbortSignal)) {
            return this._createFileAsync_2(args[0], args[1], args[2]);
        }
        return this._createFileAsync_1(args[0], args[1]);
    }
    async _createFolderAsync_1(desiredName, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolder.method(8).invoke(this._obj, [DynWinRtValue.hstring(desiredName)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : StorageFolder._fromNative(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    async _createFolderAsync_2(desiredName, options, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolder.method(9).invoke(this._obj, [DynWinRtValue.hstring(desiredName), DynWinRtValue.i32(options)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : StorageFolder._fromNative(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    /**
     * Overload of `createFolderAsync` with default options.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     */
    createFolderAsync(...args) {
        if (args.length >= 2 && args[1] !== undefined && !(args[1] instanceof AbortSignal)) {
            return this._createFolderAsync_2(args[0], args[1], args[2]);
        }
        return this._createFolderAsync_1(args[0], args[1]);
    }
    async getFileAsync(name, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolder.method(10).invoke(this._obj, [DynWinRtValue.hstring(name)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : (__get_StorageFile())._fromNative(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    async getFolderAsync(name, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolder.method(11).invoke(this._obj, [DynWinRtValue.hstring(name)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : StorageFolder._fromNative(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    async getItemAsync(name, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolder.method(12).invoke(this._obj, [DynWinRtValue.hstring(name)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : new (__get_IStorageItem())(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    /**
     * Overload of `getFilesAsync` with default options, start, count.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     */
    async getFilesAsync(query, startIndex, maxItemsToRetrieve, signal) {
        if (query !== undefined && !(query instanceof AbortSignal)) {
            return IStorageFolderQueryOperations.from(this._obj).getFilesAsync(query, startIndex, maxItemsToRetrieve, signal);
        }
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolder.method(13).invoke(this._obj, []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : new (__get_IVectorView_StorageFile())(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    /**
     * Overload of `getFoldersAsync` with default options, start, count.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     */
    async getFoldersAsync(query, startIndex, maxItemsToRetrieve, signal) {
        if (query !== undefined && !(query instanceof AbortSignal)) {
            return IStorageFolderQueryOperations.from(this._obj).getFoldersAsync(query, startIndex, maxItemsToRetrieve, signal);
        }
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolder.method(14).invoke(this._obj, []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : new (__get_IVectorView_StorageFolder())(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    /**
     * Overload of `getItemsAsync` with default start, count.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     */
    async getItemsAsync(startIndex, maxItemsToRetrieve, signal) {
        if (startIndex !== undefined && !(startIndex instanceof AbortSignal)) {
            return IStorageFolderQueryOperations.from(this._obj).getItemsAsync(startIndex, maxItemsToRetrieve, signal);
        }
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolder.method(15).invoke(this._obj, []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : new (__get_IVectorView_IStorageItem())(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
    async _renameAsync_1(desiredName, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageItem.method(6).invoke(this._obj.cast(IID_IStorageItem), [DynWinRtValue.hstring(desiredName)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            await _op.toPromise();
            return;
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    async _renameAsync_2(desiredName, option, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageItem.method(7).invoke(this._obj.cast(IID_IStorageItem), [DynWinRtValue.hstring(desiredName), DynWinRtValue.i32(option)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            await _op.toPromise();
            return;
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    /**
     * Overload of `renameAsync` with default options.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     */
    renameAsync(...args) {
        if (args.length >= 2 && args[1] !== undefined && !(args[1] instanceof AbortSignal)) {
            return this._renameAsync_2(args[0], args[1], args[2]);
        }
        return this._renameAsync_1(args[0], args[1]);
    }
    async _deleteAsync_1(signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageItem.method(8).invoke(this._obj.cast(IID_IStorageItem), []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            await _op.toPromise();
            return;
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    async _deleteAsync_2(option, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageItem.method(9).invoke(this._obj.cast(IID_IStorageItem), [DynWinRtValue.i32(option)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            await _op.toPromise();
            return;
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    /**
     * Overload of `deleteAsync` with default options.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     */
    deleteAsync(...args) {
        if (args.length >= 1 && args[0] !== undefined && !(args[0] instanceof AbortSignal)) {
            return this._deleteAsync_2(args[0], args[1]);
        }
        return this._deleteAsync_1(args[0]);
    }
    async getBasicPropertiesAsync(signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageItem.method(10).invoke(this._obj.cast(IID_IStorageItem), []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : (__get_BasicProperties())._fromNative(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    get name() {
        return _IStorageItem.method(11).invoke(this._obj.cast(IID_IStorageItem), []).toString();
    }
    get path() {
        return _IStorageItem.method(12).invoke(this._obj.cast(IID_IStorageItem), []).toString();
    }
    get attributes() {
        return _IStorageItem.method(13).invoke(this._obj.cast(IID_IStorageItem), []).toNumber();
    }
    get dateCreated() {
        return _unpackDateTime(_IStorageItem.method(14).invoke(this._obj.cast(IID_IStorageItem), []));
    }
    isOfType(type) {
        return _IStorageItem.method(15).invoke(this._obj.cast(IID_IStorageItem), [DynWinRtValue.i32(type)]).toBool();
    }
    async getIndexedStateAsync(signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolderQueryOperations.method(6).invoke(this._obj.cast(IID_IStorageFolderQueryOperations), []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return _v.toNumber();
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    _createFileQuery_1() {
        return ((v) => v.isNull() ? null : (__get_StorageFileQueryResult())._fromNative(v))(_IStorageFolderQueryOperations.method(7).invoke(this._obj.cast(IID_IStorageFolderQueryOperations), []));
    }
    _createFileQuery_2(query) {
        return ((v) => v.isNull() ? null : (__get_StorageFileQueryResult())._fromNative(v))(_IStorageFolderQueryOperations.method(8).invoke(this._obj.cast(IID_IStorageFolderQueryOperations), [DynWinRtValue.i32(query)]));
    }
    /**
     * Parameterless overload of `createFileQuery`.
     */
    createFileQuery(...args) {
        if (args.length >= 1 && args[0] !== undefined && !(args[0] instanceof AbortSignal)) {
            return this._createFileQuery_2(args[0]);
        }
        return this._createFileQuery_1();
    }
    createFileQueryWithOptions(queryOptions) {
        return ((v) => v.isNull() ? null : (__get_StorageFileQueryResult())._fromNative(v))(_IStorageFolderQueryOperations.method(9).invoke(this._obj.cast(IID_IStorageFolderQueryOperations), [(queryOptions == null ? DynWinRtValue.nullValue() : _unwrap(queryOptions))]));
    }
    _createFolderQuery_1() {
        return ((v) => v.isNull() ? null : (__get_StorageFolderQueryResult())._fromNative(v))(_IStorageFolderQueryOperations.method(10).invoke(this._obj.cast(IID_IStorageFolderQueryOperations), []));
    }
    _createFolderQuery_2(query) {
        return ((v) => v.isNull() ? null : (__get_StorageFolderQueryResult())._fromNative(v))(_IStorageFolderQueryOperations.method(11).invoke(this._obj.cast(IID_IStorageFolderQueryOperations), [DynWinRtValue.i32(query)]));
    }
    /**
     * Parameterless overload of `createFolderQuery`.
     */
    createFolderQuery(...args) {
        if (args.length >= 1 && args[0] !== undefined && !(args[0] instanceof AbortSignal)) {
            return this._createFolderQuery_2(args[0]);
        }
        return this._createFolderQuery_1();
    }
    createFolderQueryWithOptions(queryOptions) {
        return ((v) => v.isNull() ? null : (__get_StorageFolderQueryResult())._fromNative(v))(_IStorageFolderQueryOperations.method(12).invoke(this._obj.cast(IID_IStorageFolderQueryOperations), [(queryOptions == null ? DynWinRtValue.nullValue() : _unwrap(queryOptions))]));
    }
    createItemQuery() {
        return ((v) => v.isNull() ? null : (__get_StorageItemQueryResult())._fromNative(v))(_IStorageFolderQueryOperations.method(13).invoke(this._obj.cast(IID_IStorageFolderQueryOperations), []));
    }
    createItemQueryWithOptions(queryOptions) {
        return ((v) => v.isNull() ? null : (__get_StorageItemQueryResult())._fromNative(v))(_IStorageFolderQueryOperations.method(14).invoke(this._obj.cast(IID_IStorageFolderQueryOperations), [(queryOptions == null ? DynWinRtValue.nullValue() : _unwrap(queryOptions))]));
    }
    areQueryOptionsSupported(queryOptions) {
        return _IStorageFolderQueryOperations.method(20).invoke(this._obj.cast(IID_IStorageFolderQueryOperations), [(queryOptions == null ? DynWinRtValue.nullValue() : _unwrap(queryOptions))]).toBool();
    }
    isCommonFolderQuerySupported(query) {
        return _IStorageFolderQueryOperations.method(21).invoke(this._obj.cast(IID_IStorageFolderQueryOperations), [DynWinRtValue.i32(query)]).toBool();
    }
    isCommonFileQuerySupported(query) {
        return _IStorageFolderQueryOperations.method(22).invoke(this._obj.cast(IID_IStorageFolderQueryOperations), [DynWinRtValue.i32(query)]).toBool();
    }
    async _getThumbnailAsync_1(mode, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageItemProperties.method(6).invoke(this._obj.cast(IID_IStorageItemProperties), [DynWinRtValue.i32(mode)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : (__get_StorageItemThumbnail())._fromNative(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    async _getThumbnailAsync_2(mode, requestedSize, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageItemProperties.method(7).invoke(this._obj.cast(IID_IStorageItemProperties), [DynWinRtValue.i32(mode), DynWinRtValue.u32(requestedSize)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : (__get_StorageItemThumbnail())._fromNative(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    async _getThumbnailAsync_3(mode, requestedSize, options, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageItemProperties.method(8).invoke(this._obj.cast(IID_IStorageItemProperties), [DynWinRtValue.i32(mode), DynWinRtValue.u32(requestedSize), DynWinRtValue.i32(options)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : (__get_StorageItemThumbnail())._fromNative(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    /**
     * Overload of `getThumbnailAsync` with default size, default, options.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     */
    getThumbnailAsync(...args) {
        if (args.length >= 3 && args[2] !== undefined && !(args[2] instanceof AbortSignal)) {
            return this._getThumbnailAsync_3(args[0], args[1], args[2], args[3]);
        }
        if (args.length >= 2 && args[1] !== undefined && !(args[1] instanceof AbortSignal)) {
            return this._getThumbnailAsync_2(args[0], args[1], args[2]);
        }
        return this._getThumbnailAsync_1(args[0], args[1]);
    }
    get displayName() {
        return _IStorageItemProperties.method(9).invoke(this._obj.cast(IID_IStorageItemProperties), []).toString();
    }
    get displayType() {
        return _IStorageItemProperties.method(10).invoke(this._obj.cast(IID_IStorageItemProperties), []).toString();
    }
    get folderRelativeId() {
        return _IStorageItemProperties.method(11).invoke(this._obj.cast(IID_IStorageItemProperties), []).toString();
    }
    get properties() {
        return ((v) => v.isNull() ? null : (__get_StorageItemContentProperties())._fromNative(v))(_IStorageItemProperties.method(12).invoke(this._obj.cast(IID_IStorageItemProperties), []));
    }
    async _getScaledImageAsThumbnailAsync_1(mode, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageItemProperties2.method(6).invoke(this._obj.cast(IID_IStorageItemProperties2), [DynWinRtValue.i32(mode)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : (__get_StorageItemThumbnail())._fromNative(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    async _getScaledImageAsThumbnailAsync_2(mode, requestedSize, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageItemProperties2.method(7).invoke(this._obj.cast(IID_IStorageItemProperties2), [DynWinRtValue.i32(mode), DynWinRtValue.u32(requestedSize)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : (__get_StorageItemThumbnail())._fromNative(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    async _getScaledImageAsThumbnailAsync_3(mode, requestedSize, options, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageItemProperties2.method(8).invoke(this._obj.cast(IID_IStorageItemProperties2), [DynWinRtValue.i32(mode), DynWinRtValue.u32(requestedSize), DynWinRtValue.i32(options)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : (__get_StorageItemThumbnail())._fromNative(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    /**
     * Overload of `getScaledImageAsThumbnailAsync` with default size, default, options.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     */
    getScaledImageAsThumbnailAsync(...args) {
        if (args.length >= 3 && args[2] !== undefined && !(args[2] instanceof AbortSignal)) {
            return this._getScaledImageAsThumbnailAsync_3(args[0], args[1], args[2], args[3]);
        }
        if (args.length >= 2 && args[1] !== undefined && !(args[1] instanceof AbortSignal)) {
            return this._getScaledImageAsThumbnailAsync_2(args[0], args[1], args[2]);
        }
        return this._getScaledImageAsThumbnailAsync_1(args[0], args[1]);
    }
    async getParentAsync(signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageItem2.method(6).invoke(this._obj.cast(IID_IStorageItem2), []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : StorageFolder._fromNative(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    isEqual(item) {
        return _IStorageItem2.method(7).invoke(this._obj.cast(IID_IStorageItem2), [(item == null ? DynWinRtValue.nullValue() : _unwrap(item))]).toBool();
    }
    async tryGetItemAsync(name, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolder2.method(6).invoke(this._obj.cast(IID_IStorageFolder2), [DynWinRtValue.hstring(name)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : new (__get_IStorageItem())(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    get provider() {
        return ((v) => v.isNull() ? null : (__get_StorageProvider())._fromNative(v))(_IStorageItemPropertiesWithProvider.method(6).invoke(this._obj.cast(IID_IStorageItemPropertiesWithProvider), []));
    }
    tryGetChangeTracker() {
        return ((v) => v.isNull() ? null : (__get_StorageLibraryChangeTracker())._fromNative(v))(_IStorageFolder3.method(6).invoke(this._obj.cast(IID_IStorageFolder3), []));
    }
}

class IStorageFolderQueryOperations {
    _obj;

    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IStorageFolderQueryOperations(obj.cast(IID_IStorageFolderQueryOperations));
    }

    async getIndexedStateAsync(signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolderQueryOperations.method(6).invoke(this._obj, []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return _v.toNumber();
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }

    /**
     * Parameterless overload of `createFileQuery`.
     */
    createFileQueryOverloadDefault() {
        return ((v) => v.isNull() ? null : (__get_StorageFileQueryResult())._fromNative(v))(_IStorageFolderQueryOperations.method(7).invoke(this._obj, []));
    }

    createFileQuery(query) {
        return ((v) => v.isNull() ? null : (__get_StorageFileQueryResult())._fromNative(v))(_IStorageFolderQueryOperations.method(8).invoke(this._obj, [DynWinRtValue.i32(query)]));
    }

    createFileQueryWithOptions(queryOptions) {
        return ((v) => v.isNull() ? null : (__get_StorageFileQueryResult())._fromNative(v))(_IStorageFolderQueryOperations.method(9).invoke(this._obj, [(queryOptions == null ? DynWinRtValue.nullValue() : _unwrap(queryOptions))]));
    }

    /**
     * Parameterless overload of `createFolderQuery`.
     */
    createFolderQueryOverloadDefault() {
        return ((v) => v.isNull() ? null : (__get_StorageFolderQueryResult())._fromNative(v))(_IStorageFolderQueryOperations.method(10).invoke(this._obj, []));
    }

    createFolderQuery(query) {
        return ((v) => v.isNull() ? null : (__get_StorageFolderQueryResult())._fromNative(v))(_IStorageFolderQueryOperations.method(11).invoke(this._obj, [DynWinRtValue.i32(query)]));
    }

    createFolderQueryWithOptions(queryOptions) {
        return ((v) => v.isNull() ? null : (__get_StorageFolderQueryResult())._fromNative(v))(_IStorageFolderQueryOperations.method(12).invoke(this._obj, [(queryOptions == null ? DynWinRtValue.nullValue() : _unwrap(queryOptions))]));
    }

    createItemQuery() {
        return ((v) => v.isNull() ? null : (__get_StorageItemQueryResult())._fromNative(v))(_IStorageFolderQueryOperations.method(13).invoke(this._obj, []));
    }

    createItemQueryWithOptions(queryOptions) {
        return ((v) => v.isNull() ? null : (__get_StorageItemQueryResult())._fromNative(v))(_IStorageFolderQueryOperations.method(14).invoke(this._obj, [(queryOptions == null ? DynWinRtValue.nullValue() : _unwrap(queryOptions))]));
    }

    async getFilesAsync(query, startIndex, maxItemsToRetrieve, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolderQueryOperations.method(15).invoke(this._obj, [DynWinRtValue.i32(query), DynWinRtValue.u32(startIndex), DynWinRtValue.u32(maxItemsToRetrieve)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : new (__get_IVectorView_StorageFile())(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }

    /**
     * Overload of `getFilesAsync` with default start, count.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     */
    async getFilesAsyncOverloadDefaultStartAndCount(query, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolderQueryOperations.method(16).invoke(this._obj, [DynWinRtValue.i32(query)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : new (__get_IVectorView_StorageFile())(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }

    async getFoldersAsync(query, startIndex, maxItemsToRetrieve, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolderQueryOperations.method(17).invoke(this._obj, [DynWinRtValue.i32(query), DynWinRtValue.u32(startIndex), DynWinRtValue.u32(maxItemsToRetrieve)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : new (__get_IVectorView_StorageFolder())(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }

    /**
     * Overload of `getFoldersAsync` with default start, count.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     */
    async getFoldersAsyncOverloadDefaultStartAndCount(query, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolderQueryOperations.method(18).invoke(this._obj, [DynWinRtValue.i32(query)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : new (__get_IVectorView_StorageFolder())(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }

    async getItemsAsync(startIndex, maxItemsToRetrieve, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolderQueryOperations.method(19).invoke(this._obj, [DynWinRtValue.u32(startIndex), DynWinRtValue.u32(maxItemsToRetrieve)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : new (__get_IVectorView_IStorageItem())(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }

    areQueryOptionsSupported(queryOptions) {
        return _IStorageFolderQueryOperations.method(20).invoke(this._obj, [(queryOptions == null ? DynWinRtValue.nullValue() : _unwrap(queryOptions))]).toBool();
    }

    isCommonFolderQuerySupported(query) {
        return _IStorageFolderQueryOperations.method(21).invoke(this._obj, [DynWinRtValue.i32(query)]).toBool();
    }

    isCommonFileQuerySupported(query) {
        return _IStorageFolderQueryOperations.method(22).invoke(this._obj, [DynWinRtValue.i32(query)]).toBool();
    }
}

class IStorageFolder2 {
    _obj;

    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IStorageFolder2(obj.cast(IID_IStorageFolder2));
    }

    async tryGetItemAsync(name, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolder2.method(6).invoke(this._obj, [DynWinRtValue.hstring(name)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : new (__get_IStorageItem())(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
}

class IStorageFolder3 {
    _obj;

    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IStorageFolder3(obj.cast(IID_IStorageFolder3));
    }

    tryGetChangeTracker() {
        return ((v) => v.isNull() ? null : (__get_StorageLibraryChangeTracker())._fromNative(v))(_IStorageFolder3.method(6).invoke(this._obj, []));
    }
}
exports.IID_StorageFolder = IID_StorageFolder;
exports.unpackDateTime = unpackDateTime;
exports.DateTime_Type = DateTime_Type;
exports.packDateTime = packDateTime;
exports.StorageFolder = StorageFolder;
exports.IStorageFolderQueryOperations = IStorageFolderQueryOperations;
exports.IStorageFolder2 = IStorageFolder2;
exports.IStorageFolder3 = IStorageFolder3;
