// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '../../dist/index.js';

export declare const IID_StorageProvider: WinGuid;
export declare class StorageProvider {
    private constructor();
    get id(): string;
    get displayName(): string;
    /** Cast this object to another WinRT interface. */
    as<T>(InterfaceClass: { from(obj: any): T }): T;
    isPropertySupportedForPartialFileAsync(propertyCanonicalName: string, signal?: AbortSignal): Promise<boolean>;
}

export declare class IStorageProvider2 {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IStorageProvider2;

    isPropertySupportedForPartialFileAsync(propertyCanonicalName: string, signal?: AbortSignal): Promise<boolean>;
}
