// Generated by dynwinrt-codegen — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } = require('../../dist/index.js');
let __m_IMap_String_IVectorView_TextSegment;
const __load_IMap_String_IVectorView_TextSegment = () => (__m_IMap_String_IVectorView_TextSegment ??= require('./IMap_String_IVectorView_TextSegment.js'));
const __get_IMap_String_IVectorView_TextSegment = () => __load_IMap_String_IVectorView_TextSegment().IMap_String_IVectorView_TextSegment;
let __m_IVectorView_StorageFile;
const __load_IVectorView_StorageFile = () => (__m_IVectorView_StorageFile ??= require('./IVectorView_StorageFile.js'));
const __get_IVectorView_StorageFile = () => __load_IVectorView_StorageFile().IVectorView_StorageFile;
let __m_IVectorView_TextSegment;
const __load_IVectorView_TextSegment = () => (__m_IVectorView_TextSegment ??= require('./IVectorView_TextSegment.js'));
const __get_IVectorView_TextSegment = () => __load_IVectorView_TextSegment().IVectorView_TextSegment;
const { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } = require('./TypedEventHandler_IStorageQueryResultBase_Object.js');
let __m_StorageFile;
const __load_StorageFile = () => (__m_StorageFile ??= require('./StorageFile.js'));
const __get_StorageFile = () => __load_StorageFile().StorageFile;
let __m_StorageFolder;
const __load_StorageFolder = () => (__m_StorageFolder ??= require('./StorageFolder.js'));
const __get_StorageFolder = () => __load_StorageFolder().StorageFolder;
const { IID_IStorageQueryResultBase } = require('./IStorageQueryResultBase.js');
let __m_IStorageQueryResultBase;
const __load_IStorageQueryResultBase = () => (__m_IStorageQueryResultBase ??= require('./IStorageQueryResultBase.js'));
const __get_IStorageQueryResultBase = () => __load_IStorageQueryResultBase().IStorageQueryResultBase;
let __m_QueryOptions;
const __load_QueryOptions = () => (__m_QueryOptions ??= require('./QueryOptions.js'));
const __get_QueryOptions = () => __load_QueryOptions().QueryOptions;
let __m_lifetime;
const __load_lifetime = () => (__m_lifetime ??= require('./lifetime.js'));
const __get_trackProjectedValue = () => __load_lifetime().trackProjectedValue;

const _unwrap = (x) => x?._obj ?? x;

const IID_IStorageFileQueryResult = WinGuid.parse('52fda447-2baa-412c-b29f-d4b1778efa1e');
const IID_IStorageFileQueryResult2 = WinGuid.parse('4e5db9dd-7141-46c4-8be3-e9dc9e27275c');
const IID_StorageFileQueryResult = WinGuid.parse('52fda447-2baa-412c-b29f-d4b1778efa1e');

let _IStorageFileQueryResultCache;
const _IStorageFileQueryResult = new Proxy({}, {
    get(_target, prop) {
        _IStorageFileQueryResultCache ??= DynWinRtType.registerInterface(
        "IStorageFileQueryResult", IID_IStorageFileQueryResult)
        .addMethod("GetFilesAsync", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addIn(DynWinRtType.u32()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea'))]))))
        .addMethod("GetFilesAsyncDefaultStartAndCount", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea'))]))));
        const value = _IStorageFileQueryResultCache[prop];
        return typeof value === 'function' ? value.bind(_IStorageFileQueryResultCache) : value;
    }
});

let _IStorageQueryResultBaseCache;
const _IStorageQueryResultBase = new Proxy({}, {
    get(_target, prop) {
        _IStorageQueryResultBaseCache ??= DynWinRtType.registerInterface(
        "IStorageQueryResultBase", IID_IStorageQueryResultBase)
        .addMethod("GetItemCountAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.u32())))
        .addMethod("get_Folder", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.Storage.StorageFolder', WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b'))))
        .addMethod("add_ContentsChanged", new DynWinRtMethodSig().addIn(DynWinRtType.parameterized(WinGuid.parse('9de1c534-6ae1-11e0-84e1-18a905bcc53f'), [DynWinRtType.interface(WinGuid.parse('c297d70d-7353-47ab-ba58-8c61425dc54b')), DynWinRtType.object()])).addOut(DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()])))
        .addMethod("remove_ContentsChanged", new DynWinRtMethodSig().addIn(DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()])))
        .addMethod("add_OptionsChanged", new DynWinRtMethodSig().addIn(DynWinRtType.parameterized(WinGuid.parse('9de1c534-6ae1-11e0-84e1-18a905bcc53f'), [DynWinRtType.interface(WinGuid.parse('c297d70d-7353-47ab-ba58-8c61425dc54b')), DynWinRtType.object()])).addOut(DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()])))
        .addMethod("remove_OptionsChanged", new DynWinRtMethodSig().addIn(DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()])))
        .addMethod("FindStartIndexAsync", new DynWinRtMethodSig().addIn(DynWinRtType.object()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.u32())))
        .addMethod("GetCurrentQueryOptions", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.Storage.Search.QueryOptions', WinGuid.parse('1e5e46ee-0f45-4838-a8e9-d0479d446c30'))))
        .addMethod("ApplyNewQueryOptions", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Windows.Storage.Search.QueryOptions', WinGuid.parse('1e5e46ee-0f45-4838-a8e9-d0479d446c30'))));
        const value = _IStorageQueryResultBaseCache[prop];
        return typeof value === 'function' ? value.bind(_IStorageQueryResultBaseCache) : value;
    }
});

let _IStorageFileQueryResult2Cache;
const _IStorageFileQueryResult2 = new Proxy({}, {
    get(_target, prop) {
        _IStorageFileQueryResult2Cache ??= DynWinRtType.registerInterface(
        "IStorageFileQueryResult2", IID_IStorageFileQueryResult2)
        .addMethod("GetMatchingPropertiesWithRanges", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea'))).addOut(DynWinRtType.parameterized(WinGuid.parse('3c2925fe-8519-45c1-aa79-197b6718c1c1'), [DynWinRtType.hstring(), DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.structType('Windows.Data.Text.TextSegment', [DynWinRtType.u32(), DynWinRtType.u32()])])])));
        const value = _IStorageFileQueryResult2Cache[prop];
        return typeof value === 'function' ? value.bind(_IStorageFileQueryResult2Cache) : value;
    }
});

function unpackEventRegistrationToken(v) {
    const s = v.asStruct();
    return { value: s.getI64(0) };
}
const _unpackEventRegistrationToken = unpackEventRegistrationToken;
const EventRegistrationToken_Type = DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()]);
const _EventRegistrationToken_Type = EventRegistrationToken_Type;
function packEventRegistrationToken(v) {
    const s = DynWinRtStruct.create(EventRegistrationToken_Type);
    s.setI64(0, v.value);
    return s;
}
const _packEventRegistrationToken = packEventRegistrationToken;

function unpackTextSegment(v) {
    const s = v.asStruct();
    return { startPosition: s.getU32(0), length: s.getU32(1) };
}
const _unpackTextSegment = unpackTextSegment;
const TextSegment_Type = DynWinRtType.structType('Windows.Data.Text.TextSegment', [DynWinRtType.u32(), DynWinRtType.u32()]);
const _TextSegment_Type = TextSegment_Type;
function packTextSegment(v) {
    const s = DynWinRtStruct.create(TextSegment_Type);
    s.setU32(0, v.startPosition);
    s.setU32(1, v.length);
    return s;
}
const _packTextSegment = packTextSegment;

class StorageFileQueryResult {
    _obj;

    constructor() {
        throw new TypeError('StorageFileQueryResult cannot be constructed directly.');
    }
    static _fromNative(obj) {
        return Object.assign(Object.create(StorageFileQueryResult.prototype), { _obj: (__get_trackProjectedValue())((__get_trackProjectedValue())(obj, 'StorageFileQueryResult').cast(IID_IStorageFileQueryResult), 'StorageFileQueryResult') });
    }
    async _getFilesAsync_1(signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFileQueryResult.method(7).invoke(this._obj, []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : new (__get_IVectorView_StorageFile())(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    async _getFilesAsync_2(startIndex, maxNumberOfItems, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFileQueryResult.method(6).invoke(this._obj, [DynWinRtValue.u32(startIndex), DynWinRtValue.u32(maxNumberOfItems)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : new (__get_IVectorView_StorageFile())(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    getFilesAsync(...args) {
        if (args.length >= 2 && args[0] !== undefined && !(args[0] instanceof AbortSignal)) {
            return this._getFilesAsync_2(args[0], args[1], args[2]);
        }
        return this._getFilesAsync_1(args[0]);
    }
    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
    async getItemCountAsync(signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageQueryResultBase.method(6).invoke(this._obj.cast(IID_IStorageQueryResultBase), []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return _v.toNumber();
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    get folder() {
        return ((v) => v.isNull() ? null : (__get_StorageFolder())._fromNative(v))(_IStorageQueryResultBase.method(7).invoke(this._obj.cast(IID_IStorageQueryResultBase), []));
    }
    onContentsChanged(callback) {
        const wrapped = (__a0__, __a1__) => callback(((v) => v.isNull() ? null : new (__get_IStorageQueryResultBase())(v))(__a0__), ((v) => v.isNull() ? null : v)(__a1__));
        const handler = DynWinRtDelegate.create(IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES, wrapped);
        const __token = _IStorageQueryResultBase.method(8).invoke(this._obj.cast(IID_IStorageQueryResultBase), [handler.toValue()]);
        return () => { void handler; _IStorageQueryResultBase.method(9).invoke(this._obj.cast(IID_IStorageQueryResultBase), [__token]); };
    }
    onceContentsChanged(callback) {
        const unsub = this.onContentsChanged((...args) => { unsub(); callback(...args); });
        return unsub;
    }
    offContentsChanged(token) {
        _IStorageQueryResultBase.method(9).invoke(this._obj.cast(IID_IStorageQueryResultBase), [token]);
    }
    offContentsChanged(token) {
        _IStorageQueryResultBase.method(9).invoke(this._obj.cast(IID_IStorageQueryResultBase), [token]);
    }
    onOptionsChanged(callback) {
        const wrapped = (__a0__, __a1__) => callback(((v) => v.isNull() ? null : new (__get_IStorageQueryResultBase())(v))(__a0__), ((v) => v.isNull() ? null : v)(__a1__));
        const handler = DynWinRtDelegate.create(IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES, wrapped);
        const __token = _IStorageQueryResultBase.method(10).invoke(this._obj.cast(IID_IStorageQueryResultBase), [handler.toValue()]);
        return () => { void handler; _IStorageQueryResultBase.method(11).invoke(this._obj.cast(IID_IStorageQueryResultBase), [__token]); };
    }
    onceOptionsChanged(callback) {
        const unsub = this.onOptionsChanged((...args) => { unsub(); callback(...args); });
        return unsub;
    }
    offOptionsChanged(token) {
        _IStorageQueryResultBase.method(11).invoke(this._obj.cast(IID_IStorageQueryResultBase), [token]);
    }
    async findStartIndexAsync(value, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageQueryResultBase.method(12).invoke(this._obj.cast(IID_IStorageQueryResultBase), [(value == null ? DynWinRtValue.nullValue() : _unwrap(value))]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return _v.toNumber();
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    getCurrentQueryOptions() {
        return ((v) => v.isNull() ? null : (__get_QueryOptions())._fromNative(v))(_IStorageQueryResultBase.method(13).invoke(this._obj.cast(IID_IStorageQueryResultBase), []));
    }
    applyNewQueryOptions(newQueryOptions) {
        _IStorageQueryResultBase.method(14).invoke(this._obj.cast(IID_IStorageQueryResultBase), [(newQueryOptions == null ? DynWinRtValue.nullValue() : _unwrap(newQueryOptions))]);
    }
    getMatchingPropertiesWithRanges(file) {
        return ((v) => v.isNull() ? null : new (__get_IMap_String_IVectorView_TextSegment())(v))(_IStorageFileQueryResult2.method(6).invoke(this._obj.cast(IID_IStorageFileQueryResult2), [(file == null ? DynWinRtValue.nullValue() : _unwrap(file))]));
    }
}

class IStorageFileQueryResult2 {
    _obj;

    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IStorageFileQueryResult2(obj.cast(IID_IStorageFileQueryResult2));
    }

    getMatchingPropertiesWithRanges(file) {
        return ((v) => v.isNull() ? null : new (__get_IMap_String_IVectorView_TextSegment())(v))(_IStorageFileQueryResult2.method(6).invoke(this._obj, [(file == null ? DynWinRtValue.nullValue() : _unwrap(file))]));
    }
}
exports.IID_StorageFileQueryResult = IID_StorageFileQueryResult;
exports.unpackEventRegistrationToken = unpackEventRegistrationToken;
exports.EventRegistrationToken_Type = EventRegistrationToken_Type;
exports.packEventRegistrationToken = packEventRegistrationToken;
exports.unpackTextSegment = unpackTextSegment;
exports.TextSegment_Type = TextSegment_Type;
exports.packTextSegment = packTextSegment;
exports.StorageFileQueryResult = StorageFileQueryResult;
exports.IStorageFileQueryResult2 = IStorageFileQueryResult2;
