// Generated by dynwinrt-codegen — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('../../dist/index.js');
let __m_IIterable_IKeyValuePair_String_Object;
const __load_IIterable_IKeyValuePair_String_Object = () => (__m_IIterable_IKeyValuePair_String_Object ??= require('./IIterable_IKeyValuePair_String_Object.js'));
const __get_IIterable_IKeyValuePair_String_Object = () => __load_IIterable_IKeyValuePair_String_Object().IIterable_IKeyValuePair_String_Object;
let __m_IIterable_String;
const __load_IIterable_String = () => (__m_IIterable_String ??= require('./IIterable_String.js'));
const __get_IIterable_String = () => __load_IIterable_String().IIterable_String;
let __m_IKeyValuePair_String_Object;
const __load_IKeyValuePair_String_Object = () => (__m_IKeyValuePair_String_Object ??= require('./IKeyValuePair_String_Object.js'));
const __get_IKeyValuePair_String_Object = () => __load_IKeyValuePair_String_Object().IKeyValuePair_String_Object;
let __m_IMap_String_Object;
const __load_IMap_String_Object = () => (__m_IMap_String_Object ??= require('./IMap_String_Object.js'));
const __get_IMap_String_Object = () => __load_IMap_String_Object().IMap_String_Object;
let __m_DocumentProperties;
const __load_DocumentProperties = () => (__m_DocumentProperties ??= require('./DocumentProperties.js'));
const __get_DocumentProperties = () => __load_DocumentProperties().DocumentProperties;
let __m_ImageProperties;
const __load_ImageProperties = () => (__m_ImageProperties ??= require('./ImageProperties.js'));
const __get_ImageProperties = () => __load_ImageProperties().ImageProperties;
let __m_MusicProperties;
const __load_MusicProperties = () => (__m_MusicProperties ??= require('./MusicProperties.js'));
const __get_MusicProperties = () => __load_MusicProperties().MusicProperties;
let __m_VideoProperties;
const __load_VideoProperties = () => (__m_VideoProperties ??= require('./VideoProperties.js'));
const __get_VideoProperties = () => __load_VideoProperties().VideoProperties;
const { IID_IStorageItemExtraProperties } = require('./IStorageItemExtraProperties.js');
let __m_IStorageItemExtraProperties;
const __load_IStorageItemExtraProperties = () => (__m_IStorageItemExtraProperties ??= require('./IStorageItemExtraProperties.js'));
const __get_IStorageItemExtraProperties = () => __load_IStorageItemExtraProperties().IStorageItemExtraProperties;
let __m_lifetime;
const __load_lifetime = () => (__m_lifetime ??= require('./lifetime.js'));
const __get_trackProjectedValue = () => __load_lifetime().trackProjectedValue;

const _unwrap = (x) => x?._obj ?? x;

const IID_IStorageItemContentProperties = WinGuid.parse('05294bad-bc38-48bf-85d7-770e0e2ae0ba');
const IID_StorageItemContentProperties = WinGuid.parse('05294bad-bc38-48bf-85d7-770e0e2ae0ba');

let _IStorageItemContentPropertiesCache;
const _IStorageItemContentProperties = new Proxy({}, {
    get(_target, prop) {
        _IStorageItemContentPropertiesCache ??= DynWinRtType.registerInterface(
        "IStorageItemContentProperties", IID_IStorageItemContentProperties)
        .addMethod("GetMusicPropertiesAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.FileProperties.MusicProperties', WinGuid.parse('bc8aab62-66ec-419a-bc5d-ca65a4cb46da')))))
        .addMethod("GetVideoPropertiesAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.FileProperties.VideoProperties', WinGuid.parse('719ae507-68de-4db8-97de-49998c059f2f')))))
        .addMethod("GetImagePropertiesAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.FileProperties.ImageProperties', WinGuid.parse('523c9424-fcff-4275-afee-ecdb9ab47973')))))
        .addMethod("GetDocumentPropertiesAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.FileProperties.DocumentProperties', WinGuid.parse('7eab19bc-1821-4923-b4a9-0aea404d0070')))));
        const value = _IStorageItemContentPropertiesCache[prop];
        return typeof value === 'function' ? value.bind(_IStorageItemContentPropertiesCache) : value;
    }
});

let _IStorageItemExtraPropertiesCache;
const _IStorageItemExtraProperties = new Proxy({}, {
    get(_target, prop) {
        _IStorageItemExtraPropertiesCache ??= DynWinRtType.registerInterface(
        "IStorageItemExtraProperties", IID_IStorageItemExtraProperties)
        .addMethod("RetrievePropertiesAsync", new DynWinRtMethodSig().addIn(DynWinRtType.parameterized(WinGuid.parse('faa585ea-6214-4217-afda-7f46de5869b3'), [DynWinRtType.hstring()])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.parameterized(WinGuid.parse('3c2925fe-8519-45c1-aa79-197b6718c1c1'), [DynWinRtType.hstring(), DynWinRtType.object()]))))
        .addMethod("SavePropertiesAsync", new DynWinRtMethodSig().addIn(DynWinRtType.parameterized(WinGuid.parse('faa585ea-6214-4217-afda-7f46de5869b3'), [DynWinRtType.parameterized(WinGuid.parse('02b51929-c1c4-4a7e-8940-0312b5c18500'), [DynWinRtType.hstring(), DynWinRtType.object()])])).addOut(DynWinRtType.iAsyncAction()))
        .addMethod("SavePropertiesAsyncOverloadDefault", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncAction()));
        const value = _IStorageItemExtraPropertiesCache[prop];
        return typeof value === 'function' ? value.bind(_IStorageItemExtraPropertiesCache) : value;
    }
});

class StorageItemContentProperties {
    _obj;

    constructor() {
        throw new TypeError('StorageItemContentProperties cannot be constructed directly.');
    }
    static _fromNative(obj) {
        return Object.assign(Object.create(StorageItemContentProperties.prototype), { _obj: (__get_trackProjectedValue())((__get_trackProjectedValue())(obj, 'StorageItemContentProperties').cast(IID_IStorageItemContentProperties), 'StorageItemContentProperties') });
    }
    async getMusicPropertiesAsync(signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageItemContentProperties.method(6).invoke(this._obj, []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : (__get_MusicProperties())._fromNative(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    async getVideoPropertiesAsync(signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageItemContentProperties.method(7).invoke(this._obj, []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : (__get_VideoProperties())._fromNative(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    async getImagePropertiesAsync(signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageItemContentProperties.method(8).invoke(this._obj, []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : (__get_ImageProperties())._fromNative(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    async getDocumentPropertiesAsync(signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageItemContentProperties.method(9).invoke(this._obj, []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : (__get_DocumentProperties())._fromNative(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
    async retrievePropertiesAsync(propertiesToRetrieve, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageItemExtraProperties.method(6).invoke(this._obj.cast(IID_IStorageItemExtraProperties), [(Array.isArray(propertiesToRetrieve) ? DynWinRtValue.createVector(propertiesToRetrieve.map(_i => DynWinRtValue.hstring(_i)), DynWinRtType.hstring()).cast(DynWinRtType.parameterized(WinGuid.parse('faa585ea-6214-4217-afda-7f46de5869b3'), [DynWinRtType.hstring()]).iid()) : _unwrap(propertiesToRetrieve).cast(DynWinRtType.parameterized(WinGuid.parse('faa585ea-6214-4217-afda-7f46de5869b3'), [DynWinRtType.hstring()]).iid()))]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return ((v) => v.isNull() ? null : new (__get_IMap_String_Object())(v))(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    async _savePropertiesAsync_1(signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageItemExtraProperties.method(8).invoke(this._obj.cast(IID_IStorageItemExtraProperties), []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            await _op.toPromise();
            return;
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    async _savePropertiesAsync_2(propertiesToSave, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageItemExtraProperties.method(7).invoke(this._obj.cast(IID_IStorageItemExtraProperties), [(Array.isArray(propertiesToSave) ? DynWinRtValue.createVector(propertiesToSave.map(_i => _unwrap(_i)), DynWinRtType.parameterized(WinGuid.parse('02b51929-c1c4-4a7e-8940-0312b5c18500'), [DynWinRtType.hstring(), DynWinRtType.object()])).cast(DynWinRtType.parameterized(WinGuid.parse('faa585ea-6214-4217-afda-7f46de5869b3'), [DynWinRtType.parameterized(WinGuid.parse('02b51929-c1c4-4a7e-8940-0312b5c18500'), [DynWinRtType.hstring(), DynWinRtType.object()])]).iid()) : _unwrap(propertiesToSave).cast(DynWinRtType.parameterized(WinGuid.parse('faa585ea-6214-4217-afda-7f46de5869b3'), [DynWinRtType.parameterized(WinGuid.parse('02b51929-c1c4-4a7e-8940-0312b5c18500'), [DynWinRtType.hstring(), DynWinRtType.object()])]).iid()))]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            await _op.toPromise();
            return;
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    savePropertiesAsync(...args) {
        if (args.length >= 1 && args[0] !== undefined && !(args[0] instanceof AbortSignal)) {
            return this._savePropertiesAsync_2(args[0], args[1]);
        }
        return this._savePropertiesAsync_1(args[0]);
    }
}
exports.IID_StorageItemContentProperties = IID_StorageItemContentProperties;
exports.StorageItemContentProperties = StorageItemContentProperties;
