// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '../../dist/index.js';
import { IStorageItem } from './IStorageItem.js';
import { StorageItemTypes } from './StorageItemTypes.js';
import { StorageLibraryChangeType } from './StorageLibraryChangeType.js';

export declare const IID_StorageLibraryChange: WinGuid;
export declare class StorageLibraryChange {
    private constructor();
    get changeType(): StorageLibraryChangeType;
    get path(): string;
    get previousPath(): string;
    isOfType(type: StorageItemTypes): boolean;
    getStorageItemAsync(signal?: AbortSignal): Promise<IStorageItem>;
}
