// Generated by dynwinrt-codegen — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('../../dist/index.js');
let __m_StreamedFileFailureMode;
const __load_StreamedFileFailureMode = () => (__m_StreamedFileFailureMode ??= require('./StreamedFileFailureMode.js'));
const __get_StreamedFileFailureMode = () => __load_StreamedFileFailureMode().StreamedFileFailureMode;
const { IID_IBuffer } = require('./IBuffer.js');
let __m_IBuffer;
const __load_IBuffer = () => (__m_IBuffer ??= require('./IBuffer.js'));
const __get_IBuffer = () => __load_IBuffer().IBuffer;
const { IID_IClosable } = require('./IClosable.js');
let __m_IClosable;
const __load_IClosable = () => (__m_IClosable ??= require('./IClosable.js'));
const __get_IClosable = () => __load_IClosable().IClosable;
let __m_lifetime;
const __load_lifetime = () => (__m_lifetime ??= require('./lifetime.js'));
const __get_trackProjectedValue = () => __load_lifetime().trackProjectedValue;

const _unwrap = (x) => x?._obj ?? x;

const IID_IOutputStream = WinGuid.parse('905a0fe6-bc53-11df-8c49-001e4fc686da');
const IID_IStreamedFileDataRequest = WinGuid.parse('1673fcce-dabd-4d50-beee-180b8a8191b6');
const IID_StreamedFileDataRequest = WinGuid.parse('905a0fe6-bc53-11df-8c49-001e4fc686da');

let _IOutputStreamCache;
const _IOutputStream = new Proxy({}, {
    get(_target, prop) {
        _IOutputStreamCache ??= DynWinRtType.registerInterface(
        "IOutputStream", IID_IOutputStream)
        .addMethod("WriteAsync", new DynWinRtMethodSig().addIn(DynWinRtType.interface(WinGuid.parse('905a0fe0-bc53-11df-8c49-001e4fc686da'))).addOut(DynWinRtType.iAsyncOperationWithProgress(DynWinRtType.u32(), DynWinRtType.u32())))
        .addMethod("FlushAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.boolType())));
        const value = _IOutputStreamCache[prop];
        return typeof value === 'function' ? value.bind(_IOutputStreamCache) : value;
    }
});

let _IClosableCache;
const _IClosable = new Proxy({}, {
    get(_target, prop) {
        _IClosableCache ??= DynWinRtType.registerInterface(
        "IClosable", IID_IClosable)
        .addMethod("Close", new DynWinRtMethodSig());
        const value = _IClosableCache[prop];
        return typeof value === 'function' ? value.bind(_IClosableCache) : value;
    }
});

let _IStreamedFileDataRequestCache;
const _IStreamedFileDataRequest = new Proxy({}, {
    get(_target, prop) {
        _IStreamedFileDataRequestCache ??= DynWinRtType.registerInterface(
        "IStreamedFileDataRequest", IID_IStreamedFileDataRequest)
        .addMethod("FailAndClose", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.StreamedFileFailureMode', ['Failed', 'CurrentlyUnavailable', 'Incomplete'], [0, 1, 2])));
        const value = _IStreamedFileDataRequestCache[prop];
        return typeof value === 'function' ? value.bind(_IStreamedFileDataRequestCache) : value;
    }
});

class StreamedFileDataRequest {
    _obj;

    constructor() {
        throw new TypeError('StreamedFileDataRequest cannot be constructed directly.');
    }
    static _fromNative(obj) {
        return Object.assign(Object.create(StreamedFileDataRequest.prototype), { _obj: (__get_trackProjectedValue())((__get_trackProjectedValue())(obj, 'StreamedFileDataRequest').cast(IID_IOutputStream), 'StreamedFileDataRequest') });
    }
    writeAsync(buffer, signal) {
        if (signal?.aborted) {
            const _rej = Promise.reject(signal.reason);
            _rej.catch(() => {});
            return Object.assign(_rej, {
                progress(_cb) { return this; },
                toPromise() { const _p = Promise.reject(signal.reason); _p.catch(() => {}); return _p; },
                cancel() {},
            });
        }
        const _op = _IOutputStream.method(6).invoke(this._obj, [(buffer == null ? DynWinRtValue.nullValue() : _unwrap(buffer))]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        const _wrap = (p) => p.then((_v) => _v.toNumber(), (_e) => { if (signal?.aborted) throw signal.reason; throw _e; }).finally(() => { if (_onAbort) signal.removeEventListener('abort', _onAbort); });
        const _promise = _wrap(_op.toPromise());
        return Object.assign(_promise, {
            progress(cb) { _op.onProgress((_p) => cb(_p.toNumber())); return this; },
            toPromise() { return _wrap(_op.toPromise()); },
            cancel() { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } },
        });
    }
    async flushAsync(signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IOutputStream.method(7).invoke(this._obj, []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return _v.toBool();
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    close() {
        (__get_IClosable()).from(this._obj).close();
    }
    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
    failAndClose(failureMode) {
        _IStreamedFileDataRequest.method(6).invoke(this._obj.cast(IID_IStreamedFileDataRequest), [DynWinRtValue.i32(failureMode)]);
    }
}

class IStreamedFileDataRequest {
    _obj;

    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IStreamedFileDataRequest(obj.cast(IID_IStreamedFileDataRequest));
    }

    failAndClose(failureMode) {
        _IStreamedFileDataRequest.method(6).invoke(this._obj, [DynWinRtValue.i32(failureMode)]);
    }
}
exports.IID_StreamedFileDataRequest = IID_StreamedFileDataRequest;
exports.StreamedFileDataRequest = StreamedFileDataRequest;
exports.IStreamedFileDataRequest = IStreamedFileDataRequest;
