// Generated by dynwinrt-codegen — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('../../dist/index.js');
let __m_ImageDisplayProperties;
const __load_ImageDisplayProperties = () => (__m_ImageDisplayProperties ??= require('./ImageDisplayProperties.js'));
const __get_ImageDisplayProperties = () => __load_ImageDisplayProperties().ImageDisplayProperties;
let __m_MediaPlaybackType;
const __load_MediaPlaybackType = () => (__m_MediaPlaybackType ??= require('./MediaPlaybackType.js'));
const __get_MediaPlaybackType = () => __load_MediaPlaybackType().MediaPlaybackType;
let __m_MusicDisplayProperties;
const __load_MusicDisplayProperties = () => (__m_MusicDisplayProperties ??= require('./MusicDisplayProperties.js'));
const __get_MusicDisplayProperties = () => __load_MusicDisplayProperties().MusicDisplayProperties;
let __m_VideoDisplayProperties;
const __load_VideoDisplayProperties = () => (__m_VideoDisplayProperties ??= require('./VideoDisplayProperties.js'));
const __get_VideoDisplayProperties = () => __load_VideoDisplayProperties().VideoDisplayProperties;
let __m_StorageFile;
const __load_StorageFile = () => (__m_StorageFile ??= require('./StorageFile.js'));
const __get_StorageFile = () => __load_StorageFile().StorageFile;
let __m_RandomAccessStreamReference;
const __load_RandomAccessStreamReference = () => (__m_RandomAccessStreamReference ??= require('./RandomAccessStreamReference.js'));
const __get_RandomAccessStreamReference = () => __load_RandomAccessStreamReference().RandomAccessStreamReference;
let __m_lifetime;
const __load_lifetime = () => (__m_lifetime ??= require('./lifetime.js'));
const __get_trackProjectedValue = () => __load_lifetime().trackProjectedValue;

const _unwrap = (x) => x?._obj ?? x;

const IID_ISystemMediaTransportControlsDisplayUpdater = WinGuid.parse('8abbc53e-fa55-4ecf-ad8e-c984e5dd1550');
const IID_SystemMediaTransportControlsDisplayUpdater = WinGuid.parse('8abbc53e-fa55-4ecf-ad8e-c984e5dd1550');

let _ISystemMediaTransportControlsDisplayUpdaterCache;
const _ISystemMediaTransportControlsDisplayUpdater = new Proxy({}, {
    get(_target, prop) {
        _ISystemMediaTransportControlsDisplayUpdaterCache ??= DynWinRtType.registerInterface(
        "ISystemMediaTransportControlsDisplayUpdater", IID_ISystemMediaTransportControlsDisplayUpdater)
        .addMethod("get_Type", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Windows.Media.MediaPlaybackType', ['Unknown', 'Music', 'Video', 'Image'], [0, 1, 2, 3])))
        .addMethod("put_Type", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Media.MediaPlaybackType', ['Unknown', 'Music', 'Video', 'Image'], [0, 1, 2, 3])))
        .addMethod("get_AppMediaId", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
        .addMethod("put_AppMediaId", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()))
        .addMethod("get_Thumbnail", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.Storage.Streams.RandomAccessStreamReference', WinGuid.parse('33ee3134-1dd6-4e3a-8067-d1c162e8642b'))))
        .addMethod("put_Thumbnail", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Windows.Storage.Streams.RandomAccessStreamReference', WinGuid.parse('33ee3134-1dd6-4e3a-8067-d1c162e8642b'))))
        .addMethod("get_MusicProperties", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.Media.MusicDisplayProperties', WinGuid.parse('6bbf0c59-d0a0-4d26-92a0-f978e1d18e7b'))))
        .addMethod("get_VideoProperties", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.Media.VideoDisplayProperties', WinGuid.parse('5609fdb1-5d2d-4872-8170-45dee5bc2f5c'))))
        .addMethod("get_ImageProperties", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.Media.ImageDisplayProperties', WinGuid.parse('cd0bc7ef-54e7-411f-9933-f0e98b0a96d2'))))
        .addMethod("CopyFromFileAsync", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Media.MediaPlaybackType', ['Unknown', 'Music', 'Video', 'Image'], [0, 1, 2, 3])).addIn(DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea'))).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.boolType())))
        .addMethod("ClearAll", new DynWinRtMethodSig())
        .addMethod("Update", new DynWinRtMethodSig());
        const value = _ISystemMediaTransportControlsDisplayUpdaterCache[prop];
        return typeof value === 'function' ? value.bind(_ISystemMediaTransportControlsDisplayUpdaterCache) : value;
    }
});

class SystemMediaTransportControlsDisplayUpdater {
    _obj;

    constructor() {
        throw new TypeError('SystemMediaTransportControlsDisplayUpdater cannot be constructed directly.');
    }
    static _fromNative(obj) {
        return Object.assign(Object.create(SystemMediaTransportControlsDisplayUpdater.prototype), { _obj: (__get_trackProjectedValue())((__get_trackProjectedValue())(obj, 'SystemMediaTransportControlsDisplayUpdater').cast(IID_ISystemMediaTransportControlsDisplayUpdater), 'SystemMediaTransportControlsDisplayUpdater') });
    }
    get type() {
        return _ISystemMediaTransportControlsDisplayUpdater.method(6).invoke(this._obj, []).toNumber();
    }
    set type(value) {
        _ISystemMediaTransportControlsDisplayUpdater.method(7).invoke(this._obj, [DynWinRtValue.i32(value)]);
    }
    get appMediaId() {
        return _ISystemMediaTransportControlsDisplayUpdater.method(8).invoke(this._obj, []).toString();
    }
    set appMediaId(value) {
        _ISystemMediaTransportControlsDisplayUpdater.method(9).invoke(this._obj, [DynWinRtValue.hstring(value)]);
    }
    get thumbnail() {
        return ((v) => v.isNull() ? null : (__get_RandomAccessStreamReference())._fromNative(v))(_ISystemMediaTransportControlsDisplayUpdater.method(10).invoke(this._obj, []));
    }
    set thumbnail(value) {
        _ISystemMediaTransportControlsDisplayUpdater.method(11).invoke(this._obj, [(value == null ? DynWinRtValue.nullValue() : _unwrap(value))]);
    }
    get musicProperties() {
        return ((v) => v.isNull() ? null : (__get_MusicDisplayProperties())._fromNative(v))(_ISystemMediaTransportControlsDisplayUpdater.method(12).invoke(this._obj, []));
    }
    get videoProperties() {
        return ((v) => v.isNull() ? null : (__get_VideoDisplayProperties())._fromNative(v))(_ISystemMediaTransportControlsDisplayUpdater.method(13).invoke(this._obj, []));
    }
    get imageProperties() {
        return ((v) => v.isNull() ? null : (__get_ImageDisplayProperties())._fromNative(v))(_ISystemMediaTransportControlsDisplayUpdater.method(14).invoke(this._obj, []));
    }
    async copyFromFileAsync(type, source, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _ISystemMediaTransportControlsDisplayUpdater.method(15).invoke(this._obj, [DynWinRtValue.i32(type), (source == null ? DynWinRtValue.nullValue() : _unwrap(source))]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return _v.toBool();
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    clearAll() {
        _ISystemMediaTransportControlsDisplayUpdater.method(16).invoke(this._obj, []);
    }
    update() {
        _ISystemMediaTransportControlsDisplayUpdater.method(17).invoke(this._obj, []);
    }
}
exports.IID_SystemMediaTransportControlsDisplayUpdater = IID_SystemMediaTransportControlsDisplayUpdater;
exports.SystemMediaTransportControlsDisplayUpdater = SystemMediaTransportControlsDisplayUpdater;
