// Generated by dynwinrt-codegen — do not edit
const { DynWinRtType, WinGuid } = require('../../dist/index.js');

const IID_TypedEventHandler_SystemMediaTransportControls_ShuffleEnabledChangeRequestedEventArgs = DynWinRtType.parameterized(WinGuid.parse('9de1c534-6ae1-11e0-84e1-18a905bcc53f'), [DynWinRtType.runtimeClass('Windows.Media.SystemMediaTransportControls', WinGuid.parse('99fa3ff4-1742-42a6-902e-087d41f965ec')), DynWinRtType.runtimeClass('Windows.Media.ShuffleEnabledChangeRequestedEventArgs', WinGuid.parse('49b593fe-4fd0-4666-a314-c0e01940d302'))]).iid();
const TypedEventHandler_SystemMediaTransportControls_ShuffleEnabledChangeRequestedEventArgs_PARAM_TYPES = [DynWinRtType.runtimeClass('Windows.Media.SystemMediaTransportControls', WinGuid.parse('99fa3ff4-1742-42a6-902e-087d41f965ec')), DynWinRtType.runtimeClass('Windows.Media.ShuffleEnabledChangeRequestedEventArgs', WinGuid.parse('49b593fe-4fd0-4666-a314-c0e01940d302'))];
exports.IID_TypedEventHandler_SystemMediaTransportControls_ShuffleEnabledChangeRequestedEventArgs = IID_TypedEventHandler_SystemMediaTransportControls_ShuffleEnabledChangeRequestedEventArgs;
exports.TypedEventHandler_SystemMediaTransportControls_ShuffleEnabledChangeRequestedEventArgs_PARAM_TYPES = TypedEventHandler_SystemMediaTransportControls_ShuffleEnabledChangeRequestedEventArgs_PARAM_TYPES;
