// Generated by dynwinrt-codegen — do not edit
const { DynWinRtType, WinGuid } = require('../../dist/index.js');

const IID_TypedEventHandler_SystemMediaTransportControls_AutoRepeatModeChangeRequestedEventArgs = DynWinRtType.parameterized(WinGuid.parse('9de1c534-6ae1-11e0-84e1-18a905bcc53f'), [DynWinRtType.runtimeClass('Windows.Media.SystemMediaTransportControls', WinGuid.parse('99fa3ff4-1742-42a6-902e-087d41f965ec')), DynWinRtType.runtimeClass('Windows.Media.AutoRepeatModeChangeRequestedEventArgs', WinGuid.parse('ea137efa-d852-438e-882b-c990109a78f4'))]).iid();
const TypedEventHandler_SystemMediaTransportControls_AutoRepeatModeChangeRequestedEventArgs_PARAM_TYPES = [DynWinRtType.runtimeClass('Windows.Media.SystemMediaTransportControls', WinGuid.parse('99fa3ff4-1742-42a6-902e-087d41f965ec')), DynWinRtType.runtimeClass('Windows.Media.AutoRepeatModeChangeRequestedEventArgs', WinGuid.parse('ea137efa-d852-438e-882b-c990109a78f4'))];
exports.IID_TypedEventHandler_SystemMediaTransportControls_AutoRepeatModeChangeRequestedEventArgs = IID_TypedEventHandler_SystemMediaTransportControls_AutoRepeatModeChangeRequestedEventArgs;
exports.TypedEventHandler_SystemMediaTransportControls_AutoRepeatModeChangeRequestedEventArgs_PARAM_TYPES = TypedEventHandler_SystemMediaTransportControls_AutoRepeatModeChangeRequestedEventArgs_PARAM_TYPES;
