// Generated by dynwinrt-codegen — do not edit
export type UserWatcherStatus = (typeof UserWatcherStatus)[keyof typeof UserWatcherStatus];
export declare const UserWatcherStatus: {
    readonly Created: 0;
    readonly Started: 1;
    readonly EnumerationCompleted: 2;
    readonly Stopping: 3;
    readonly Stopped: 4;
    readonly Aborted: 5;
};
