// Generated by dynwinrt-codegen — do not edit
export type UserAgeConsentGroup = (typeof UserAgeConsentGroup)[keyof typeof UserAgeConsentGroup];
export declare const UserAgeConsentGroup: {
    readonly Child: 0;
    readonly Minor: 1;
    readonly Adult: 2;
};
