// Generated by dynwinrt-codegen — do not edit

const UserPictureSize = Object.freeze({
    Size64x64: 0,
    Size208x208: 1,
    Size424x424: 2,
    Size1080x1080: 3,
});
exports.UserPictureSize = UserPictureSize;
