// Generated by dynwinrt-codegen — do not edit
export type UserAuthenticationStatus = (typeof UserAuthenticationStatus)[keyof typeof UserAuthenticationStatus];
export declare const UserAuthenticationStatus: {
    readonly Unauthenticated: 0;
    readonly LocallyAuthenticated: 1;
    readonly RemotelyAuthenticated: 2;
};
