// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! Generate Python `.pyi` stub files for IDE / type-checker support.
//! Stubs contain only type signatures; method bodies are `...`.
//! Implementation details (interface registration, struct helpers, IID
//! constants tied to runtime, factory activation) are not emitted.

use std::collections::HashSet;

use crate::meta::{ClassMeta, InterfaceMeta, MethodMeta};
use crate::types::{TypeKind, TypeMeta};

use crate::codegen::winrt::extensions::winui;
use crate::codegen::winrt::shared::imports::{
    collect_iface_type_imports, collect_struct_field_type_imports, collect_type_imports,
    collect_used_generic_identities_from_class, collect_used_generic_identities_from_methods,
    collect_used_generic_identities_from_type,
};
use crate::codegen::winrt::shared::structs::{
    collect_used_structs_from_class, collect_used_structs_from_iface,
    collect_used_structs_from_struct,
};

use super::collections::{
    CollectionKind, abc_name, class_interface, interface_kind, observable_vector_identity,
};
use super::naming::{PythonProjectionContext, is_py_reserved, to_snake_case};
use super::native_types::foundation_type;
use super::shared::reorder_getters_before_setters;
use super::signature::py_dynwinrt_type;
use super::stub_helpers::{
    emit_method_stub, emit_method_stub_named, emit_static_method_stub,
    emit_static_method_stub_named, emit_struct_stub, format_py_type_import,
    generate_struct_stub_imports, py_struct_export_names,
};
use super::type_helpers::methods_have_async_output;

const HEADER: &str = "# Generated by dynwinrt-codegen — do not edit\n";
const FUTURE_ANNOTATIONS: &str = "from __future__ import annotations\n";
const IMPORT_LINE: &str = "\
import builtins
from ._typing import (
    Callable, Iterable, Iterator, Mapping, MutableMapping, MutableSequence, Sequence,
    UUID, WinGUID, datetime, overload, timedelta,
    DynWinRTType, DynWinRTValue, DynWinRTArray, DynWinRTStruct, DynWinRtDelegate,
    _DynWinRTProjector,
)\n";
const ASYNC_IMPORT_LINE: &str = "from dynwinrt import WinRTCoroutine, WinRTCoroutineWithProgress\n";

pub fn generate_typing_support_module() -> String {
    format!(
        "{HEADER}\
from collections.abc import (\n\
    Callable as Callable, Iterable as Iterable, Iterator as Iterator,\n\
    Mapping as Mapping, MutableMapping as MutableMapping,\n\
    MutableSequence as MutableSequence, Sequence as Sequence,\n\
)\n\
from datetime import datetime as datetime, timedelta as timedelta\n\
from typing import overload as overload\n\
from uuid import UUID as UUID\n\
from dynwinrt import (\n\
    DynWinRTType as DynWinRTType, DynWinRTValue as DynWinRTValue,\n\
    DynWinRTArray as DynWinRTArray, DynWinRTStruct as DynWinRTStruct,\n\
    DynWinRtDelegate as DynWinRtDelegate, WinGUID as WinGUID,\n\
    _DynWinRTProjector as _DynWinRTProjector,\n\
    _DynWinRTProjectableClass as _DynWinRTProjectableClass,\n\
    _DynWinRTRuntimeClass as _DynWinRTRuntimeClass,\n\
)\n"
    )
}

pub fn generate_runtime_support_stub() -> String {
    format!("{HEADER}{FUTURE_ANNOTATIONS}")
}

fn identity_marker(prefix: &str, namespace: &str, name: &str) -> String {
    let identity = format!("{namespace}_{name}")
        .chars()
        .map(|character| {
            if character.is_ascii_alphanumeric() {
                character.to_ascii_lowercase()
            } else {
                '_'
            }
        })
        .collect::<String>();
    format!("_dynwinrt_{prefix}_{identity}")
}

fn interface_marker(interface: &InterfaceMeta) -> String {
    identity_marker("iid", &interface.namespace, &interface.name)
}

fn interface_symbol(context: &PythonProjectionContext, interface: &InterfaceMeta) -> String {
    context.reference_name(&interface.type_identity())
}

fn class_marker(class: &ClassMeta) -> String {
    identity_marker("class", &class.namespace, &class.name)
}

pub fn generate_struct_stub(context: &PythonProjectionContext, s: &TypeMeta) -> Option<String> {
    let TypeMeta::Struct { name, .. } = s else {
        return None;
    };
    if name == "HResult" {
        return None;
    }

    let mut out = String::new();
    out.push_str(HEADER);
    out.push_str(FUTURE_ANNOTATIONS);
    out.push_str(IMPORT_LINE);
    out.push_str(&generate_struct_stub_imports(
        context,
        &collect_used_structs_from_struct(s),
    ));

    let mut imports = collect_struct_field_type_imports(s)
        .into_iter()
        .map(|type_ref| {
            format_py_type_import(context, &type_ref.namespace, &type_ref.name, type_ref.kind)
        })
        .collect::<Vec<_>>();
    imports.extend(
        collect_used_generic_identities_from_type(s)
            .into_iter()
            .map(|identity| {
                let identity = context.normalize_identity(&identity);
                let name = context.projected_name(&identity);
                let reference_name = context.reference_name(&identity);
                let import = if name == reference_name {
                    name
                } else {
                    format!("{name} as {reference_name}")
                };
                format!(
                    "from .{} import {import}  # noqa: F401\n",
                    context.implementation_module(&identity),
                )
            }),
    );
    imports.sort();
    imports.dedup();
    out.push_str(&imports.concat());
    out.push_str(&emit_struct_stub(context, s));
    Some(out)
}

/// Generate a `.pyi` stub for an enum. Returns `None` for non-enum TypeMeta.
pub fn generate_enum_stub(_context: &PythonProjectionContext, en: &TypeMeta) -> Option<String> {
    let (name, members, is_flags, doc, deprecated) = match en {
        TypeMeta::Enum {
            name,
            members,
            is_flags,
            doc,
            deprecated,
            ..
        } => (
            name,
            members,
            *is_flags,
            doc.as_deref(),
            deprecated.as_deref(),
        ),
        _ => return None,
    };
    let mut out = String::new();
    out.push_str(HEADER);
    let enum_base = if is_flags { "IntFlag" } else { "IntEnum" };
    out.push_str(&format!("from enum import {enum_base}\n\n\n"));
    out.push_str(&format!("class {}({enum_base}):\n", name));
    out.push_str(&super::docs::format_pydoc(
        &crate::codegen::winrt::shared::docs::DocText {
            summary: doc,
            deprecated,
            ..Default::default()
        },
        "    ",
    ));
    if members.is_empty() {
        out.push_str("    pass\n");
    } else {
        for m in members {
            let member_name = if is_py_reserved(&m.name) {
                format!("{}_", m.name)
            } else {
                m.name.clone()
            };
            out.push_str(&format!("    {} = {}\n", member_name, m.value));
        }
    }
    Some(out)
}

/// Generate a `.pyi` stub for an interface (or a delegate).
pub fn generate_interface_stub(context: &PythonProjectionContext, iface: &InterfaceMeta) -> String {
    let mut projected_iface = iface.clone();
    projected_iface.name = context.projected_name_for_interface(iface);
    let iface = &projected_iface;
    let is_delegate = iface.is_delegate();
    if is_delegate {
        // Delegate stub: only IID + PARAM_TYPES declarations
        let mut out = String::new();
        out.push_str(HEADER);
        out.push_str(FUTURE_ANNOTATIONS);
        out.push_str("from dynwinrt import DynWinRTType, WinGUID\n\n");
        out.push_str(&format!("IID_{}: WinGUID\n", iface.name));
        out.push_str(&format!("{}_PARAM_TYPES: list[DynWinRTType]\n", iface.name));
        return out;
    }

    let used_structs = collect_used_structs_from_iface(iface);

    let mut out = String::new();
    out.push_str(HEADER);
    out.push_str(FUTURE_ANNOTATIONS);
    out.push_str(IMPORT_LINE);
    let collection_kind = interface_kind(iface);
    let is_protocol = collection_kind.is_none();
    out.push_str("from typing import Protocol, Self, TypeVar\n");
    if methods_have_async_output(iface.methods.iter()) {
        out.push_str(ASYNC_IMPORT_LINE);
    }
    if iface
        .methods
        .iter()
        .any(|method| method.is_event_add || method.is_event_remove)
    {
        out.push_str("from typing import Callable\n");
    }
    if context.is_packaged() {
        out.push_str(&generate_struct_stub_imports(context, &used_structs));
    }
    out.push('\n');
    if !iface.iid.is_empty() || iface.generic_piid.is_some() {
        out.push_str("_InterfaceT = TypeVar('_InterfaceT')\n\n");
    }

    let delegate_names = super::collect_referenced_delegate_names(&iface.methods, context);
    let runtime_delegate_names = super::collect_runtime_delegate_names(&iface.methods, context);

    let collection_identities = collect_used_generic_identities_from_methods(&iface.methods);
    let observable_vector = observable_vector_identity(iface);
    for identity in &collection_identities {
        let identity = context.normalize_identity(identity);
        if identity != iface.type_identity() && !delegate_names.contains(&identity) {
            let module = context.implementation_module(&identity);
            let name = context.projected_name(&identity);
            let reference_name = context.reference_name(&identity);
            let import = if name == reference_name {
                name
            } else {
                format!("{name} as {reference_name}")
            };
            out.push_str(&format!("from .{module} import {import}  # noqa: F401\n"));
        }
    }
    if observable_vector.is_some() {
        let identity = crate::types::TypeIdentity::closed_generic(
            crate::types::TypeIdentityKind::Interface,
            crate::meta::WINDOWS_FOUNDATION_COLLECTIONS_NAMESPACE,
            "IVector",
            iface.generic_args.iter().map(TypeMeta::type_identity),
        );
        if !collection_identities
            .iter()
            .any(|candidate| context.normalize_identity(candidate) == identity)
        {
            let module = context.implementation_module(&identity);
            let vector_name = context.projected_name(&identity);
            let reference_name = context.reference_name(&identity);
            let import = if vector_name == reference_name {
                vector_name
            } else {
                format!("{vector_name} as {reference_name}")
            };
            out.push_str(&format!("from .{module} import {import}  # noqa: F401\n"));
        }
    }
    if observable_vector.is_some() {
        let event_args = "IVectorChangedEventArgs";
        let identity = crate::types::TypeIdentity::named(
            crate::types::TypeIdentityKind::Interface,
            crate::meta::WINDOWS_FOUNDATION_COLLECTIONS_NAMESPACE,
            event_args,
        );
        let module = context.implementation_module(&identity);
        out.push_str(&format!(
            "from .{module} import {event_args}  # noqa: F401\n"
        ));
    }

    let mut sorted_delegates: Vec<_> = runtime_delegate_names.iter().collect();
    sorted_delegates.sort();
    for identity in &sorted_delegates {
        let module = context.implementation_module(identity);
        let dname = context.projected_name(identity);
        let reference_name = context.reference_name(identity);
        let imports = if dname == reference_name {
            format!("IID_{dname}, {dname}_PARAM_TYPES")
        } else {
            format!(
                "IID_{dname} as IID_{reference_name}, \
                 {dname}_PARAM_TYPES as {reference_name}_PARAM_TYPES"
            )
        };
        out.push_str(&format!("from .{module} import {imports}  # noqa: F401\n",));
    }

    let type_imports = collect_iface_type_imports(iface);
    let mut sorted_type_imports: Vec<_> = type_imports.iter().collect();
    sorted_type_imports
        .sort_by(|a, b| (&a.namespace, &a.name, &a.kind).cmp(&(&b.namespace, &b.name, &b.kind)));
    for r in &sorted_type_imports {
        let identity_kind = match r.kind {
            TypeKind::Class => crate::types::TypeIdentityKind::Class,
            TypeKind::Enum => crate::types::TypeIdentityKind::Enum,
            TypeKind::Interface => crate::types::TypeIdentityKind::Interface,
        };
        let identity = context.normalize_identity(&crate::types::TypeIdentity::named(
            identity_kind,
            r.namespace.clone(),
            r.name.clone(),
        ));
        if context.is_known_ref(r) && !delegate_names.contains(&identity) {
            out.push_str(&format_py_type_import(
                context,
                &r.namespace,
                &r.name,
                r.kind,
            ));
        }
    }
    out.push('\n');

    if iface.generic_piid.is_some() || !iface.iid.is_empty() {
        out.push_str(&format!("IID_{}: WinGUID\n", iface.name));
    }
    out.push('\n');

    if !context.is_packaged() {
        for s in &used_structs {
            out.push_str(&emit_struct_stub(context, s));
            out.push('\n');
        }
    }

    let collection_base =
        collection_kind
            .and_then(abc_name)
            .and_then(|abc| match iface.generic_args.as_slice() {
                [element] => Some(format!(
                    "{}[{}]",
                    abc,
                    super::type_helpers::py_return_type_safe(Some(element), context)
                )),
                [key, value] => Some(format!(
                    "{}[{}, {}]",
                    abc,
                    super::type_helpers::py_return_type_safe(Some(key), context),
                    super::type_helpers::py_return_type_safe(Some(value), context)
                )),
                _ => None,
            });
    let identity_name = format!("_{}Identity", iface.name);
    out.push_str(&format!("\nclass {identity_name}(Protocol):\n"));
    out.push_str(&format!(
        "    def {}(self) -> None: ...\n",
        interface_marker(iface)
    ));

    let mut bases = vec![identity_name];
    if is_protocol {
        bases.push("Protocol".into());
    } else if let Some(base) = collection_base {
        bases.push(base);
    }
    let mut seen_bases = HashSet::new();
    bases.retain(|base| seen_bases.insert(base.clone()));
    if bases.is_empty() {
        out.push_str(&format!("\nclass {}:\n", iface.name));
    } else {
        out.push_str(&format!("\nclass {}({}):\n", iface.name, bases.join(", ")));
    }
    out.push_str(&super::docs::format_pydoc(
        &crate::codegen::winrt::shared::docs::DocText {
            summary: iface.doc.as_deref(),
            deprecated: iface.deprecated.as_deref(),
            ..Default::default()
        },
        "    ",
    ));
    if !is_protocol {
        out.push_str("    def __init__(self, obj: DynWinRTValue) -> None: ...\n");
    }
    out.push_str(&collection_protocol_stubs(iface, context, 4));
    if !iface.iid.is_empty() || iface.generic_piid.is_some() {
        out.push('\n');
        out.push_str("    @classmethod\n");
        out.push_str("    def from_value(cls, obj: DynWinRTValue) -> Self: ...\n");
        out.push_str(
            "    def as_interface(self, interface_class: _DynWinRTProjector[_InterfaceT]) -> _InterfaceT: ...\n",
        );
    }
    if crate::codegen::winrt::is_ibuffer_interface(&iface.namespace, &iface.name, &iface.iid) {
        out.push_str(
            "\n    @staticmethod\n\
             \x20   def from_bytes(data: bytes | bytearray) -> 'IBuffer': ...\n\
             \x20   def to_bytes(self) -> bytes: ...\n",
        );
    }

    // IVector<T> / IMap<K,V> create()
    if let Some(ref piid) = iface.generic_piid {
        if piid == "5917eb53-50b4-4a0d-b309-65862b3f1dbc" && iface.generic_args.len() == 1 {
            let element = super::type_helpers::py_param_type_safe(&iface.generic_args[0], context);
            let vector_name = context.projected_name(
                observable_vector
                    .as_ref()
                    .expect("observable vector companion"),
            );
            out.push('\n');
            out.push_str("    @staticmethod\n");
            out.push_str(&format!(
                "    def create(items: Iterable[{}]) -> '{}': ...\n",
                element, iface.name
            ));
            out.push_str(&format!(
                "    def as_vector(self) -> '{}': ...\n",
                vector_name
            ));
        } else if piid == "913337e9-11a1-4345-a3a2-4e7f956e222d" && iface.generic_args.len() == 1 {
            let element = super::type_helpers::py_param_type_safe(&iface.generic_args[0], context);
            out.push('\n');
            out.push_str("    @staticmethod\n");
            out.push_str(&format!(
                "    def create(items: Iterable[{}]) -> '{}': ...\n",
                element, iface.name
            ));
        } else if piid == "3c2925fe-8519-45c1-aa79-197b6718c1c1" && iface.generic_args.len() == 2 {
            let key = super::type_helpers::py_param_type_safe(&iface.generic_args[0], context);
            let value = super::type_helpers::py_param_type_safe(&iface.generic_args[1], context);
            out.push('\n');
            out.push_str("    @staticmethod\n");
            out.push_str(&format!(
                "    def create(items: Mapping[{}, {}]) -> '{}': ...\n",
                key, value, iface.name
            ));
        }
    }

    if iface.namespace == "Microsoft.UI.Xaml" && iface.name == "IElementFactory" {
        out.push_str(
            "\n    @staticmethod\n\
             \x20   def create(\n\
             \x20       get_element: Callable[['ElementFactoryGetArgs'], 'UIElement'],\n\
             \x20       recycle_element: Callable[['ElementFactoryRecycleArgs'], object],\n\
             \x20   ) -> 'IElementFactory': ...\n\
             \x20   def release_callbacks(self) -> None: ...\n",
        );
    }

    for methods in super::overloads::grouped_methods(reorder_getters_before_setters(&iface.methods))
    {
        let event_has_remove = methods.first().is_some_and(|method| {
            method.name.strip_prefix("add_").is_some_and(|suffix| {
                iface
                    .methods
                    .iter()
                    .any(|candidate| candidate.name == format!("remove_{suffix}"))
            })
        });
        let property_has_getter = methods.first().is_none_or(|method| {
            !method.is_property_setter
                || method.name.strip_prefix("put_").is_some_and(|suffix| {
                    iface
                        .methods
                        .iter()
                        .any(|candidate| candidate.name == format!("get_{suffix}"))
                })
        });
        out.push('\n');
        out.push_str(&emit_instance_stub_group(
            &methods,
            context,
            4,
            event_has_remove,
            property_has_getter,
            collection_kind == Some(CollectionKind::MutableSequence),
        ));
    }
    out.push_str(&emit_instance_compatibility_alias_stubs(
        iface.methods.iter(),
        context,
        4,
        collection_kind == Some(CollectionKind::MutableSequence),
    ));

    out
}

/// Generate a `.pyi` stub for a runtime class.
pub fn generate_class_stub(
    context: &PythonProjectionContext,
    class: &ClassMeta,
    shared_iids: &HashSet<String>,
) -> String {
    let used_structs = collect_used_structs_from_class(class);
    let collection_iface = class_interface(class);
    let collection_kind = collection_iface.and_then(interface_kind);
    let known_full_names = context.known_full_names();
    let winui_bootstrap = winui::resolve_application_bootstrap(class, &known_full_names);
    let has_public_composition = class
        .constructors
        .iter()
        .any(|constructor| constructor.kind == crate::meta::ConstructorKind::PublicComposition);
    let has_events = class.all_interfaces().any(|iface| {
        iface
            .methods
            .iter()
            .any(|method| method.is_event_add || method.is_event_remove)
    });
    let has_closable = class
        .required_interfaces
        .iter()
        .any(|interface| interface.iid == "30d5a829-7fa4-4026-83bb-d75bae4ea99e");
    let projectable = super::has_projectable_default_interface(class);
    let native_projectable = super::has_native_projector(class);
    let supports_interface_projection = projectable || !class.required_interfaces.is_empty();

    let mut out = String::new();
    out.push_str(HEADER);
    out.push_str(FUTURE_ANNOTATIONS);
    out.push_str(IMPORT_LINE);
    if projectable {
        out.push_str("from ._typing import _DynWinRTRuntimeClass\n");
    } else if native_projectable {
        out.push_str("from ._typing import _DynWinRTProjectableClass\n");
    }
    out.push_str("from typing import Protocol, Self\n");
    if !has_constructor_stub_overload(class) {
        out.push_str("from typing import NoReturn\n");
    }
    if has_public_composition {
        out.push_str("from dynwinrt import DynWinRTXamlRegistration\n");
    }
    if methods_have_async_output(
        class
            .all_interfaces()
            .flat_map(|interface| interface.methods.iter()),
    ) {
        out.push_str(ASYNC_IMPORT_LINE);
    }
    if has_events || winui_bootstrap.is_some() {
        out.push_str("from typing import Callable\n");
    }
    if has_closable {
        out.push_str("from typing import Literal\n");
    }
    if supports_interface_projection {
        out.push_str("from typing import TypeVar\n");
    } else if winui::is_dispatcher_queue(class) {
        out.push_str("from typing import TypeVar\n");
    }
    if context.is_packaged() {
        out.push_str(&generate_struct_stub_imports(context, &used_structs));
    }
    out.push('\n');
    if winui::is_dispatcher_queue(class) {
        out.push_str("_DispatchResultT = TypeVar('_DispatchResultT')\n\n");
    }

    let mut delegate_names = HashSet::new();
    let mut runtime_delegate_names = HashSet::new();
    for iface in class.all_interfaces() {
        delegate_names.extend(super::collect_referenced_delegate_names(
            &iface.methods,
            context,
        ));
        runtime_delegate_names.extend(super::collect_runtime_delegate_names(
            &iface.methods,
            context,
        ));
    }

    let mut imported_names: HashSet<String> = HashSet::new();
    let collection_identities = collect_used_generic_identities_from_class(class);
    for identity in &collection_identities {
        let identity = context.normalize_identity(identity);
        if !delegate_names.contains(&identity) {
            let module = context.implementation_module(&identity);
            let name = context.projected_name(&identity);
            let reference_name = context.reference_name(&identity);
            let import = if name == reference_name {
                name
            } else {
                format!("{name} as {reference_name}")
            };
            out.push_str(&format!("from .{module} import {import}  # noqa: F401\n"));
            imported_names.insert(reference_name);
        }
    }
    for iface in class.all_interfaces() {
        if iface.generic_piid.as_deref() == Some(super::collections::IOBSERVABLE_VECTOR_PIID) {
            let identity = iface.type_identity();
            let projected_name = context.projected_name(&identity);
            if imported_names.insert(projected_name.clone()) {
                let module = context.implementation_module(&identity);
                out.push_str(&format!(
                    "from .{module} import {projected_name}  # noqa: F401\n"
                ));
            }
            let event_args = "IVectorChangedEventArgs";
            if imported_names.insert(event_args.into()) {
                let identity = crate::types::TypeIdentity::named(
                    crate::types::TypeIdentityKind::Interface,
                    crate::meta::WINDOWS_FOUNDATION_COLLECTIONS_NAMESPACE,
                    event_args,
                );
                let module = context.implementation_module(&identity);
                out.push_str(&format!(
                    "from .{module} import {event_args}  # noqa: F401\n"
                ));
            }
        }
    }

    let mut sorted_delegates: Vec<_> = runtime_delegate_names.iter().collect();
    sorted_delegates.sort();
    for identity in &sorted_delegates {
        let module = context.implementation_module(identity);
        let dname = context.projected_name(identity);
        let reference_name = context.reference_name(identity);
        let imports = if dname == reference_name {
            format!("IID_{dname}, {dname}_PARAM_TYPES")
        } else {
            format!(
                "IID_{dname} as IID_{reference_name}, \
                 {dname}_PARAM_TYPES as {reference_name}_PARAM_TYPES"
            )
        };
        out.push_str(&format!("from .{module} import {imports}  # noqa: F401\n",));
    }

    let imports = collect_type_imports(class);
    let mut sorted_imports: Vec<_> = imports.iter().collect();
    sorted_imports
        .sort_by(|a, b| (&a.namespace, &a.name, &a.kind).cmp(&(&b.namespace, &b.name, &b.kind)));
    for r in &sorted_imports {
        let identity_kind = match r.kind {
            TypeKind::Class => crate::types::TypeIdentityKind::Class,
            TypeKind::Enum => crate::types::TypeIdentityKind::Enum,
            TypeKind::Interface => crate::types::TypeIdentityKind::Interface,
        };
        let identity = context.normalize_identity(&crate::types::TypeIdentity::named(
            identity_kind,
            r.namespace.clone(),
            r.name.clone(),
        ));
        if context.is_known_ref(r) && !delegate_names.contains(&identity) {
            out.push_str(&format_py_type_import(
                context,
                &r.namespace,
                &r.name,
                r.kind,
            ));
            let reference_name = context.reference_name(&identity);
            imported_names.insert(reference_name.clone());
            if r.kind == TypeKind::Interface {
                imported_names.insert(format!("IID_{reference_name}"));
            }
        }
    }
    let base_identity = class
        .base_class
        .as_ref()
        .filter(|base| context.is_known_ref(base))
        .map(|base| {
            let identity = crate::types::TypeIdentity::named(
                crate::types::TypeIdentityKind::Class,
                base.namespace.clone(),
                base.name.clone(),
            );
            let name = context.reference_name(&identity);
            out.push_str(&format!(
                "from .{} import _{}Identity  # noqa: F401\n",
                context.implementation_module(&identity),
                name
            ));
            format!("_{name}Identity")
        });
    for req_iface in &class.required_interfaces {
        let symbol = interface_symbol(context, req_iface);
        if req_iface.generic_piid.is_none()
            && !req_iface.iid.is_empty()
            && shared_iids.contains(&req_iface.iid)
            && !imported_names.contains(&symbol)
        {
            out.push_str(&format_py_type_import(
                context,
                &req_iface.namespace,
                &req_iface.name,
                TypeKind::Interface,
            ));
            imported_names.insert(symbol.clone());
            imported_names.insert(format!("IID_{symbol}"));
        }
    }
    if let Some(bootstrap) = winui_bootstrap {
        let metadata_provider = bootstrap.spec.metadata_provider;
        out.push_str(&format!(
            "from .{} import {}  # noqa: F401\n",
            context.implementation_module_for_named(
                crate::types::TypeIdentityKind::Class,
                metadata_provider.namespace,
                metadata_provider.name,
            ),
            metadata_provider.name,
        ));
    }
    out.push('\n');
    if supports_interface_projection {
        out.push_str("_InterfaceT = TypeVar('_InterfaceT')\n\n");
    }

    // IID constants (declarations only)
    let mut declared_iids = HashSet::new();
    for iface in class.all_interfaces() {
        let iid_name = format!("IID_{}", interface_symbol(context, iface));
        if !iface.iid.is_empty()
            && !imported_names.contains(&iid_name)
            && declared_iids.insert(iid_name.clone())
        {
            out.push_str(&format!("{}: WinGUID\n", iid_name));
        }
    }
    out.push('\n');

    if !context.is_packaged() {
        for s in &used_structs {
            out.push_str(&emit_struct_stub(context, s));
            out.push('\n');
        }
    }

    let collection_base = collection_iface
        .zip(collection_kind.and_then(abc_name))
        .and_then(|(iface, abc)| match iface.generic_args.as_slice() {
            [element] => Some(format!(
                "{}[{}]",
                abc,
                super::type_helpers::py_return_type_safe(Some(element), context)
            )),
            [key, value] => Some(format!(
                "{}[{}, {}]",
                abc,
                super::type_helpers::py_return_type_safe(Some(key), context),
                super::type_helpers::py_return_type_safe(Some(value), context)
            )),
            _ => None,
        });
    let mut instance_stub_body =
        emit_class_instance_stubs(class, context, collection_iface, false, has_closable);
    if crate::codegen::winrt::is_buffer_class(&class.namespace, &class.name) {
        instance_stub_body.push_str("    def to_bytes(self) -> bytes: ...\n");
    }
    let identity_name = format!("_{}Identity", class.name);
    let mut identity_bases = base_identity.into_iter().collect::<Vec<_>>();
    identity_bases.push("Protocol".into());
    out.push_str(&format!(
        "\nclass {identity_name}({}):\n",
        identity_bases.join(", ")
    ));
    out.push_str(&format!(
        "    def {}(self) -> None: ...\n",
        class_marker(class)
    ));
    let mut interface_markers = class
        .default_interface
        .iter()
        .chain(class.required_interfaces.iter())
        .map(interface_marker)
        .collect::<Vec<_>>();
    interface_markers.sort();
    interface_markers.dedup();
    for marker in interface_markers {
        out.push_str(&format!("    def {marker}(self) -> None: ...\n"));
    }

    out.push_str(&format!(
        "\nclass {}Like({identity_name}, Protocol):\n",
        class.name
    ));
    if instance_stub_body.is_empty() {
        out.push_str("    pass\n");
    } else {
        out.push_str(&instance_stub_body);
    }

    let bases = collection_base
        .as_ref()
        .map(|base| vec![identity_name, base.clone()])
        .unwrap_or_else(|| vec![format!("{}Like", class.name)]);
    let mut bases = bases;
    if projectable {
        bases.push("_DynWinRTRuntimeClass".into());
    } else if native_projectable {
        bases.push("_DynWinRTProjectableClass".into());
    }
    out.push_str(&format!("\nclass {}({}):\n", class.name, bases.join(", ")));
    out.push_str(&super::docs::format_pydoc(
        &crate::codegen::winrt::shared::docs::DocText {
            summary: class.doc.as_deref(),
            deprecated: class.deprecated.as_deref(),
            ..Default::default()
        },
        "    ",
    ));
    out.push_str(&emit_constructor_stubs(class, context));
    if crate::codegen::winrt::is_buffer_class(&class.namespace, &class.name) {
        out.push_str(
            "    @staticmethod\n\
             \x20   def from_bytes(data: bytes | bytearray) -> 'Buffer': ...\n",
        );
    }
    if collection_base.is_some() {
        out.push_str(&emit_class_instance_stubs(
            class,
            context,
            collection_iface,
            collection_kind == Some(CollectionKind::MutableSequence),
            has_closable,
        ));
    }

    // Default constructor
    if class.has_default_activation() {
        let has_create_factory = class.factory_interfaces.iter().any(|iface| {
            iface.methods.iter().any(|m| {
                let snake = to_snake_case(&m.name);
                snake == "create" || snake.starts_with("create")
            })
        });
        let ctor_name = if has_create_factory {
            "create_default"
        } else {
            "create"
        };
        out.push('\n');
        out.push_str("    @staticmethod\n");
        out.push_str(&format!(
            "    def {}() -> '{}': ...\n",
            ctor_name, class.name
        ));
    }

    let static_methods = class
        .factory_interfaces
        .iter()
        .flat_map(|iface| iface.methods.iter().map(|method| (method, true)))
        .chain(
            class
                .static_interfaces
                .iter()
                .flat_map(|iface| iface.methods.iter().map(|method| (method, false))),
        )
        .collect::<Vec<_>>();
    for group in grouped_static_stubs(&static_methods) {
        out.push('\n');
        out.push_str(&emit_static_stub_group(&class.name, &group, context));
    }
    out.push_str(&emit_static_compatibility_alias_stubs(
        &class.name,
        static_methods.iter().copied(),
        context,
        4,
    ));

    let has_explicit_create_factory = class.factory_interfaces.iter().any(|iface| {
        iface
            .methods
            .iter()
            .any(|method| to_snake_case(&method.name) == "create")
    });
    let has_create_instance_alias = !class.has_default_activation()
        && !has_explicit_create_factory
        && class.factory_interfaces.iter().any(|iface| {
            class.is_public_constructor_factory(iface)
                && iface.methods.iter().any(|method| {
                    method.name == "CreateInstance"
                        && matches!(
                            method.return_type.as_ref(),
                            Some(TypeMeta::RuntimeClass { namespace, name, .. })
                                if namespace == &class.namespace && name == &class.name
                        )
                        && crate::codegen::winrt::shared::imports::get_in_params(method).is_empty()
                })
        });
    if has_create_instance_alias {
        out.push('\n');
        out.push_str("    @staticmethod\n");
        out.push_str(&format!("    def create() -> '{}': ...\n", class.name));
    }

    if let Some(bootstrap) = winui_bootstrap {
        let metadata_provider = bootstrap.spec.metadata_provider.name;
        out.push('\n');
        out.push_str("    @staticmethod\n");
        out.push_str(&format!(
            "    def create_with_metadata_provider(metadata_provider: '{metadata_provider}', on_launched: Callable[[], object] | None = ...) -> '{}': ...\n",
            class.name,
        ));
        out.push_str("    @staticmethod\n");
        out.push_str(&format!(
            "    def create(on_launched: Callable[[], object] | None = ...) -> '{}': ...\n",
            class.name
        ));
    }

    // Inline wrapper classes for required interfaces
    for req_iface in &class.required_interfaces {
        if req_iface.iid.is_empty() {
            continue;
        }
        let symbol = interface_symbol(context, req_iface);
        if imported_names.contains(&symbol) {
            continue;
        }
        out.push('\n');
        let required_base = interface_kind(req_iface)
            .and_then(abc_name)
            .and_then(|abc| match req_iface.generic_args.as_slice() {
                [element] => Some(format!(
                    "{}[{}]",
                    abc,
                    super::type_helpers::py_return_type_safe(Some(element), context)
                )),
                [key, value] => Some(format!(
                    "{}[{}, {}]",
                    abc,
                    super::type_helpers::py_return_type_safe(Some(key), context),
                    super::type_helpers::py_return_type_safe(Some(value), context)
                )),
                _ => None,
            });
        if let Some(base) = required_base {
            out.push_str(&format!("\nclass {symbol}({base}):\n"));
        } else {
            out.push_str(&format!("\nclass {symbol}:\n"));
        }
        out.push_str("    def __init__(self, obj: DynWinRTValue) -> None: ...\n");
        out.push_str(&collection_protocol_stubs(req_iface, context, 4));
        out.push('\n');
        out.push_str("    @classmethod\n");
        out.push_str("    def from_value(cls, obj: DynWinRTValue) -> Self: ...\n");
        out.push_str(
            "    def as_interface(self, interface_class: _DynWinRTProjector[_InterfaceT]) -> _InterfaceT: ...\n",
        );
        for methods in
            super::overloads::grouped_methods(reorder_getters_before_setters(&req_iface.methods))
        {
            let event_has_remove = methods.first().is_some_and(|method| {
                method.name.strip_prefix("add_").is_some_and(|suffix| {
                    req_iface
                        .methods
                        .iter()
                        .any(|candidate| candidate.name == format!("remove_{suffix}"))
                })
            });
            let property_has_getter = methods.first().is_none_or(|method| {
                !method.is_property_setter
                    || method.name.strip_prefix("put_").is_some_and(|suffix| {
                        req_iface
                            .methods
                            .iter()
                            .any(|candidate| candidate.name == format!("get_{suffix}"))
                    })
            });
            out.push('\n');
            out.push_str(&emit_instance_stub_group(
                &methods,
                context,
                4,
                event_has_remove,
                property_has_getter,
                interface_kind(req_iface) == Some(CollectionKind::MutableSequence),
            ));
        }
        out.push_str(&emit_instance_compatibility_alias_stubs(
            req_iface.methods.iter(),
            context,
            4,
            interface_kind(req_iface) == Some(CollectionKind::MutableSequence),
        ));
    }

    let _ = py_dynwinrt_type; // keep import referenced
    out
}

fn emit_class_instance_stubs(
    class: &ClassMeta,
    context: &PythonProjectionContext,
    collection_iface: Option<&InterfaceMeta>,
    mutable_sequence_override: bool,
    has_closable: bool,
) -> String {
    let mut out = String::new();
    if let Some(collection_iface) = collection_iface {
        out.push_str(&collection_protocol_stubs(collection_iface, context, 4));
    }

    let instance_ifaces = class
        .default_interface
        .iter()
        .chain(class.required_interfaces.iter())
        .filter(|iface| iface.iid != "30d5a829-7fa4-4026-83bb-d75bae4ea99e")
        .collect::<Vec<_>>();
    let paired_events = instance_ifaces
        .iter()
        .flat_map(|iface| {
            iface.methods.iter().filter_map(|method| {
                let suffix = method.name.strip_prefix("add_")?;
                iface
                    .methods
                    .iter()
                    .any(|candidate| candidate.name == format!("remove_{suffix}"))
                    .then_some(suffix.to_string())
            })
        })
        .collect::<HashSet<_>>();
    let property_getters = instance_ifaces
        .iter()
        .flat_map(|iface| iface.methods.iter())
        .filter(|method| method.is_property_getter)
        .filter_map(|method| method.name.strip_prefix("get_"))
        .map(str::to_string)
        .collect::<HashSet<_>>();
    let original_instance_methods = instance_ifaces
        .iter()
        .flat_map(|iface| reorder_getters_before_setters(&iface.methods))
        .collect::<Vec<_>>();
    let mut emitted = HashSet::<*const MethodMeta>::new();
    let mut instance_methods = Vec::with_capacity(original_instance_methods.len());
    for method in &original_instance_methods {
        if emitted.contains(&(*method as *const MethodMeta)) {
            continue;
        }
        if method.is_property_setter
            && method
                .name
                .strip_prefix("put_")
                .is_some_and(|suffix| property_getters.contains(suffix))
        {
            continue;
        }

        instance_methods.push(*method);
        emitted.insert(*method as *const MethodMeta);
        if let Some(suffix) = method
            .is_property_getter
            .then(|| method.name.strip_prefix("get_"))
            .flatten()
        {
            for setter in original_instance_methods
                .iter()
                .copied()
                .filter(|candidate| {
                    candidate.is_property_setter
                        && candidate.name.strip_prefix("put_") == Some(suffix)
                })
            {
                if emitted.insert(setter as *const MethodMeta) {
                    instance_methods.push(setter);
                }
            }
        }
    }
    for methods in super::overloads::grouped_methods(instance_methods) {
        let event_has_remove = methods.first().is_some_and(|method| {
            method
                .name
                .strip_prefix("add_")
                .is_some_and(|suffix| paired_events.contains(suffix))
        });
        let property_has_getter = methods.first().is_none_or(|method| {
            !method.is_property_setter
                || method
                    .name
                    .strip_prefix("put_")
                    .is_some_and(|suffix| property_getters.contains(suffix))
        });
        out.push('\n');
        out.push_str(&emit_instance_stub_group(
            &methods,
            context,
            4,
            event_has_remove,
            property_has_getter,
            mutable_sequence_override,
        ));
    }
    out.push_str(&emit_instance_compatibility_alias_stubs(
        original_instance_methods.iter().copied(),
        context,
        4,
        mutable_sequence_override,
    ));
    if has_closable {
        out.push('\n');
        out.push_str("    def close(self) -> None: ...\n");
        out.push_str(&format!(
            "    def __enter__(self) -> '{}': ...\n",
            class.name
        ));
        out.push_str(
            "    def __exit__(self, exc_type: object, exc_value: object, traceback: object) -> Literal[False]: ...\n",
        );
    }

    if super::has_projectable_default_interface(class) || !class.required_interfaces.is_empty() {
        out.push('\n');
        out.push_str(
            "    def as_interface(self, interface_class: _DynWinRTProjector[_InterfaceT]) -> _InterfaceT: ...\n",
        );
    }

    if winui::is_dispatcher_queue(class) {
        out.push_str(
            "\n    async def enqueue_async(\n\
             \x20       self,\n\
             \x20       callback: Callable[..., _DispatchResultT],\n\
             \x20       *args: object,\n\
             \x20       **kwargs: object,\n\
             \x20   ) -> _DispatchResultT: ...\n",
        );
        out.push_str(
            "\n    async def enqueue_with_priority_async(\n\
             \x20       self,\n\
             \x20       priority: 'DispatcherQueuePriority',\n\
             \x20       callback: Callable[..., _DispatchResultT],\n\
             \x20       *args: object,\n\
             \x20       **kwargs: object,\n\
             \x20   ) -> _DispatchResultT: ...\n",
        );
    }

    out
}

fn collection_protocol_stubs(
    iface: &InterfaceMeta,
    context: &PythonProjectionContext,
    indent_spaces: usize,
) -> String {
    let Some(kind) = interface_kind(iface) else {
        return String::new();
    };
    let indent = " ".repeat(indent_spaces);
    let item_type = iface
        .generic_args
        .first()
        .map(|typ| super::type_helpers::py_return_type_safe(Some(typ), context))
        .unwrap_or_else(|| "object".to_string());
    match kind {
        super::collections::CollectionKind::Iterable => {
            format!("\n{indent}def __iter__(self) -> Iterator[{item_type}]: ...\n")
        }

        super::collections::CollectionKind::Iterator => format!(
            "\n{indent}def __iter__(self) -> Iterator[{item_type}]: ...\n\
             {indent}def __next__(self) -> {item_type}: ...\n"
        ),
        super::collections::CollectionKind::Sequence
        | super::collections::CollectionKind::MutableSequence => {
            let mut result = format!(
                "\n{indent}def __len__(self) -> int: ...\n\
                 {indent}@overload\n\
                 {indent}def __getitem__(self, index: int) -> {item_type}: ...\n\
                 {indent}@overload\n\
                 {indent}def __getitem__(self, index: slice) -> list[{item_type}]: ...\n"
            );
            if kind == super::collections::CollectionKind::MutableSequence {
                result.push_str(&format!(
                    "{indent}def __setitem__(self, index: int | slice, value: {item_type} | Iterable[{item_type}]) -> None: ...\n\
                     {indent}def __delitem__(self, index: int | slice) -> None: ...\n\
                     {indent}def insert(self, index: int, value: {item_type}) -> None: ...\n"
                ));
            }
            result
        }
        super::collections::CollectionKind::Mapping
        | super::collections::CollectionKind::MutableMapping => {
            let key_type = item_type;
            let value_type = iface
                .generic_args
                .get(1)
                .map(|typ| super::type_helpers::py_return_type_safe(Some(typ), context))
                .unwrap_or_else(|| "object".to_string());
            let mut result = format!(
                "\n{indent}def __len__(self) -> int: ...\n\
                 {indent}def __iter__(self) -> Iterator[{key_type}]: ...\n\
                 {indent}def __getitem__(self, key: {key_type}) -> {value_type}: ...\n"
            );
            if kind == super::collections::CollectionKind::MutableMapping {
                result.push_str(&format!(
                    "{indent}def __setitem__(self, key: {key_type}, value: {value_type}) -> None: ...\n\
                     {indent}def __delitem__(self, key: {key_type}) -> None: ...\n"
                ));
            }
            result
        }
        super::collections::CollectionKind::KeyValuePair => String::new(),
    }
}

fn emit_constructor_stubs(class: &ClassMeta, context: &PythonProjectionContext) -> String {
    // Collect (public_params_only, ...) for each accessible constructor.
    // Composable factories: strip trailing outer + skip ProtectedComposition.
    let mut overloads: Vec<Vec<&crate::meta::ParamMeta>> = Vec::new();
    let has_public_composition = class
        .constructors
        .iter()
        .any(|constructor| constructor.kind == crate::meta::ConstructorKind::PublicComposition);

    // Deduplicate by param-type signature.
    fn push_unique<'a>(
        overloads: &mut Vec<Vec<&'a crate::meta::ParamMeta>>,
        params: Vec<&'a crate::meta::ParamMeta>,
    ) {
        if overloads.iter().any(|existing| {
            existing.len() == params.len()
                && existing
                    .iter()
                    .zip(&params)
                    .all(|(left, right)| left.name == right.name && left.typ == right.typ)
        }) {
            return;
        }
        overloads.push(params);
    }

    for constructor in &class.constructors {
        match constructor.kind {
            crate::meta::ConstructorKind::DefaultActivation => {
                push_unique(&mut overloads, Vec::new());
            }
            crate::meta::ConstructorKind::FactoryActivation => {
                let Some(factory_ref) = constructor.factory_interface.as_ref() else {
                    continue;
                };
                let Some(factory) = class.factory_interfaces.iter().find(|iface| {
                    iface.namespace == factory_ref.namespace && iface.name == factory_ref.name
                }) else {
                    continue;
                };
                for method in &factory.methods {
                    if !matches!(
                        method.return_type.as_ref(),
                        Some(TypeMeta::RuntimeClass { namespace, name, .. })
                            if namespace == &class.namespace && name == &class.name
                    ) {
                        continue;
                    }
                    let in_params = crate::codegen::winrt::shared::imports::get_in_params(method);
                    push_unique(&mut overloads, in_params);
                }
            }
            crate::meta::ConstructorKind::PublicComposition => {
                let Some(factory_ref) = constructor.factory_interface.as_ref() else {
                    continue;
                };
                let Some(factory) = class.factory_interfaces.iter().find(|iface| {
                    iface.namespace == factory_ref.namespace && iface.name == factory_ref.name
                }) else {
                    continue;
                };
                for method in &factory.methods {
                    if !constructor_method_returns_class(method, class) {
                        continue;
                    }
                    let in_params = crate::codegen::winrt::shared::imports::get_in_params(method);
                    if composable_has_public_shape(method, &in_params) {
                        push_unique(&mut overloads, in_params[..in_params.len() - 1].to_vec());
                    }
                }
            }
            crate::meta::ConstructorKind::ProtectedComposition => {}
        }
    }

    let mut out = String::new();
    if has_public_composition {
        out.push_str(
            "    # Python subclasses may use public composable constructors. Metadata-supported\n\
             \x20   # native overrides are registered during construction; unsupported ABI shapes fail closed.\n",
        );
        out.push_str("    @classmethod\n");
        out.push_str(
            "    def register_xaml_runtime_class(cls, runtime_class_name: str, control_type: type[Self]) -> DynWinRTXamlRegistration: ...\n",
        );
    }
    if overloads.is_empty() {
        out.push_str("    def __init__(self, _not_constructible: NoReturn) -> None: ...\n");
        return out;
    }
    overloads.sort_by(|left, right| super::overloads::cmp_python_dispatch_params(left, right));

    let count = overloads.len();
    for params in &overloads {
        if count > 1 {
            out.push_str("    @overload\n");
        }
        let param_str = super::type_helpers::py_param_list(params, context);
        if param_str.is_empty() {
            out.push_str("    def __init__(self) -> None: ...\n");
        } else {
            out.push_str(&format!(
                "    def __init__(self, {param_str}) -> None: ...\n"
            ));
        }
    }
    out
}

fn constructor_method_returns_class(method: &MethodMeta, class: &ClassMeta) -> bool {
    matches!(
        method.return_type.as_ref(),
        Some(TypeMeta::RuntimeClass { namespace, name, .. })
            if namespace == &class.namespace && name == &class.name
    )
}

fn composable_has_public_shape(method: &MethodMeta, in_params: &[&crate::meta::ParamMeta]) -> bool {
    let Some(outer) = in_params.last() else {
        return false;
    };
    let outer_name = outer.name.to_ascii_lowercase();
    let is_outer_name = matches!(
        outer_name.as_str(),
        "outer" | "base" | "baseinterface" | "outerinterface"
    );
    let has_inner_output = method.params.iter().any(|param| {
        param.direction == crate::meta::ParamDirection::Out
            && matches!(param.typ, TypeMeta::Object)
            && param.name.to_ascii_lowercase().contains("inner")
    });
    is_outer_name && matches!(outer.typ, TypeMeta::Object) && has_inner_output
}

fn has_constructor_stub_overload(class: &ClassMeta) -> bool {
    class
        .constructors
        .iter()
        .any(|constructor| match constructor.kind {
            crate::meta::ConstructorKind::DefaultActivation => true,
            crate::meta::ConstructorKind::FactoryActivation
            | crate::meta::ConstructorKind::PublicComposition => {
                let Some(factory_ref) = constructor.factory_interface.as_ref() else {
                    return false;
                };
                let Some(factory) = class.factory_interfaces.iter().find(|interface| {
                    interface.namespace == factory_ref.namespace
                        && interface.name == factory_ref.name
                }) else {
                    return false;
                };
                factory.methods.iter().any(|method| {
                    if !constructor_method_returns_class(method, class) {
                        return false;
                    }
                    constructor.kind == crate::meta::ConstructorKind::FactoryActivation
                        || composable_has_public_shape(
                            method,
                            &crate::codegen::winrt::shared::imports::get_in_params(method),
                        )
                })
            }
            crate::meta::ConstructorKind::ProtectedComposition => false,
        })
}

fn emit_instance_stub_group(
    methods: &[&MethodMeta],
    context: &PythonProjectionContext,
    indent_spaces: usize,
    event_has_remove: bool,
    property_has_getter: bool,
    overrides_mutable_sequence: bool,
) -> String {
    let mut ordered_methods = methods.iter().copied().collect::<Vec<_>>();
    ordered_methods
        .sort_by(|left, right| super::overloads::cmp_python_dispatch_methods(left, right));

    if ordered_methods.len() == 1 {
        return emit_method_stub(
            ordered_methods[0],
            context,
            indent_spaces,
            event_has_remove,
            property_has_getter,
            overrides_mutable_sequence,
        );
    }
    let names = super::overloads::method_names(ordered_methods.iter().copied());
    let public_name = super::overloads::method_group_key(ordered_methods[0], &names);
    let indent = " ".repeat(indent_spaces);
    ordered_methods
        .iter()
        .map(|method| {
            format!(
                "{indent}@overload\n{}",
                emit_method_stub_named(
                    method,
                    context,
                    indent_spaces,
                    Some(&public_name),
                    event_has_remove,
                    property_has_getter,
                    overrides_mutable_sequence,
                )
            )
        })
        .collect()
}

fn emit_instance_compatibility_alias_stubs<'a>(
    methods: impl IntoIterator<Item = &'a MethodMeta>,
    context: &PythonProjectionContext,
    indent_spaces: usize,
    overrides_mutable_sequence: bool,
) -> String {
    let methods = methods.into_iter().collect::<Vec<_>>();
    let aliases = super::overloads::compatibility_aliases(methods.iter().copied());
    let indent = " ".repeat(indent_spaces);
    let mut out = String::new();
    for (legacy, _) in aliases {
        let matching = methods
            .iter()
            .copied()
            .filter(|method| to_snake_case(&method.name) == legacy)
            .collect::<Vec<_>>();
        for method in &matching {
            if matching.len() > 1 {
                out.push_str(&format!("{indent}@overload\n"));
            }
            out.push_str(&emit_method_stub_named(
                method,
                context,
                indent_spaces,
                Some(&legacy),
                false,
                true,
                overrides_mutable_sequence,
            ));
        }
    }
    out
}

fn emit_static_compatibility_alias_stubs<'a>(
    class_name: &str,
    methods: impl IntoIterator<Item = (&'a MethodMeta, bool)>,
    context: &PythonProjectionContext,
    indent_spaces: usize,
) -> String {
    let methods = methods.into_iter().collect::<Vec<_>>();
    let aliases =
        super::overloads::compatibility_aliases(methods.iter().map(|(method, _)| *method));
    let indent = " ".repeat(indent_spaces);
    let mut out = String::new();
    for (legacy, _) in aliases {
        let matching = methods
            .iter()
            .filter(|(method, _)| to_snake_case(&method.name) == legacy)
            .collect::<Vec<_>>();
        for (method, is_factory) in &matching {
            if matching.len() > 1 {
                out.push_str(&format!("{indent}@overload\n"));
            }
            out.push_str(&emit_static_method_stub_named(
                class_name,
                method,
                context,
                *is_factory,
                Some(&legacy),
            ));
        }
    }
    out
}

fn grouped_static_stubs<'a>(
    methods: &[(&'a MethodMeta, bool)],
) -> Vec<Vec<(&'a MethodMeta, bool)>> {
    let names = super::overloads::method_names(methods.iter().map(|(method, _)| *method));
    let mut groups: Vec<(String, Vec<(&MethodMeta, bool)>)> = Vec::new();
    for &(method, is_factory) in methods {
        let key = super::overloads::method_group_key(method, &names);
        if let Some((_, group)) = groups.iter_mut().find(|(name, _)| name == &key) {
            group.push((method, is_factory));
        } else {
            groups.push((key, vec![(method, is_factory)]));
        }
    }
    groups.into_iter().map(|(_, group)| group).collect()
}

fn emit_static_stub_group(
    class_name: &str,
    methods: &[(&MethodMeta, bool)],
    context: &PythonProjectionContext,
) -> String {
    let mut ordered_methods = methods.iter().copied().collect::<Vec<_>>();
    ordered_methods.sort_by(|(left, _), (right, _)| {
        super::overloads::cmp_python_dispatch_methods(left, right)
    });

    if ordered_methods.len() == 1 {
        let (method, is_factory) = ordered_methods[0];
        return emit_static_method_stub(class_name, method, context, is_factory);
    }
    let names = super::overloads::method_names(ordered_methods.iter().map(|(method, _)| *method));
    let public_name = super::overloads::method_group_key(ordered_methods[0].0, &names);
    ordered_methods
        .iter()
        .map(|(method, is_factory)| {
            format!(
                "    @overload\n{}",
                emit_static_method_stub_named(
                    class_name,
                    method,
                    context,
                    *is_factory,
                    Some(&public_name),
                )
            )
        })
        .collect()
}

/// Generate an `__init__.pyi` index stub.
pub fn generate_index_stub(
    context: &PythonProjectionContext,
    classes: &[ClassMeta],
    interfaces: &[InterfaceMeta],
    enums: &[TypeMeta],
) -> String {
    let mut out = String::new();
    let mut seen: HashSet<String> = HashSet::new();
    out.push_str(HEADER);

    let mut sorted_classes: Vec<_> = classes.iter().collect();
    sorted_classes.sort_by(|a, b| a.name.cmp(&b.name));
    for class in sorted_classes {
        if seen.insert(class.name.clone()) {
            let identity = crate::types::TypeIdentity::named(
                crate::types::TypeIdentityKind::Class,
                class.namespace.clone(),
                class.name.clone(),
            );
            let module = context.implementation_module(&identity);
            let name = context.projected_name(&identity);
            out.push_str(&format!("from .{} import {} as {}\n", module, name, name));
        }
    }

    let mut sorted_ifaces: Vec<_> = interfaces.iter().collect();
    sorted_ifaces.sort_by(|a, b| a.name.cmp(&b.name));
    for iface in sorted_ifaces {
        if !seen.insert(iface.name.clone()) {
            continue;
        }
        let is_delegate = iface.is_delegate();
        let identity = iface.type_identity();
        let module = context.implementation_module(&identity);
        let name = context.projected_name(&identity);
        if is_delegate {
            out.push_str(&format!(
                "from .{module} import IID_{iname}, {iname}_PARAM_TYPES\n",
                module = module,
                iname = name
            ));
        } else {
            out.push_str(&format!(
                "from .{module} import IID_{iname}, {iname} as {iname}\n",
                module = module,
                iname = name
            ));
        }
    }

    let mut sorted_enums: Vec<_> = enums.iter().collect();
    sorted_enums.sort_by(|a, b| {
        let na = match a {
            TypeMeta::Enum { name, .. } => name.as_str(),
            _ => "",
        };
        let nb = match b {
            TypeMeta::Enum { name, .. } => name.as_str(),
            _ => "",
        };
        na.cmp(nb)
    });
    for en in sorted_enums {
        if let TypeMeta::Enum { name, .. } = en {
            if seen.insert(name.clone()) {
                let identity = en.type_identity();
                let module = context.implementation_module(&identity);
                let name = context.projected_name(&identity);
                out.push_str(&format!("from .{} import {} as {}\n", module, name, name));
            }
        }
    }
    out
}

pub fn generate_public_index_stub(
    context: &PythonProjectionContext,
    classes: &[ClassMeta],
    interfaces: &[InterfaceMeta],
    enums: &[TypeMeta],
) -> String {
    let mut out = String::from(HEADER);
    let mut seen = HashSet::new();

    let mut classes = classes.iter().collect::<Vec<_>>();
    classes.sort_by(|left, right| left.name.cmp(&right.name));
    for class in classes {
        if seen.insert(class.name.clone()) {
            let identity = crate::types::TypeIdentity::named(
                crate::types::TypeIdentityKind::Class,
                class.namespace.clone(),
                class.name.clone(),
            );
            let name = context.projected_name(&identity);
            out.push_str(&format!(
                "from .{} import {} as {}\n",
                context.public_qualified_module(&identity),
                name,
                name
            ));
        }
    }

    let mut interfaces = interfaces.iter().collect::<Vec<_>>();
    interfaces.sort_by(|left, right| left.name.cmp(&right.name));
    for interface in interfaces {
        let is_delegate = interface.is_delegate();
        if !is_delegate && seen.insert(interface.name.clone()) {
            let identity = interface.type_identity();
            let name = context.projected_name(&identity);
            out.push_str(&format!(
                "from .{} import {} as {}\n",
                context.public_qualified_module(&identity),
                name,
                name
            ));
        }
    }

    let mut enums = enums.iter().collect::<Vec<_>>();
    enums.sort_by_key(|typ| match typ {
        TypeMeta::Enum { name, .. } => name.as_str(),
        _ => "",
    });
    for typ in enums {
        let TypeMeta::Enum { name, .. } = typ else {
            continue;
        };
        if seen.insert(name.clone()) {
            let identity = typ.type_identity();
            let name = context.projected_name(&identity);
            out.push_str(&format!(
                "from .{} import {} as {}\n",
                context.public_qualified_module(&identity),
                name,
                name,
            ));
        }
    }
    out
}

pub fn generate_struct_index_stub(
    context: &PythonProjectionContext,
    structs: &[TypeMeta],
) -> String {
    let mut out = String::from(HEADER);
    let mut seen = HashSet::new();
    let mut sorted = structs.iter().collect::<Vec<_>>();
    sorted.sort_by_key(|typ| match typ {
        TypeMeta::Struct {
            namespace, name, ..
        } => format!("{namespace}.{name}"),
        _ => String::new(),
    });
    for typ in sorted {
        let TypeMeta::Struct {
            namespace, name, ..
        } = typ
        else {
            continue;
        };
        if !seen.insert((namespace, name)) {
            continue;
        }
        out.push_str(&format!(
            "from .{} import {}\n",
            context.implementation_module_for_type(typ),
            py_struct_export_names(typ)
                .into_iter()
                .map(|name| format!("{name} as {name}"))
                .collect::<Vec<_>>()
                .join(", ")
        ));
    }
    out
}

pub fn generate_public_struct_index_stub(
    context: &PythonProjectionContext,
    structs: &[TypeMeta],
) -> String {
    let mut out = String::from(HEADER);
    let mut seen = HashSet::new();
    let mut sorted = structs.iter().collect::<Vec<_>>();
    sorted.sort_by_key(|typ| match typ {
        TypeMeta::Struct {
            namespace, name, ..
        } => format!("{namespace}.{name}"),
        _ => String::new(),
    });
    for typ in sorted {
        let TypeMeta::Struct {
            namespace, name, ..
        } = typ
        else {
            continue;
        };
        if foundation_type(typ).is_some() || !seen.insert((namespace, name)) {
            continue;
        }
        out.push_str(&format!(
            "from .{} import {} as {}\n",
            context.public_qualified_module(&typ.type_identity()),
            name,
            name
        ));
    }
    out
}
