// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import test from 'ava'
import { spawnSync } from 'node:child_process'
import { lstatSync, readFileSync, readlinkSync, rmSync, mkdirSync, symlinkSync, writeFileSync } from 'node:fs'
import { basename, dirname, join, resolve } from 'node:path'

test.serial('actual generated IWbemServices and IAudioClient companions use hardened strategies', (t) => {
  const winmd = process.env.DYNWINRT_WIN32_WINMD
  t.truthy(winmd, 'DYNWINRT_WIN32_WINMD is required')
  const packageRoot = resolve(process.cwd())
  const repositoryRoot = resolve(packageRoot, '..', '..')
  const output = join(packageRoot, 'target-generated-unsafe-companion')
  const externalLinkTarget = join(packageRoot, 'target-generated-unsafe-link-target')
  const lock = join(dirname(output), `.${basename(output)}.dynwinrt-generation.lock`)
  const transactionResidues = ['stage', 'backup', 'failed-output'].map((kind) =>
    join(dirname(output), `.${basename(output)}.dynwinrt-${kind}`),
  )
  rmSync(output, { recursive: true, force: true })
  rmSync(externalLinkTarget, { recursive: true, force: true })
  rmSync(lock, { force: true })
  for (const residue of transactionResidues) rmSync(residue, { recursive: true, force: true })

  try {
    const generationArgs = [
        'run',
        '--quiet',
        '-p',
        'dynwinrt-codegen',
        '--',
        'generate',
        '--winmd',
        winmd!,
        '--class-name',
        'Windows.Win32.System.Wmi.IWbemServices,Windows.Win32.Media.Audio.IAudioClient',
        '--output',
        output,
      ]
    const runGeneration = (extraEnv: NodeJS.ProcessEnv = {}) =>
      spawnSync('cargo', generationArgs, {
        cwd: repositoryRoot,
        encoding: 'utf8',
        env: { ...process.env, DYNWINRT_CODEGEN_TEST_STRATEGY_RUNTIME: '1', ...extraEnv },
        windowsHide: true,
      })
    const generation = runGeneration()
    t.is(generation.status, 0, generation.stderr)

    const packageScope = join(output, 'node_modules', '@microsoft')
    mkdirSync(packageScope, { recursive: true })
    const packageJunction = join(packageScope, 'dynwinrt')
    symlinkSync(packageRoot, packageJunction, 'junction')
    mkdirSync(externalLinkTarget, { recursive: true })
    const sentinel = join(externalLinkTarget, 'sentinel.txt')
    writeFileSync(sentinel, 'outside-target-must-survive')
    const externalJunction = join(output, 'external-junction')
    symlinkSync(externalLinkTarget, externalJunction, 'junction')
    const packageJunctionTarget = resolve(dirname(packageJunction), readlinkSync(packageJunction))
    const externalJunctionTarget = resolve(dirname(externalJunction), readlinkSync(externalJunction))

    const incremental = runGeneration()
    t.is(incremental.status, 0, incremental.stderr)
    t.true(lstatSync(packageJunction).isSymbolicLink())
    t.true(lstatSync(externalJunction).isSymbolicLink())
    t.is(resolve(dirname(packageJunction), readlinkSync(packageJunction)), packageJunctionTarget)
    t.is(resolve(dirname(externalJunction), readlinkSync(externalJunction)), externalJunctionTarget)
    t.is(readFileSync(sentinel, 'utf8'), 'outside-target-must-survive')

    const rolledBack = runGeneration({ DYNWINRT_CODEGEN_TEST_FAIL_OUTPUT_COMMIT: 'after_link_move' })
    t.not(rolledBack.status, 0)
    t.regex(rolledBack.stderr, /after_link_move/)
    t.true(lstatSync(packageJunction).isSymbolicLink())
    t.true(lstatSync(externalJunction).isSymbolicLink())
    t.is(readFileSync(sentinel, 'utf8'), 'outside-target-must-survive')

    const publishedFailure = runGeneration({ DYNWINRT_CODEGEN_TEST_FAIL_OUTPUT_COMMIT: 'after_publish' })
    t.not(publishedFailure.status, 0)
    t.regex(publishedFailure.stderr, /after_publish/)
    t.true(lstatSync(packageJunction).isSymbolicLink())
    t.true(lstatSync(externalJunction).isSymbolicLink())
    t.is(readFileSync(sentinel, 'utf8'), 'outside-target-must-survive')

    const cleanupRun = runGeneration()
    t.is(cleanupRun.status, 0, cleanupRun.stderr)
    t.true(lstatSync(packageJunction).isSymbolicLink())
    t.true(lstatSync(externalJunction).isSymbolicLink())
    t.is(readFileSync(sentinel, 'utf8'), 'outside-target-must-survive')

    const deepBase = join(output, 'com', 'unsafe', 'windows', 'win32', 'system', 'wmi', 'IWbemServicesUnsafe')
    const audioBase = join(output, 'com', 'unsafe', 'windows', 'win32', 'media', 'audio', 'IAudioClientUnsafe')
    const runner = join(output, 'generated-companion-runner.cjs')
    writeFileSync(
      runner,
      [
        "'use strict'",
        "const assert = require('node:assert/strict')",
        "const { pathToFileURL } = require('node:url')",
        `const runtime = require(${JSON.stringify(join(packageRoot, 'dist', 'index.js'))})`,
        "const { DynComRaw, DynComRawMemory, DynComRawOwnedComPointer, DynComRawPointer, WinGuid } = require('@microsoft/dynwinrt/com/unsafe/raw')",
        `const strategyRuntime = require(${JSON.stringify(join(output, 'com', 'unsafe', 'runtime.js'))})`,
        'const { UnsafePointee, UnsafePointerOutput, UnsafeHandleOutput, UnsafeInterfaceReplacement, UnsafeCountedBuffer, UnsafeRawCall, __prepareStrategy, __prepareWritableStorage, __prepareExactWritableSpan, __strategyArgument, __assertRawContract, __validateStrategySpans, __activateStrategies, __markDispatchEntered, __finishStrategy, __failStrategy, __releaseExtracted, __attachUnsafeOutputs, __testRunOwnedFinalizer, __testCreateOwnedPointer } = strategyRuntime',
        `const cjs = require(${JSON.stringify(`${deepBase}.js`)})`,
        `const audio = require(${JSON.stringify(`${audioBase}.js`)})`,
        `const cjsBarrel = require(${JSON.stringify(join(output, 'com', 'unsafe', 'index.js'))})`,
        'function finishTransaction(records) {',
        '  const extracted = []',
        '  try {',
        '    for (const record of records) { const value = __finishStrategy(record); extracted.push(value) }',
        '    return extracted',
        '  } catch (error) {',
        '    const unsafeOutputs = []',
        '    for (let index = records.length - 1; index >= 0; index--) { const output = __failStrategy(records[index]); if (output) unsafeOutputs.push(output) }',
        '    for (let index = extracted.length - 1; index >= 0; index--) { const output = __releaseExtracted(extracted[index]); if (output) unsafeOutputs.push(output) }',
        '    throw __attachUnsafeOutputs(error, unsafeOutputs)',
        '  }',
        '}',
        'async function main() {',
        `  const esmDeep = await import(pathToFileURL(${JSON.stringify(`${deepBase}.js`)}).href)`,
        `  const esmAudio = await import(pathToFileURL(${JSON.stringify(`${audioBase}.js`)}).href)`,
        `  const esmBarrel = await import(pathToFileURL(${JSON.stringify(join(output, 'com', 'unsafe', 'index.mjs'))}).href)`,
        "  assert.equal(typeof cjs.IWbemServicesUnsafe, 'function')",
        "  assert.equal(typeof audio.IAudioClientUnsafe, 'function')",
        '  assert.equal(cjs.IWbemServicesUnsafe.support.schemaVersion, 11)',
        "  const openNamespaceSupport = cjs.IWbemServicesUnsafe.support.methods.find(method => method.name === 'OpenNamespace')",
        "  assert.equal(openNamespaceSupport.status, 'raw_metadata_complete')",
        "  assert.deepEqual(openNamespaceSupport.reasons, [])",
        "  assert.deepEqual(openNamespaceSupport.strategyRequirements, [])",
        "  assert.deepEqual(openNamespaceSupport.exactInterfaceOutputs.map(output => [output.parameterName, output.interfaceIid, output.argumentOptional, output.nullableOnSuccess]), [",
        "    ['ppWorkingNamespace', '9556dc99-828c-11cf-a37e-00aa003240c7', true, false],",
        "    ['ppResult', '44aca675-e8fc-11d0-a07c-00c04fb68820', true, false],",
        '  ])',
        "  assert.equal(openNamespaceSupport.exactInterfaceOutputs[0].entryId, 'wmi.conditional-output.entry.windows-win32-system-wmi.iwbemservices.9556dc99828c11cfa37e00aa003240c7.opennamespace.slot-3.v1')",
        "  assert.equal(openNamespaceSupport.exactInterfaceOutputs[0].familyId, 'wmi.conditional-output.v1')",
        "  assert.equal(openNamespaceSupport.exactInterfaceOutputs[0].contractKind, 'conditional-output')",
        "  assert.equal(openNamespaceSupport.exactInterfaceOutputCall.entryId, 'wmi.conditional-output.entry.windows-win32-system-wmi.iwbemservices.9556dc99828c11cfa37e00aa003240c7.opennamespace.slot-3.v1')",
        "  assert.equal(openNamespaceSupport.exactInterfaceOutputCall.familyId, 'wmi.conditional-output.v1')",
        "  assert.equal(openNamespaceSupport.exactInterfaceOutputCall.contractKind, 'conditional-output')",
        "  assert.equal(openNamespaceSupport.exactInterfaceOutputCall.sourceFingerprint, 'EA3628EB9E45E1A0BAA0BC9F6DA1FD82FE938091EF1730E25E3CCEEA9EFD316B')",
        '  assert.equal(openNamespaceSupport.exactInterfaceOutputCall.synchronousFlags, 0)',
        '  assert.equal(openNamespaceSupport.exactInterfaceOutputCall.semisynchronousFlagValue, 0x10)',
        '  assert.equal(esmAudio.IAudioClientUnsafe, audio.IAudioClientUnsafe)',
        '  assert.equal(cjsBarrel.IWbemServicesUnsafe, cjs.IWbemServicesUnsafe)',
        '  assert.equal(cjsBarrel.UnsafePointerOutput, UnsafePointerOutput)',
        '  assert.equal(esmDeep.IWbemServicesUnsafe, cjs.IWbemServicesUnsafe)',
        '  assert.equal(esmBarrel.IWbemServicesUnsafe, cjs.IWbemServicesUnsafe)',
        '  assert.equal(esmBarrel.UnsafePointerOutput, UnsafePointerOutput)',
        '  const createFake = runtime.createGeneratedIwbemServicesFake',
        '  const readStats = runtime.generatedUnsafeComStats',
        '  const setOpenNamespaceMode = runtime.setGeneratedIwbemServicesOpenNamespaceMode',
        "  assert.equal(typeof createFake, 'function')",
        "  assert.equal(typeof readStats, 'function')",
        '  runtime.initializeCom(1)',
        '  let fake = createFake()',
        '  let wrapper',
        '  let slot',
        '  try {',
        '    assert.deepEqual(readStats(), { queryInterfaceCalls: 0, addRefCalls: 1, releaseCalls: 1, openNamespaceCalls: 0, openNamespaceWorkingSlotNull: false, openNamespaceWorkingArgumentNull: false, openNamespaceResultSlotNull: false, openNamespaceResultArgumentNull: false, openNamespaceContextArgumentNull: false, openNamespaceLastFlags: 0, queryObjectSinkCalls: 0, lastFlags: 0, currentRefCount: 1, lastOutputAddress: 0 })',
        '    wrapper = cjs.IWbemServicesUnsafe.from(fake)',
        '    assert.deepEqual(readStats(), { queryInterfaceCalls: 1, addRefCalls: 3, releaseCalls: 2, openNamespaceCalls: 0, openNamespaceWorkingSlotNull: false, openNamespaceWorkingArgumentNull: false, openNamespaceResultSlotNull: false, openNamespaceResultArgumentNull: false, openNamespaceContextArgumentNull: false, openNamespaceLastFlags: 0, queryObjectSinkCalls: 0, lastFlags: 0, currentRefCount: 2, lastOutputAddress: 0 })',
        '    const pointerSize = DynComRaw.pointerSize()',
        '    slot = DynComRawMemory.allocate(pointerSize, pointerSize)',
        '    wrapper.queryObjectSink(73, slot)',
        '    assert.equal(slot.readPointer(0).address, 0x1234n)',
        '    const invalidWorkingSlot = DynComRawMemory.allocate(pointerSize, pointerSize)',
        '    invalidWorkingSlot.writePointer(0, DynComRawPointer.fromAddress(0x1234n))',
        "    assert.throws(() => wrapper.openNamespace('root', { lFlags: 0, workingNamespace: invalidWorkingSlot, result: null }), /start null/)",
        '    assert.equal(readStats().openNamespaceCalls, 0)',
        '    invalidWorkingSlot.writePointer(0, DynComRawPointer.null())',
        '    invalidWorkingSlot.release()',
        "    assert.throws(() => wrapper.openNamespace('root', { lFlags: 0, workingNamespace: null, result: null }), /Exactly one/)",
        "    assert.throws(() => wrapper.openNamespace('root', { lFlags: 0, workingNamespace: slot, result: slot }), /Exactly one/)",
        "    assert.throws(() => wrapper.openNamespace('root', { lFlags: 0x10, workingNamespace: slot, result: null }), /synchronous lFlags/)",
        "    assert.throws(() => wrapper.openNamespace('root', { lFlags: 0, workingNamespace: null, result: slot }), /RETURN_IMMEDIATELY/)",
        "    assert.throws(() => wrapper.openNamespace('root', { lFlags: 0, workingNamespace: slot, result: null, pCtx: fake }), /pCtx is reserved/)",
        '    assert.equal(readStats().openNamespaceCalls, 0)',
        '    const invalidFlagsSlot = DynComRawMemory.allocate(pointerSize, pointerSize)',
        "    for (const invalidFlags of [0x11, 0x80000010, -16, 1, 15, 17, 1.5, '16', 16n, null, undefined, NaN, Infinity]) {",
        "      assert.throws(() => wrapper.openNamespace('root', { lFlags: invalidFlags, workingNamespace: null, result: invalidFlagsSlot }), /signed 32-bit|exact WBEM_FLAG_RETURN_IMMEDIATELY/)",
        '      assert.equal(invalidFlagsSlot.readPointer(0).isNull, true)',
        '      assert.equal(readStats().openNamespaceCalls, 0)',
        '    }',
        '    invalidFlagsSlot.release()',
        '    const undersizedWbemSlot = DynComRawMemory.allocate(Math.max(1, pointerSize - 1), 1)',
        "    assert.throws(() => wrapper.openNamespace('root', { lFlags: 0, workingNamespace: undersizedWbemSlot, result: null }), /smaller/)",
        '    undersizedWbemSlot.release()',
        '    const alignedWbemBase = DynComRawMemory.allocate(pointerSize * 2, pointerSize)',
        '    const misalignedWbemSlot = DynComRawMemory.fromUnsafePointer(alignedWbemBase.pointer(1), pointerSize, 1)',
        "    assert.throws(() => wrapper.openNamespace('root', { lFlags: 0, workingNamespace: misalignedWbemSlot, result: null }), /pointer-aligned/)",
        '    misalignedWbemSlot.release()',
        '    const overlappingWbemResult = DynComRawMemory.fromUnsafePointer(alignedWbemBase.pointer(Math.floor(pointerSize / 2)), pointerSize, 1)',
        "    assert.throws(() => wrapper.openNamespace('root', { lFlags: 0, workingNamespace: alignedWbemBase, result: overlappingWbemResult }), /Exactly one/)",
        '    assert.equal(alignedWbemBase.readPointer(0).isNull, true)',
        '    overlappingWbemResult.release()',
        '    alignedWbemBase.release()',
        '    const workingSlot = DynComRawMemory.allocate(pointerSize, pointerSize)',
        '    setOpenNamespaceMode(0)',
        '    const syncBefore = readStats()',
        "    const workingNamespace = wrapper.openNamespace('root', { lFlags: 0, workingNamespace: workingSlot, result: null })",
        '    assert.ok(workingNamespace)',
        '    assert.equal(workingSlot.readPointer(0).isNull, true)',
        '    assert.equal(readStats().openNamespaceWorkingSlotNull, true)',
        '    assert.equal(readStats().openNamespaceWorkingArgumentNull, false)',
        '    assert.equal(readStats().openNamespaceResultArgumentNull, true)',
        '    assert.equal(readStats().openNamespaceContextArgumentNull, true)',
        '    assert.equal(readStats().openNamespaceLastFlags, 0)',
        '    assert.equal(readStats().currentRefCount, syncBefore.currentRefCount + 1)',
        '    workingNamespace.release()',
        '    assert.equal(readStats().addRefCalls, syncBefore.addRefCalls + 3)',
        '    assert.equal(readStats().releaseCalls, syncBefore.releaseCalls + 3)',
        '    assert.equal(readStats().currentRefCount, syncBefore.currentRefCount)',
        '    workingSlot.release()',
        '    const resultSlot = DynComRawMemory.allocate(pointerSize, pointerSize)',
        '    setOpenNamespaceMode(1)',
        '    const asyncBefore = readStats()',
        "    const callResult = wrapper.openNamespace('root', { lFlags: 0x10, workingNamespace: null, result: resultSlot })",
        '    assert.ok(callResult)',
        '    assert.equal(resultSlot.readPointer(0).isNull, true)',
        '    assert.equal(readStats().openNamespaceWorkingSlotNull, true)',
        '    assert.equal(readStats().openNamespaceWorkingArgumentNull, true)',
        '    assert.equal(readStats().openNamespaceResultSlotNull, true)',
        '    assert.equal(readStats().openNamespaceResultArgumentNull, false)',
        '    assert.equal(readStats().openNamespaceContextArgumentNull, true)',
        '    assert.equal(readStats().openNamespaceLastFlags, 0x10)',
        '    assert.equal(readStats().currentRefCount, asyncBefore.currentRefCount + 1)',
        '    callResult.release()',
        '    assert.equal(readStats().addRefCalls, asyncBefore.addRefCalls + 3)',
        '    assert.equal(readStats().releaseCalls, asyncBefore.releaseCalls + 3)',
        '    assert.equal(readStats().currentRefCount, asyncBefore.currentRefCount)',
        '    resultSlot.release()',
        '    const failureWorkingSlot = DynComRawMemory.allocate(pointerSize, pointerSize)',
        '    setOpenNamespaceMode(-1)',
        '    const failureBefore = readStats()',
        "    assert.throws(() => wrapper.openNamespace('root', { lFlags: 0, workingNamespace: failureWorkingSlot, result: null }), /native call failed|HRESULT|0x80004005/i)",
        '    assert.equal(failureWorkingSlot.readPointer(0).isNull, true)',
        '    assert.equal(readStats().currentRefCount, failureBefore.currentRefCount)',
        '    assert.equal(readStats().addRefCalls, failureBefore.addRefCalls + 2)',
        '    assert.equal(readStats().releaseCalls, failureBefore.releaseCalls + 2)',
        '    failureWorkingSlot.release()',
        '    const failureResultSlot = DynComRawMemory.allocate(pointerSize, pointerSize)',
        '    const resultFailureBefore = readStats()',
        "    assert.throws(() => wrapper.openNamespace('root', { lFlags: 0x10, workingNamespace: null, result: failureResultSlot }), /native call failed|HRESULT|0x80004005/i)",
        '    assert.equal(failureResultSlot.readPointer(0).isNull, true)',
        '    failureResultSlot.release()',
        '    assert.equal(readStats().currentRefCount, resultFailureBefore.currentRefCount)',
        '    assert.equal(readStats().addRefCalls, resultFailureBefore.addRefCalls + 2)',
        '    assert.equal(readStats().releaseCalls, resultFailureBefore.releaseCalls + 2)',
        '    assert.equal(readStats().openNamespaceCalls, 4)',
        '    wrapper.release()',
        '    assert.equal(readStats().currentRefCount, 1)',
        '    wrapper.release()',
        '    assert.throws(() => wrapper.queryObjectSink(74, slot), /released|apartment-bound/)',
        '    assert.equal(readStats().queryObjectSinkCalls, 1)',
        '    fake.release()',
        '    assert.equal(readStats().currentRefCount, 0)',
        '    wrapper = undefined',
        '    fake = undefined',
        '  } finally {',
        '    wrapper?.release()',
        '    fake?.release()',
        '    slot?.release()',
        '  }',
        '  const createAudio = runtime.createGeneratedAudioClientFake',
        '  const audioStats = runtime.generatedAudioClientStats',
        '  const setServiceMode = runtime.setGeneratedAudioClientGetServiceMode',
        '  const createCleanupResource = runtime.createGeneratedNativeCleanupResource',
        "  assert.equal(typeof createAudio, 'function')",
        "  assert.equal(typeof createCleanupResource, 'function')",
        '  assert.throws(() => new UnsafePointee(), /factory methods/)',
        '  assert.throws(() => new UnsafePointerOutput(), /factory methods/)',
        '  assert.throws(() => new UnsafeHandleOutput(), /factory methods/)',
        '  assert.throws(() => new UnsafeInterfaceReplacement(), /factory methods/)',
        '  assert.throws(() => { strategyRuntime.__prepareStrategy = () => null }, TypeError)',
        '  assert.throws(() => { delete strategyRuntime.__prepareStrategy }, TypeError)',
        "  assert.throws(() => Object.defineProperty(strategyRuntime, '__prepareStrategy', { value: () => null }), TypeError)",
        '  let audioFake = createAudio()',
        '  let audioWrapper',
        '  try {',
        '    audioWrapper = audio.IAudioClientUnsafe.from(audioFake)',
        '    const format = DynComRawMemory.allocate(22, 2)',
        '    format.writeU16(0, 1)',
        "    const inPointeeContract = Object.freeze({ direction: 'in', nullable: false, pointeeLayouts: Object.freeze({ x64: null, i686: null, arm64: null }) })",
        "    const nullableInPointeeContract = Object.freeze({ direction: 'in', nullable: true, pointeeLayouts: Object.freeze({ x64: null, i686: null, arm64: null }) })",
        "    const knownWritablePointeeContract = Object.freeze({ direction: 'out', nullable: false, pointeeLayouts: Object.freeze({ x64: Object.freeze({ size: 8, alignment: 8 }), i686: Object.freeze({ size: 4, alignment: 4 }), arm64: Object.freeze({ size: 8, alignment: 8 }) }) })",
        "    const unknownWritablePointeeContract = Object.freeze({ direction: 'inout', nullable: false, pointeeLayouts: Object.freeze({ x64: null, i686: null, arm64: null }) })",
        "    const nullableWritablePointeeContract = Object.freeze({ direction: 'out', nullable: true, pointeeLayouts: Object.freeze({ x64: null, i686: null, arm64: null }) })",
        "    assert.throws(() => UnsafePointerOutput.comOwned({}), /WinGUID|convert|class/i)",
        "    assert.throws(() => UnsafePointerOutput.comOwned(new Proxy(audio.IAudioClientUnsafe.iid, {})), /WinGUID|convert|class/i)",
        '    const invalidReplacementOwner = DynComRawOwnedComPointer.addRef(audioFake)',
        "    assert.throws(() => UnsafeInterfaceReplacement.unchanged(invalidReplacementOwner, {}), /WinGUID|convert|class/i)",
        '    invalidReplacementOwner.release()',
        '    assert.equal(audioStats().isFormatSupportedCalls, 0)',
        '    const hardened = UnsafePointerOutput.coTaskMem()',
        "    const opaqueRecord = __prepareStrategy(UnsafePointee.required(format), 'UnsafePointee', 'opaque', inPointeeContract)",
        '    assert.equal(Object.isFrozen(opaqueRecord), true)',
        '    assert.deepEqual(Object.keys(opaqueRecord), [])',
        '    assert.equal(opaqueRecord.state, undefined)',
        '    assert.throws(() => { opaqueRecord.state = {} }, TypeError)',
        "    assert.throws(() => __strategyArgument(Object.freeze({})), /not authentic/)",
        "    assert.throws(() => __activateStrategies([Object.freeze({})]), /not authentic/)",
        "    assert.throws(() => __finishStrategy(Object.freeze({})), /not authentic/)",
        "    assert.throws(() => __markDispatchEntered([opaqueRecord], { entered: true }), /DispatchState|convert|class/i)",
        '    assert.equal(Object.isFrozen(hardened), true)',
        "    assert.throws(() => { hardened._state = 'prepared' }, TypeError)",
        '    assert.throws(() => Object.setPrototypeOf(hardened, {}), TypeError)',
        '    assert.throws(() => { UnsafePointerOutput.prototype.prepare = () => null }, TypeError)',
        '    class ForgedOutput extends UnsafePointerOutput {}',
        '    assert.equal(Object.getPrototypeOf(ForgedOutput.coTaskMem()), UnsafePointerOutput.prototype)',
        '    assert.throws(() => audioWrapper.isFormatSupported(1, UnsafePointee.required(format), new Proxy(hardened, {})), /exact generated UnsafePointerOutput/)',
        '    assert.throws(() => audioWrapper.isFormatSupported(1, UnsafePointee.required(format), {}), /exact generated UnsafePointerOutput/)',
        '    assert.equal(audioStats().isFormatSupportedCalls, 0)',
        '    assert.throws(() => audioWrapper.isFormatSupported(1, UnsafePointee.required(DynComRawPointer.null()), UnsafePointerOutput.coTaskMem()), /non-null/)',
        '    assert.throws(() => audioWrapper.isFormatSupported(1, UnsafePointee.required(null), UnsafePointerOutput.coTaskMem()), /non-null/)',
        '    const releasedFormat = DynComRawMemory.allocate(22, 2)',
        '    releasedFormat.release()',
        '    assert.throws(() => audioWrapper.isFormatSupported(1, UnsafePointee.required(releasedFormat), UnsafePointerOutput.coTaskMem()), /released/)',
        '    const releasedSlot = DynComRawMemory.allocate(DynComRaw.pointerSize(), DynComRaw.pointerSize())',
        '    const releasedOutput = UnsafePointerOutput.coTaskMem(releasedSlot)',
        '    releasedSlot.release()',
        '    assert.throws(() => audioWrapper.isFormatSupported(1, UnsafePointee.required(format), releasedOutput), /released/)',
        '    assert.throws(() => DynComRawMemory.fromUnsafeAddress(0n, 8, 1), /non-null/)',
        '    assert.equal(audioStats().isFormatSupportedCalls, 0)',
        '    const spanBase = DynComRawMemory.allocate(DynComRaw.pointerSize() * 2, DynComRaw.pointerSize())',
        '    const spanA = DynComRawMemory.fromUnsafePointer(spanBase.pointer(), DynComRaw.pointerSize(), DynComRaw.pointerSize())',
        '    const spanB = DynComRawMemory.fromUnsafePointer(spanBase.pointer(Math.floor(DynComRaw.pointerSize() / 2)), DynComRaw.pointerSize(), 1)',
        "    const exactSpan = __prepareExactWritableSpan(spanA, 'exactSpan', false)",
        "    const duplicateExactSpan = __prepareExactWritableSpan(spanA, 'duplicateExactSpan', false)",
        '    assert.throws(() => __validateStrategySpans([exactSpan, duplicateExactSpan]), /overlap/)',
        "    const exactOutputSpan = __prepareStrategy(UnsafePointerOutput.rawResponsibility(spanA), 'UnsafePointerOutput', 'exactOutputSpan')",
        '    assert.throws(() => __validateStrategySpans([exactSpan, exactOutputSpan]), /overlap/)',
        '    __failStrategy(exactOutputSpan)',
        "    const exactHandleSpan = __prepareStrategy(UnsafeHandleOutput.rawResponsibility(spanA), 'UnsafeHandleOutput', 'exactHandleSpan')",
        '    assert.throws(() => __validateStrategySpans([exactSpan, exactHandleSpan]), /overlap/)',
        '    __failStrategy(exactHandleSpan)',
        "    const partialExactSpan = __prepareStrategy(UnsafeCountedBuffer.required(spanB), 'UnsafeCountedBuffer', 'partialExactSpan')",
        '    assert.throws(() => __validateStrategySpans([exactSpan, partialExactSpan]), /overlap/)',
        '    for (const [kind, factory] of [',
        "      ['UnsafePointerOutput', slot => UnsafePointerOutput.comOwned(audio.IAudioClientUnsafe.iid, slot)],",
        "      ['UnsafePointerOutput', slot => UnsafePointerOutput.coTaskMem(slot)],",
        "      ['UnsafePointerOutput', slot => UnsafePointerOutput.bstr(slot)],",
        "      ['UnsafePointerOutput', slot => UnsafePointerOutput.localAlloc(slot)],",
        "      ['UnsafePointerOutput', slot => UnsafePointerOutput.globalAlloc(slot)],",
        "      ['UnsafeHandleOutput', slot => UnsafeHandleOutput.rawResponsibility(slot)],",
        '    ]) {',
        "      const first = __prepareStrategy(factory(spanA), kind, 'first')",
        "      const second = __prepareStrategy(UnsafePointerOutput.rawResponsibility(spanA), 'UnsafePointerOutput', 'second')",
        '      assert.throws(() => __validateStrategySpans([first, second]), /overlap/)',
        '      __failStrategy(second)',
        '      __failStrategy(first)',
        '    }',
        "    assert.throws(() => __prepareStrategy(UnsafePointerOutput.bstr(spanB), 'UnsafePointerOutput', 'misaligned'), /pointer-aligned/)",
        "    const partialFirst = __prepareStrategy(UnsafePointerOutput.coTaskMem(spanA), 'UnsafePointerOutput', 'partialFirst')",
        "    const partialSecond = __prepareStrategy(UnsafeCountedBuffer.required(spanB), 'UnsafeCountedBuffer', 'partialSecond')",
        '    assert.throws(() => __validateStrategySpans([partialFirst, partialSecond]), /overlap/)',
        "    const countedRecord = __prepareStrategy(UnsafeCountedBuffer.required(spanBase), 'UnsafeCountedBuffer', 'countedSpan')",
        "    const countedOutput = __prepareStrategy(UnsafePointerOutput.rawResponsibility(spanA), 'UnsafePointerOutput', 'countedOutput')",
        '    assert.throws(() => __validateStrategySpans([countedRecord, countedOutput]), /overlap/)',
        '    __failStrategy(countedOutput)',
        "    const writablePointee = __prepareStrategy(UnsafePointee.required(spanA), 'UnsafePointee', 'writablePointee', knownWritablePointeeContract)",
        '    assert.throws(() => __validateStrategySpans([exactSpan, writablePointee]), /overlap/)',
        "    const writableOutput = __prepareStrategy(UnsafePointerOutput.rawResponsibility(spanA), 'UnsafePointerOutput', 'writableOutput')",
        '    assert.throws(() => __validateStrategySpans([writablePointee, writableOutput]), /overlap/)',
        '    __failStrategy(writableOutput)',
        "    const partialWritable = __prepareStrategy(UnsafePointee.required(spanB), 'UnsafePointee', 'partialWritable', unknownWritablePointeeContract)",
        "    const partialWritableOutput = __prepareStrategy(UnsafePointerOutput.rawResponsibility(spanA), 'UnsafePointerOutput', 'partialWritableOutput')",
        '    assert.throws(() => __validateStrategySpans([partialWritable, partialWritableOutput]), /overlap/)',
        '    __failStrategy(partialWritableOutput)',
        "    const otherWritable = __prepareStrategy(UnsafePointee.required(spanBase), 'UnsafePointee', 'otherWritable', unknownWritablePointeeContract)",
        '    assert.throws(() => __validateStrategySpans([partialWritable, otherWritable]), /overlap/)',
        "    const countSlot = __prepareWritableStorage(spanA, 'countSlot', Object.freeze({ direction: 'out', nullable: false, pointeeLayouts: Object.freeze({ x64: Object.freeze({ size: 4, alignment: 4 }), i686: Object.freeze({ size: 4, alignment: 4 }), arm64: Object.freeze({ size: 4, alignment: 4 }) }) }))",
        '    assert.throws(() => __validateStrategySpans([exactSpan, countSlot]), /overlap/)',
        '    assert.throws(() => __validateStrategySpans([otherWritable, countSlot]), /overlap/)',
        '    const undersizedPointee = DynComRawMemory.allocate(4, 4)',
        "    assert.throws(() => __prepareStrategy(UnsafePointee.required(undersizedPointee), 'UnsafePointee', 'undersizedPointee', knownWritablePointeeContract), /smaller/)",
        '    undersizedPointee.release()',
        "    assert.throws(() => __prepareStrategy(UnsafePointee.required(spanB), 'UnsafePointee', 'misalignedPointee', knownWritablePointeeContract), /alignment/)",
        '    const releasedPointee = DynComRawMemory.allocate(8, 8)',
        '    releasedPointee.release()',
        "    assert.throws(() => __prepareStrategy(UnsafePointee.required(releasedPointee), 'UnsafePointee', 'releasedPointee', knownWritablePointeeContract), /released/)",
        "    assert.throws(() => __prepareStrategy(UnsafePointee.required(spanA.pointer()), 'UnsafePointee', 'unboundedPointee', knownWritablePointeeContract), /bounded/)",
        "    assert.throws(() => __prepareStrategy(UnsafePointee.required(DynComRawPointer.null()), 'UnsafePointee', 'rawNullPointee', knownWritablePointeeContract), /non-null/)",
        "    assert.throws(() => __prepareStrategy(UnsafePointee.required(null), 'UnsafePointee', 'nullPointee', knownWritablePointeeContract), /non-null/)",
        "    assert.throws(() => __prepareStrategy(UnsafePointee.nullable(), 'UnsafePointee', 'requiredContractPointee', knownWritablePointeeContract), /non-null/)",
        "    assert.ok(__strategyArgument(__prepareStrategy(UnsafePointee.nullable(), 'UnsafePointee', 'nullableWritablePointee', nullableWritablePointeeContract)))",
        "    assert.ok(__strategyArgument(__prepareStrategy(UnsafePointee.nullable(DynComRawPointer.null()), 'UnsafePointee', 'nullableRawWritablePointee', nullableWritablePointeeContract)))",
        '    const replacementOwner = DynComRawOwnedComPointer.addRef(audioFake)',
        '    const replacementSlot = DynComRawMemory.fromUnsafePointer(spanBase.pointer(), DynComRaw.pointerSize(), 1)',
        "    const replacementRecord = __prepareStrategy(UnsafeInterfaceReplacement.unchanged(replacementOwner, audio.IAudioClientUnsafe.iid, replacementSlot), 'UnsafeInterfaceReplacement', 'replacementSpan')",
        '    assert.throws(() => __validateStrategySpans([exactSpan, replacementRecord]), /overlap/)',
        "    const replacementOutput = __prepareStrategy(UnsafePointerOutput.rawResponsibility(replacementSlot), 'UnsafePointerOutput', 'replacementOutput')",
        '    assert.throws(() => __validateStrategySpans([replacementRecord, replacementOutput]), /overlap/)',
        '    __failStrategy(replacementOutput)',
        '    __failStrategy(replacementRecord)',
        '    replacementOwner.release()',
        '    replacementSlot.release()',
        '    spanB.release()',
        '    spanA.release()',
        '    spanBase.release()',
        '    for (let failAt = 0; failAt < 3; failAt++) {',
        '      const finishSlots = [0, 1, 2].map(() => DynComRawMemory.allocate(DynComRaw.pointerSize(), DynComRaw.pointerSize()))',
        '      const finishStrategies = finishSlots.map(slot => UnsafePointerOutput.rawResponsibility(slot))',
        "      const finishRecords = finishStrategies.map((strategy, index) => __prepareStrategy(strategy, 'UnsafePointerOutput', `finish${index}`))",
        '      __validateStrategySpans(finishRecords)',
        '      __activateStrategies(finishRecords)',
        '      for (let index = 0; index < 3; index++) { if (index !== failAt) finishSlots[index].writePointer(0, DynComRawPointer.fromAddress(BigInt(0x100 + index))) }',
        '      let finishError',
        '      try { finishTransaction(finishRecords) } catch (error) { finishError = error }',
        '      assert.equal(finishError.unsafeOutputs.length, 3)',
        '      for (const slot of finishSlots) slot.release()',
        '    }',
        '    assert.equal(audioStats().isFormatSupportedCalls, 0)',
        '    const closest = UnsafePointerOutput.coTaskMem()',
        '    const formatResult = audioWrapper.isFormatSupported(1, UnsafePointee.required(format), closest)',
        '    assert.equal(formatResult[0], 1)',
        '    assert.equal(audioStats().isFormatSupportedCalls, 1)',
        '    assert.equal(audioStats().lastShareMode, 1)',
        '    assert.equal(audioStats().lastFormatTag, 1)',
        '    const closestOwner = formatResult[1]',
        '    const closestView = closestOwner.view(16, 4)',
        '    assert.equal(closestView.readU32(0), 0xaabbccdd)',
        '    closestView.release()',
        '    assert.equal(__testRunOwnedFinalizer(closestOwner), true)',
        '    assert.equal(__testRunOwnedFinalizer(closestOwner), true)',
        '    assert.throws(() => closestOwner.view(16, 4), /released/)',
        '    assert.throws(() => audioWrapper.isFormatSupported(2, UnsafePointee.required(format), UnsafePointerOutput.coTaskMem()), /native call failed|HRESULT|0x80004005/i)',
        '    assert.equal(audioStats().isFormatSupportedCalls, 2)',
        '    assert.throws(() => audioWrapper.isFormatSupported(1, UnsafePointee.required(format), closest), /finished/)',
        '    assert.equal(audioStats().isFormatSupportedCalls, 2)',
        '    assert.throws(() => audioWrapper.isFormatSupported(1, UnsafePointee.required(format), UnsafePointee.required(format)), /UnsafePointerOutput/)',
        '    assert.equal(audioStats().isFormatSupportedCalls, 2)',
        '    const iidStorage = DynComRawMemory.allocate(16, 4)',
        '    setServiceMode(1)',
        '    const beforeFailureRefs = audioStats().currentRefCount',
        '    assert.throws(() => audioWrapper.getService(iidStorage, UnsafePointerOutput.comOwned(audio.IAudioClientUnsafe.iid)), /native call failed|HRESULT|0x80004005/i)',
        '    assert.equal(audioStats().getServiceCalls, 1)',
        '    assert.equal(audioStats().currentRefCount, beforeFailureRefs)',
        '    const rawFailure = UnsafePointerOutput.rawResponsibility()',
        '    let rawFailureError',
        '    try { audioWrapper.getService(iidStorage, rawFailure) } catch (error) { rawFailureError = error }',
        '    assert.equal(rawFailureError.unsafeOutputs.length, 1)',
        '    const dirtyPointer = rawFailure.takeFailurePointer()',
        '    assert.equal(dirtyPointer.address, rawFailureError.unsafeOutputs[0].pointer.address)',
        '    assert.throws(() => rawFailure.takeFailurePointer(), /No raw failure pointer/)',
        '    DynComRawOwnedComPointer.assumeTransferred(dirtyPointer, audio.IAudioClientUnsafe.iid).release()',
        '    assert.equal(audioStats().currentRefCount, beforeFailureRefs)',
        '    setServiceMode(-2)',
        '    const nullFailure = UnsafePointerOutput.rawResponsibility()',
        '    let nullFailureError',
        '    try { audioWrapper.getService(iidStorage, nullFailure) } catch (error) { nullFailureError = error }',
        '    assert.equal(nullFailureError.unsafeOutputs[0].pointer.isNull, true)',
        '    assert.equal(nullFailure.takeFailurePointer().isNull, true)',
        '    assert.throws(() => nullFailure.takeFailurePointer(), /No raw failure pointer/)',
        '    setServiceMode(0)',
        '    const managedService = audioWrapper.getService(iidStorage, UnsafePointerOutput.comOwned(audio.IAudioClientUnsafe.iid))',
        '    assert.equal(audioStats().currentRefCount, beforeFailureRefs + 1)',
        '    managedService.release()',
        '    assert.equal(audioStats().currentRefCount, beforeFailureRefs)',
        "    const wrongIid = WinGuid.parse('aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee')",
        '    assert.throws(() => audioWrapper.getService(iidStorage, UnsafePointerOutput.comOwned(wrongIid)), /interface|0x80004002/i)',
        '    assert.equal(audioStats().currentRefCount, beforeFailureRefs)',
        '    setServiceMode(2)',
        '    assert.throws(() => audioWrapper.getService(iidStorage, UnsafePointerOutput.comOwned(audio.IAudioClientUnsafe.iid)), /Required pointer output was null/)',
        '    const nullable = audioWrapper.getService(iidStorage, UnsafePointerOutput.comOwned(audio.IAudioClientUnsafe.iid, null, true))',
        '    assert.equal(nullable, null)',
        '    setServiceMode(3)',
        '    assert.equal(__testRunOwnedFinalizer(audioWrapper.getService(iidStorage, UnsafePointerOutput.bstr())), true)',
        '    setServiceMode(-3)',
        '    assert.throws(() => audioWrapper.getService(iidStorage, UnsafePointerOutput.bstr()), /native call failed|HRESULT|0x80004005/i)',
        '    setServiceMode(4)',
        '    assert.equal(__testRunOwnedFinalizer(audioWrapper.getService(iidStorage, UnsafePointerOutput.localAlloc())), true)',
        '    setServiceMode(-4)',
        '    assert.throws(() => audioWrapper.getService(iidStorage, UnsafePointerOutput.localAlloc()), /native call failed|HRESULT|0x80004005/i)',
        '    setServiceMode(5)',
        '    assert.equal(__testRunOwnedFinalizer(audioWrapper.getService(iidStorage, UnsafePointerOutput.globalAlloc())), true)',
        '    setServiceMode(-5)',
        '    assert.throws(() => audioWrapper.getService(iidStorage, UnsafePointerOutput.globalAlloc()), /native call failed|HRESULT|0x80004005/i)',
        '    setServiceMode(2)',
        '    assert.equal(audioWrapper.getService(iidStorage, UnsafePointerOutput.borrowed(null, true)), null)',
        '    assert.equal(audioWrapper.getService(iidStorage, UnsafePointerOutput.unclassified(null, true)), null)',
        '    assert.equal(audioWrapper.getService(iidStorage, UnsafePointerOutput.rawResponsibility(null, true)), null)',
        '    const rawSlot = DynComRawMemory.allocate(DynComRaw.pointerSize(), DynComRaw.pointerSize())',
        '    const handle = UnsafeHandleOutput.rawResponsibility(rawSlot)',
        "    const handleRecord = __prepareStrategy(handle, 'UnsafeHandleOutput', 'handle')",
        '    __activateStrategies([handleRecord])',
        '    rawSlot.writePointer(0, DynComRawPointer.fromAddress(0x55n))',
        '    assert.equal(__finishStrategy(handleRecord).address, 0x55n)',
        "    assert.throws(() => __prepareStrategy(handle, 'UnsafeHandleOutput', 'handle'), /finished/)",
        '    rawSlot.release()',
        '    for (const factory of [UnsafeHandleOutput.borrowed, UnsafeHandleOutput.closeHandle, UnsafeHandleOutput.destroyIcon, UnsafeHandleOutput.deleteObject]) {',
        '      const nullableHandle = factory.call(UnsafeHandleOutput, null, true)',
        "      const nullableRecord = __prepareStrategy(nullableHandle, 'UnsafeHandleOutput', 'nullableHandle')",
        '      __activateStrategies([nullableRecord])',
        '      assert.equal(__finishStrategy(nullableRecord), null)',
        '    }',
        '    for (const [kind, factory] of [[1, UnsafeHandleOutput.closeHandle], [2, UnsafeHandleOutput.destroyIcon], [3, UnsafeHandleOutput.deleteObject]]) {',
        '      const nativeSlot = DynComRawMemory.allocate(DynComRaw.pointerSize(), DynComRaw.pointerSize())',
        '      const nativeStrategy = factory.call(UnsafeHandleOutput, nativeSlot)',
        "      const nativeRecord = __prepareStrategy(nativeStrategy, 'UnsafeHandleOutput', 'nativeHandle')",
        '      __activateStrategies([nativeRecord])',
        '      nativeSlot.writePointer(0, DynComRawPointer.fromAddress(createCleanupResource(kind)))',
        '      const nativeOwner = __finishStrategy(nativeRecord)',
        '      assert.equal(__testRunOwnedFinalizer(nativeOwner), true)',
        '      assert.equal(__testRunOwnedFinalizer(nativeOwner), true)',
        '      nativeSlot.release()',
        '    }',
        '    const owner = DynComRawOwnedComPointer.addRef(audioFake)',
        '    const unchanged = UnsafeInterfaceReplacement.unchanged(owner, audio.IAudioClientUnsafe.iid)',
        "    const unchangedRecord = __prepareStrategy(unchanged, 'UnsafeInterfaceReplacement', 'unchanged')",
        '    __activateStrategies([unchangedRecord])',
        '    const unchangedResult = __finishStrategy(unchangedRecord)',
        '    assert.equal(unchangedResult.previous, owner)',
        '    assert.equal(unchangedResult.current, owner)',
        '    unchangedResult.release()',
        "    assert.throws(() => __prepareStrategy(unchanged, 'UnsafeInterfaceReplacement', 'unchanged'), /finished/)",
        '    const preservesOwner = DynComRawOwnedComPointer.addRef(audioFake)',
        '    const preserves = UnsafeInterfaceReplacement.preservesOld(preservesOwner, audio.IAudioClientUnsafe.iid)',
        "    const preservesRecord = __prepareStrategy(preserves, 'UnsafeInterfaceReplacement', 'preserves')",
        '    __activateStrategies([preservesRecord])',
        '    const preservesResult = __finishStrategy(preservesRecord)',
        '    assert.equal(preservesResult.previous, preservesOwner)',
        '    assert.equal(preservesResult.current, preservesOwner)',
        '    preservesResult.release()',
        '    const reentrantOwner = DynComRawOwnedComPointer.addRef(audioFake)',
        '    const reentrant = UnsafeInterfaceReplacement.preservesOld(reentrantOwner, audio.IAudioClientUnsafe.iid)',
        "    const reentrantRecord = __prepareStrategy(reentrant, 'UnsafeInterfaceReplacement', 'reentrant')",
        '    __activateStrategies([reentrantRecord])',
        '    reentrantOwner.release()',
        '    const reentrantResult = __finishStrategy(reentrantRecord)',
        '    assert.notEqual(reentrantResult.previous, reentrantOwner)',
        '    assert.equal(reentrantResult.previous.released, false)',
        '    assert.equal(reentrantResult.current, reentrantResult.previous)',
        '    reentrantResult.release()',
        '    const consumesOwner = DynComRawOwnedComPointer.addRef(audioFake)',
        '    const consumes = UnsafeInterfaceReplacement.consumesOld(consumesOwner, audio.IAudioClientUnsafe.iid)',
        "    const consumesRecord = __prepareStrategy(consumes, 'UnsafeInterfaceReplacement', 'consumes')",
        '    __activateStrategies([consumesRecord])',
        '    const consumesResult = __finishStrategy(consumesRecord)',
        '    assert.equal(consumesResult.previous, null)',
        '    assert.ok(consumesResult.current)',
        '    consumesResult.release()',
        '    const preDispatchOwner = DynComRawOwnedComPointer.addRef(audioFake)',
        '    const preDispatchReplacement = UnsafeInterfaceReplacement.consumesOld(preDispatchOwner, audio.IAudioClientUnsafe.iid)',
        "    const preDispatchRecord = __prepareStrategy(preDispatchReplacement, 'UnsafeInterfaceReplacement', 'preDispatch')",
        '    __activateStrategies([preDispatchRecord])',
        '    __markDispatchEntered([preDispatchRecord], DynComRaw.__createDispatchState())',
        '    __failStrategy(preDispatchRecord)',
        "    const preDispatchRetry = __prepareStrategy(preDispatchReplacement, 'UnsafeInterfaceReplacement', 'preDispatchRetry')",
        '    __activateStrategies([preDispatchRetry])',
        '    const preDispatchResult = __finishStrategy(preDispatchRetry)',
        '    preDispatchResult.release()',
        "    const replacementFactories = [UnsafeInterfaceReplacement.consumesOld, UnsafeInterfaceReplacement.preservesOld, UnsafeInterfaceReplacement.unchanged]",
        '    const aliasCallCount = audioStats().isFormatSupportedCalls',
        '    for (let first = 0; first < replacementFactories.length; first++) {',
        '      for (let second = first; second < replacementFactories.length; second++) {',
        '        const sharedOwner = DynComRawOwnedComPointer.addRef(audioFake)',
        '        const slots = [0, 1].map(() => DynComRawMemory.allocate(DynComRaw.pointerSize(), DynComRaw.pointerSize()))',
        "        const records = [first, second].map((mode, index) => __prepareStrategy(replacementFactories[mode](sharedOwner, audio.IAudioClientUnsafe.iid, slots[index]), 'UnsafeInterfaceReplacement', `pair${first}${second}${index}`))",
        '        assert.throws(() => __validateStrategySpans(records), /owner is used by multiple/)',
        '        assert.ok(sharedOwner.address > 0n)',
        '        sharedOwner.release()',
        '        for (const slot of slots) slot.release()',
        '      }',
        '    }',
        '    for (let first = 0; first < replacementFactories.length; first++) {',
        '      for (let second = first; second < replacementFactories.length; second++) {',
        '        for (let third = second; third < replacementFactories.length; third++) {',
        '          const sharedOwner = DynComRawOwnedComPointer.addRef(audioFake)',
        '          const slots = [0, 1, 2].map(() => DynComRawMemory.allocate(DynComRaw.pointerSize(), DynComRaw.pointerSize()))',
        "          const records = [first, second, third].map((mode, index) => __prepareStrategy(replacementFactories[mode](sharedOwner, audio.IAudioClientUnsafe.iid, slots[index]), 'UnsafeInterfaceReplacement', `triple${first}${second}${third}${index}`))",
        '          assert.throws(() => __validateStrategySpans(records), /owner is used by multiple/)',
        '          assert.ok(sharedOwner.address > 0n)',
        '          sharedOwner.release()',
        '          for (const slot of slots) slot.release()',
        '        }',
        '      }',
        '    }',
        '    const independentOwners = [0, 1, 2].map(() => DynComRawOwnedComPointer.addRef(audioFake))',
        '    const independentSlots = [0, 1, 2].map(() => DynComRawMemory.allocate(DynComRaw.pointerSize(), DynComRaw.pointerSize()))',
        "    const independentRecords = replacementFactories.map((factory, index) => __prepareStrategy(factory(independentOwners[index], audio.IAudioClientUnsafe.iid, independentSlots[index]), 'UnsafeInterfaceReplacement', `independent${index}`))",
        '    __validateStrategySpans(independentRecords)',
        '    __activateStrategies(independentRecords)',
        '    const independentResults = independentRecords.map(record => __finishStrategy(record))',
        '    for (const result of independentResults) result.release()',
        '    for (const slot of independentSlots) slot.release()',
        '    assert.equal(audioStats().isFormatSupportedCalls, aliasCallCount)',
        '    const rollbackOwnerA = DynComRawOwnedComPointer.addRef(audioFake)',
        '    const rollbackOwnerB = DynComRawOwnedComPointer.addRef(audioFake)',
        '    const rollbackSlotA = DynComRawMemory.allocate(DynComRaw.pointerSize(), DynComRaw.pointerSize())',
        '    const rollbackSlotB = DynComRawMemory.allocate(DynComRaw.pointerSize(), DynComRaw.pointerSize())',
        '    const rollbackA = UnsafeInterfaceReplacement.consumesOld(rollbackOwnerA, audio.IAudioClientUnsafe.iid, rollbackSlotA)',
        '    const rollbackB = UnsafeInterfaceReplacement.consumesOld(rollbackOwnerB, audio.IAudioClientUnsafe.iid, rollbackSlotB)',
        "    const rollbackRecordA = __prepareStrategy(rollbackA, 'UnsafeInterfaceReplacement', 'rollbackA')",
        "    const rollbackRecordB = __prepareStrategy(rollbackB, 'UnsafeInterfaceReplacement', 'rollbackB')",
        '    __validateStrategySpans([rollbackRecordA, rollbackRecordB])',
        '    rollbackSlotB.release()',
        '    assert.throws(() => __activateStrategies([rollbackRecordA, rollbackRecordB]), /released/)',
        "    const rollbackRetry = __prepareStrategy(rollbackA, 'UnsafeInterfaceReplacement', 'rollbackRetry')",
        '    __activateStrategies([rollbackRetry])',
        '    const rollbackResult = __finishStrategy(rollbackRetry)',
        '    rollbackResult.release()',
        '    rollbackOwnerB.release()',
        '    rollbackSlotA.release()',
        "    assert.ok(__strategyArgument(__prepareStrategy(UnsafeCountedBuffer.required(format), 'UnsafeCountedBuffer', 'counted')))",
        "    assert.ok(__strategyArgument(__prepareStrategy(UnsafeCountedBuffer.nullable(), 'UnsafeCountedBuffer', 'nullableCounted')))",
        "    assert.ok(__strategyArgument(__prepareStrategy(UnsafePointee.nullable(), 'UnsafePointee', 'nullablePointee', nullableInPointeeContract)))",
        "    assert.throws(() => __prepareStrategy(UnsafePointee.required(null), 'UnsafePointee', 'requiredPointee', inPointeeContract), /non-null/)",
        "    assert.ok(__strategyArgument(__prepareStrategy(UnsafeRawCall.value(format), 'UnsafeRawCall', 'raw')))",
        '    __assertRawContract(UnsafeRawCall.acknowledge())',
        '    assert.throws(() => __assertRawContract(UnsafeRawCall.value(format)), /acknowledge/)',
        '    let retryCleanupCalls = 0',
        "    const retryOwner = __testCreateOwnedPointer(() => { retryCleanupCalls++; if (retryCleanupCalls === 1) throw new Error('retry cleanup') })",
        '    assert.throws(() => retryOwner.release(), /retry cleanup/)',
        '    assert.equal(retryOwner.released, false)',
        '    retryOwner.release()',
        '    assert.equal(retryCleanupCalls, 2)',
        '    __testRunOwnedFinalizer(retryOwner)',
        '    assert.equal(retryCleanupCalls, 2)',
        '    let abandonedCleanupCalls = 0',
        '    const abandonedOwner = __testCreateOwnedPointer(() => { abandonedCleanupCalls++ })',
        '    __testRunOwnedFinalizer(abandonedOwner)',
        '    __testRunOwnedFinalizer(abandonedOwner)',
        '    assert.equal(abandonedCleanupCalls, 1)',
        '    let failedFinalizerCalls = 0',
        "    const failedFinalizerOwner = __testCreateOwnedPointer(() => { failedFinalizerCalls++; throw new Error('finalizer cleanup') })",
        '    assert.equal(__testRunOwnedFinalizer(failedFinalizerOwner), false)',
        '    assert.equal(__testRunOwnedFinalizer(failedFinalizerOwner), false)',
        '    assert.equal(failedFinalizerCalls, 1)',
        '    assert.equal(failedFinalizerOwner.released, false)',
        '    iidStorage.release()',
        '    format.release()',
        '    audioWrapper.release()',
        '    audioFake.release()',
        '    audioWrapper = undefined',
        '    audioFake = undefined',
        '    assert.equal(audioStats().currentRefCount, 0)',
        '  } finally {',
        '    audioWrapper?.release()',
        '    audioFake?.release()',
        '  }',
        "  console.log('generated-unsafe-companion-ok')",
        '}',
        'main().catch(error => { console.error(error); process.exitCode = 1 })',
        '',
      ].join('\n'),
    )
    const execution = spawnSync(process.execPath, [runner], {
      cwd: output,
      encoding: 'utf8',
      windowsHide: true,
    })
    t.is(execution.status, 0, `${execution.stderr}\n${execution.stdout}`)
    t.regex(execution.stdout, /generated-unsafe-companion-ok/)

    const consumer = join(output, 'generated-consumer.ts')
    writeFileSync(
      consumer,
      [
        "import { IWbemServicesUnsafe } from './com/unsafe/windows/win32/system/wmi/IWbemServicesUnsafe.js'",
        "import { IAudioClientUnsafe } from './com/unsafe/windows/win32/media/audio/IAudioClientUnsafe.js'",
        "import { IWbemServicesUnsafe as FromBarrel } from './com/unsafe/index.js'",
        "import { UnsafePointee, UnsafePointerOutput } from './com/unsafe/runtime.js'",
        "import type { UnsafeOwnedPointer } from './com/unsafe/runtime.js'",
        "import type { DynComRawMemory, DynWinRtValue } from '@microsoft/dynwinrt/com/unsafe/raw'",
        'declare const native: DynWinRtValue',
        'declare const storage: DynComRawMemory',
        'const direct: IWbemServicesUnsafe = IWbemServicesUnsafe.from(native)',
        'const barrel: FromBarrel = FromBarrel.from(native)',
        'direct.queryObjectSink(7, storage)',
        "const namespaceOutput = direct.openNamespace('root', { lFlags: 0, workingNamespace: storage, result: null })",
        'namespaceOutput.release()',
        "const resultOutput = direct.openNamespace('root', { lFlags: 16, workingNamespace: null, result: storage })",
        'resultOutput.release()',
        '// @ts-expect-error semisynchronous flags are exactly 16',
        "direct.openNamespace('root', { lFlags: 17, workingNamespace: null, result: storage })",
        '// @ts-expect-error lFlags must be numeric',
        "direct.openNamespace('root', { lFlags: '16', workingNamespace: null, result: storage })",
        'const audio = IAudioClientUnsafe.from(native)',
        '// @ts-expect-error strategy result types are invariant',
        'const wrongOutput: UnsafePointerOutput<string> = UnsafePointerOutput.coTaskMem()',
        'const ownedOutput: UnsafePointerOutput<UnsafeOwnedPointer | null> = UnsafePointerOutput.coTaskMem()',
        'void wrongOutput',
        'void ownedOutput',
        'audio.isFormatSupported(0, UnsafePointee.required(storage), UnsafePointerOutput.coTaskMem())',
        'audio.release()',
        'barrel.release()',
        'direct.release()',
        '',
      ].join('\n'),
    )
    const tsc = spawnSync(
      process.execPath,
      [
        join(packageRoot, 'node_modules', 'typescript', 'bin', 'tsc'),
        '--noEmit',
        '--strict',
        '--module',
        'Node16',
        '--moduleResolution',
        'Node16',
        '--target',
        'ES2022',
        consumer,
      ],
      { cwd: packageRoot, encoding: 'utf8', windowsHide: true },
    )
    t.is(tsc.status, 0, `${tsc.stdout}\n${tsc.stderr}`)
  } finally {
    rmSync(output, { recursive: true, force: true })
    rmSync(externalLinkTarget, { recursive: true, force: true })
    rmSync(lock, { force: true })
    for (const residue of transactionResidues) rmSync(residue, { recursive: true, force: true })
  }
})
