from collections.abc import Coroutine
from typing import Any, Awaitable, Callable, List, Literal, Mapping, Optional, Protocol, Sequence, TypeVar, Union, final, overload
from uuid import UUID

_T = TypeVar("_T", covariant=True)
_P = TypeVar("_P", covariant=True)
_Tracked = TypeVar("_Tracked")
_Projected_co = TypeVar("_Projected_co", covariant=True)
_ProjectableClass = TypeVar("_ProjectableClass", bound="_DynWinRTProjectableClass")


class _DynWinRTProjector(Protocol[_Projected_co]):
    @classmethod
    def from_value(cls, obj: "DynWinRTValue") -> _Projected_co: ...


class _DynWinRTProjectableClass: ...


class _DynWinRTRuntimeClass(_DynWinRTProjectableClass): ...


__all__ = [
    "WinAppSDKContext",
    "RoApartment",
    "WinGUID",
    "DynWinRTType",
    "DynWinRTMethodSig",
    "DynWinRTMethodHandle",
    "DynWinRTOverrideInterface",
    "DynWinRTXamlRegistration",
    "DynWinRTValue",
    "DynWinRTArray",
    "DynWinRTStruct",
    "DynWinRtDelegate",
    "DynWinRtElementFactory",
    "WinRTAsync",
    "WinRTAsyncWithProgress",
    "WinRTCoroutine",
    "WinRTCoroutineWithProgress",
    "ProjectedLifetimeScope",
    "projected_lifetime_scope",
    "project_as",
    "release_projected",
    "unbox_object",
    "init_winappsdk",
    "ro_initialize",
    "ro_uninitialize",
    "register_xaml_runtime_class",
    "has_package_identity",
    "get_winappsdk_resource_pri_path",
    "get_computer_name",
]

@final
class WinAppSDKContext:
    def resource_pri_path(self) -> str: ...


@final
class RoApartment:
    def __new__(
        cls, apartment_type: Optional[int] = ...
    ) -> RoApartment: ...
    def __enter__(self) -> RoApartment: ...
    def __exit__(
        self, exc_type: object, exc_value: object, traceback: object
    ) -> Literal[False]: ...
    def close(self) -> None: ...
    def __repr__(self) -> str: ...

@final
class DynWinRTXamlRegistration:
    @property
    def name(self) -> Optional[str]: ...
    @property
    def active(self) -> bool: ...
    @property
    def supported_overrides(self) -> List[str]: ...
    def unregister(self) -> bool: ...
    def release_instances(self) -> int: ...
    def close(self) -> bool: ...
    def __enter__(self) -> DynWinRTXamlRegistration: ...
    def __exit__(
        self, exc_type: object, exc_value: object, traceback: object
    ) -> Literal[False]: ...

def register_xaml_runtime_class(
    runtime_class_name: str,
    base_type_name: str,
    base_iid: WinGUID,
    constructor: Callable[[], object],
    supported_overrides: Optional[Sequence[str]] = ...,
) -> DynWinRTXamlRegistration: ...


@final
class ProjectedLifetimeScope:
    @property
    def disposed(self) -> bool: ...
    def __enter__(self) -> ProjectedLifetimeScope: ...
    def __exit__(
        self, exc_type: object, exc_value: object, traceback: object
    ) -> Literal[False]: ...
    def track(
        self, value: _Tracked, type_name: Optional[str] = ...
    ) -> _Tracked: ...
    def close(self) -> None: ...


def projected_lifetime_scope() -> ProjectedLifetimeScope: ...

def project_as(
    value: object, wrapper_type: type[_ProjectableClass]
) -> _ProjectableClass: ...

def release_projected(value: object) -> None: ...

_UnboxedPropertyValue = Union[
    bool,
    int,
    float,
    str,
    UUID,
    bytes,
    List[int],
    List[float],
    List[bool],
    List[str],
    List[UUID],
]

@overload
def unbox_object(value: None) -> None: ...
@overload
def unbox_object(
    value: "DynWinRTValue",
) -> Union[_UnboxedPropertyValue, "DynWinRTValue", None]: ...


@final
class WinGUID:
    @staticmethod
    def parse(guid_str: str) -> WinGUID: ...
    def to_string(self) -> str: ...
    def __repr__(self) -> str: ...


@final
class DynWinRTType:
    @staticmethod
    def i8_type() -> DynWinRTType: ...
    @staticmethod
    def u8_type() -> DynWinRTType: ...
    @staticmethod
    def i16_type() -> DynWinRTType: ...
    @staticmethod
    def u16_type() -> DynWinRTType: ...
    @staticmethod
    def i32_type() -> DynWinRTType: ...
    @staticmethod
    def u32_type() -> DynWinRTType: ...
    @staticmethod
    def i64_type() -> DynWinRTType: ...
    @staticmethod
    def u64_type() -> DynWinRTType: ...
    @staticmethod
    def f32_type() -> DynWinRTType: ...
    @staticmethod
    def f64_type() -> DynWinRTType: ...
    @staticmethod
    def bool_type() -> DynWinRTType: ...
    @staticmethod
    def char16() -> DynWinRTType: ...
    @staticmethod
    def hstring() -> DynWinRTType: ...
    @staticmethod
    def guid_type() -> DynWinRTType: ...
    @staticmethod
    def object() -> DynWinRTType: ...
    @staticmethod
    def hresult() -> DynWinRTType: ...
    @staticmethod
    def runtime_class(
        name: str, default_interface_type: DynWinRTType
    ) -> DynWinRTType: ...
    @staticmethod
    def interface(iid: WinGUID) -> DynWinRTType: ...
    @staticmethod
    def delegate(iid: WinGUID) -> DynWinRTType: ...
    @staticmethod
    def i_async_action() -> DynWinRTType: ...
    @staticmethod
    def i_async_action_with_progress(progress_type: DynWinRTType) -> DynWinRTType: ...
    @staticmethod
    def i_async_operation(result_type: DynWinRTType) -> DynWinRTType: ...
    @staticmethod
    def i_async_operation_with_progress(
        result_type: DynWinRTType, progress_type: DynWinRTType
    ) -> DynWinRTType: ...
    @staticmethod
    def struct_type(name: str, fields: Sequence[DynWinRTType]) -> DynWinRTType: ...
    @staticmethod
    def enum_type(
        name: str,
        member_names: Optional[Sequence[str]] = ...,
        member_values: Optional[Sequence[int]] = ...,
    ) -> DynWinRTType: ...
    @staticmethod
    def get_enum_value(enum_name: str, member_name: str) -> Optional[int]: ...
    @staticmethod
    def parameterized(
        generic_iid: WinGUID, args: Sequence[DynWinRTType]
    ) -> DynWinRTType: ...
    @staticmethod
    def array_type(element_type: DynWinRTType) -> DynWinRTType: ...
    @staticmethod
    def register_interface(name: str, iid: WinGUID) -> DynWinRTType: ...
    def add_method(self, name: str, sig: DynWinRTMethodSig) -> DynWinRTType: ...
    def method(self, vtable_index: int) -> DynWinRTMethodHandle: ...
    def method_by_name(self, name: str) -> DynWinRTMethodHandle: ...
    def iid(self) -> WinGUID: ...
    def __repr__(self) -> str: ...


@final
class DynWinRTMethodSig:
    def __init__(self) -> None: ...
    def add_in(self, typ: DynWinRTType) -> DynWinRTMethodSig: ...
    def add_out(self, typ: DynWinRTType) -> DynWinRTMethodSig: ...
    def add_out_fill(self, typ: DynWinRTType) -> DynWinRTMethodSig: ...


@final
class DynWinRTOverrideInterface:
    def __new__(
        cls,
        iid: WinGUID,
        abi_shapes: Sequence[str],
        callbacks: Mapping[int, Callable[..., object]],
    ) -> DynWinRTOverrideInterface: ...


@final
class DynWinRTMethodHandle:
    def invoke(
        self, obj: DynWinRTValue, args: Sequence[DynWinRTValue]
    ) -> DynWinRTValue: ...
    def invoke_detached(
        self, obj: DynWinRTValue, args: Sequence[DynWinRTValue]
    ) -> DynWinRTValue: ...
    def invoke_all(
        self, obj: DynWinRTValue, args: Sequence[DynWinRTValue]
    ) -> List[DynWinRTValue]: ...
    def invoke_composed(
        self,
        factory: DynWinRTValue,
        args: Sequence[DynWinRTValue],
        outer_index: int,
        inner_output_index: int,
        instance_output_index: int,
        agile: bool,
    ) -> DynWinRTValue: ...
    def invoke_composed_with_overrides(
        self,
        factory: DynWinRTValue,
        args: Sequence[DynWinRTValue],
        outer_index: int,
        inner_output_index: int,
        instance_output_index: int,
        agile: bool,
        override_interfaces: Sequence[DynWinRTOverrideInterface],
    ) -> DynWinRTValue: ...
    def get_string(self, obj: DynWinRTValue) -> str: ...
    def get_i32(self, obj: DynWinRTValue) -> int: ...
    def get_bool(self, obj: DynWinRTValue) -> bool: ...
    def get_obj(self, obj: DynWinRTValue) -> DynWinRTValue: ...
    def invoke_hstring(self, obj: DynWinRTValue, arg: str) -> DynWinRTValue: ...
    def invoke_i32(self, obj: DynWinRTValue, arg: int) -> DynWinRTValue: ...


@final
class DynWinRTValue:
    @staticmethod
    def activation_factory(name: str) -> DynWinRTValue: ...
    @staticmethod
    def from_bytes(data: Union[bytes, bytearray]) -> DynWinRTValue: ...
    @staticmethod
    def create_xaml_application(
        metadata_provider: DynWinRTValue,
        launched_callback: Optional[DynWinRTValue] = ...,
    ) -> DynWinRTValue: ...
    @staticmethod
    def from_bool(value: bool) -> DynWinRTValue: ...
    @staticmethod
    def from_i8(value: int) -> DynWinRTValue: ...
    @staticmethod
    def from_u8(value: int) -> DynWinRTValue: ...
    @staticmethod
    def from_i16(value: int) -> DynWinRTValue: ...
    @staticmethod
    def from_u16(value: int) -> DynWinRTValue: ...
    @staticmethod
    def from_i32(value: int) -> DynWinRTValue: ...
    @staticmethod
    def from_u32(value: int) -> DynWinRTValue: ...
    @staticmethod
    def from_i64(value: int) -> DynWinRTValue: ...
    @staticmethod
    def from_u64(value: int) -> DynWinRTValue: ...
    @staticmethod
    def from_f32(value: float) -> DynWinRTValue: ...
    @staticmethod
    def from_f64(value: float) -> DynWinRTValue: ...
    @staticmethod
    def from_hstring(value: str) -> DynWinRTValue: ...
    @staticmethod
    def from_guid(value: WinGUID) -> DynWinRTValue: ...
    @staticmethod
    def null_value() -> DynWinRTValue: ...
    @staticmethod
    def enum_value(enum_type: DynWinRTType, value: int) -> DynWinRTValue: ...
    @staticmethod
    def box_reference(
        value: DynWinRTValue, value_type: DynWinRTType
    ) -> DynWinRTValue: ...
    @staticmethod
    def create_vector(
        items: Sequence[DynWinRTValue], element_type: DynWinRTType
    ) -> DynWinRTValue: ...
    @staticmethod
    def create_map(
        keys: Sequence[DynWinRTValue],
        values: Sequence[DynWinRTValue],
        key_type: DynWinRTType,
        value_type: DynWinRTType,
    ) -> DynWinRTValue: ...
    def get_enum_int(self) -> Optional[int]: ...
    def get_enum_name(self) -> Optional[str]: ...
    def wait(self) -> DynWinRTValue: ...
    def cancel(self) -> None: ...
    def on_progress(self, callback: Callable[[DynWinRTValue], object]) -> None: ...
    def to_string(self) -> str: ...
    def to_number(self) -> int: ...
    def to_int(self) -> int: ...
    def to_float(self) -> float: ...
    def to_bool(self) -> bool: ...
    def to_i64(self) -> int: ...
    def to_u32(self) -> int: ...
    def to_u64(self) -> int: ...
    def to_f64(self) -> float: ...
    def to_guid(self) -> WinGUID: ...
    def to_bytes(self) -> bytes: ...
    def is_null(self) -> bool: ...
    def release(self) -> None: ...
    def as_raw(self) -> int: ...
    def identity_raw(self) -> int: ...
    def cast(self, iid: WinGUID) -> DynWinRTValue: ...
    def activate(self) -> DynWinRTValue: ...
    def call_0(
        self, method_index: int, return_type: DynWinRTType
    ) -> DynWinRTValue: ...
    def call_1(
        self,
        method_index: int,
        return_type: DynWinRTType,
        v1: DynWinRTValue,
    ) -> DynWinRTValue: ...
    def call(
        self,
        method_index: int,
        return_type: DynWinRTType,
        in_types: Sequence[DynWinRTType],
        args: Sequence[DynWinRTValue],
    ) -> DynWinRTValue: ...
    def is_array(self) -> bool: ...
    def as_array(self) -> DynWinRTArray: ...
    def is_struct(self) -> bool: ...
    def as_struct(self) -> DynWinRTStruct: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...


class WinRTAsync(Awaitable[_T], Protocol[_T]):
    def wait(self) -> _T: ...
    def cancel(self) -> None: ...
    def release(self) -> None: ...


class WinRTAsyncWithProgress(WinRTAsync[_T], Protocol[_T, _P]):
    def progress(self, callback: Callable[[_P], object]) -> None: ...


class WinRTCoroutine(  # type: ignore[misc]
    WinRTAsync[_T], Coroutine[Any, Any, _T], Protocol[_T]
): ...


class WinRTCoroutineWithProgress(
    WinRTAsyncWithProgress[_T, _P],
    WinRTCoroutine[_T],
    Protocol[_T, _P],
): ...


@final
class DynWinRTArray:
    def __len__(self) -> int: ...
    def get(self, index: int) -> DynWinRTValue: ...
    def to_values(self) -> List[DynWinRTValue]: ...
    def to_i8_list(self) -> List[int]: ...
    def to_u8_list(self) -> bytes: ...
    def to_i16_list(self) -> List[int]: ...
    def to_u16_list(self) -> List[int]: ...
    def to_i32_list(self) -> List[int]: ...
    def to_u32_list(self) -> List[int]: ...
    def to_f32_list(self) -> List[float]: ...
    def to_f64_list(self) -> List[float]: ...
    def to_i64_list(self) -> List[int]: ...
    def to_u64_list(self) -> List[int]: ...
    def to_string_list(self) -> List[str]: ...
    @staticmethod
    def from_i8_values(values: Sequence[int]) -> DynWinRTArray: ...
    @staticmethod
    def from_u8_values(values: Sequence[int]) -> DynWinRTArray: ...
    @staticmethod
    def from_i16_values(values: Sequence[int]) -> DynWinRTArray: ...
    @staticmethod
    def from_u16_values(values: Sequence[int]) -> DynWinRTArray: ...
    @staticmethod
    def from_i32_values(values: Sequence[int]) -> DynWinRTArray: ...
    @staticmethod
    def from_u32_values(values: Sequence[int]) -> DynWinRTArray: ...
    @staticmethod
    def from_f32_values(values: Sequence[float]) -> DynWinRTArray: ...
    @staticmethod
    def from_f64_values(values: Sequence[float]) -> DynWinRTArray: ...
    @staticmethod
    def from_i64_values(values: Sequence[int]) -> DynWinRTArray: ...
    @staticmethod
    def from_u64_values(values: Sequence[int]) -> DynWinRTArray: ...
    @staticmethod
    def from_string_values(values: Sequence[str]) -> DynWinRTArray: ...
    @staticmethod
    def from_values(
        values: Sequence[DynWinRTValue], element_type: DynWinRTType
    ) -> DynWinRTArray: ...
    @staticmethod
    def from_object_values(
        values: Sequence[DynWinRTValue], element_type: DynWinRTType
    ) -> DynWinRTArray: ...
    def to_bytes(self) -> bytes: ...
    @staticmethod
    def from_bytes(data: Union[bytes, bytearray]) -> DynWinRTArray: ...
    def to_value(self) -> DynWinRTValue: ...
    def __repr__(self) -> str: ...


@final
class DynWinRTStruct:
    @staticmethod
    def create(typ: DynWinRTType) -> DynWinRTStruct: ...
    def get_i8(self, index: int) -> int: ...
    def set_i8(self, index: int, value: int) -> None: ...
    def get_u8(self, index: int) -> int: ...
    def set_u8(self, index: int, value: int) -> None: ...
    def get_i16(self, index: int) -> int: ...
    def set_i16(self, index: int, value: int) -> None: ...
    def get_u16(self, index: int) -> int: ...
    def set_u16(self, index: int, value: int) -> None: ...
    def get_i32(self, index: int) -> int: ...
    def set_i32(self, index: int, value: int) -> None: ...
    def get_u32(self, index: int) -> int: ...
    def set_u32(self, index: int, value: int) -> None: ...
    def get_f32(self, index: int) -> float: ...
    def set_f32(self, index: int, value: float) -> None: ...
    def get_f64(self, index: int) -> float: ...
    def set_f64(self, index: int, value: float) -> None: ...
    def get_i64(self, index: int) -> int: ...
    def set_i64(self, index: int, value: int) -> None: ...
    def get_u64(self, index: int) -> int: ...
    def set_u64(self, index: int, value: int) -> None: ...
    def get_hstring(self, index: int) -> str: ...
    def set_hstring(self, index: int, value: str) -> None: ...
    def get_guid(self, index: int) -> WinGUID: ...
    def set_guid(self, index: int, value: WinGUID) -> None: ...
    def get_struct(self, index: int) -> DynWinRTStruct: ...
    def set_struct(self, index: int, value: DynWinRTStruct) -> None: ...
    def get_object(self, index: int) -> DynWinRTValue: ...
    def set_object(self, index: int, value: DynWinRTValue) -> None: ...
    def to_value(self) -> DynWinRTValue: ...
    def __repr__(self) -> str: ...


@final
class DynWinRtDelegate:
    @staticmethod
    def create(
        iid: WinGUID,
        param_types: Sequence[DynWinRTType],
        callback: Callable[..., object],
    ) -> DynWinRtDelegate: ...
    def to_value(self) -> DynWinRTValue: ...


@final
class DynWinRtElementFactory:
    @staticmethod
    def create(
        element_iid: WinGUID,
        get_element: Callable[[DynWinRTValue], DynWinRTValue],
        recycle_element: Callable[[DynWinRTValue], object],
    ) -> DynWinRtElementFactory: ...
    def to_value(self) -> DynWinRTValue: ...
    def release_callbacks(self) -> None: ...
    def release(self) -> None: ...
    def __repr__(self) -> str: ...


def init_winappsdk(major: int, minor: int) -> WinAppSDKContext: ...
def ro_initialize(apartment_type: Optional[int]) -> None: ...
def ro_uninitialize() -> None: ...
def has_package_identity() -> bool: ...
def get_winappsdk_resource_pri_path() -> str: ...
def get_computer_name() -> str: ...
