[build-system]
requires = ["maturin>=1.11,<2.0"]
build-backend = "maturin"

[project]
name = "dynwinrt"
description = "Python bindings for dynamic WinRT API invocation"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.11,<3.15"
license = {text = "MIT"}
authors = [
    {name = "Microsoft"},
]
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "License :: OSI Approved :: MIT License",
    "Operating System :: Microsoft :: Windows",
]
dynamic = ["version"]

[project.urls]
Homepage = "https://github.com/microsoft/dynwinrt"
Repository = "https://github.com/microsoft/dynwinrt"
Issues = "https://github.com/microsoft/dynwinrt/issues"

[dependency-groups]
dev = [
    "maturin>=1.11.5",
    "mypy>=1.13,<2",
    "pytest>=8.3.5",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-ra -q"     # Shows extra summary info, keeps output quiet
