// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, WinGuid } from '@microsoft/dynwinrt';
import { DataTransferManager } from './DataTransferManager.js';

export const IID_IDataTransferManagerInterop = WinGuid.parse('3a3dcd6c-3eab-43dc-bcde-45671ce800c8');
const IID_DataTransferManager_default = WinGuid.parse('a5caee9b-8708-49d1-8d36-67d25a8da00c');

let _IDataTransferManagerInteropCache;
const _IDataTransferManagerInterop = new Proxy({}, {
    get(_target, prop) {
        _IDataTransferManagerInteropCache ??= DynWinRtType.registerInterfaceUnknown('IDataTransferManagerInterop', IID_IDataTransferManagerInterop)
            .addMethod('GetForWindow', new DynWinRtMethodSig().addIn(DynWinRtType.pointer()).addIn(DynWinRtType.pointer()).addOut(DynWinRtType.pointer()))
            .addMethod('ShowShareUIForWindow', new DynWinRtMethodSig().addIn(DynWinRtType.pointer()));
        const value = _IDataTransferManagerInteropCache[prop];
        return typeof value === 'function' ? value.bind(_IDataTransferManagerInteropCache) : value;
    },
});

export class IDataTransferManagerInterop {
    _obj;
    constructor(obj) { this._obj = obj; }
    static _fromNative(obj) { return new IDataTransferManagerInterop(obj); }
    /** Create a new `IDataTransferManagerInterop` by activating the `Windows.ApplicationModel.DataTransfer.DataTransferManager` factory and QI'ing to the interop. */
    static create() {
        const factory = DynWinRtValue.activationFactory('Windows.ApplicationModel.DataTransfer.DataTransferManager');
        const _obj = factory.cast(IID_IDataTransferManagerInterop);
        return new IDataTransferManagerInterop(_obj);
    }
    getForWindow(appWindow) {
        const _out = _IDataTransferManagerInterop.method(3).invoke(this._obj, [DynWinRtValue.pointer(appWindow), DynWinRtValue.iidPointer(IID_DataTransferManager_default)]);
        return DataTransferManager._fromNative(_out);
    }
    showShareUIForWindow(appWindow) {
        _IDataTransferManagerInterop.method(4).invoke(this._obj, [DynWinRtValue.pointer(appWindow)]);
    }
}
