// Generated by dynwinrt-codegen — do not edit
import type { WinGuid } from '@microsoft/dynwinrt/com';
import type { DynWinRtValue } from '@microsoft/dynwinrt/com';

/** Opaque Win32 handle value. Pass a raw pointer value as a `bigint` (full pointer width) or `number` (safe integer). */
export type HWND = bigint | number;

export declare const IID_IDataTransferManagerInterop: WinGuid;

export declare class IDataTransferManagerInterop {
    static readonly IID: typeof IID_IDataTransferManagerInterop;
    protected constructor(obj: unknown);
    /** Activate the projected WinRT class and QI to the interop.
     * `initializeCom()` must be called once (e.g. at process startup) before this is used. */
    static create(): IDataTransferManagerInterop;
    /** Wrap an existing native COM pointer (for QueryInterface bridging). */
    static _fromNative(obj: unknown): IDataTransferManagerInterop;
    /** Release the underlying native COM reference. Safe to call more than once. */
    release(): void;
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-idatatransfermanagerinterop-getforwindow} */
    getForWindow(appWindow: HWND | Buffer | Uint8Array): DynWinRtValue;
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-idatatransfermanagerinterop-showshareuiforwindow} */
    showShareUIForWindow(appWindow: HWND | Buffer | Uint8Array): void;
}
