// Generated by dynwinrt-codegen — do not edit
import type { DynComImplementation, WinGuid } from '@microsoft/dynwinrt/com';
import type { DynWinRtValue } from '@microsoft/dynwinrt/com';

/** Opaque Win32 handle value. Pass a raw pointer value as a `bigint` (full pointer width) or `number` (safe integer). */
export type HWND = bigint | number;

export interface ITaskbarListImplementation {
    hrInit: () => void | number;
    addTab: (hwnd: HWND | Buffer | Uint8Array) => void | number;
    deleteTab: (hwnd: HWND | Buffer | Uint8Array) => void | number;
    activateTab: (hwnd: HWND | Buffer | Uint8Array) => void | number;
    setActiveAlt: (hwnd: HWND | Buffer | Uint8Array) => void | number;
}

export declare const IID_ITaskbarList: WinGuid;

export declare class ITaskbarList {
    static readonly IID: typeof IID_ITaskbarList;
    protected constructor(obj: unknown);
    /** Wrap an existing native COM pointer (for QueryInterface bridging). */
    static _fromNative(obj: unknown): ITaskbarList;
    /** Borrowed native value for passing this implementation to generated COM methods. Do not release it separately. */
    readonly nativeValue: DynWinRtValue;
    /** Query another generated interface implemented by the same COM identity. */
    as<T>(InterfaceClass: { readonly IID: unknown; _fromNative(obj: unknown): T }): T;
    /** Describe this interface implementation for composition with other generated interfaces. */
    static implementation(handlers: ITaskbarListImplementation): DynComImplementation;
    /** Create an apartment-bound COM object, optionally implementing additional generated interfaces. */
    static implement(handlers: ITaskbarListImplementation, ...additional: DynComImplementation[]): ITaskbarList;
    /** Release the underlying native COM reference. Safe to call more than once. */
    release(): void;
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-itaskbarlist-hrinit} */
    hrInit(): void;
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-itaskbarlist-addtab} */
    addTab(hwnd: HWND | Buffer | Uint8Array): void;
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-itaskbarlist-deletetab} */
    deleteTab(hwnd: HWND | Buffer | Uint8Array): void;
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-itaskbarlist-activatetab} */
    activateTab(hwnd: HWND | Buffer | Uint8Array): void;
    /** @see {@link https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-itaskbarlist-setactivealt} */
    setActiveAlt(hwnd: HWND | Buffer | Uint8Array): void;
}
