# Generated by dynwinrt-codegen — do not edit
from __future__ import annotations
from ._runtime import (
    Callable, Iterable, Iterator, Mapping, MutableMapping, MutableSequence, Sequence,
    TYPE_CHECKING, UUID, WinGUID, datetime, timedelta,
    DynWinRTType, DynWinRTMethodSig, DynWinRTValue, DynWinRTArray,
    DynWinRTStruct, DynWinRtDelegate, DynWinRTOverrideInterface,
    _property, _weakref_ref,
    _dynwinrt_array, _dynwinrt_bind_overload, _dynwinrt_can_cast, _dynwinrt_create_delegate,
    _dynwinrt_datetime_to_ticks, _dynwinrt_delegate, _dynwinrt_enum, _dynwinrt_guid,
    _dynwinrt_map, _dynwinrt_new_vector, _dynwinrt_ticks_to_datetime,
    _dynwinrt_ticks_to_timedelta, _dynwinrt_timedelta_to_ticks,
    _dynwinrt_cache_projected, _dynwinrt_projected_from_native,
    _dynwinrt_symbol, _dynwinrt_track_projected, _dynwinrt_uuid,
    _dynwinrt_vector, _dynwinrt_wrap_values,
)
from dynwinrt import WinRTCoroutine, WinRTCoroutineWithProgress
from dynwinrt.dynwinrt import _DynWinRTAsync, _DynWinRTAsyncWithProgress

if TYPE_CHECKING:
    from .windows__storage__streams__byte_order import ByteOrder  # noqa: F401
    from .windows__storage__streams__i_buffer import IID_IBuffer, IBuffer  # noqa: F401
    from .windows__storage__streams__i_output_stream import IID_IOutputStream, IOutputStream  # noqa: F401
    from .windows__storage__streams__unicode_encoding import UnicodeEncoding  # noqa: F401

IID_IDataWriter = WinGUID.parse('64b89265-d341-4922-b38a-dd4af8808c4e')
IID_IDataWriterFactory = WinGUID.parse('338c67c2-8b84-4c2b-9c50-7b8767847a1f')
IID_IClosable = WinGUID.parse('30d5a829-7fa4-4026-83bb-d75bae4ea99e')

_IDataWriter = DynWinRTType.register_interface(
    "IDataWriter", IID_IDataWriter) \
    .add_method("get_UnstoredBufferLength", DynWinRTMethodSig().add_out(DynWinRTType.u32_type())) \
    .add_method("get_UnicodeEncoding", DynWinRTMethodSig().add_out(DynWinRTType.enum_type('Windows.Storage.Streams.UnicodeEncoding', ['Utf8', 'Utf16LE', 'Utf16BE'], [0, 1, 2]))) \
    .add_method("put_UnicodeEncoding", DynWinRTMethodSig().add_in(DynWinRTType.enum_type('Windows.Storage.Streams.UnicodeEncoding', ['Utf8', 'Utf16LE', 'Utf16BE'], [0, 1, 2]))) \
    .add_method("get_ByteOrder", DynWinRTMethodSig().add_out(DynWinRTType.enum_type('Windows.Storage.Streams.ByteOrder', ['LittleEndian', 'BigEndian'], [0, 1]))) \
    .add_method("put_ByteOrder", DynWinRTMethodSig().add_in(DynWinRTType.enum_type('Windows.Storage.Streams.ByteOrder', ['LittleEndian', 'BigEndian'], [0, 1]))) \
    .add_method("WriteByte", DynWinRTMethodSig().add_in(DynWinRTType.u8_type())) \
    .add_method("WriteBytes", DynWinRTMethodSig().add_in(DynWinRTType.array_type(DynWinRTType.u8_type()))) \
    .add_method("WriteBuffer", DynWinRTMethodSig().add_in(DynWinRTType.interface(WinGUID.parse('905a0fe0-bc53-11df-8c49-001e4fc686da')))) \
    .add_method("WriteBufferRange", DynWinRTMethodSig().add_in(DynWinRTType.interface(WinGUID.parse('905a0fe0-bc53-11df-8c49-001e4fc686da'))).add_in(DynWinRTType.u32_type()).add_in(DynWinRTType.u32_type())) \
    .add_method("WriteBoolean", DynWinRTMethodSig().add_in(DynWinRTType.bool_type())) \
    .add_method("WriteGuid", DynWinRTMethodSig().add_in(DynWinRTType.guid_type())) \
    .add_method("WriteInt16", DynWinRTMethodSig().add_in(DynWinRTType.i16_type())) \
    .add_method("WriteInt32", DynWinRTMethodSig().add_in(DynWinRTType.i32_type())) \
    .add_method("WriteInt64", DynWinRTMethodSig().add_in(DynWinRTType.i64_type())) \
    .add_method("WriteUInt16", DynWinRTMethodSig().add_in(DynWinRTType.u16_type())) \
    .add_method("WriteUInt32", DynWinRTMethodSig().add_in(DynWinRTType.u32_type())) \
    .add_method("WriteUInt64", DynWinRTMethodSig().add_in(DynWinRTType.u64_type())) \
    .add_method("WriteSingle", DynWinRTMethodSig().add_in(DynWinRTType.f32_type())) \
    .add_method("WriteDouble", DynWinRTMethodSig().add_in(DynWinRTType.f64_type())) \
    .add_method("WriteDateTime", DynWinRTMethodSig().add_in(DynWinRTType.struct_type('Windows.Foundation.DateTime', [DynWinRTType.i64_type()]))) \
    .add_method("WriteTimeSpan", DynWinRTMethodSig().add_in(DynWinRTType.struct_type('Windows.Foundation.TimeSpan', [DynWinRTType.i64_type()]))) \
    .add_method("WriteString", DynWinRTMethodSig().add_in(DynWinRTType.hstring()).add_out(DynWinRTType.u32_type())) \
    .add_method("MeasureString", DynWinRTMethodSig().add_in(DynWinRTType.hstring()).add_out(DynWinRTType.u32_type())) \
    .add_method("StoreAsync", DynWinRTMethodSig().add_out(DynWinRTType.i_async_operation(DynWinRTType.u32_type()))) \
    .add_method("FlushAsync", DynWinRTMethodSig().add_out(DynWinRTType.i_async_operation(DynWinRTType.bool_type()))) \
    .add_method("DetachBuffer", DynWinRTMethodSig().add_out(DynWinRTType.interface(WinGUID.parse('905a0fe0-bc53-11df-8c49-001e4fc686da')))) \
    .add_method("DetachStream", DynWinRTMethodSig().add_out(DynWinRTType.interface(WinGUID.parse('905a0fe6-bc53-11df-8c49-001e4fc686da'))))

_IDataWriterFactory = DynWinRTType.register_interface(
    "IDataWriterFactory", IID_IDataWriterFactory) \
    .add_method("CreateDataWriter", DynWinRTMethodSig().add_in(DynWinRTType.interface(WinGUID.parse('905a0fe6-bc53-11df-8c49-001e4fc686da'))).add_out(DynWinRTType.runtime_class('Windows.Storage.Streams.DataWriter', DynWinRTType.interface(WinGUID.parse('64b89265-d341-4922-b38a-dd4af8808c4e')))))

_IClosable = DynWinRTType.register_interface(
    "IClosable", IID_IClosable) \
    .add_method("Close", DynWinRTMethodSig())

_IActivationFactory = DynWinRTType.register_interface(
    'IActivationFactory', WinGUID.parse('00000035-0000-0000-c000-000000000046')) \
    .add_method('ActivateInstance', DynWinRTMethodSig().add_out(DynWinRTType.object()))


def unpack_date_time(v: DynWinRTValue) -> datetime:
    return _dynwinrt_ticks_to_datetime(v.as_struct().get_i64(0))
_unpack_date_time = unpack_date_time
DateTime_TYPE = DynWinRTType.struct_type('Windows.Foundation.DateTime', [DynWinRTType.i64_type()])
_DateTime_TYPE = DateTime_TYPE

def pack_date_time(v: datetime) -> DynWinRTStruct:
    s = DynWinRTStruct.create(DateTime_TYPE)
    s.set_i64(0, _dynwinrt_datetime_to_ticks(v))
    return s
_pack_date_time = pack_date_time


def unpack_time_span(v: DynWinRTValue) -> timedelta:
    return _dynwinrt_ticks_to_timedelta(v.as_struct().get_i64(0))
_unpack_time_span = unpack_time_span
TimeSpan_TYPE = DynWinRTType.struct_type('Windows.Foundation.TimeSpan', [DynWinRTType.i64_type()])
_TimeSpan_TYPE = TimeSpan_TYPE

def pack_time_span(v: timedelta) -> DynWinRTStruct:
    s = DynWinRTStruct.create(TimeSpan_TYPE)
    s.set_i64(0, _dynwinrt_timedelta_to_ticks(v))
    return s
_pack_time_span = pack_time_span


class DataWriter:
    _dynwinrt_runtime_class_type = True
    def __new__(cls, *args, **kwargs):
        if len(args) == 1 and not kwargs and isinstance(args[0], DynWinRTValue):
            return _dynwinrt_projected_from_native(cls, args[0], '_set_native')
        if cls is DataWriter:
            _bound = _dynwinrt_bind_overload((), args, kwargs)
            if _bound is not None:
                return cls.create_default()
            _bound = _dynwinrt_bind_overload(('output_stream',), args, kwargs)
            if _bound is not None and isinstance(_bound[0], _dynwinrt_symbol('windows__storage__streams__i_output_stream', 'IOutputStream')):
                return cls.create_data_writer(_bound[0])
        return super().__new__(cls)

    def _set_native(self, obj: DynWinRTValue):
        self._obj = obj.cast(IID_IDataWriter)
        self._closed = False
        self._dynwinrt_native_ready = True
        _dynwinrt_track_projected(self, 'Windows.Storage.Streams.DataWriter')
        _dynwinrt_cache_projected(self)

    @classmethod
    def _from_native(cls, obj: DynWinRTValue):
        return cls(obj)

    def __init__(self, *args, **kwargs):
        if getattr(self, '_dynwinrt_native_ready', False):
            return
        if len(args) == 1 and not kwargs and isinstance(args[0], DynWinRTValue):
            self._set_native(args[0])
            return
        _bound = _dynwinrt_bind_overload((), args, kwargs)
        if _bound is not None:
            self._set_native(type(self).create_default()._obj)
            return
        _bound = _dynwinrt_bind_overload(('output_stream',), args, kwargs)
        if _bound is not None and isinstance(_bound[0], _dynwinrt_symbol('windows__storage__streams__i_output_stream', 'IOutputStream')):
            self._set_native(type(self).create_data_writer(_bound[0])._obj)
            return
        raise TypeError("No matching constructor for DataWriter")

    @staticmethod
    def _get_f_IDataWriterFactory():
        return DynWinRTValue.activation_factory('Windows.Storage.Streams.DataWriter').cast(IID_IDataWriterFactory)

    @staticmethod
    def create_default() -> 'DataWriter':
        return DataWriter._from_native(_IActivationFactory.method(6).invoke(DynWinRTValue.activation_factory('Windows.Storage.Streams.DataWriter'), []))


    @staticmethod
    def create_data_writer(output_stream: 'IOutputStream') -> 'DataWriter':
        return DataWriter._from_native(_IDataWriterFactory.method(6).invoke(DataWriter._get_f_IDataWriterFactory(), [getattr(output_stream, '_obj', output_stream)]))

    @_property
    def unstored_buffer_length(self) -> int:
        return _IDataWriter.method(6).invoke(self._obj, []).to_u32()

    @_property
    def unicode_encoding(self) -> 'UnicodeEncoding':
        return _dynwinrt_enum('windows__storage__streams__unicode_encoding', 'UnicodeEncoding', _IDataWriter.method(7).invoke(self._obj, []).to_number())

    @_property
    def byte_order(self) -> 'ByteOrder':
        return _dynwinrt_enum('windows__storage__streams__byte_order', 'ByteOrder', _IDataWriter.method(9).invoke(self._obj, []).to_number())

    def write_byte(self, value: int) -> None:
        _IDataWriter.method(11).invoke(self._obj, [DynWinRTValue.from_u8(value)])

    def write_bytes(self, value: DynWinRTArray | bytes | bytearray | Sequence[int]) -> None:
        _IDataWriter.method(12).invoke(self._obj, [_dynwinrt_array(value, lambda item: DynWinRTValue.from_u8(item), DynWinRTType.u8_type(), True)])

    def write_buffer(self, buffer: 'IBuffer') -> None:
        _IDataWriter.method(13).invoke(self._obj, [getattr(buffer, '_obj', buffer)])

    def write_buffer_range(self, buffer: 'IBuffer', start: int, count: int) -> None:
        _IDataWriter.method(14).invoke(self._obj, [getattr(buffer, '_obj', buffer), DynWinRTValue.from_u32(start), DynWinRTValue.from_u32(count)])

    def write_boolean(self, value: bool) -> None:
        _IDataWriter.method(15).invoke(self._obj, [DynWinRTValue.from_bool(value)])

    def write_guid(self, value: UUID) -> None:
        _IDataWriter.method(16).invoke(self._obj, [DynWinRTValue.from_guid(_dynwinrt_guid(value))])

    def write_int16(self, value: int) -> None:
        _IDataWriter.method(17).invoke(self._obj, [DynWinRTValue.from_i16(value)])

    def write_int32(self, value: int) -> None:
        _IDataWriter.method(18).invoke(self._obj, [DynWinRTValue.from_i32(value)])

    def write_int64(self, value: int) -> None:
        _IDataWriter.method(19).invoke(self._obj, [DynWinRTValue.from_i64(value)])

    def write_uint16(self, value: int) -> None:
        _IDataWriter.method(20).invoke(self._obj, [DynWinRTValue.from_u16(value)])

    def write_uint32(self, value: int) -> None:
        _IDataWriter.method(21).invoke(self._obj, [DynWinRTValue.from_u32(value)])

    def write_uint64(self, value: int) -> None:
        _IDataWriter.method(22).invoke(self._obj, [DynWinRTValue.from_u64(value)])

    def write_single(self, value: float) -> None:
        _IDataWriter.method(23).invoke(self._obj, [DynWinRTValue.from_f32(value)])

    def write_double(self, value: float) -> None:
        _IDataWriter.method(24).invoke(self._obj, [DynWinRTValue.from_f64(value)])

    def write_date_time(self, value: datetime) -> None:
        _IDataWriter.method(25).invoke(self._obj, [_pack_date_time(value).to_value()])

    def write_time_span(self, value: timedelta) -> None:
        _IDataWriter.method(26).invoke(self._obj, [_pack_time_span(value).to_value()])

    def write_string(self, value: str) -> int:
        return _IDataWriter.method(27).invoke(self._obj, [DynWinRTValue.from_hstring(value)]).to_u32()

    def measure_string(self, value: str) -> int:
        return _IDataWriter.method(28).invoke(self._obj, [DynWinRTValue.from_hstring(value)]).to_u32()

    def store_async(self) -> WinRTCoroutine[int]:
        return _dynwinrt_track_projected(_DynWinRTAsync(_IDataWriter.method(29).invoke(self._obj, []), lambda value: value.to_u32()), 'WinRTAsync')

    def flush_async(self) -> WinRTCoroutine[bool]:
        return _dynwinrt_track_projected(_DynWinRTAsync(_IDataWriter.method(30).invoke(self._obj, []), lambda value: value.to_bool()), 'WinRTAsync')

    def detach_buffer(self) -> IBuffer | None:
        return (lambda value: None if value.is_null() else _dynwinrt_symbol('windows__storage__streams__i_buffer', 'IBuffer')(value))(_IDataWriter.method(31).invoke(self._obj, []))

    def detach_stream(self) -> IOutputStream | None:
        return (lambda value: None if value.is_null() else _dynwinrt_symbol('windows__storage__streams__i_output_stream', 'IOutputStream')(value))(_IDataWriter.method(32).invoke(self._obj, []))

    @unicode_encoding.setter
    def unicode_encoding(self, value: 'UnicodeEncoding'):
        _IDataWriter.method(8).invoke(self._obj, [DynWinRTValue.enum_value(DynWinRTType.enum_type('Windows.Storage.Streams.UnicodeEncoding', ['Utf8', 'Utf16LE', 'Utf16BE'], [0, 1, 2]), int(value))])

    @byte_order.setter
    def byte_order(self, value: 'ByteOrder'):
        _IDataWriter.method(10).invoke(self._obj, [DynWinRTValue.enum_value(DynWinRTType.enum_type('Windows.Storage.Streams.ByteOrder', ['LittleEndian', 'BigEndian'], [0, 1]), int(value))])

    def close(self):
        if self._closed:
            return
        _dynwinrt_symbol('windows__foundation__i_closable', 'IClosable').from_value(self._obj).close()
        self._closed = True

    def __enter__(self):
        if self._closed:
            raise RuntimeError('cannot enter a closed WinRT object')
        return self

    def __exit__(self, _exc_type, _exc_value, _traceback):
        self.close()
        return False

    def as_interface(self, interface_class):
        return interface_class.from_value(self._obj)


class IClosable:
    _dynwinrt_interface_type = True
    _dynwinrt_interface_iid = IID_IClosable
    def __new__(cls, *args, **kwargs):
        if len(args) == 1 and not kwargs and isinstance(args[0], DynWinRTValue):
            return _dynwinrt_projected_from_native(cls, args[0], '_set_native')
        return super().__new__(cls)

    def _set_native(self, obj: DynWinRTValue):
        self._obj = obj.cast(IID_IClosable)
        self._dynwinrt_native_ready = True
        _dynwinrt_track_projected(self, 'Windows.Foundation.IClosable')
        _dynwinrt_cache_projected(self)

    def __init__(self, obj: DynWinRTValue):
        if getattr(self, '_dynwinrt_native_ready', False):
            return
        IClosable._set_native(self, obj)

    @classmethod
    def _from_native(cls, obj: DynWinRTValue) -> 'IClosable':
        return cls(obj)

    @classmethod
    def from_value(cls, obj: DynWinRTValue) -> 'IClosable':
        return cls._from_native(obj.cast(IID_IClosable))

    def as_interface(self, interface_class):
        return interface_class.from_value(self._obj)

    def close(self) -> None:
        _IClosable.method(6).invoke(self._obj, [])
