# Generated by dynwinrt-codegen — do not edit
from __future__ import annotations
from ._runtime import (
    Callable, Iterable, Iterator, Mapping, MutableMapping, MutableSequence, Sequence,
    TYPE_CHECKING, UUID, WinGUID, datetime, timedelta,
    DynWinRTType, DynWinRTMethodSig, DynWinRTValue, DynWinRTArray,
    DynWinRTStruct, DynWinRtDelegate, DynWinRTOverrideInterface,
    _property, _weakref_ref,
    _dynwinrt_array, _dynwinrt_bind_overload, _dynwinrt_can_cast, _dynwinrt_create_delegate,
    _dynwinrt_datetime_to_ticks, _dynwinrt_delegate, _dynwinrt_enum, _dynwinrt_guid,
    _dynwinrt_map, _dynwinrt_new_vector, _dynwinrt_ticks_to_datetime,
    _dynwinrt_ticks_to_timedelta, _dynwinrt_timedelta_to_ticks,
    _dynwinrt_cache_projected, _dynwinrt_projected_from_native,
    _dynwinrt_symbol, _dynwinrt_track_projected, _dynwinrt_uuid,
    _dynwinrt_vector, _dynwinrt_wrap_values,
)
from dynwinrt.dynwinrt import _WinRTIteratorMixin

if TYPE_CHECKING:
    from .windows__foundation__i_www_form_url_decoder_entry import IID_IWwwFormUrlDecoderEntry, IWwwFormUrlDecoderEntry  # noqa: F401

IID_IIterator_IWwwFormUrlDecoderEntry = DynWinRTType.parameterized(WinGUID.parse('6a79e863-4300-459a-9966-cbb660963ee1'), [DynWinRTType.interface(WinGUID.parse('125e7431-f678-4e8e-b670-20a9b06c512d'))]).iid()

_IIterator_IWwwFormUrlDecoderEntry = DynWinRTType.register_interface(
    "IIterator_IWwwFormUrlDecoderEntry", IID_IIterator_IWwwFormUrlDecoderEntry) \
    .add_method("get_Current", DynWinRTMethodSig().add_out(DynWinRTType.interface(WinGUID.parse('125e7431-f678-4e8e-b670-20a9b06c512d')))) \
    .add_method("get_HasCurrent", DynWinRTMethodSig().add_out(DynWinRTType.bool_type())) \
    .add_method("MoveNext", DynWinRTMethodSig().add_out(DynWinRTType.bool_type())) \
    .add_method("GetMany", DynWinRTMethodSig().add_out_fill(DynWinRTType.array_type(DynWinRTType.interface(WinGUID.parse('125e7431-f678-4e8e-b670-20a9b06c512d')))).add_out(DynWinRTType.u32_type()))


class IIterator_IWwwFormUrlDecoderEntry(_WinRTIteratorMixin):
    _dynwinrt_interface_type = True
    _dynwinrt_interface_iid = IID_IIterator_IWwwFormUrlDecoderEntry
    def __new__(cls, *args, **kwargs):
        if len(args) == 1 and not kwargs and isinstance(args[0], DynWinRTValue):
            return _dynwinrt_projected_from_native(cls, args[0], '_set_native')
        return super().__new__(cls)

    def _set_native(self, obj: DynWinRTValue):
        self._obj = obj.cast(IID_IIterator_IWwwFormUrlDecoderEntry)
        self._dynwinrt_native_ready = True
        _dynwinrt_track_projected(self, 'Windows.Foundation.Collections.IIterator_IWwwFormUrlDecoderEntry')
        _dynwinrt_cache_projected(self)

    def __init__(self, obj: DynWinRTValue):
        if getattr(self, '_dynwinrt_native_ready', False):
            return
        IIterator_IWwwFormUrlDecoderEntry._set_native(self, obj)

    @classmethod
    def _from_native(cls, obj: DynWinRTValue) -> 'IIterator_IWwwFormUrlDecoderEntry':
        return cls(obj)

    @classmethod
    def from_value(cls, obj: DynWinRTValue) -> 'IIterator_IWwwFormUrlDecoderEntry':
        return cls._from_native(obj.cast(IID_IIterator_IWwwFormUrlDecoderEntry))

    def as_interface(self, interface_class):
        return interface_class.from_value(self._obj)


    @_property
    def current(self) -> IWwwFormUrlDecoderEntry | None:
        return (lambda value: None if value.is_null() else _dynwinrt_symbol('windows__foundation__i_www_form_url_decoder_entry', 'IWwwFormUrlDecoderEntry')(value))(_IIterator_IWwwFormUrlDecoderEntry.method(6).invoke(self._obj, []))

    @_property
    def has_current(self) -> bool:
        return _IIterator_IWwwFormUrlDecoderEntry.method(7).invoke(self._obj, []).to_bool()

    def move_next(self) -> bool:
        return _IIterator_IWwwFormUrlDecoderEntry.method(8).invoke(self._obj, []).to_bool()

    def get_many(self, items: DynWinRTArray | Sequence['IWwwFormUrlDecoderEntry']) -> list[IWwwFormUrlDecoderEntry | None]:
        _results = _IIterator_IWwwFormUrlDecoderEntry.method(9).invoke_all(self._obj, [_dynwinrt_array(items, lambda item: getattr(item, '_obj', item), DynWinRTType.interface(WinGUID.parse('125e7431-f678-4e8e-b670-20a9b06c512d')), False)])
        return _dynwinrt_wrap_values('windows__foundation__i_www_form_url_decoder_entry', 'IWwwFormUrlDecoderEntry', _results[0].as_array().to_values())[:_results[1].to_number()]
