# Generated by dynwinrt-codegen — do not edit
from __future__ import annotations
from ._runtime import (
    Callable, Iterable, Iterator, Mapping, MutableMapping, MutableSequence, Sequence,
    TYPE_CHECKING, UUID, WinGUID, datetime, timedelta,
    DynWinRTType, DynWinRTMethodSig, DynWinRTValue, DynWinRTArray,
    DynWinRTStruct, DynWinRtDelegate, DynWinRTOverrideInterface,
    _property, _weakref_ref,
    _dynwinrt_array, _dynwinrt_bind_overload, _dynwinrt_can_cast, _dynwinrt_create_delegate,
    _dynwinrt_datetime_to_ticks, _dynwinrt_delegate, _dynwinrt_enum, _dynwinrt_guid,
    _dynwinrt_map, _dynwinrt_new_vector, _dynwinrt_ticks_to_datetime,
    _dynwinrt_ticks_to_timedelta, _dynwinrt_timedelta_to_ticks,
    _dynwinrt_cache_projected, _dynwinrt_projected_from_native,
    _dynwinrt_symbol, _dynwinrt_track_projected, _dynwinrt_uuid,
    _dynwinrt_vector, _dynwinrt_wrap_values,
)

IID_IUriRuntimeClassWithAbsoluteCanonicalUri = WinGUID.parse('758d9661-221c-480f-a339-50656673f46f')

_IUriRuntimeClassWithAbsoluteCanonicalUri = DynWinRTType.register_interface(
    "IUriRuntimeClassWithAbsoluteCanonicalUri", IID_IUriRuntimeClassWithAbsoluteCanonicalUri) \
    .add_method("get_AbsoluteCanonicalUri", DynWinRTMethodSig().add_out(DynWinRTType.hstring())) \
    .add_method("get_DisplayIri", DynWinRTMethodSig().add_out(DynWinRTType.hstring()))


class IUriRuntimeClassWithAbsoluteCanonicalUri:
    _dynwinrt_interface_type = True
    _dynwinrt_interface_iid = IID_IUriRuntimeClassWithAbsoluteCanonicalUri
    def __new__(cls, *args, **kwargs):
        if len(args) == 1 and not kwargs and isinstance(args[0], DynWinRTValue):
            return _dynwinrt_projected_from_native(cls, args[0], '_set_native')
        return super().__new__(cls)

    def _set_native(self, obj: DynWinRTValue):
        self._obj = obj
        self._dynwinrt_native_ready = True
        _dynwinrt_track_projected(self, 'Windows.Foundation.IUriRuntimeClassWithAbsoluteCanonicalUri')
        _dynwinrt_cache_projected(self)

    def __init__(self, obj: DynWinRTValue):
        if getattr(self, '_dynwinrt_native_ready', False):
            return
        IUriRuntimeClassWithAbsoluteCanonicalUri._set_native(self, obj)

    @classmethod
    def _from_native(cls, obj: DynWinRTValue) -> 'IUriRuntimeClassWithAbsoluteCanonicalUri':
        return cls(obj)

    @classmethod
    def from_value(cls, obj: DynWinRTValue) -> 'IUriRuntimeClassWithAbsoluteCanonicalUri':
        return cls._from_native(obj.cast(IID_IUriRuntimeClassWithAbsoluteCanonicalUri))

    def as_interface(self, interface_class):
        return interface_class.from_value(self._obj)


    @_property
    def absolute_canonical_uri(self) -> str:
        return _IUriRuntimeClassWithAbsoluteCanonicalUri.method(6).invoke(self._obj, []).to_string()

    @_property
    def display_iri(self) -> str:
        return _IUriRuntimeClassWithAbsoluteCanonicalUri.method(7).invoke(self._obj, []).to_string()
