# Generated by dynwinrt-codegen — do not edit
from __future__ import annotations
from functools import lru_cache
from importlib import import_module
from collections.abc import (
    Callable, Iterable, Iterator, Mapping, MutableMapping, MutableSequence, Sequence,
)
from datetime import datetime, timedelta
from typing import TYPE_CHECKING
from uuid import UUID
from dynwinrt_py import (
    DynWinRTType, DynWinRTMethodSig, DynWinRTValue, DynWinRTArray,
    DynWinRTStruct, DynWinRtDelegate, WinGUID,
)
from dynwinrt_py.dynwinrt_py import (
    _dynwinrt_array, _dynwinrt_bind_overload, _dynwinrt_datetime_to_ticks, _dynwinrt_guid,
    _dynwinrt_map, _dynwinrt_ticks_to_datetime, _dynwinrt_ticks_to_timedelta,
    _dynwinrt_timedelta_to_ticks, _dynwinrt_uuid, _dynwinrt_vector,
)


@lru_cache(maxsize=None)
def _dynwinrt_symbol(module, name):
    return getattr(import_module(f'.{module}', __package__), name)


def _dynwinrt_wrap_values(module, name, values):
    wrapper = _dynwinrt_symbol(module, name)
    wrap = getattr(wrapper, '_from_native', wrapper)
    return [wrap(value) for value in values]


def _dynwinrt_enum(module, name, value):
    enum_type = _dynwinrt_symbol(module, name)
    try:
        return enum_type(value)
    except ValueError:
        return value


def _dynwinrt_delegate(value, iid, parameter_types):
    raw = getattr(value, '_obj', value)
    if isinstance(raw, DynWinRTValue):
        return raw
    if not callable(value):
        raise TypeError('delegate value must be callable or a DynWinRTValue')
    return DynWinRtDelegate.create(iid, parameter_types, value).to_value()


if TYPE_CHECKING:
    from .www_form_url_decoder import WwwFormUrlDecoder  # noqa: F401

IID_IUriRuntimeClass = WinGUID.parse('9e365e57-48b2-4160-956f-c7385120bbfc')
IID_IUriRuntimeClassFactory = WinGUID.parse('44a9796f-723e-4fdf-a218-033e75b0c084')
IID_IUriEscapeStatics = WinGUID.parse('c1d432ba-c824-4452-a7fd-512bc3bbe9a1')
IID_IUriRuntimeClassWithAbsoluteCanonicalUri = WinGUID.parse('758d9661-221c-480f-a339-50656673f46f')
IID_IStringable = WinGUID.parse('96369f54-8eb6-48f0-abce-c1b211e627c3')
IID_ARG_Windows_Foundation_Uri = WinGUID.parse('9e365e57-48b2-4160-956f-c7385120bbfc')

_IUriRuntimeClass = DynWinRTType.register_interface(
    "IUriRuntimeClass", IID_IUriRuntimeClass) \
    .add_method("get_AbsoluteUri", DynWinRTMethodSig().add_out(DynWinRTType.hstring())) \
    .add_method("get_DisplayUri", DynWinRTMethodSig().add_out(DynWinRTType.hstring())) \
    .add_method("get_Domain", DynWinRTMethodSig().add_out(DynWinRTType.hstring())) \
    .add_method("get_Extension", DynWinRTMethodSig().add_out(DynWinRTType.hstring())) \
    .add_method("get_Fragment", DynWinRTMethodSig().add_out(DynWinRTType.hstring())) \
    .add_method("get_Host", DynWinRTMethodSig().add_out(DynWinRTType.hstring())) \
    .add_method("get_Password", DynWinRTMethodSig().add_out(DynWinRTType.hstring())) \
    .add_method("get_Path", DynWinRTMethodSig().add_out(DynWinRTType.hstring())) \
    .add_method("get_Query", DynWinRTMethodSig().add_out(DynWinRTType.hstring())) \
    .add_method("get_QueryParsed", DynWinRTMethodSig().add_out(DynWinRTType.runtime_class('Windows.Foundation.WwwFormUrlDecoder', DynWinRTType.interface(WinGUID.parse('d45a0451-f225-4542-9296-0e1df5d254df'))))) \
    .add_method("get_RawUri", DynWinRTMethodSig().add_out(DynWinRTType.hstring())) \
    .add_method("get_SchemeName", DynWinRTMethodSig().add_out(DynWinRTType.hstring())) \
    .add_method("get_UserName", DynWinRTMethodSig().add_out(DynWinRTType.hstring())) \
    .add_method("get_Port", DynWinRTMethodSig().add_out(DynWinRTType.i32_type())) \
    .add_method("get_Suspicious", DynWinRTMethodSig().add_out(DynWinRTType.bool_type())) \
    .add_method("Equals", DynWinRTMethodSig().add_in(DynWinRTType.runtime_class('Windows.Foundation.Uri', DynWinRTType.interface(WinGUID.parse('9e365e57-48b2-4160-956f-c7385120bbfc')))).add_out(DynWinRTType.bool_type())) \
    .add_method("CombineUri", DynWinRTMethodSig().add_in(DynWinRTType.hstring()).add_out(DynWinRTType.runtime_class('Windows.Foundation.Uri', DynWinRTType.interface(WinGUID.parse('9e365e57-48b2-4160-956f-c7385120bbfc')))))

_IUriRuntimeClassFactory = DynWinRTType.register_interface(
    "IUriRuntimeClassFactory", IID_IUriRuntimeClassFactory) \
    .add_method("CreateUri", DynWinRTMethodSig().add_in(DynWinRTType.hstring()).add_out(DynWinRTType.runtime_class('Windows.Foundation.Uri', DynWinRTType.interface(WinGUID.parse('9e365e57-48b2-4160-956f-c7385120bbfc'))))) \
    .add_method("CreateWithRelativeUri", DynWinRTMethodSig().add_in(DynWinRTType.hstring()).add_in(DynWinRTType.hstring()).add_out(DynWinRTType.runtime_class('Windows.Foundation.Uri', DynWinRTType.interface(WinGUID.parse('9e365e57-48b2-4160-956f-c7385120bbfc')))))

_IUriEscapeStatics = DynWinRTType.register_interface(
    "IUriEscapeStatics", IID_IUriEscapeStatics) \
    .add_method("UnescapeComponent", DynWinRTMethodSig().add_in(DynWinRTType.hstring()).add_out(DynWinRTType.hstring())) \
    .add_method("EscapeComponent", DynWinRTMethodSig().add_in(DynWinRTType.hstring()).add_out(DynWinRTType.hstring()))

_IUriRuntimeClassWithAbsoluteCanonicalUri = DynWinRTType.register_interface(
    "IUriRuntimeClassWithAbsoluteCanonicalUri", IID_IUriRuntimeClassWithAbsoluteCanonicalUri) \
    .add_method("get_AbsoluteCanonicalUri", DynWinRTMethodSig().add_out(DynWinRTType.hstring())) \
    .add_method("get_DisplayIri", DynWinRTMethodSig().add_out(DynWinRTType.hstring()))

_IStringable = DynWinRTType.register_interface(
    "IStringable", IID_IStringable) \
    .add_method("ToString", DynWinRTMethodSig().add_out(DynWinRTType.hstring()))


class Uri:
    def _set_native(self, obj: DynWinRTValue):
        self._obj = obj.cast(IID_IUriRuntimeClass)

    @classmethod
    def _from_native(cls, obj: DynWinRTValue):
        instance = cls.__new__(cls)
        instance._set_native(obj)
        return instance

    def __init__(self, *args, **kwargs):
        if len(args) == 1 and not kwargs and isinstance(args[0], DynWinRTValue):
            self._set_native(args[0])
            return
        _bound = _dynwinrt_bind_overload(('uri',), args, kwargs)
        if _bound is not None and isinstance(_bound[0], str):
            self._set_native(type(self).create_uri(*_bound)._obj)
            return
        _bound = _dynwinrt_bind_overload(('base_uri', 'relative_uri',), args, kwargs)
        if _bound is not None and isinstance(_bound[0], str) and isinstance(_bound[1], str):
            self._set_native(type(self).create_with_relative_uri(*_bound)._obj)
            return
        raise TypeError("No matching constructor for Uri")

    _f_IUriRuntimeClassFactory = None

    @classmethod
    def _get_f_IUriRuntimeClassFactory(cls):
        if cls._f_IUriRuntimeClassFactory is None:
            cls._f_IUriRuntimeClassFactory = DynWinRTValue.activation_factory('Windows.Foundation.Uri').cast(IID_IUriRuntimeClassFactory)
        return cls._f_IUriRuntimeClassFactory

    _s_IUriEscapeStatics = None

    @classmethod
    def _get_s_IUriEscapeStatics(cls):
        if cls._s_IUriEscapeStatics is None:
            cls._s_IUriEscapeStatics = DynWinRTValue.activation_factory('Windows.Foundation.Uri').cast(IID_IUriEscapeStatics)
        return cls._s_IUriEscapeStatics


    @staticmethod
    def create_uri(uri: str) -> 'Uri':
        return Uri._from_native(_IUriRuntimeClassFactory.method(6).invoke(Uri._get_f_IUriRuntimeClassFactory(), [DynWinRTValue.from_hstring(uri)]))

    @staticmethod
    def create_with_relative_uri(base_uri: str, relative_uri: str) -> 'Uri':
        return Uri._from_native(_IUriRuntimeClassFactory.method(7).invoke(Uri._get_f_IUriRuntimeClassFactory(), [DynWinRTValue.from_hstring(base_uri), DynWinRTValue.from_hstring(relative_uri)]))

    @staticmethod
    def unescape_component(to_unescape: str) -> str:
        return _IUriEscapeStatics.method(6).invoke(Uri._get_s_IUriEscapeStatics(), [DynWinRTValue.from_hstring(to_unescape)]).to_string()

    @staticmethod
    def escape_component(to_escape: str) -> str:
        return _IUriEscapeStatics.method(7).invoke(Uri._get_s_IUriEscapeStatics(), [DynWinRTValue.from_hstring(to_escape)]).to_string()

    @property
    def absolute_uri(self) -> str:
        return _IUriRuntimeClass.method(6).invoke(self._obj, []).to_string()

    @property
    def display_uri(self) -> str:
        return _IUriRuntimeClass.method(7).invoke(self._obj, []).to_string()

    @property
    def domain(self) -> str:
        return _IUriRuntimeClass.method(8).invoke(self._obj, []).to_string()

    @property
    def extension(self) -> str:
        return _IUriRuntimeClass.method(9).invoke(self._obj, []).to_string()

    @property
    def fragment(self) -> str:
        return _IUriRuntimeClass.method(10).invoke(self._obj, []).to_string()

    @property
    def host(self) -> str:
        return _IUriRuntimeClass.method(11).invoke(self._obj, []).to_string()

    @property
    def password(self) -> str:
        return _IUriRuntimeClass.method(12).invoke(self._obj, []).to_string()

    @property
    def path(self) -> str:
        return _IUriRuntimeClass.method(13).invoke(self._obj, []).to_string()

    @property
    def query(self) -> str:
        return _IUriRuntimeClass.method(14).invoke(self._obj, []).to_string()

    @property
    def query_parsed(self) -> 'WwwFormUrlDecoder':
        return _dynwinrt_symbol('www_form_url_decoder', 'WwwFormUrlDecoder')._from_native(_IUriRuntimeClass.method(15).invoke(self._obj, []))

    @property
    def raw_uri(self) -> str:
        return _IUriRuntimeClass.method(16).invoke(self._obj, []).to_string()

    @property
    def scheme_name(self) -> str:
        return _IUriRuntimeClass.method(17).invoke(self._obj, []).to_string()

    @property
    def user_name(self) -> str:
        return _IUriRuntimeClass.method(18).invoke(self._obj, []).to_string()

    @property
    def port(self) -> int:
        return _IUriRuntimeClass.method(19).invoke(self._obj, []).to_number()

    @property
    def suspicious(self) -> bool:
        return _IUriRuntimeClass.method(20).invoke(self._obj, []).to_bool()

    def equals(self, p_uri: 'Uri') -> bool:
        return _IUriRuntimeClass.method(21).invoke(self._obj, [getattr(p_uri, '_obj', p_uri).cast(IID_ARG_Windows_Foundation_Uri)]).to_bool()

    def combine_uri(self, relative_uri: str) -> 'Uri':
        return _dynwinrt_symbol('uri', 'Uri')._from_native(_IUriRuntimeClass.method(22).invoke(self._obj, [DynWinRTValue.from_hstring(relative_uri)]))

    @property
    def absolute_canonical_uri(self) -> str:
        return _IUriRuntimeClassWithAbsoluteCanonicalUri.method(6).invoke(self._obj.cast(IID_IUriRuntimeClassWithAbsoluteCanonicalUri), []).to_string()

    @property
    def display_iri(self) -> str:
        return _IUriRuntimeClassWithAbsoluteCanonicalUri.method(7).invoke(self._obj.cast(IID_IUriRuntimeClassWithAbsoluteCanonicalUri), []).to_string()

    def to_string(self) -> str:
        return _IStringable.method(6).invoke(self._obj.cast(IID_IStringable), []).to_string()

    def as_interface(self, interface_class):
        return interface_class.from_value(self._obj)


class IUriRuntimeClassWithAbsoluteCanonicalUri:
    def __init__(self, obj: DynWinRTValue):
        self._obj = obj.cast(IID_IUriRuntimeClassWithAbsoluteCanonicalUri)

    @staticmethod
    def from_value(obj: DynWinRTValue) -> 'IUriRuntimeClassWithAbsoluteCanonicalUri':
        return IUriRuntimeClassWithAbsoluteCanonicalUri(obj.cast(IID_IUriRuntimeClassWithAbsoluteCanonicalUri))

    @property
    def absolute_canonical_uri(self) -> str:
        return _IUriRuntimeClassWithAbsoluteCanonicalUri.method(6).invoke(self._obj, []).to_string()

    @property
    def display_iri(self) -> str:
        return _IUriRuntimeClassWithAbsoluteCanonicalUri.method(7).invoke(self._obj, []).to_string()


class IStringable:
    def __init__(self, obj: DynWinRTValue):
        self._obj = obj.cast(IID_IStringable)

    @staticmethod
    def from_value(obj: DynWinRTValue) -> 'IStringable':
        return IStringable(obj.cast(IID_IStringable))

    def to_string(self) -> str:
        return _IStringable.method(6).invoke(self._obj, []).to_string()
