# Generated by dynwinrt-codegen — do not edit
from __future__ import annotations
from ._runtime import (
    Callable, Iterable, Iterator, Mapping, MutableMapping, MutableSequence, Sequence,
    TYPE_CHECKING, UUID, WinGUID, datetime, timedelta,
    DynWinRTType, DynWinRTMethodSig, DynWinRTValue, DynWinRTArray,
    DynWinRTStruct, DynWinRtDelegate, DynWinRTOverrideInterface,
    _property, _weakref_ref,
    _dynwinrt_array, _dynwinrt_bind_overload, _dynwinrt_can_cast, _dynwinrt_create_delegate,
    _dynwinrt_datetime_to_ticks, _dynwinrt_delegate, _dynwinrt_enum, _dynwinrt_guid,
    _dynwinrt_map, _dynwinrt_new_vector, _dynwinrt_ticks_to_datetime,
    _dynwinrt_ticks_to_timedelta, _dynwinrt_timedelta_to_ticks,
    _dynwinrt_cache_projected, _dynwinrt_projected_from_native,
    _dynwinrt_symbol, _dynwinrt_track_projected, _dynwinrt_uuid,
    _dynwinrt_vector, _dynwinrt_wrap_values,
)
from dynwinrt.dynwinrt import _WinRTIterableMixin, _WinRTSequenceMixin

if TYPE_CHECKING:
    from .i_iterator_i_www_form_url_decoder_entry import IIterator_IWwwFormUrlDecoderEntry  # noqa: F401
    from .windows__foundation__i_www_form_url_decoder_entry import IID_IWwwFormUrlDecoderEntry, IWwwFormUrlDecoderEntry  # noqa: F401

IID_IWwwFormUrlDecoderRuntimeClass = WinGUID.parse('d45a0451-f225-4542-9296-0e1df5d254df')
IID_IWwwFormUrlDecoderRuntimeClassFactory = WinGUID.parse('5b8c6b3d-24ae-41b5-a1bf-f0c3d544845b')
IID_IVectorView_IWwwFormUrlDecoderEntry = DynWinRTType.parameterized(WinGUID.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRTType.interface(WinGUID.parse('125e7431-f678-4e8e-b670-20a9b06c512d'))]).iid()
IID_IIterable_IWwwFormUrlDecoderEntry = DynWinRTType.parameterized(WinGUID.parse('faa585ea-6214-4217-afda-7f46de5869b3'), [DynWinRTType.interface(WinGUID.parse('125e7431-f678-4e8e-b670-20a9b06c512d'))]).iid()

_IWwwFormUrlDecoderRuntimeClass = DynWinRTType.register_interface(
    "IWwwFormUrlDecoderRuntimeClass", IID_IWwwFormUrlDecoderRuntimeClass) \
    .add_method("GetFirstValueByName", DynWinRTMethodSig().add_in(DynWinRTType.hstring()).add_out(DynWinRTType.hstring()))

_IWwwFormUrlDecoderRuntimeClassFactory = DynWinRTType.register_interface(
    "IWwwFormUrlDecoderRuntimeClassFactory", IID_IWwwFormUrlDecoderRuntimeClassFactory) \
    .add_method("CreateWwwFormUrlDecoder", DynWinRTMethodSig().add_in(DynWinRTType.hstring()).add_out(DynWinRTType.runtime_class('Windows.Foundation.WwwFormUrlDecoder', DynWinRTType.interface(WinGUID.parse('d45a0451-f225-4542-9296-0e1df5d254df')))))

_IVectorView_IWwwFormUrlDecoderEntry = DynWinRTType.register_interface(
    "IVectorView_IWwwFormUrlDecoderEntry", IID_IVectorView_IWwwFormUrlDecoderEntry) \
    .add_method("GetAt", DynWinRTMethodSig().add_in(DynWinRTType.u32_type()).add_out(DynWinRTType.interface(WinGUID.parse('125e7431-f678-4e8e-b670-20a9b06c512d')))) \
    .add_method("get_Size", DynWinRTMethodSig().add_out(DynWinRTType.u32_type())) \
    .add_method("IndexOf", DynWinRTMethodSig().add_in(DynWinRTType.interface(WinGUID.parse('125e7431-f678-4e8e-b670-20a9b06c512d'))).add_out(DynWinRTType.u32_type()).add_out(DynWinRTType.bool_type())) \
    .add_method("GetMany", DynWinRTMethodSig().add_in(DynWinRTType.u32_type()).add_out_fill(DynWinRTType.array_type(DynWinRTType.interface(WinGUID.parse('125e7431-f678-4e8e-b670-20a9b06c512d')))).add_out(DynWinRTType.u32_type()))

_IIterable_IWwwFormUrlDecoderEntry = DynWinRTType.register_interface(
    "IIterable_IWwwFormUrlDecoderEntry", IID_IIterable_IWwwFormUrlDecoderEntry) \
    .add_method("First", DynWinRTMethodSig().add_out(DynWinRTType.parameterized(WinGUID.parse('6a79e863-4300-459a-9966-cbb660963ee1'), [DynWinRTType.interface(WinGUID.parse('125e7431-f678-4e8e-b670-20a9b06c512d'))])))


class WwwFormUrlDecoder(_WinRTSequenceMixin):
    _dynwinrt_runtime_class_type = True
    def __new__(cls, *args, **kwargs):
        if len(args) == 1 and not kwargs and isinstance(args[0], DynWinRTValue):
            return _dynwinrt_projected_from_native(cls, args[0], '_set_native')
        if cls is WwwFormUrlDecoder:
            _bound = _dynwinrt_bind_overload(('query',), args, kwargs)
            if _bound is not None and isinstance(_bound[0], str):
                return cls.create_www_form_url_decoder(_bound[0])
        return super().__new__(cls)

    def _set_native(self, obj: DynWinRTValue):
        self._obj = obj.cast(IID_IWwwFormUrlDecoderRuntimeClass)
        self._collection_obj = obj.cast(IID_IVectorView_IWwwFormUrlDecoderEntry)
        self._dynwinrt_native_ready = True
        _dynwinrt_track_projected(self, 'Windows.Foundation.WwwFormUrlDecoder')
        _dynwinrt_cache_projected(self)

    @classmethod
    def _from_native(cls, obj: DynWinRTValue):
        return cls(obj)

    def __init__(self, *args, **kwargs):
        if getattr(self, '_dynwinrt_native_ready', False):
            return
        if len(args) == 1 and not kwargs and isinstance(args[0], DynWinRTValue):
            self._set_native(args[0])
            return
        _bound = _dynwinrt_bind_overload(('query',), args, kwargs)
        if _bound is not None and isinstance(_bound[0], str):
            self._set_native(type(self).create_www_form_url_decoder(_bound[0])._obj)
            return
        raise TypeError("No matching constructor for WwwFormUrlDecoder")

    @staticmethod
    def _get_f_IWwwFormUrlDecoderRuntimeClassFactory():
        return DynWinRTValue.activation_factory('Windows.Foundation.WwwFormUrlDecoder').cast(IID_IWwwFormUrlDecoderRuntimeClassFactory)


    @staticmethod
    def create_www_form_url_decoder(query: str) -> 'WwwFormUrlDecoder':
        return WwwFormUrlDecoder._from_native(_IWwwFormUrlDecoderRuntimeClassFactory.method(6).invoke(WwwFormUrlDecoder._get_f_IWwwFormUrlDecoderRuntimeClassFactory(), [DynWinRTValue.from_hstring(query)]))

    def get_first_value_by_name(self, name: str) -> str:
        return _IWwwFormUrlDecoderRuntimeClass.method(6).invoke(self._obj, [DynWinRTValue.from_hstring(name)]).to_string()

    @_property
    def size(self) -> int:
        return _IVectorView_IWwwFormUrlDecoderEntry.method(7).invoke(self._collection_obj, []).to_u32()

    def get_at(self, index: int) -> IWwwFormUrlDecoderEntry | None:
        return (lambda value: None if value.is_null() else _dynwinrt_symbol('windows__foundation__i_www_form_url_decoder_entry', 'IWwwFormUrlDecoderEntry')(value))(_IVectorView_IWwwFormUrlDecoderEntry.method(6).invoke(self._collection_obj, [DynWinRTValue.from_u32(index)]))

    def index_of(self, value: 'IWwwFormUrlDecoderEntry') -> tuple[int, bool]:
        _results = _IVectorView_IWwwFormUrlDecoderEntry.method(8).invoke_all(self._collection_obj, [getattr(value, '_obj', value)])
        return (_results[0].to_u32(), _results[1].to_bool())

    def get_many(self, start_index: int, items: DynWinRTArray | Sequence['IWwwFormUrlDecoderEntry']) -> list[IWwwFormUrlDecoderEntry | None]:
        _results = _IVectorView_IWwwFormUrlDecoderEntry.method(9).invoke_all(self._collection_obj, [DynWinRTValue.from_u32(start_index), _dynwinrt_array(items, lambda item: getattr(item, '_obj', item), DynWinRTType.interface(WinGUID.parse('125e7431-f678-4e8e-b670-20a9b06c512d')), False)])
        return _dynwinrt_wrap_values('windows__foundation__i_www_form_url_decoder_entry', 'IWwwFormUrlDecoderEntry', _results[0].as_array().to_values())[:_results[1].to_number()]

    def first(self) -> Iterator[IWwwFormUrlDecoderEntry | None] | None:
        return (lambda value: None if value.is_null() else _dynwinrt_symbol('i_iterator_i_www_form_url_decoder_entry', 'IIterator_IWwwFormUrlDecoderEntry')(value))(_IIterable_IWwwFormUrlDecoderEntry.method(6).invoke(self._obj.cast(IID_IIterable_IWwwFormUrlDecoderEntry), []))

    def as_interface(self, interface_class):
        return interface_class.from_value(self._obj)


class IVectorView_IWwwFormUrlDecoderEntry(_WinRTSequenceMixin):
    _dynwinrt_interface_type = True
    _dynwinrt_interface_iid = IID_IVectorView_IWwwFormUrlDecoderEntry
    def __new__(cls, *args, **kwargs):
        if len(args) == 1 and not kwargs and isinstance(args[0], DynWinRTValue):
            return _dynwinrt_projected_from_native(cls, args[0], '_set_native')
        return super().__new__(cls)

    def _set_native(self, obj: DynWinRTValue):
        self._obj = obj.cast(IID_IVectorView_IWwwFormUrlDecoderEntry)
        self._dynwinrt_native_ready = True
        _dynwinrt_track_projected(self, 'Windows.Foundation.Collections.IVectorView_IWwwFormUrlDecoderEntry')
        _dynwinrt_cache_projected(self)

    def __init__(self, obj: DynWinRTValue):
        if getattr(self, '_dynwinrt_native_ready', False):
            return
        IVectorView_IWwwFormUrlDecoderEntry._set_native(self, obj)

    @classmethod
    def _from_native(cls, obj: DynWinRTValue) -> 'IVectorView_IWwwFormUrlDecoderEntry':
        return cls(obj)

    @classmethod
    def from_value(cls, obj: DynWinRTValue) -> 'IVectorView_IWwwFormUrlDecoderEntry':
        return cls._from_native(obj.cast(IID_IVectorView_IWwwFormUrlDecoderEntry))

    def as_interface(self, interface_class):
        return interface_class.from_value(self._obj)

    @_property
    def size(self) -> int:
        return _IVectorView_IWwwFormUrlDecoderEntry.method(7).invoke(self._obj, []).to_u32()

    def get_at(self, index: int) -> IWwwFormUrlDecoderEntry | None:
        return (lambda value: None if value.is_null() else _dynwinrt_symbol('windows__foundation__i_www_form_url_decoder_entry', 'IWwwFormUrlDecoderEntry')(value))(_IVectorView_IWwwFormUrlDecoderEntry.method(6).invoke(self._obj, [DynWinRTValue.from_u32(index)]))

    def index_of(self, value: 'IWwwFormUrlDecoderEntry') -> tuple[int, bool]:
        _results = _IVectorView_IWwwFormUrlDecoderEntry.method(8).invoke_all(self._obj, [getattr(value, '_obj', value)])
        return (_results[0].to_u32(), _results[1].to_bool())

    def get_many(self, start_index: int, items: DynWinRTArray | Sequence['IWwwFormUrlDecoderEntry']) -> list[IWwwFormUrlDecoderEntry | None]:
        _results = _IVectorView_IWwwFormUrlDecoderEntry.method(9).invoke_all(self._obj, [DynWinRTValue.from_u32(start_index), _dynwinrt_array(items, lambda item: getattr(item, '_obj', item), DynWinRTType.interface(WinGUID.parse('125e7431-f678-4e8e-b670-20a9b06c512d')), False)])
        return _dynwinrt_wrap_values('windows__foundation__i_www_form_url_decoder_entry', 'IWwwFormUrlDecoderEntry', _results[0].as_array().to_values())[:_results[1].to_number()]


class IIterable_IWwwFormUrlDecoderEntry(_WinRTIterableMixin):
    _dynwinrt_interface_type = True
    _dynwinrt_interface_iid = IID_IIterable_IWwwFormUrlDecoderEntry
    def __new__(cls, *args, **kwargs):
        if len(args) == 1 and not kwargs and isinstance(args[0], DynWinRTValue):
            return _dynwinrt_projected_from_native(cls, args[0], '_set_native')
        return super().__new__(cls)

    def _set_native(self, obj: DynWinRTValue):
        self._obj = obj.cast(IID_IIterable_IWwwFormUrlDecoderEntry)
        self._dynwinrt_native_ready = True
        _dynwinrt_track_projected(self, 'Windows.Foundation.Collections.IIterable_IWwwFormUrlDecoderEntry')
        _dynwinrt_cache_projected(self)

    def __init__(self, obj: DynWinRTValue):
        if getattr(self, '_dynwinrt_native_ready', False):
            return
        IIterable_IWwwFormUrlDecoderEntry._set_native(self, obj)

    @classmethod
    def _from_native(cls, obj: DynWinRTValue) -> 'IIterable_IWwwFormUrlDecoderEntry':
        return cls(obj)

    @classmethod
    def from_value(cls, obj: DynWinRTValue) -> 'IIterable_IWwwFormUrlDecoderEntry':
        return cls._from_native(obj.cast(IID_IIterable_IWwwFormUrlDecoderEntry))

    def as_interface(self, interface_class):
        return interface_class.from_value(self._obj)

    def first(self) -> Iterator[IWwwFormUrlDecoderEntry | None] | None:
        return (lambda value: None if value.is_null() else _dynwinrt_symbol('i_iterator_i_www_form_url_decoder_entry', 'IIterator_IWwwFormUrlDecoderEntry')(value))(_IIterable_IWwwFormUrlDecoderEntry.method(6).invoke(self._obj, []))
