// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! ESM-to-CommonJS conversion with lazy sibling imports.

// ======================================================================
// ESM → CJS + lazy sibling requires post-process
// ======================================================================
//
// Rationale: the projection layer emits idiomatic ESM (`import ... from`,
// `export class`). To keep consumer startup fast we convert the final text
// to CommonJS with lazy sibling loaders:
//
//   * `import { A, B } from '@microsoft/dynwinrt'` → eager `const { A, B } = require(...)`
//   * `import { X, IID_Y } from './Sibling.js'`    → lazy Proxy per symbol; the sibling
//                                                    module is only `require`d on first
//                                                    access.
//   * `export class`/`export const`/`export function` → strip `export`, emit `exports.X = X`
//     trailer at the end of the file.
//
// The generated CJS sibling files still parse cleanly under ESM callers because
// Node's CJS-named-exports interop maps `exports.X = X` back to `import { X }`.
// See docs/design (Node 20+ ESM/CJS interop).

pub(super) fn convert_to_cjs_with_lazy(
    esm: &str,
    runtime_sources: &std::collections::HashSet<String>,
) -> String {
    use std::collections::BTreeMap;

    // Split into (imports, body_lines). Imports at top only; the body starts
    // at the first non-import, non-blank, non-comment line.
    let mut runtime_imports: Vec<(Vec<String>, String)> = Vec::new();
    // Preserve first-seen order of sibling modules so generated output is stable.
    let mut sibling_order: Vec<String> = Vec::new();
    let mut sibling_symbols: BTreeMap<String, Vec<String>> = BTreeMap::new();
    let mut body: String = String::with_capacity(esm.len());

    let mut in_header = true;
    for line in esm.split_inclusive('\n') {
        if in_header {
            let trimmed = line.trim();
            if trimmed.is_empty() || trimmed.starts_with("//") {
                // Skip header comment; regenerate below.
                continue;
            }
            if let Some((symbols, source)) = parse_import_line(trimmed) {
                // Runtime imports must match the caller-supplied set exactly;
                // textual heuristics like `starts_with("./")` misclassify
                // `--import-name ./runtime.js` overrides.
                if runtime_sources.contains(&source) {
                    runtime_imports.push((symbols, source));
                } else if !source.starts_with("./") {
                    runtime_imports.push((symbols, source));
                } else {
                    let module = source
                        .trim_start_matches("./")
                        .trim_end_matches(".js")
                        .to_string();
                    if !sibling_symbols.contains_key(&module) {
                        sibling_order.push(module.clone());
                    }
                    let entry = sibling_symbols.entry(module).or_default();
                    for s in symbols {
                        if !entry.contains(&s) {
                            entry.push(s);
                        }
                    }
                }
                continue;
            }
            // First non-import content — header is done.
            in_header = false;
        }
        body.push_str(line);
    }

    // Now transform the body: strip `export ` prefix from top-level declarations
    // and record names for the trailer.
    let (transformed_body, exported_names) = strip_exports_and_collect(&body);

    // Assemble output.
    let mut out = String::with_capacity(esm.len() + 4096);
    out.push_str("// Generated by dynwinrt-codegen \u{2014} do not edit\n");

    // Eager runtime imports (small, hot, always used at load time).
    for (symbols, source) in &runtime_imports {
        let deduped = dedupe_preserving_order(symbols);
        if deduped.is_empty() {
            continue;
        }
        out.push_str(&format!(
            "const {{ {} }} = require('{}');\n",
            deduped.join(", "),
            source
        ));
    }

    // Lazy sibling loaders. Symbols are classified per-name:
    //   * `IID_*` (GUID), `*_PARAM_TYPES` (DynWinRtType[]), and `*_Type` (struct
    //     type descriptor) values are handed *directly* to the native runtime
    //     via N-API. Their napi-rs bindings identify them via type tags, which
    //     Proxy objects cannot forward — so we require them eagerly and
    //     destructure the real objects out of the sibling module.
    //   * Everything else (class wrappers, `pack*`/`unpack*` helpers, enums)
    //     is exposed to internal call sites via a per-symbol getter function
    //     `__get_X()` that dereferences the sibling module on first call. The
    //     body of this file is rewritten below (see
    //     `rewrite_lazy_use_sites`) so bare occurrences of `X` become
    //     `(__get_X())`. This avoids the Proxy pitfalls that hurt
    //     `instanceof`, `JSON.stringify`, `Object.freeze`, and
    //     `.constructor.name`, because every consumer touches the real,
    //     unwrapped value directly.
    fn is_eager_symbol(name: &str) -> bool {
        name.starts_with("IID_") || name.ends_with("_PARAM_TYPES") || name.ends_with("_Type")
    }

    // Track every lazy symbol across every sibling so the body rewrite pass
    // knows what identifiers to rewrap.
    let mut all_lazy_symbols: std::collections::HashSet<String> = std::collections::HashSet::new();

    for module in &sibling_order {
        let symbols = &sibling_symbols[module];
        let var_name = sanitize_ident(module);

        let all_eager: Vec<&String> = symbols
            .iter()
            .filter(|symbol| is_eager_symbol(symbol))
            .collect();
        let eager: Vec<&String> = all_eager
            .iter()
            .copied()
            .filter(|symbol| transformed_body.contains(symbol.as_str()))
            .collect();
        let lazy: Vec<&String> = symbols.iter().filter(|s| !is_eager_symbol(s)).collect();

        // Eager block first: `const { IID_X, X_PARAM_TYPES } = require('./X.js');`
        if !eager.is_empty() {
            let list = eager
                .iter()
                .map(|s| s.as_str())
                .collect::<Vec<_>>()
                .join(", ");
            out.push_str(&format!(
                "const {{ {} }} = require('./{}.js');\n",
                list, module
            ));
        } else if !all_eager.is_empty() {
            // Keep the sibling's initialization side effects without reading
            // an export that may not exist yet during a CommonJS cycle.
            out.push_str(&format!("require('./{}.js');\n", module));
        }

        if !lazy.is_empty() {
            out.push_str(&format!("let __m_{};\n", var_name));
            out.push_str(&format!(
                "const __load_{0} = () => (__m_{0} ??= require('./{1}.js'));\n",
                var_name, module
            ));
            for sym in lazy {
                // Per-symbol getter: returns the *real* value from the loaded
                // sibling module — no Proxy in sight.
                out.push_str(&format!(
                    "const __get_{0} = () => __load_{1}().{0};\n",
                    sym, var_name
                ));
                all_lazy_symbols.insert(sym.to_string());
            }
        }
    }

    // Blank line between imports and body for readability.
    out.push('\n');

    // Resolve `__DWRT_REF__X__` markers embedded in the body by the projection
    // layer. This is a simple, unambiguous string substitution — no JS
    // tokenization needed because the marker syntax (`__DWRT_REF__…__`) cannot
    // legitimately appear in string literals or comments produced by our
    // codegen. Each marker either turns into `(__get_X())` when X is a lazy
    // cross-file sibling, or into the bare `X` when X is same-file (self).
    let rewritten_body = resolve_ref_markers(&transformed_body, &all_lazy_symbols);
    out.push_str(&rewritten_body);

    // Trailer — exports.
    if !exported_names.is_empty() {
        // If the body already ends with a newline we don't need to add one.
        if !out.ends_with('\n') {
            out.push('\n');
        }
        for name in &exported_names {
            out.push_str(&format!("exports.{0} = {0};\n", name));
        }
    }

    out
}

#[cfg(test)]
mod tests {
    use super::convert_to_cjs_with_lazy;
    use std::collections::HashSet;

    #[test]
    fn unused_eager_symbol_keeps_module_initialization_only() {
        let esm = "\
import { IXamlType, IID_IXamlType } from './IXamlType.js';\n\
export function getType(value) {\n\
  return new __DWRT_REF__IXamlType__(value);\n\
}\n";

        let cjs = convert_to_cjs_with_lazy(esm, &HashSet::new());

        assert!(!cjs.contains("const { IID_IXamlType }"), "{cjs}");
        assert!(cjs.contains("require('./IXamlType.js');"), "{cjs}");
        assert!(cjs.contains("const __get_IXamlType"), "{cjs}");
        assert!(cjs.contains("new (__get_IXamlType())(value)"), "{cjs}");
    }

    #[test]
    fn used_eager_symbol_is_still_destructured() {
        let esm = "\
import { IID_IFoo } from './IFoo.js';\n\
export function cast(value) {\n\
  return value.cast(IID_IFoo);\n\
}\n";

        let cjs = convert_to_cjs_with_lazy(esm, &HashSet::new());

        assert!(
            cjs.contains("const { IID_IFoo } = require('./IFoo.js');"),
            "{cjs}"
        );
    }
}

/// Parse `import { A, B } from 'source';` (single-line). Returns Some(symbols, source)
/// on success. Returns None if the line isn't a well-formed static import.
fn parse_import_line(line: &str) -> Option<(Vec<String>, String)> {
    let line = line.trim().trim_end_matches(';');
    if !line.starts_with("import") {
        return None;
    }
    let rest = &line[6..].trim_start();
    if !rest.starts_with('{') {
        return None;
    }
    let close = rest.find('}')?;
    let symbols_str = &rest[1..close];
    let after = rest[close + 1..].trim_start();
    let after = after.strip_prefix("from")?.trim_start();
    // source can be single- or double-quoted
    let (quote_char, source) = if let Some(rest) = after.strip_prefix('\'') {
        ('\'', rest)
    } else if let Some(rest) = after.strip_prefix('"') {
        ('"', rest)
    } else {
        return None;
    };
    let end_quote = source.find(quote_char)?;
    let source = &source[..end_quote];
    let symbols: Vec<String> = symbols_str
        .split(',')
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty())
        .collect();
    Some((symbols, source.to_string()))
}

/// Turn a module basename into a valid JS identifier stem. WinRT type names use
/// only [A-Za-z0-9_], so this is defensive against any future codegen additions.
fn sanitize_ident(name: &str) -> String {
    name.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect()
}

fn dedupe_preserving_order(v: &[String]) -> Vec<String> {
    let mut seen: std::collections::HashSet<String> = std::collections::HashSet::new();
    let mut out = Vec::with_capacity(v.len());
    for s in v {
        if seen.insert(s.clone()) {
            out.push(s.clone());
        }
    }
    out
}

/// Walk the body and:
///   * `export class Name { ... }`     → strip `export `, remember Name
///   * `export const Name = ...;`      → strip `export `, remember Name
///   * `export function name(...) { }` → strip `export `, remember name
///
/// Everything else passes through unchanged.
fn strip_exports_and_collect(body: &str) -> (String, Vec<String>) {
    let mut out = String::with_capacity(body.len());
    let mut exports: Vec<String> = Vec::new();

    for line in body.split_inclusive('\n') {
        // Preserve leading whitespace so nested `export`s inside JSDoc etc are untouched.
        let trimmed_start = line.trim_start();
        let leading = &line[..line.len() - trimmed_start.len()];

        if let Some(name) = extract_export_decl_name(trimmed_start) {
            // Replace `export ` prefix.
            let after_export = trimmed_start
                .strip_prefix("export ")
                .unwrap_or(trimmed_start);
            out.push_str(leading);
            out.push_str(after_export);
            exports.push(name);
        } else {
            out.push_str(line);
        }
    }

    (out, exports)
}

/// Detect a top-level `export class|const|function|async function <Name>` and
/// return `<Name>` if it matches, else None. The input must already be trimmed
/// of leading whitespace.
fn extract_export_decl_name(line: &str) -> Option<String> {
    let rest = line.strip_prefix("export ")?;
    let (keyword_len, rest_after_kw) = if let Some(r) = rest.strip_prefix("class ") {
        (6, r)
    } else if let Some(r) = rest.strip_prefix("const ") {
        (6, r)
    } else if let Some(r) = rest.strip_prefix("function ") {
        (9, r)
    } else if let Some(r) = rest.strip_prefix("async function ") {
        (15, r)
    } else if let Some(r) = rest.strip_prefix("let ") {
        (4, r)
    } else if let Some(r) = rest.strip_prefix("var ") {
        (4, r)
    } else {
        return None;
    };
    let _ = keyword_len;
    // Take chars until whitespace, `(`, `=`, `{`, or end.
    let name: String = rest_after_kw
        .chars()
        .take_while(|c| c.is_ascii_alphanumeric() || *c == '_' || *c == '$')
        .collect();
    if name.is_empty() { None } else { Some(name) }
}

// __REWRITE_MARKER__

/// Resolve `__DWRT_REF__X__` markers embedded in generated code by the
/// projection layer. Each marker is a unique token that maps deterministically
/// to a target-specific output:
///   * If `X` is in `lazy_symbols` (declared as a cross-file lazy sibling in
///     this file's imports), the marker becomes `(__get_X())` — a call to
///     the per-symbol getter emitted alongside the `__load_*` loader.
///   * Otherwise `X` is treated as a same-file identifier and the marker is
///     stripped, yielding the bare name.
///
/// This is a straight string substitution — no JS tokenization is required
/// because the `__DWRT_REF__…__` syntax cannot legitimately appear in string
/// literals or comments produced by our codegen. Compared to the earlier
/// tokenizer-based approach, this cleanly separates responsibilities:
///
///   * The projection layer (project.rs / sig.rs) uses `ref_marker()` to
///     encode "this is a type-name reference" whenever it bakes a bare
///     identifier into a body string.
///   * The render layer (this function) decides how to spell it based on the
///     import classification of the surrounding file.
fn resolve_ref_markers(body: &str, lazy_symbols: &std::collections::HashSet<String>) -> String {
    // Fast path: no markers present.
    if !body.contains(crate::codegen::winrt::javascript::signature::REF_MARKER_PREFIX) {
        return body.to_string();
    }

    let mut out = String::with_capacity(body.len());
    let mut cursor = 0usize;
    let bytes = body.as_bytes();
    let prefix = crate::codegen::winrt::javascript::signature::REF_MARKER_PREFIX;
    let suffix = crate::codegen::winrt::javascript::signature::REF_MARKER_SUFFIX;

    while let Some(rel_start) = body[cursor..].find(prefix) {
        let start = cursor + rel_start;
        out.push_str(&body[cursor..start]);
        let name_start = start + prefix.len();
        // Find the closing suffix. The name must contain only identifier chars
        // (alphanumerics + underscore + $) so we walk forward until we hit the
        // suffix. Codegen never embeds a marker without a matching suffix, so
        // if we don't find one we treat the prefix as literal text and move on.
        let rest = &body[name_start..];
        let Some(suffix_pos) = rest.find(suffix) else {
            // Unmatched prefix — emit it as-is and continue from after it.
            out.push_str(prefix);
            cursor = name_start;
            continue;
        };
        let name = &rest[..suffix_pos];
        // Validate that `name` is a legal JS identifier body — defensive against
        // adjacent markers, e.g. `__DWRT_REF____DWRT_REF__X____`.
        let name_ok = !name.is_empty()
            && name
                .chars()
                .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '$');
        if !name_ok {
            // Not a real marker — emit prefix literally and continue scanning
            // after it. This lets us recover gracefully if a marker-like
            // string happens to appear in test fixtures etc.
            out.push_str(prefix);
            cursor = name_start;
            continue;
        }

        if lazy_symbols.contains(name) {
            out.push('(');
            out.push_str("__get_");
            out.push_str(name);
            out.push_str("())");
        } else {
            out.push_str(name);
        }

        cursor = name_start + suffix_pos + suffix.len();
    }
    out.push_str(&body[cursor..]);
    // Silence the unused-variable lint on `bytes` — we keep it for potential
    // future byte-level analysis without changing the function signature.
    let _ = bytes;
    out
}
