// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! JS renderer: emits plain ESM JavaScript from the projected IR.
//!
//! At the end of render(), we post-process the ESM output into CJS with
//! lazy sibling requires. This keeps the projection layer simple (still emits
//! ESM shapes) while giving consumers fast startup.

pub(crate) mod commonjs;
mod helpers;

use crate::codegen::winrt::javascript::ir::*;
use crate::codegen::winrt::javascript::signature::ref_marker;

use commonjs::convert_to_cjs_with_lazy;
use helpers::{
    emit_abortable_async_body, emit_delegate_wraps, emit_with_progress_body, inject_unwrap,
    render_jsdoc, render_overload_dispatcher_js, render_same_class_overload_js,
};

/// Render a projected file as CJS with lazy sibling requires.
pub fn render(file: &ProjectedFile) -> String {
    let esm = render_esm(file);
    // Runtime imports are anything declared with `is_runtime_package: true`
    // (default `@microsoft/dynwinrt`, or whatever `--import-name` set).
    // We can't infer this from the source path — `--import-name ./runtime.js`
    // is a valid override that would otherwise get classified as a sibling
    // and wrapped in the lazy loader.
    let mut runtime_sources: std::collections::HashSet<String> = std::collections::HashSet::new();
    for imp in &file.imports {
        if imp.is_runtime_package {
            runtime_sources.insert(imp.from.clone());
        }
    }
    convert_to_cjs_with_lazy(&esm, &runtime_sources)
}

/// Render a projected file as ESM JS (internal — post-processed to CJS by render()).
fn render_esm(file: &ProjectedFile) -> String {
    let mut out = String::new();

    // Header
    out.push_str("// Generated by dynwinrt-codegen — do not edit\n");

    // Delegate files are special
    if !file.delegates.is_empty() {
        render_delegate_js(&mut out, file);
        return out;
    }

    // Imports (all, including runtime_only, but skip dts_only) — deduplicate symbols
    let mut seen_symbols: std::collections::HashSet<String> = std::collections::HashSet::new();
    for imp in &file.imports {
        if imp.dts_only {
            continue;
        }
        let deduped: Vec<&str> = imp
            .symbols
            .iter()
            .filter(|s| seen_symbols.insert(s.to_string()))
            .map(|s| s.as_str())
            .collect();
        if !deduped.is_empty() {
            out.push_str(&format!(
                "import {{ {} }} from '{}';\n",
                deduped.join(", "),
                imp.from
            ));
        }
    }
    out.push('\n');

    if !file.classes.is_empty() {
        out.push_str(
            "import { castProjectedValueBorrowed, castProjectedValueOwned, trackProjectedValue } from './lifetime.js';\n\n",
        );
    }

    // IID consts
    for iid in &file.iid_consts {
        let prefix = if iid.exported {
            "export const"
        } else {
            "const"
        };
        out.push_str(&format!("{} {} = {};\n", prefix, iid.name, iid.rhs_expr));
    }
    if !file.iid_consts.is_empty() {
        out.push('\n');
    }

    // Interface registrations
    for reg in &file.registrations {
        out.push_str(reg);
        out.push('\n');
    }

    // Activation factory (if needed)
    if file.needs_activation_factory {
        out.push_str("const _IActivationFactory = DynWinRtType.registerInterface('IActivationFactory', WinGuid.parse('00000035-0000-0000-c000-000000000046'))\n    .addMethod('ActivateInstance', new DynWinRtMethodSig().addOut(DynWinRtType.object()));\n");
        out.push_str("let __activateInstance;\nconst __get_ActivateInstance = () => (__activateInstance ??= _IActivationFactory.method(6));\n");
        out.push('\n');
    }

    // Struct helpers — deduplicate by name
    let mut seen_structs: std::collections::HashSet<String> = std::collections::HashSet::new();
    for s in &file.structs {
        if seen_structs.insert(s.name.clone()) {
            render_struct_js(&mut out, s);
            out.push('\n');
        }
    }

    // Classes
    for class in &file.classes {
        render_class_js(&mut out, class);

        // Required interface inline wrappers
        for ri in &class.required_ifaces {
            out.push('\n');
            render_required_iface_js(&mut out, ri);
        }
    }

    // Standalone interfaces
    for iface in &file.ifaces {
        render_iface_js(&mut out, iface, file);
    }

    // Enums
    for en in &file.enums {
        render_enum_js(&mut out, en);
    }

    // Inject _unwrap if used
    if file.needs_unwrap_helper {
        out = inject_unwrap(out);
    }

    out
}

fn render_delegate_js(out: &mut String, file: &ProjectedFile) {
    // Import — deduplicate, skip dts_only
    let mut seen_symbols: std::collections::HashSet<String> = std::collections::HashSet::new();
    for imp in &file.imports {
        if imp.dts_only {
            continue;
        }
        let deduped: Vec<&str> = imp
            .symbols
            .iter()
            .filter(|s| seen_symbols.insert(s.to_string()))
            .map(|s| s.as_str())
            .collect();
        if !deduped.is_empty() {
            out.push_str(&format!(
                "import {{ {} }} from '{}';\n",
                deduped.join(", "),
                imp.from
            ));
        }
    }
    out.push('\n');
    for d in &file.delegates {
        out.push_str(&format!("export const IID_{} = {};\n", d.name, d.iid_rhs));
        if d.has_param_types {
            out.push_str(&format!(
                "export const {}_PARAM_TYPES = {};\n",
                d.name, d.param_types_expr
            ));
        }
    }
}

fn render_struct_js(out: &mut String, s: &ProjectedStruct) {
    // unpack function
    out.push_str(&format!("export function unpack{}(v) {{\n", s.name));
    for line in &s.unpack_body {
        out.push_str(&format!("    {}\n", line));
    }
    out.push_str("}\n");
    out.push_str(&format!("const _unpack{0} = unpack{0};\n", s.name));

    // Type constant
    out.push_str(&format!(
        "export const {}_Type = {};\n",
        s.name, s.type_expr
    ));
    out.push_str(&format!("const _{0}_Type = {0}_Type;\n", s.name));

    // pack function
    out.push_str(&format!("export function pack{}(v) {{\n", s.name));
    for line in &s.pack_body {
        out.push_str(&format!("    {}\n", line));
    }
    out.push_str("}\n");
    out.push_str(&format!("const _pack{0} = pack{0};\n", s.name));
}

fn render_class_js(out: &mut String, class: &ProjectedClass) {
    // JSDoc for class
    if let Some(ref doc) = class.doc {
        out.push_str(&render_jsdoc(doc, ""));
    }
    out.push_str(&format!("export class {} {{\n", class.name));
    out.push_str("    _obj;\n");

    // Static cache fields + accessors
    for field in &class.static_cache_fields {
        out.push_str(&format!("    {}\n", field));
    }
    for accessor in &class.static_accessors {
        out.push_str(&format!("    {}\n", accessor));
    }

    // Collect member names from main class for overload detection.
    // Include Symbol names (toString, etc.) to prevent duplicates from required interfaces.
    let main_methods: std::collections::HashMap<String, usize> = class
        .members
        .iter()
        .filter_map(|m| match m {
            ProjectedMember::Method(method) => Some((method.name.clone(), method.params.len())),
            ProjectedMember::Symbol(s) => Some((
                crate::codegen::winrt::javascript::project::symbol_dedup_key(&s.kind),
                0,
            )),
            ProjectedMember::Close { .. } => Some(("close".into(), 0)),
            ProjectedMember::AsCast => Some(("as".into(), 0)),
            ProjectedMember::Property(p) => Some((p.name.clone(), 0)),
            _ => None,
        })
        .collect();

    // Collect overloads from required interfaces that share a name with a main class method
    let mut overloaded_methods: std::collections::HashMap<String, Vec<(&ProjectedMethod, &str)>> =
        std::collections::HashMap::new();
    for ri in &class.required_ifaces {
        for member in &ri.members {
            if let ProjectedMember::Method(method) = member {
                if main_methods.contains_key(&method.name) && !method.js_only {
                    overloaded_methods
                        .entry(method.name.clone())
                        .or_default()
                        .push((method, &ri.name));
                }
            }
        }
    }

    // Members — handle same-name overloads (from OverloadAttribute merging)
    out.push('\n');
    let mut emitted_names: std::collections::HashSet<String> = std::collections::HashSet::new();
    // Group same-name methods within class.members
    let mut same_class_groups: std::collections::HashMap<String, Vec<usize>> =
        std::collections::HashMap::new();
    for (i, member) in class.members.iter().enumerate() {
        if let ProjectedMember::Method(method) = member {
            if !method.js_only {
                same_class_groups
                    .entry(method.name.clone())
                    .or_default()
                    .push(i);
            }
        }
    }

    for (i, member) in class.members.iter().enumerate() {
        if let ProjectedMember::Method(method) = member {
            // Skip if already emitted as part of a group
            if !emitted_names.insert(method.name.clone()) {
                continue;
            }

            // Check for same-class overloads first (OverloadAttribute / numeric suffix merge)
            let group = same_class_groups.get(&method.name);
            if let Some(indices) = group {
                if indices.len() > 1 {
                    let others: Vec<&ProjectedMethod> = indices
                        .iter()
                        .filter(|&&j| j != i)
                        .filter_map(|&j| {
                            if let ProjectedMember::Method(m) = &class.members[j] {
                                Some(m)
                            } else {
                                None
                            }
                        })
                        .collect();
                    render_same_class_overload_js(out, method, &others);
                    continue;
                }
            }

            // Check for cross-interface overloads
            if let Some(overloads) = overloaded_methods.get(&method.name) {
                render_overload_dispatcher_js(out, method, overloads, &class.name);
                continue;
            }
        }
        render_member_js(out, member, &class.name);
    }
    out.push_str("}\n");
}

fn render_iface_js(out: &mut String, iface: &ProjectedIface, _file: &ProjectedFile) {
    if let Some(ref doc) = iface.doc {
        out.push_str(&render_jsdoc(doc, ""));
    }
    out.push_str(&format!("export class {} {{\n", iface.name));
    out.push_str("    _obj;\n\n");

    // Constructor
    if iface.has_parameterized_cast {
        out.push_str("    constructor(obj) {\n");
        out.push_str(&format!(
            "        this._obj = obj.cast(IID_{});\n",
            iface.name
        ));
        out.push_str("    }\n");
    } else {
        out.push_str("    constructor(obj) {\n");
        out.push_str("        this._obj = obj;\n");
        out.push_str("    }\n");
    }

    // static from()
    if iface.has_static_from {
        out.push('\n');
        out.push_str(&format!(
            "    static from(obj) {{\n        return new {}(obj.cast(IID_{}));\n    }}\n",
            iface.name, iface.name
        ));
    }

    // Members
    for member in &iface.members {
        out.push('\n');
        render_member_js(out, member, &iface.name);
    }

    // IID const exported at file level, not within the class — handled in render()
    // so we just need the file.iid_consts to contain it

    out.push_str("}\n");
}

fn render_required_iface_js(out: &mut String, ri: &ProjectedRequiredIface) {
    out.push_str(&format!("export class {} {{\n", ri.name));
    out.push_str("    _obj;\n\n");
    out.push_str("    constructor(obj) {\n");
    out.push_str("        this._obj = obj;\n");
    out.push_str("    }\n\n");
    out.push_str(&format!(
        "    static from(obj) {{\n        return new {}(obj.cast(IID_{}));\n    }}\n",
        ri.name, ri.name
    ));
    for member in &ri.members {
        out.push('\n');
        render_member_js(out, member, &ri.name);
    }
    out.push_str("}\n");
}

fn render_member_js(out: &mut String, member: &ProjectedMember, _class_name: &str) {
    match member {
        ProjectedMember::Constructor(ctor) => {
            let params_str = if ctor.overloads.is_empty() {
                ""
            } else {
                "...args"
            };
            out.push_str(&format!("    constructor({}) {{\n", params_str));
            for line in &ctor.body_lines {
                out.push_str(&format!("        {}\n", line));
            }
            out.push_str("    }\n");
        }
        ProjectedMember::Property(prop) => {
            if let Some(ref doc) = prop.doc {
                out.push_str(&render_jsdoc(doc, "    "));
            }
            let static_kw = if prop.is_static { "static " } else { "" };
            if !prop.getter_expr.is_empty() {
                out.push_str(&format!("    {}get {}() {{\n", static_kw, prop.name));
                out.push_str(&format!("        return {};\n", prop.getter_expr));
                out.push_str("    }\n");
            }
            if let Some(ref setter) = prop.setter_line {
                out.push_str(&format!("    {}set {}(value) {{\n", static_kw, prop.name));
                out.push_str(&format!("        {}\n", setter));
                out.push_str("    }\n");
            }
        }
        ProjectedMember::Method(method) => {
            if let Some(ref doc) = method.doc {
                out.push_str(&render_jsdoc(doc, "    "));
            }
            let params_str = method
                .params
                .iter()
                .map(|p| p.name.as_str())
                .collect::<Vec<_>>()
                .join(", ");
            let static_kw = if method.is_static { "static " } else { "" };
            let async_kw = match method.async_kind {
                AsyncKind::Action | AsyncKind::Operation(_) => "async ",
                _ => "",
            };
            out.push_str(&format!(
                "    {}{}{}({}) {{\n",
                static_kw, async_kw, method.name, params_str
            ));

            emit_delegate_wraps(out, method);

            match &method.async_kind {
                AsyncKind::None => {
                    if let Some(ref arr_expr) = method.array_return_expr {
                        out.push_str(&format!("        return {};\n", arr_expr));
                    } else if method.is_void {
                        out.push_str(&format!("        {};\n", method.invoke_expr));
                    } else if let Some(ref ret) = method.sync_return_expr {
                        out.push_str(&format!("        return {};\n", ret));
                    }
                }
                AsyncKind::Action => {
                    emit_abortable_async_body(out, &method.invoke_expr, "", true);
                }
                AsyncKind::Operation(_) => {
                    let convert = method.async_convert_v.as_deref().unwrap_or("_v");
                    emit_abortable_async_body(out, &method.invoke_expr, convert, false);
                }
                AsyncKind::ActionWithProgress(_) => {
                    let convert = method.async_convert_v.as_deref().unwrap_or("undefined");
                    emit_with_progress_body(
                        out,
                        &method.invoke_expr,
                        convert,
                        true,
                        method.progress_convert.as_deref(),
                    );
                }
                AsyncKind::OperationWithProgress(_, _) => {
                    let convert = method.async_convert_v.as_deref().unwrap_or("_v");
                    emit_with_progress_body(
                        out,
                        &method.invoke_expr,
                        convert,
                        false,
                        method.progress_convert.as_deref(),
                    );
                }
            }
            out.push_str("    }\n");
        }
        ProjectedMember::Event(event) => {
            // Subscribe (onX)
            if !event.subscribe_name.is_empty() {
                if let Some(ref doc) = event.doc {
                    out.push_str(&render_jsdoc(doc, "    "));
                }
                out.push_str(&format!("    {}(callback) {{\n", event.subscribe_name));
                if event.needs_wrap {
                    let s_expr = event.sender_wrap.as_deref().unwrap_or("__a0__");
                    let a_expr = event.args_wrap.as_deref().unwrap_or("__a1__");
                    out.push_str(&format!(
                        "        const wrapped = (__a0__, __a1__) => callback({}, {});\n",
                        s_expr, a_expr
                    ));
                } else {
                    out.push_str("        const wrapped = callback;\n");
                }
                if let Some(ref dname) = event.delegate_name {
                    out.push_str(&format!(
                        "        const handler = DynWinRtDelegate.create(IID_{}, {}_PARAM_TYPES, wrapped);\n",
                        dname, dname
                    ));
                } else {
                    out.push_str(
                        "        const handler = DynWinRtDelegate.create(DynWinRtType.object().iid(), [DynWinRtType.object(), DynWinRtType.object()], wrapped);\n"
                    );
                }
                out.push_str(&format!(
                    "        const __token = {}.method({}).invoke({}, [handler.toValue()]);\n",
                    event.add_iface_var, event.add_vtable_index, event.add_obj_expr
                ));
                if let Some(idx) = event.remove_vtable_index {
                    out.push_str(&format!(
                        "        return () => {{ void handler; {}.method({}).invoke({}, [__token]); }};\n",
                        event.remove_iface_var, idx, event.remove_obj_expr
                    ));
                } else {
                    let cap = event
                        .subscribe_name
                        .strip_prefix("on")
                        .unwrap_or(&event.subscribe_name);
                    out.push_str(&format!(
                        "        return () => {{ void handler; this.off{}(__token); }};\n",
                        cap
                    ));
                }
                out.push_str("    }\n");

                // onceXxx — subscribe and auto-unsubscribe after first call
                let once_name = format!(
                    "once{}",
                    event
                        .subscribe_name
                        .strip_prefix("on")
                        .unwrap_or(&event.subscribe_name)
                );
                out.push_str(&format!("    {}(callback) {{\n", once_name));
                out.push_str(&format!("        const unsub = this.{}((...args) => {{ unsub(); callback(...args); }});\n", event.subscribe_name));
                out.push_str("        return unsub;\n");
                out.push_str("    }\n");

                // offXxx — token-based unsubscribe. DTS advertises this even
                // when the event has both add and remove; keep JS in sync so
                // consumers who saved the raw token can call off explicitly.
                if let Some(idx) = event.remove_vtable_index {
                    let event_name = event
                        .subscribe_name
                        .strip_prefix("on")
                        .unwrap_or(&event.subscribe_name);
                    let off_name = format!("off{}", event_name);
                    out.push_str(&format!("    {}(token) {{\n", off_name));
                    out.push_str(&format!(
                        "        {}.method({}).invoke({}, [token]);\n",
                        event.remove_iface_var, idx, event.remove_obj_expr
                    ));
                    out.push_str("    }\n");
                }
            }
            // Unsubscribe (offX) — standalone event remove
            if event.subscribe_name.is_empty() && !event.unsubscribe_name.is_empty() {
                out.push_str(&format!("    {}(token) {{\n", event.unsubscribe_name));
                out.push_str(&format!(
                    "        {}.method({}).invoke({}, [token]);\n",
                    event.remove_iface_var,
                    event.remove_vtable_index.unwrap_or(0),
                    event.remove_obj_expr
                ));
                out.push_str("    }\n");
            }
        }
        ProjectedMember::Symbol(symbol) => {
            match &symbol.kind {
                SymbolKind::ToString { iface_name } => {
                    out.push_str(&format!(
                        "    toString() {{\n        return {}.from(this._obj).toString();\n    }}\n",
                        ref_marker(iface_name)
                    ));
                }
                SymbolKind::ToPrimitive => {
                    out.push_str("    [Symbol.toPrimitive](_hint) {\n        return this.toString();\n    }\n");
                }
                SymbolKind::ToStringTag { tag } => {
                    out.push_str(&format!(
                        "    get [Symbol.toStringTag]() {{ return '{}'; }}\n",
                        tag
                    ));
                }
                SymbolKind::Iterator { body_lines, .. } => {
                    if body_lines.is_empty() {
                        // IIterable: delegate to first() which returns the IIterator
                        out.push_str("    [Symbol.iterator]() { return this.first(); }\n");
                    } else if body_lines.len() == 1 && body_lines[0].starts_with("return ") {
                        // Simple return (e.g. IIterator: return this)
                        out.push_str(&format!(
                            "    [Symbol.iterator]() {{ {} }}\n",
                            body_lines[0]
                        ));
                    } else {
                        // Generator function (e.g. IVector: yield elements)
                        out.push_str("    *[Symbol.iterator]() {\n");
                        for line in body_lines {
                            out.push_str(&format!("        {}\n", line));
                        }
                        out.push_str("    }\n");
                    }
                }
                SymbolKind::CollectionLength => {
                    if let Some(ref doc) = symbol.doc {
                        out.push_str(&format!("    /** {} */\n", doc));
                    }
                    out.push_str("    get length() { return this.size; }\n");
                }
                SymbolKind::CollectionAt { .. } => {
                    if let Some(ref doc) = symbol.doc {
                        out.push_str(&format!("    /** {} */\n", doc));
                    }
                    out.push_str("    at(index) {\n");
                    out.push_str("        const n = this.size;\n");
                    out.push_str("        const i = index < 0 ? n + index : index;\n");
                    out.push_str("        if (i < 0 || i >= n) return undefined;\n");
                    out.push_str("        return this.getAt(i);\n");
                    out.push_str("    }\n");
                }
                SymbolKind::CollectionToArray { .. } => {
                    if let Some(ref doc) = symbol.doc {
                        out.push_str(&format!("    /** {} */\n", doc));
                    }
                    out.push_str("    toArray() {\n");
                    out.push_str("        const n = this.size;\n");
                    out.push_str("        const out = new Array(n);\n");
                    out.push_str("        for (let i = 0; i < n; i++) out[i] = this.getAt(i);\n");
                    out.push_str("        return out;\n");
                    out.push_str("    }\n");
                }
                SymbolKind::IteratorNext { .. } => {
                    if let Some(ref doc) = symbol.doc {
                        out.push_str(&format!("    /** {} */\n", doc));
                    }
                    out.push_str("    next() {\n");
                    out.push_str(
                        "        if (!this.hasCurrent) return { value: undefined, done: true };\n",
                    );
                    out.push_str("        const value = this.current;\n");
                    out.push_str("        this.moveNext();\n");
                    out.push_str("        return { value, done: false };\n");
                    out.push_str("    }\n");
                }
            }
        }
        ProjectedMember::AsCast => {
            out.push_str("    as(InterfaceClass) {\n");
            out.push_str("        return InterfaceClass.from(this._obj);\n");
            out.push_str("    }\n");
        }
        ProjectedMember::Close { interface_name } => {
            out.push_str("    close() {\n");
            out.push_str(&format!(
                "        {}.from(this._obj).close();\n",
                ref_marker(interface_name)
            ));
            out.push_str("    }\n");
        }
    }
}

fn render_enum_js(out: &mut String, en: &ProjectedEnum) {
    if let Some(ref doc) = en.doc {
        out.push_str(&render_jsdoc(doc, ""));
    }
    out.push_str(&format!("export const {} = Object.freeze({{\n", en.name));
    for member in &en.members {
        if let Some(ref doc) = member.doc {
            let di = DocInfo {
                summary: Some(doc.clone()),
                deprecated: None,
                returns: None,
                params: vec![],
            };
            out.push_str(&render_jsdoc(&di, "    "));
        }
        out.push_str(&format!("    {}: {},\n", member.name, member.value));
    }
    out.push_str("});\n");
}
