// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, WinGuid } from '../dist/index.js';
import { ISystemMediaTransportControlsInterop } from './ISystemMediaTransportControlsInterop.js';

const IID_IInspectable = WinGuid.parse('af86e2e0-b12d-4c6a-9c5a-d7aa65101e90');

let _IInspectableCache;
const _IInspectable = new Proxy({}, {
    get(_target, prop) {
        _IInspectableCache ??= DynWinRtType.registerInterfaceUnknown('IInspectable_projected', IID_IInspectable)
            .addMethod('GetIids', new DynWinRtMethodSig().addOut(DynWinRtType.pointer()).addOut(DynWinRtType.pointer()))
            .addMethod('GetRuntimeClassName', new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
            .addMethod('GetTrustLevel', new DynWinRtMethodSig().addOut(DynWinRtType.i32Type()));
        const value = _IInspectableCache[prop];
        return typeof value === 'function' ? value.bind(_IInspectableCache) : value;
    },
});

export class SystemMediaTransportControls {
    _obj;
    constructor(obj) { this._obj = obj; }
    static _fromNative(obj) { return new SystemMediaTransportControls(obj); }
    /** Get a `SystemMediaTransportControls` for the given HWND via the ISystemMediaTransportControlsInterop interop. */
    static getForWindow(appWindow) {
        const interop = ISystemMediaTransportControlsInterop.create();
        return interop.getForWindow(appWindow);
    }
    /** IInspectable::GetRuntimeClassName — the projected class name. */
    get runtimeClassName() {
        return _IInspectable.method(4).getString(this._obj);
    }
}
