// Generated by dynwinrt-codegen — do not edit
// Flat-Win32 [DllImport] wrappers for Windows.Win32.System.Registry.Apis
//
// Each exported function is a natural JS wrapper around
// DynWinRtValue.flatInvoke(dll, entry, retKind, args). Pointer-to-scalar
// [out]/[in,out] params are projected as return-object fields; opaque
// pointer params (Buffer|bigint|null) stay in the argument list.

import { DynWinRtValue } from '@microsoft/dynwinrt';

// Build a NUL-terminated UTF-16LE Buffer for LPCWSTR args. Rejects embedded
// U+0000 up front — Win32 wide-string APIs would silently truncate at the
// first NUL, which is a source of validation-bypass bugs.
function _wideStringBuffer(str) {
    if (str === null || str === undefined) return null;
    if (typeof str !== 'string') {
        throw new TypeError(`expected string, got ${typeof str}`);
    }
    if (str.indexOf('\u0000') !== -1) {
        throw new RangeError('string contains embedded NUL (U+0000)');
    }
    const buf = Buffer.alloc((str.length + 1) * 2);
    buf.write(str, 'utf16le');
    return buf;
}

/**
 * GetRegistryValueWithFallbackW — api-ms-win-core-state-helpers-l1-1-0.dll export.
 *
 * @param hkeyPrimary  [in] HKEY handle
 * @param primarySubKey  [in] LPCWSTR string
 * @param hkeyFallback  [in] HKEY handle
 * @param fallbackSubKey  [in] LPCWSTR string
 * @param value  [in] LPCWSTR string
 * @param flags  [in] U32
 * @param pdwType  [out] pointer to U32
 * @param data  [in/out pointer] opaque pointer
 * @param dataIn  [in] U32
 * @param pcbDataOut  [out] pointer to U32
 * @returns { status: number, pdwType: <out>, pcbDataOut: <out> }
 */
export function getRegistryValueWithFallbackW(hkeyPrimary, primarySubKey, hkeyFallback, fallbackSubKey, value, flags, data, dataIn) {
    const _pdwTypeSlot = Buffer.alloc(4);
    const _pcbDataOutSlot = Buffer.alloc(4);
    const _ret = DynWinRtValue.flatInvoke('api-ms-win-core-state-helpers-l1-1-0.dll', 'GetRegistryValueWithFallbackW', 'I32', [DynWinRtValue.pointer(hkeyPrimary), DynWinRtValue.pointer(_wideStringBuffer(primarySubKey)), DynWinRtValue.pointer(hkeyFallback), DynWinRtValue.pointer(_wideStringBuffer(fallbackSubKey)), DynWinRtValue.pointer(_wideStringBuffer(value)), DynWinRtValue.u32(flags), DynWinRtValue.pointer(_pdwTypeSlot), DynWinRtValue.pointer(data), DynWinRtValue.u32(dataIn), DynWinRtValue.pointer(_pcbDataOutSlot)]);
    return {
        status: _ret.toNumber(),
        pdwType: _pdwTypeSlot.readUInt32LE(0),
        pcbDataOut: _pcbDataOutSlot.readUInt32LE(0),
    };
}

/**
 * RegCloseKey — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @returns { status: number }
 */
export function regCloseKey(hKey) {
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegCloseKey', 'I32', [DynWinRtValue.pointer(hKey)]);
    return { status: _ret.toNumber() };
}

/**
 * RegConnectRegistryA — ADVAPI32.dll export.
 *
 * @param machineName  [in] LPCSTR string
 * @param hKey  [in] HKEY handle
 * @param phkResult  [out] pointer to HKEY handle
 * @returns { status: number, phkResult: <out> }
 */
export function regConnectRegistryA(machineName, hKey) {
    const _phkResultSlot = Buffer.alloc(8);
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegConnectRegistryA', 'I32', [DynWinRtValue.pointer(_wideStringBuffer(machineName)), DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_phkResultSlot)]);
    return {
        status: _ret.toNumber(),
        phkResult: _phkResultSlot.readBigUInt64LE(0),
    };
}

/**
 * RegConnectRegistryExA — ADVAPI32.dll export.
 *
 * @param machineName  [in] LPCSTR string
 * @param hKey  [in] HKEY handle
 * @param flags  [in] U32
 * @param phkResult  [out] pointer to HKEY handle
 * @returns { status: number, phkResult: <out> }
 */
export function regConnectRegistryExA(machineName, hKey, flags) {
    const _phkResultSlot = Buffer.alloc(8);
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegConnectRegistryExA', 'I32', [DynWinRtValue.pointer(_wideStringBuffer(machineName)), DynWinRtValue.pointer(hKey), DynWinRtValue.u32(flags), DynWinRtValue.pointer(_phkResultSlot)]);
    return {
        status: _ret.toNumber(),
        phkResult: _phkResultSlot.readBigUInt64LE(0),
    };
}

/**
 * RegConnectRegistryExW — ADVAPI32.dll export.
 *
 * @param machineName  [in] LPCWSTR string
 * @param hKey  [in] HKEY handle
 * @param flags  [in] U32
 * @param phkResult  [out] pointer to HKEY handle
 * @returns { status: number, phkResult: <out> }
 */
export function regConnectRegistryExW(machineName, hKey, flags) {
    const _phkResultSlot = Buffer.alloc(8);
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegConnectRegistryExW', 'I32', [DynWinRtValue.pointer(_wideStringBuffer(machineName)), DynWinRtValue.pointer(hKey), DynWinRtValue.u32(flags), DynWinRtValue.pointer(_phkResultSlot)]);
    return {
        status: _ret.toNumber(),
        phkResult: _phkResultSlot.readBigUInt64LE(0),
    };
}

/**
 * RegConnectRegistryW — ADVAPI32.dll export.
 *
 * @param machineName  [in] LPCWSTR string
 * @param hKey  [in] HKEY handle
 * @param phkResult  [out] pointer to HKEY handle
 * @returns { status: number, phkResult: <out> }
 */
export function regConnectRegistryW(machineName, hKey) {
    const _phkResultSlot = Buffer.alloc(8);
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegConnectRegistryW', 'I32', [DynWinRtValue.pointer(_wideStringBuffer(machineName)), DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_phkResultSlot)]);
    return {
        status: _ret.toNumber(),
        phkResult: _phkResultSlot.readBigUInt64LE(0),
    };
}

/**
 * RegCopyTreeA — ADVAPI32.dll export.
 *
 * @param hKeySrc  [in] HKEY handle
 * @param subKey  [in] LPCSTR string
 * @param hKeyDest  [in] HKEY handle
 * @returns { status: number }
 */
export function regCopyTreeA(hKeySrc, subKey, hKeyDest) {
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegCopyTreeA', 'I32', [DynWinRtValue.pointer(hKeySrc), DynWinRtValue.pointer(_wideStringBuffer(subKey)), DynWinRtValue.pointer(hKeyDest)]);
    return { status: _ret.toNumber() };
}

/**
 * RegCopyTreeW — ADVAPI32.dll export.
 *
 * @param hKeySrc  [in] HKEY handle
 * @param subKey  [in] LPCWSTR string
 * @param hKeyDest  [in] HKEY handle
 * @returns { status: number }
 */
export function regCopyTreeW(hKeySrc, subKey, hKeyDest) {
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegCopyTreeW', 'I32', [DynWinRtValue.pointer(hKeySrc), DynWinRtValue.pointer(_wideStringBuffer(subKey)), DynWinRtValue.pointer(hKeyDest)]);
    return { status: _ret.toNumber() };
}

/**
 * RegCreateKeyA — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param subKey  [in] LPCSTR string
 * @param phkResult  [out] pointer to HKEY handle
 * @returns { status: number, phkResult: <out> }
 */
export function regCreateKeyA(hKey, subKey) {
    const _phkResultSlot = Buffer.alloc(8);
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegCreateKeyA', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(subKey)), DynWinRtValue.pointer(_phkResultSlot)]);
    return {
        status: _ret.toNumber(),
        phkResult: _phkResultSlot.readBigUInt64LE(0),
    };
}

/**
 * RegCreateKeyExA — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param subKey  [in] LPCSTR string
 * @param reserved  [in] U32
 * @param class_  [in] LPCSTR string
 * @param options  [in] REG_OPEN_CREATE_OPTIONS enum
 * @param samDesired  [in] REG_SAM_FLAGS enum
 * @param securityAttributes  [in/out pointer] pointer to Unknown
 * @param phkResult  [out] pointer to HKEY handle
 * @param lpdwDisposition  [out] pointer to REG_CREATE_KEY_DISPOSITION enum
 * @returns { status: number, phkResult: <out>, lpdwDisposition: <out> }
 */
export function regCreateKeyExA(hKey, subKey, reserved, class_, options, samDesired, securityAttributes) {
    const _phkResultSlot = Buffer.alloc(8);
    const _lpdwDispositionSlot = Buffer.alloc(4);
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegCreateKeyExA', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(subKey)), DynWinRtValue.u32(reserved), DynWinRtValue.pointer(_wideStringBuffer(class_)), DynWinRtValue.i32(options), DynWinRtValue.i32(samDesired), DynWinRtValue.pointer(securityAttributes), DynWinRtValue.pointer(_phkResultSlot), DynWinRtValue.pointer(_lpdwDispositionSlot)]);
    return {
        status: _ret.toNumber(),
        phkResult: _phkResultSlot.readBigUInt64LE(0),
        lpdwDisposition: _lpdwDispositionSlot.readInt32LE(0),
    };
}

/**
 * RegCreateKeyExW — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param subKey  [in] LPCWSTR string
 * @param reserved  [in] U32
 * @param class_  [in] LPCWSTR string
 * @param options  [in] REG_OPEN_CREATE_OPTIONS enum
 * @param samDesired  [in] REG_SAM_FLAGS enum
 * @param securityAttributes  [in/out pointer] pointer to Unknown
 * @param phkResult  [out] pointer to HKEY handle
 * @param lpdwDisposition  [out] pointer to REG_CREATE_KEY_DISPOSITION enum
 * @returns { status: number, phkResult: <out>, lpdwDisposition: <out> }
 */
export function regCreateKeyExW(hKey, subKey, reserved, class_, options, samDesired, securityAttributes) {
    const _phkResultSlot = Buffer.alloc(8);
    const _lpdwDispositionSlot = Buffer.alloc(4);
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegCreateKeyExW', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(subKey)), DynWinRtValue.u32(reserved), DynWinRtValue.pointer(_wideStringBuffer(class_)), DynWinRtValue.i32(options), DynWinRtValue.i32(samDesired), DynWinRtValue.pointer(securityAttributes), DynWinRtValue.pointer(_phkResultSlot), DynWinRtValue.pointer(_lpdwDispositionSlot)]);
    return {
        status: _ret.toNumber(),
        phkResult: _phkResultSlot.readBigUInt64LE(0),
        lpdwDisposition: _lpdwDispositionSlot.readInt32LE(0),
    };
}

/**
 * RegCreateKeyTransactedA — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param subKey  [in] LPCSTR string
 * @param reserved  [in] U32
 * @param class_  [in] LPCSTR string
 * @param options  [in] REG_OPEN_CREATE_OPTIONS enum
 * @param samDesired  [in] REG_SAM_FLAGS enum
 * @param securityAttributes  [in/out pointer] pointer to Unknown
 * @param phkResult  [out] pointer to HKEY handle
 * @param lpdwDisposition  [out] pointer to REG_CREATE_KEY_DISPOSITION enum
 * @param hTransaction  [in] HANDLE handle
 * @param pExtendedParemeter  [in/out pointer] opaque pointer
 * @returns { status: number, phkResult: <out>, lpdwDisposition: <out> }
 */
export function regCreateKeyTransactedA(hKey, subKey, reserved, class_, options, samDesired, securityAttributes, hTransaction, pExtendedParemeter) {
    const _phkResultSlot = Buffer.alloc(8);
    const _lpdwDispositionSlot = Buffer.alloc(4);
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegCreateKeyTransactedA', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(subKey)), DynWinRtValue.u32(reserved), DynWinRtValue.pointer(_wideStringBuffer(class_)), DynWinRtValue.i32(options), DynWinRtValue.i32(samDesired), DynWinRtValue.pointer(securityAttributes), DynWinRtValue.pointer(_phkResultSlot), DynWinRtValue.pointer(_lpdwDispositionSlot), DynWinRtValue.pointer(hTransaction), DynWinRtValue.pointer(pExtendedParemeter)]);
    return {
        status: _ret.toNumber(),
        phkResult: _phkResultSlot.readBigUInt64LE(0),
        lpdwDisposition: _lpdwDispositionSlot.readInt32LE(0),
    };
}

/**
 * RegCreateKeyTransactedW — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param subKey  [in] LPCWSTR string
 * @param reserved  [in] U32
 * @param class_  [in] LPCWSTR string
 * @param options  [in] REG_OPEN_CREATE_OPTIONS enum
 * @param samDesired  [in] REG_SAM_FLAGS enum
 * @param securityAttributes  [in/out pointer] pointer to Unknown
 * @param phkResult  [out] pointer to HKEY handle
 * @param lpdwDisposition  [out] pointer to REG_CREATE_KEY_DISPOSITION enum
 * @param hTransaction  [in] HANDLE handle
 * @param pExtendedParemeter  [in/out pointer] opaque pointer
 * @returns { status: number, phkResult: <out>, lpdwDisposition: <out> }
 */
export function regCreateKeyTransactedW(hKey, subKey, reserved, class_, options, samDesired, securityAttributes, hTransaction, pExtendedParemeter) {
    const _phkResultSlot = Buffer.alloc(8);
    const _lpdwDispositionSlot = Buffer.alloc(4);
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegCreateKeyTransactedW', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(subKey)), DynWinRtValue.u32(reserved), DynWinRtValue.pointer(_wideStringBuffer(class_)), DynWinRtValue.i32(options), DynWinRtValue.i32(samDesired), DynWinRtValue.pointer(securityAttributes), DynWinRtValue.pointer(_phkResultSlot), DynWinRtValue.pointer(_lpdwDispositionSlot), DynWinRtValue.pointer(hTransaction), DynWinRtValue.pointer(pExtendedParemeter)]);
    return {
        status: _ret.toNumber(),
        phkResult: _phkResultSlot.readBigUInt64LE(0),
        lpdwDisposition: _lpdwDispositionSlot.readInt32LE(0),
    };
}

/**
 * RegCreateKeyW — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param subKey  [in] LPCWSTR string
 * @param phkResult  [out] pointer to HKEY handle
 * @returns { status: number, phkResult: <out> }
 */
export function regCreateKeyW(hKey, subKey) {
    const _phkResultSlot = Buffer.alloc(8);
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegCreateKeyW', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(subKey)), DynWinRtValue.pointer(_phkResultSlot)]);
    return {
        status: _ret.toNumber(),
        phkResult: _phkResultSlot.readBigUInt64LE(0),
    };
}

/**
 * RegDeleteKeyA — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param subKey  [in] LPCSTR string
 * @returns { status: number }
 */
export function regDeleteKeyA(hKey, subKey) {
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegDeleteKeyA', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(subKey))]);
    return { status: _ret.toNumber() };
}

/**
 * RegDeleteKeyExA — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param subKey  [in] LPCSTR string
 * @param samDesired  [in] U32
 * @param reserved  [in] U32
 * @returns { status: number }
 */
export function regDeleteKeyExA(hKey, subKey, samDesired, reserved) {
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegDeleteKeyExA', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(subKey)), DynWinRtValue.u32(samDesired), DynWinRtValue.u32(reserved)]);
    return { status: _ret.toNumber() };
}

/**
 * RegDeleteKeyExW — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param subKey  [in] LPCWSTR string
 * @param samDesired  [in] U32
 * @param reserved  [in] U32
 * @returns { status: number }
 */
export function regDeleteKeyExW(hKey, subKey, samDesired, reserved) {
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegDeleteKeyExW', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(subKey)), DynWinRtValue.u32(samDesired), DynWinRtValue.u32(reserved)]);
    return { status: _ret.toNumber() };
}

/**
 * RegDeleteKeyTransactedA — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param subKey  [in] LPCSTR string
 * @param samDesired  [in] U32
 * @param reserved  [in] U32
 * @param hTransaction  [in] HANDLE handle
 * @param pExtendedParameter  [in/out pointer] opaque pointer
 * @returns { status: number }
 */
export function regDeleteKeyTransactedA(hKey, subKey, samDesired, reserved, hTransaction, pExtendedParameter) {
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegDeleteKeyTransactedA', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(subKey)), DynWinRtValue.u32(samDesired), DynWinRtValue.u32(reserved), DynWinRtValue.pointer(hTransaction), DynWinRtValue.pointer(pExtendedParameter)]);
    return { status: _ret.toNumber() };
}

/**
 * RegDeleteKeyTransactedW — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param subKey  [in] LPCWSTR string
 * @param samDesired  [in] U32
 * @param reserved  [in] U32
 * @param hTransaction  [in] HANDLE handle
 * @param pExtendedParameter  [in/out pointer] opaque pointer
 * @returns { status: number }
 */
export function regDeleteKeyTransactedW(hKey, subKey, samDesired, reserved, hTransaction, pExtendedParameter) {
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegDeleteKeyTransactedW', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(subKey)), DynWinRtValue.u32(samDesired), DynWinRtValue.u32(reserved), DynWinRtValue.pointer(hTransaction), DynWinRtValue.pointer(pExtendedParameter)]);
    return { status: _ret.toNumber() };
}

/**
 * RegDeleteKeyValueA — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param subKey  [in] LPCSTR string
 * @param valueName  [in] LPCSTR string
 * @returns { status: number }
 */
export function regDeleteKeyValueA(hKey, subKey, valueName) {
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegDeleteKeyValueA', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(subKey)), DynWinRtValue.pointer(_wideStringBuffer(valueName))]);
    return { status: _ret.toNumber() };
}

/**
 * RegDeleteKeyValueW — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param subKey  [in] LPCWSTR string
 * @param valueName  [in] LPCWSTR string
 * @returns { status: number }
 */
export function regDeleteKeyValueW(hKey, subKey, valueName) {
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegDeleteKeyValueW', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(subKey)), DynWinRtValue.pointer(_wideStringBuffer(valueName))]);
    return { status: _ret.toNumber() };
}

/**
 * RegDeleteKeyW — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param subKey  [in] LPCWSTR string
 * @returns { status: number }
 */
export function regDeleteKeyW(hKey, subKey) {
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegDeleteKeyW', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(subKey))]);
    return { status: _ret.toNumber() };
}

/**
 * RegDeleteTreeA — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param subKey  [in] LPCSTR string
 * @returns { status: number }
 */
export function regDeleteTreeA(hKey, subKey) {
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegDeleteTreeA', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(subKey))]);
    return { status: _ret.toNumber() };
}

/**
 * RegDeleteTreeW — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param subKey  [in] LPCWSTR string
 * @returns { status: number }
 */
export function regDeleteTreeW(hKey, subKey) {
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegDeleteTreeW', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(subKey))]);
    return { status: _ret.toNumber() };
}

/**
 * RegDeleteValueA — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param valueName  [in] LPCSTR string
 * @returns { status: number }
 */
export function regDeleteValueA(hKey, valueName) {
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegDeleteValueA', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(valueName))]);
    return { status: _ret.toNumber() };
}

/**
 * RegDeleteValueW — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param valueName  [in] LPCWSTR string
 * @returns { status: number }
 */
export function regDeleteValueW(hKey, valueName) {
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegDeleteValueW', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(valueName))]);
    return { status: _ret.toNumber() };
}

/**
 * RegDisablePredefinedCache — ADVAPI32.dll export.
 *
 * @returns { status: number }
 */
export function regDisablePredefinedCache() {
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegDisablePredefinedCache', 'I32', []);
    return { status: _ret.toNumber() };
}

/**
 * RegDisablePredefinedCacheEx — ADVAPI32.dll export.
 *
 * @returns { status: number }
 */
export function regDisablePredefinedCacheEx() {
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegDisablePredefinedCacheEx', 'I32', []);
    return { status: _ret.toNumber() };
}

/**
 * RegDisableReflectionKey — ADVAPI32.dll export.
 *
 * @param hBase  [in] HKEY handle
 * @returns { status: number }
 */
export function regDisableReflectionKey(hBase) {
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegDisableReflectionKey', 'I32', [DynWinRtValue.pointer(hBase)]);
    return { status: _ret.toNumber() };
}

/**
 * RegEnableReflectionKey — ADVAPI32.dll export.
 *
 * @param hBase  [in] HKEY handle
 * @returns { status: number }
 */
export function regEnableReflectionKey(hBase) {
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegEnableReflectionKey', 'I32', [DynWinRtValue.pointer(hBase)]);
    return { status: _ret.toNumber() };
}

/**
 * RegEnumKeyA — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param index  [in] U32
 * @param name  [in] LPCSTR string
 * @param cchName  [in] U32
 * @returns { status: number }
 */
export function regEnumKeyA(hKey, index, name, cchName) {
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegEnumKeyA', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.u32(index), DynWinRtValue.pointer(_wideStringBuffer(name)), DynWinRtValue.u32(cchName)]);
    return { status: _ret.toNumber() };
}

/**
 * RegEnumKeyExA — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param index  [in] U32
 * @param name  [in] LPCSTR string
 * @param lpcchName  [in,out] pointer to U32
 * @param reserved  [in/out pointer] pointer to U32
 * @param class_  [in] LPCSTR string
 * @param lpcchClass  [in,out] pointer to U32
 * @param lpftLastWriteTime  [in/out pointer] pointer to Unknown
 * @returns { status: number, lpcchName: <out>, lpcchClass: <out> }
 */
export function regEnumKeyExA(hKey, index, name, lpcchName, reserved, class_, lpcchClass, lpftLastWriteTime) {
    const _lpcchNameSlot = Buffer.alloc(4);
    _lpcchNameSlot.writeUInt32LE(lpcchName, 0);
    const _lpcchClassSlot = Buffer.alloc(4);
    _lpcchClassSlot.writeUInt32LE(lpcchClass, 0);
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegEnumKeyExA', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.u32(index), DynWinRtValue.pointer(_wideStringBuffer(name)), DynWinRtValue.pointer(_lpcchNameSlot), DynWinRtValue.pointer(reserved), DynWinRtValue.pointer(_wideStringBuffer(class_)), DynWinRtValue.pointer(_lpcchClassSlot), DynWinRtValue.pointer(lpftLastWriteTime)]);
    return {
        status: _ret.toNumber(),
        lpcchName: _lpcchNameSlot.readUInt32LE(0),
        lpcchClass: _lpcchClassSlot.readUInt32LE(0),
    };
}

/**
 * RegEnumKeyExW — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param index  [in] U32
 * @param name  [in] LPCWSTR string
 * @param lpcchName  [in,out] pointer to U32
 * @param reserved  [in/out pointer] pointer to U32
 * @param class_  [in] LPCWSTR string
 * @param lpcchClass  [in,out] pointer to U32
 * @param lpftLastWriteTime  [in/out pointer] pointer to Unknown
 * @returns { status: number, lpcchName: <out>, lpcchClass: <out> }
 */
export function regEnumKeyExW(hKey, index, name, lpcchName, reserved, class_, lpcchClass, lpftLastWriteTime) {
    const _lpcchNameSlot = Buffer.alloc(4);
    _lpcchNameSlot.writeUInt32LE(lpcchName, 0);
    const _lpcchClassSlot = Buffer.alloc(4);
    _lpcchClassSlot.writeUInt32LE(lpcchClass, 0);
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegEnumKeyExW', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.u32(index), DynWinRtValue.pointer(_wideStringBuffer(name)), DynWinRtValue.pointer(_lpcchNameSlot), DynWinRtValue.pointer(reserved), DynWinRtValue.pointer(_wideStringBuffer(class_)), DynWinRtValue.pointer(_lpcchClassSlot), DynWinRtValue.pointer(lpftLastWriteTime)]);
    return {
        status: _ret.toNumber(),
        lpcchName: _lpcchNameSlot.readUInt32LE(0),
        lpcchClass: _lpcchClassSlot.readUInt32LE(0),
    };
}

/**
 * RegEnumKeyW — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param index  [in] U32
 * @param name  [in] LPCWSTR string
 * @param cchName  [in] U32
 * @returns { status: number }
 */
export function regEnumKeyW(hKey, index, name, cchName) {
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegEnumKeyW', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.u32(index), DynWinRtValue.pointer(_wideStringBuffer(name)), DynWinRtValue.u32(cchName)]);
    return { status: _ret.toNumber() };
}

/**
 * RegEnumValueA — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param index  [in] U32
 * @param valueName  [in] LPCSTR string
 * @param lpcchValueName  [in,out] pointer to U32
 * @param reserved  [in/out pointer] pointer to U32
 * @param type  [out] pointer to U32
 * @param data  [in/out pointer] pointer to U8
 * @param lpcbData  [in,out] pointer to U32
 * @returns { status: number, lpcchValueName: <out>, lpType: <out>, lpcbData: <out> }
 */
export function regEnumValueA(hKey, index, valueName, lpcchValueName, reserved, data, lpcbData) {
    const _lpcchValueNameSlot = Buffer.alloc(4);
    _lpcchValueNameSlot.writeUInt32LE(lpcchValueName, 0);
    const _typeSlot = Buffer.alloc(4);
    const _lpcbDataSlot = Buffer.alloc(4);
    _lpcbDataSlot.writeUInt32LE(lpcbData, 0);
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegEnumValueA', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.u32(index), DynWinRtValue.pointer(_wideStringBuffer(valueName)), DynWinRtValue.pointer(_lpcchValueNameSlot), DynWinRtValue.pointer(reserved), DynWinRtValue.pointer(_typeSlot), DynWinRtValue.pointer(data), DynWinRtValue.pointer(_lpcbDataSlot)]);
    return {
        status: _ret.toNumber(),
        lpcchValueName: _lpcchValueNameSlot.readUInt32LE(0),
        type: _typeSlot.readUInt32LE(0),
        lpcbData: _lpcbDataSlot.readUInt32LE(0),
    };
}

/**
 * RegEnumValueW — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param index  [in] U32
 * @param valueName  [in] LPCWSTR string
 * @param lpcchValueName  [in,out] pointer to U32
 * @param reserved  [in/out pointer] pointer to U32
 * @param type  [out] pointer to U32
 * @param data  [in/out pointer] pointer to U8
 * @param lpcbData  [in,out] pointer to U32
 * @returns { status: number, lpcchValueName: <out>, lpType: <out>, lpcbData: <out> }
 */
export function regEnumValueW(hKey, index, valueName, lpcchValueName, reserved, data, lpcbData) {
    const _lpcchValueNameSlot = Buffer.alloc(4);
    _lpcchValueNameSlot.writeUInt32LE(lpcchValueName, 0);
    const _typeSlot = Buffer.alloc(4);
    const _lpcbDataSlot = Buffer.alloc(4);
    _lpcbDataSlot.writeUInt32LE(lpcbData, 0);
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegEnumValueW', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.u32(index), DynWinRtValue.pointer(_wideStringBuffer(valueName)), DynWinRtValue.pointer(_lpcchValueNameSlot), DynWinRtValue.pointer(reserved), DynWinRtValue.pointer(_typeSlot), DynWinRtValue.pointer(data), DynWinRtValue.pointer(_lpcbDataSlot)]);
    return {
        status: _ret.toNumber(),
        lpcchValueName: _lpcchValueNameSlot.readUInt32LE(0),
        type: _typeSlot.readUInt32LE(0),
        lpcbData: _lpcbDataSlot.readUInt32LE(0),
    };
}

/**
 * RegFlushKey — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @returns { status: number }
 */
export function regFlushKey(hKey) {
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegFlushKey', 'I32', [DynWinRtValue.pointer(hKey)]);
    return { status: _ret.toNumber() };
}

/**
 * RegGetKeySecurity — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param securityInformation  [in] OBJECT_SECURITY_INFORMATION enum
 * @param pSecurityDescriptor  [in] PSECURITY_DESCRIPTOR handle
 * @param lpcbSecurityDescriptor  [in,out] pointer to U32
 * @returns { status: number, lpcbSecurityDescriptor: <out> }
 */
export function regGetKeySecurity(hKey, securityInformation, pSecurityDescriptor, lpcbSecurityDescriptor) {
    const _lpcbSecurityDescriptorSlot = Buffer.alloc(4);
    _lpcbSecurityDescriptorSlot.writeUInt32LE(lpcbSecurityDescriptor, 0);
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegGetKeySecurity', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.i32(securityInformation), DynWinRtValue.pointer(pSecurityDescriptor), DynWinRtValue.pointer(_lpcbSecurityDescriptorSlot)]);
    return {
        status: _ret.toNumber(),
        lpcbSecurityDescriptor: _lpcbSecurityDescriptorSlot.readUInt32LE(0),
    };
}

/**
 * RegGetValueA — ADVAPI32.dll export.
 *
 * @param hkey  [in] HKEY handle
 * @param subKey  [in] LPCSTR string
 * @param value  [in] LPCSTR string
 * @param flags  [in] REG_ROUTINE_FLAGS enum
 * @param pdwType  [out] pointer to REG_VALUE_TYPE enum
 * @param data  [in/out pointer] opaque pointer
 * @param pcbData  [in,out] pointer to U32
 * @returns { status: number, pdwType: <out>, pcbData: <out> }
 */
export function regGetValueA(hkey, subKey, value, flags, data, pcbData) {
    const _pdwTypeSlot = Buffer.alloc(4);
    const _pcbDataSlot = Buffer.alloc(4);
    _pcbDataSlot.writeUInt32LE(pcbData, 0);
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegGetValueA', 'I32', [DynWinRtValue.pointer(hkey), DynWinRtValue.pointer(_wideStringBuffer(subKey)), DynWinRtValue.pointer(_wideStringBuffer(value)), DynWinRtValue.i32(flags), DynWinRtValue.pointer(_pdwTypeSlot), DynWinRtValue.pointer(data), DynWinRtValue.pointer(_pcbDataSlot)]);
    return {
        status: _ret.toNumber(),
        pdwType: _pdwTypeSlot.readInt32LE(0),
        pcbData: _pcbDataSlot.readUInt32LE(0),
    };
}

/**
 * RegGetValueW — ADVAPI32.dll export.
 *
 * @param hkey  [in] HKEY handle
 * @param subKey  [in] LPCWSTR string
 * @param value  [in] LPCWSTR string
 * @param flags  [in] REG_ROUTINE_FLAGS enum
 * @param pdwType  [out] pointer to REG_VALUE_TYPE enum
 * @param data  [in/out pointer] opaque pointer
 * @param pcbData  [in,out] pointer to U32
 * @returns { status: number, pdwType: <out>, pcbData: <out> }
 */
export function regGetValueW(hkey, subKey, value, flags, data, pcbData) {
    const _pdwTypeSlot = Buffer.alloc(4);
    const _pcbDataSlot = Buffer.alloc(4);
    _pcbDataSlot.writeUInt32LE(pcbData, 0);
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegGetValueW', 'I32', [DynWinRtValue.pointer(hkey), DynWinRtValue.pointer(_wideStringBuffer(subKey)), DynWinRtValue.pointer(_wideStringBuffer(value)), DynWinRtValue.i32(flags), DynWinRtValue.pointer(_pdwTypeSlot), DynWinRtValue.pointer(data), DynWinRtValue.pointer(_pcbDataSlot)]);
    return {
        status: _ret.toNumber(),
        pdwType: _pdwTypeSlot.readInt32LE(0),
        pcbData: _pcbDataSlot.readUInt32LE(0),
    };
}

/**
 * RegLoadAppKeyA — ADVAPI32.dll export.
 *
 * @param file  [in] LPCSTR string
 * @param phkResult  [out] pointer to HKEY handle
 * @param samDesired  [in] U32
 * @param options  [in] U32
 * @param reserved  [in] U32
 * @returns { status: number, phkResult: <out> }
 */
export function regLoadAppKeyA(file, samDesired, options, reserved) {
    const _phkResultSlot = Buffer.alloc(8);
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegLoadAppKeyA', 'I32', [DynWinRtValue.pointer(_wideStringBuffer(file)), DynWinRtValue.pointer(_phkResultSlot), DynWinRtValue.u32(samDesired), DynWinRtValue.u32(options), DynWinRtValue.u32(reserved)]);
    return {
        status: _ret.toNumber(),
        phkResult: _phkResultSlot.readBigUInt64LE(0),
    };
}

/**
 * RegLoadAppKeyW — ADVAPI32.dll export.
 *
 * @param file  [in] LPCWSTR string
 * @param phkResult  [out] pointer to HKEY handle
 * @param samDesired  [in] U32
 * @param options  [in] U32
 * @param reserved  [in] U32
 * @returns { status: number, phkResult: <out> }
 */
export function regLoadAppKeyW(file, samDesired, options, reserved) {
    const _phkResultSlot = Buffer.alloc(8);
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegLoadAppKeyW', 'I32', [DynWinRtValue.pointer(_wideStringBuffer(file)), DynWinRtValue.pointer(_phkResultSlot), DynWinRtValue.u32(samDesired), DynWinRtValue.u32(options), DynWinRtValue.u32(reserved)]);
    return {
        status: _ret.toNumber(),
        phkResult: _phkResultSlot.readBigUInt64LE(0),
    };
}

/**
 * RegLoadKeyA — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param subKey  [in] LPCSTR string
 * @param file  [in] LPCSTR string
 * @returns { status: number }
 */
export function regLoadKeyA(hKey, subKey, file) {
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegLoadKeyA', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(subKey)), DynWinRtValue.pointer(_wideStringBuffer(file))]);
    return { status: _ret.toNumber() };
}

/**
 * RegLoadKeyW — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param subKey  [in] LPCWSTR string
 * @param file  [in] LPCWSTR string
 * @returns { status: number }
 */
export function regLoadKeyW(hKey, subKey, file) {
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegLoadKeyW', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(subKey)), DynWinRtValue.pointer(_wideStringBuffer(file))]);
    return { status: _ret.toNumber() };
}

/**
 * RegLoadMUIStringA — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param value  [in] LPCSTR string
 * @param outBuf  [in] LPCSTR string
 * @param outBuf_2  [in] U32
 * @param pcbData  [out] pointer to U32
 * @param flags  [in] U32
 * @param directory  [in] LPCSTR string
 * @returns { status: number, pcbData: <out> }
 */
export function regLoadMUIStringA(hKey, value, outBuf, outBuf_2, flags, directory) {
    const _pcbDataSlot = Buffer.alloc(4);
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegLoadMUIStringA', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(value)), DynWinRtValue.pointer(_wideStringBuffer(outBuf)), DynWinRtValue.u32(outBuf_2), DynWinRtValue.pointer(_pcbDataSlot), DynWinRtValue.u32(flags), DynWinRtValue.pointer(_wideStringBuffer(directory))]);
    return {
        status: _ret.toNumber(),
        pcbData: _pcbDataSlot.readUInt32LE(0),
    };
}

/**
 * RegLoadMUIStringW — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param value  [in] LPCWSTR string
 * @param outBuf  [in] LPCWSTR string
 * @param outBuf_2  [in] U32
 * @param pcbData  [out] pointer to U32
 * @param flags  [in] U32
 * @param directory  [in] LPCWSTR string
 * @returns { status: number, pcbData: <out> }
 */
export function regLoadMUIStringW(hKey, value, outBuf, outBuf_2, flags, directory) {
    const _pcbDataSlot = Buffer.alloc(4);
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegLoadMUIStringW', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(value)), DynWinRtValue.pointer(_wideStringBuffer(outBuf)), DynWinRtValue.u32(outBuf_2), DynWinRtValue.pointer(_pcbDataSlot), DynWinRtValue.u32(flags), DynWinRtValue.pointer(_wideStringBuffer(directory))]);
    return {
        status: _ret.toNumber(),
        pcbData: _pcbDataSlot.readUInt32LE(0),
    };
}

/**
 * RegNotifyChangeKeyValue — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param bWatchSubtree  [in] Bool32
 * @param notifyFilter  [in] REG_NOTIFY_FILTER enum
 * @param hEvent  [in] HANDLE handle
 * @param fAsynchronous  [in] Bool32
 * @returns { status: number }
 */
export function regNotifyChangeKeyValue(hKey, bWatchSubtree, notifyFilter, hEvent, fAsynchronous) {
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegNotifyChangeKeyValue', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.i32(bWatchSubtree ? 1 : 0), DynWinRtValue.i32(notifyFilter), DynWinRtValue.pointer(hEvent), DynWinRtValue.i32(fAsynchronous ? 1 : 0)]);
    return { status: _ret.toNumber() };
}

/**
 * RegOpenCurrentUser — ADVAPI32.dll export.
 *
 * @param samDesired  [in] U32
 * @param phkResult  [out] pointer to HKEY handle
 * @returns { status: number, phkResult: <out> }
 */
export function regOpenCurrentUser(samDesired) {
    const _phkResultSlot = Buffer.alloc(8);
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegOpenCurrentUser', 'I32', [DynWinRtValue.u32(samDesired), DynWinRtValue.pointer(_phkResultSlot)]);
    return {
        status: _ret.toNumber(),
        phkResult: _phkResultSlot.readBigUInt64LE(0),
    };
}

/**
 * RegOpenKeyA — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param subKey  [in] LPCSTR string
 * @param phkResult  [out] pointer to HKEY handle
 * @returns { status: number, phkResult: <out> }
 */
export function regOpenKeyA(hKey, subKey) {
    const _phkResultSlot = Buffer.alloc(8);
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegOpenKeyA', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(subKey)), DynWinRtValue.pointer(_phkResultSlot)]);
    return {
        status: _ret.toNumber(),
        phkResult: _phkResultSlot.readBigUInt64LE(0),
    };
}

/**
 * RegOpenKeyExA — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param subKey  [in] LPCSTR string
 * @param ulOptions  [in] U32
 * @param samDesired  [in] REG_SAM_FLAGS enum
 * @param phkResult  [out] pointer to HKEY handle
 * @returns { status: number, phkResult: <out> }
 */
export function regOpenKeyExA(hKey, subKey, ulOptions, samDesired) {
    const _phkResultSlot = Buffer.alloc(8);
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegOpenKeyExA', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(subKey)), DynWinRtValue.u32(ulOptions), DynWinRtValue.i32(samDesired), DynWinRtValue.pointer(_phkResultSlot)]);
    return {
        status: _ret.toNumber(),
        phkResult: _phkResultSlot.readBigUInt64LE(0),
    };
}

/**
 * RegOpenKeyExW — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param subKey  [in] LPCWSTR string
 * @param ulOptions  [in] U32
 * @param samDesired  [in] REG_SAM_FLAGS enum
 * @param phkResult  [out] pointer to HKEY handle
 * @returns { status: number, phkResult: <out> }
 */
export function regOpenKeyExW(hKey, subKey, ulOptions, samDesired) {
    const _phkResultSlot = Buffer.alloc(8);
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegOpenKeyExW', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(subKey)), DynWinRtValue.u32(ulOptions), DynWinRtValue.i32(samDesired), DynWinRtValue.pointer(_phkResultSlot)]);
    return {
        status: _ret.toNumber(),
        phkResult: _phkResultSlot.readBigUInt64LE(0),
    };
}

/**
 * RegOpenKeyTransactedA — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param subKey  [in] LPCSTR string
 * @param ulOptions  [in] U32
 * @param samDesired  [in] REG_SAM_FLAGS enum
 * @param phkResult  [out] pointer to HKEY handle
 * @param hTransaction  [in] HANDLE handle
 * @param pExtendedParemeter  [in/out pointer] opaque pointer
 * @returns { status: number, phkResult: <out> }
 */
export function regOpenKeyTransactedA(hKey, subKey, ulOptions, samDesired, hTransaction, pExtendedParemeter) {
    const _phkResultSlot = Buffer.alloc(8);
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegOpenKeyTransactedA', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(subKey)), DynWinRtValue.u32(ulOptions), DynWinRtValue.i32(samDesired), DynWinRtValue.pointer(_phkResultSlot), DynWinRtValue.pointer(hTransaction), DynWinRtValue.pointer(pExtendedParemeter)]);
    return {
        status: _ret.toNumber(),
        phkResult: _phkResultSlot.readBigUInt64LE(0),
    };
}

/**
 * RegOpenKeyTransactedW — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param subKey  [in] LPCWSTR string
 * @param ulOptions  [in] U32
 * @param samDesired  [in] REG_SAM_FLAGS enum
 * @param phkResult  [out] pointer to HKEY handle
 * @param hTransaction  [in] HANDLE handle
 * @param pExtendedParemeter  [in/out pointer] opaque pointer
 * @returns { status: number, phkResult: <out> }
 */
export function regOpenKeyTransactedW(hKey, subKey, ulOptions, samDesired, hTransaction, pExtendedParemeter) {
    const _phkResultSlot = Buffer.alloc(8);
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegOpenKeyTransactedW', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(subKey)), DynWinRtValue.u32(ulOptions), DynWinRtValue.i32(samDesired), DynWinRtValue.pointer(_phkResultSlot), DynWinRtValue.pointer(hTransaction), DynWinRtValue.pointer(pExtendedParemeter)]);
    return {
        status: _ret.toNumber(),
        phkResult: _phkResultSlot.readBigUInt64LE(0),
    };
}

/**
 * RegOpenKeyW — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param subKey  [in] LPCWSTR string
 * @param phkResult  [out] pointer to HKEY handle
 * @returns { status: number, phkResult: <out> }
 */
export function regOpenKeyW(hKey, subKey) {
    const _phkResultSlot = Buffer.alloc(8);
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegOpenKeyW', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(subKey)), DynWinRtValue.pointer(_phkResultSlot)]);
    return {
        status: _ret.toNumber(),
        phkResult: _phkResultSlot.readBigUInt64LE(0),
    };
}

/**
 * RegOpenUserClassesRoot — ADVAPI32.dll export.
 *
 * @param hToken  [in] HANDLE handle
 * @param options  [in] U32
 * @param samDesired  [in] U32
 * @param phkResult  [out] pointer to HKEY handle
 * @returns { status: number, phkResult: <out> }
 */
export function regOpenUserClassesRoot(hToken, options, samDesired) {
    const _phkResultSlot = Buffer.alloc(8);
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegOpenUserClassesRoot', 'I32', [DynWinRtValue.pointer(hToken), DynWinRtValue.u32(options), DynWinRtValue.u32(samDesired), DynWinRtValue.pointer(_phkResultSlot)]);
    return {
        status: _ret.toNumber(),
        phkResult: _phkResultSlot.readBigUInt64LE(0),
    };
}

/**
 * RegOverridePredefKey — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param hNewHKey  [in] HKEY handle
 * @returns { status: number }
 */
export function regOverridePredefKey(hKey, hNewHKey) {
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegOverridePredefKey', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(hNewHKey)]);
    return { status: _ret.toNumber() };
}

/**
 * RegQueryInfoKeyA — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param class_  [in] LPCSTR string
 * @param lpcchClass  [in,out] pointer to U32
 * @param reserved  [in/out pointer] pointer to U32
 * @param lpcSubKeys  [out] pointer to U32
 * @param lpcbMaxSubKeyLen  [out] pointer to U32
 * @param lpcbMaxClassLen  [out] pointer to U32
 * @param lpcValues  [out] pointer to U32
 * @param lpcbMaxValueNameLen  [out] pointer to U32
 * @param lpcbMaxValueLen  [out] pointer to U32
 * @param lpcbSecurityDescriptor  [out] pointer to U32
 * @param lpftLastWriteTime  [in/out pointer] pointer to Unknown
 * @returns { status: number, lpcchClass: <out>, lpcSubKeys: <out>, lpcbMaxSubKeyLen: <out>, lpcbMaxClassLen: <out>, lpcValues: <out>, lpcbMaxValueNameLen: <out>, lpcbMaxValueLen: <out>, lpcbSecurityDescriptor: <out> }
 */
export function regQueryInfoKeyA(hKey, class_, lpcchClass, reserved, lpftLastWriteTime) {
    const _lpcchClassSlot = Buffer.alloc(4);
    _lpcchClassSlot.writeUInt32LE(lpcchClass, 0);
    const _lpcSubKeysSlot = Buffer.alloc(4);
    const _lpcbMaxSubKeyLenSlot = Buffer.alloc(4);
    const _lpcbMaxClassLenSlot = Buffer.alloc(4);
    const _lpcValuesSlot = Buffer.alloc(4);
    const _lpcbMaxValueNameLenSlot = Buffer.alloc(4);
    const _lpcbMaxValueLenSlot = Buffer.alloc(4);
    const _lpcbSecurityDescriptorSlot = Buffer.alloc(4);
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegQueryInfoKeyA', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(class_)), DynWinRtValue.pointer(_lpcchClassSlot), DynWinRtValue.pointer(reserved), DynWinRtValue.pointer(_lpcSubKeysSlot), DynWinRtValue.pointer(_lpcbMaxSubKeyLenSlot), DynWinRtValue.pointer(_lpcbMaxClassLenSlot), DynWinRtValue.pointer(_lpcValuesSlot), DynWinRtValue.pointer(_lpcbMaxValueNameLenSlot), DynWinRtValue.pointer(_lpcbMaxValueLenSlot), DynWinRtValue.pointer(_lpcbSecurityDescriptorSlot), DynWinRtValue.pointer(lpftLastWriteTime)]);
    return {
        status: _ret.toNumber(),
        lpcchClass: _lpcchClassSlot.readUInt32LE(0),
        lpcSubKeys: _lpcSubKeysSlot.readUInt32LE(0),
        lpcbMaxSubKeyLen: _lpcbMaxSubKeyLenSlot.readUInt32LE(0),
        lpcbMaxClassLen: _lpcbMaxClassLenSlot.readUInt32LE(0),
        lpcValues: _lpcValuesSlot.readUInt32LE(0),
        lpcbMaxValueNameLen: _lpcbMaxValueNameLenSlot.readUInt32LE(0),
        lpcbMaxValueLen: _lpcbMaxValueLenSlot.readUInt32LE(0),
        lpcbSecurityDescriptor: _lpcbSecurityDescriptorSlot.readUInt32LE(0),
    };
}

/**
 * RegQueryInfoKeyW — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param class_  [in] LPCWSTR string
 * @param lpcchClass  [in,out] pointer to U32
 * @param reserved  [in/out pointer] pointer to U32
 * @param lpcSubKeys  [out] pointer to U32
 * @param lpcbMaxSubKeyLen  [out] pointer to U32
 * @param lpcbMaxClassLen  [out] pointer to U32
 * @param lpcValues  [out] pointer to U32
 * @param lpcbMaxValueNameLen  [out] pointer to U32
 * @param lpcbMaxValueLen  [out] pointer to U32
 * @param lpcbSecurityDescriptor  [out] pointer to U32
 * @param lpftLastWriteTime  [in/out pointer] pointer to Unknown
 * @returns { status: number, lpcchClass: <out>, lpcSubKeys: <out>, lpcbMaxSubKeyLen: <out>, lpcbMaxClassLen: <out>, lpcValues: <out>, lpcbMaxValueNameLen: <out>, lpcbMaxValueLen: <out>, lpcbSecurityDescriptor: <out> }
 */
export function regQueryInfoKeyW(hKey, class_, lpcchClass, reserved, lpftLastWriteTime) {
    const _lpcchClassSlot = Buffer.alloc(4);
    _lpcchClassSlot.writeUInt32LE(lpcchClass, 0);
    const _lpcSubKeysSlot = Buffer.alloc(4);
    const _lpcbMaxSubKeyLenSlot = Buffer.alloc(4);
    const _lpcbMaxClassLenSlot = Buffer.alloc(4);
    const _lpcValuesSlot = Buffer.alloc(4);
    const _lpcbMaxValueNameLenSlot = Buffer.alloc(4);
    const _lpcbMaxValueLenSlot = Buffer.alloc(4);
    const _lpcbSecurityDescriptorSlot = Buffer.alloc(4);
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegQueryInfoKeyW', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(class_)), DynWinRtValue.pointer(_lpcchClassSlot), DynWinRtValue.pointer(reserved), DynWinRtValue.pointer(_lpcSubKeysSlot), DynWinRtValue.pointer(_lpcbMaxSubKeyLenSlot), DynWinRtValue.pointer(_lpcbMaxClassLenSlot), DynWinRtValue.pointer(_lpcValuesSlot), DynWinRtValue.pointer(_lpcbMaxValueNameLenSlot), DynWinRtValue.pointer(_lpcbMaxValueLenSlot), DynWinRtValue.pointer(_lpcbSecurityDescriptorSlot), DynWinRtValue.pointer(lpftLastWriteTime)]);
    return {
        status: _ret.toNumber(),
        lpcchClass: _lpcchClassSlot.readUInt32LE(0),
        lpcSubKeys: _lpcSubKeysSlot.readUInt32LE(0),
        lpcbMaxSubKeyLen: _lpcbMaxSubKeyLenSlot.readUInt32LE(0),
        lpcbMaxClassLen: _lpcbMaxClassLenSlot.readUInt32LE(0),
        lpcValues: _lpcValuesSlot.readUInt32LE(0),
        lpcbMaxValueNameLen: _lpcbMaxValueNameLenSlot.readUInt32LE(0),
        lpcbMaxValueLen: _lpcbMaxValueLenSlot.readUInt32LE(0),
        lpcbSecurityDescriptor: _lpcbSecurityDescriptorSlot.readUInt32LE(0),
    };
}

/**
 * RegQueryMultipleValuesA — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param val_list  [in/out pointer] pointer to Unknown
 * @param num_vals  [in] U32
 * @param valueBuf  [in] LPCSTR string
 * @param ldwTotsize  [in,out] pointer to U32
 * @returns { status: number, ldwTotsize: <out> }
 */
export function regQueryMultipleValuesA(hKey, val_list, num_vals, valueBuf, ldwTotsize) {
    const _ldwTotsizeSlot = Buffer.alloc(4);
    _ldwTotsizeSlot.writeUInt32LE(ldwTotsize, 0);
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegQueryMultipleValuesA', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(val_list), DynWinRtValue.u32(num_vals), DynWinRtValue.pointer(_wideStringBuffer(valueBuf)), DynWinRtValue.pointer(_ldwTotsizeSlot)]);
    return {
        status: _ret.toNumber(),
        ldwTotsize: _ldwTotsizeSlot.readUInt32LE(0),
    };
}

/**
 * RegQueryMultipleValuesW — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param val_list  [in/out pointer] pointer to Unknown
 * @param num_vals  [in] U32
 * @param valueBuf  [in] LPCWSTR string
 * @param ldwTotsize  [in,out] pointer to U32
 * @returns { status: number, ldwTotsize: <out> }
 */
export function regQueryMultipleValuesW(hKey, val_list, num_vals, valueBuf, ldwTotsize) {
    const _ldwTotsizeSlot = Buffer.alloc(4);
    _ldwTotsizeSlot.writeUInt32LE(ldwTotsize, 0);
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegQueryMultipleValuesW', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(val_list), DynWinRtValue.u32(num_vals), DynWinRtValue.pointer(_wideStringBuffer(valueBuf)), DynWinRtValue.pointer(_ldwTotsizeSlot)]);
    return {
        status: _ret.toNumber(),
        ldwTotsize: _ldwTotsizeSlot.readUInt32LE(0),
    };
}

/**
 * RegQueryReflectionKey — ADVAPI32.dll export.
 *
 * @param hBase  [in] HKEY handle
 * @param bIsReflectionDisabled  [out] pointer to Bool32
 * @returns { status: number, bIsReflectionDisabled: <out> }
 */
export function regQueryReflectionKey(hBase) {
    const _bIsReflectionDisabledSlot = Buffer.alloc(4);
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegQueryReflectionKey', 'I32', [DynWinRtValue.pointer(hBase), DynWinRtValue.pointer(_bIsReflectionDisabledSlot)]);
    return {
        status: _ret.toNumber(),
        bIsReflectionDisabled: _bIsReflectionDisabledSlot.readInt32LE(0),
    };
}

/**
 * RegQueryValueA — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param subKey  [in] LPCSTR string
 * @param data  [in] LPCSTR string
 * @param lpcbData  [in,out] pointer to I32
 * @returns { status: number, lpcbData: <out> }
 */
export function regQueryValueA(hKey, subKey, data, lpcbData) {
    const _lpcbDataSlot = Buffer.alloc(4);
    _lpcbDataSlot.writeInt32LE(lpcbData, 0);
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegQueryValueA', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(subKey)), DynWinRtValue.pointer(_wideStringBuffer(data)), DynWinRtValue.pointer(_lpcbDataSlot)]);
    return {
        status: _ret.toNumber(),
        lpcbData: _lpcbDataSlot.readInt32LE(0),
    };
}

/**
 * RegQueryValueExA — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param valueName  [in] LPCSTR string
 * @param reserved  [in/out pointer] pointer to U32
 * @param type  [out] pointer to REG_VALUE_TYPE enum
 * @param data  [in/out pointer] pointer to U8
 * @param lpcbData  [in,out] pointer to U32
 * @returns { status: number, lpType: <out>, lpcbData: <out> }
 */
export function regQueryValueExA(hKey, valueName, reserved, data, lpcbData) {
    const _typeSlot = Buffer.alloc(4);
    const _lpcbDataSlot = Buffer.alloc(4);
    _lpcbDataSlot.writeUInt32LE(lpcbData, 0);
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegQueryValueExA', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(valueName)), DynWinRtValue.pointer(reserved), DynWinRtValue.pointer(_typeSlot), DynWinRtValue.pointer(data), DynWinRtValue.pointer(_lpcbDataSlot)]);
    return {
        status: _ret.toNumber(),
        type: _typeSlot.readInt32LE(0),
        lpcbData: _lpcbDataSlot.readUInt32LE(0),
    };
}

/**
 * RegQueryValueExW — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param valueName  [in] LPCWSTR string
 * @param reserved  [in/out pointer] pointer to U32
 * @param type  [out] pointer to REG_VALUE_TYPE enum
 * @param data  [in/out pointer] pointer to U8
 * @param lpcbData  [in,out] pointer to U32
 * @returns { status: number, lpType: <out>, lpcbData: <out> }
 */
export function regQueryValueExW(hKey, valueName, reserved, data, lpcbData) {
    const _typeSlot = Buffer.alloc(4);
    const _lpcbDataSlot = Buffer.alloc(4);
    _lpcbDataSlot.writeUInt32LE(lpcbData, 0);
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegQueryValueExW', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(valueName)), DynWinRtValue.pointer(reserved), DynWinRtValue.pointer(_typeSlot), DynWinRtValue.pointer(data), DynWinRtValue.pointer(_lpcbDataSlot)]);
    return {
        status: _ret.toNumber(),
        type: _typeSlot.readInt32LE(0),
        lpcbData: _lpcbDataSlot.readUInt32LE(0),
    };
}

/**
 * RegQueryValueW — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param subKey  [in] LPCWSTR string
 * @param data  [in] LPCWSTR string
 * @param lpcbData  [in,out] pointer to I32
 * @returns { status: number, lpcbData: <out> }
 */
export function regQueryValueW(hKey, subKey, data, lpcbData) {
    const _lpcbDataSlot = Buffer.alloc(4);
    _lpcbDataSlot.writeInt32LE(lpcbData, 0);
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegQueryValueW', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(subKey)), DynWinRtValue.pointer(_wideStringBuffer(data)), DynWinRtValue.pointer(_lpcbDataSlot)]);
    return {
        status: _ret.toNumber(),
        lpcbData: _lpcbDataSlot.readInt32LE(0),
    };
}

/**
 * RegRenameKey — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param subKeyName  [in] LPCWSTR string
 * @param newKeyName  [in] LPCWSTR string
 * @returns { status: number }
 */
export function regRenameKey(hKey, subKeyName, newKeyName) {
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegRenameKey', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(subKeyName)), DynWinRtValue.pointer(_wideStringBuffer(newKeyName))]);
    return { status: _ret.toNumber() };
}

/**
 * RegReplaceKeyA — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param subKey  [in] LPCSTR string
 * @param newFile  [in] LPCSTR string
 * @param oldFile  [in] LPCSTR string
 * @returns { status: number }
 */
export function regReplaceKeyA(hKey, subKey, newFile, oldFile) {
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegReplaceKeyA', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(subKey)), DynWinRtValue.pointer(_wideStringBuffer(newFile)), DynWinRtValue.pointer(_wideStringBuffer(oldFile))]);
    return { status: _ret.toNumber() };
}

/**
 * RegReplaceKeyW — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param subKey  [in] LPCWSTR string
 * @param newFile  [in] LPCWSTR string
 * @param oldFile  [in] LPCWSTR string
 * @returns { status: number }
 */
export function regReplaceKeyW(hKey, subKey, newFile, oldFile) {
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegReplaceKeyW', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(subKey)), DynWinRtValue.pointer(_wideStringBuffer(newFile)), DynWinRtValue.pointer(_wideStringBuffer(oldFile))]);
    return { status: _ret.toNumber() };
}

/**
 * RegRestoreKeyA — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param file  [in] LPCSTR string
 * @param flags  [in] U32
 * @returns { status: number }
 */
export function regRestoreKeyA(hKey, file, flags) {
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegRestoreKeyA', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(file)), DynWinRtValue.u32(flags)]);
    return { status: _ret.toNumber() };
}

/**
 * RegRestoreKeyW — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param file  [in] LPCWSTR string
 * @param flags  [in] U32
 * @returns { status: number }
 */
export function regRestoreKeyW(hKey, file, flags) {
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegRestoreKeyW', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(file)), DynWinRtValue.u32(flags)]);
    return { status: _ret.toNumber() };
}

/**
 * RegSaveKeyA — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param file  [in] LPCSTR string
 * @param securityAttributes  [in/out pointer] pointer to Unknown
 * @returns { status: number }
 */
export function regSaveKeyA(hKey, file, securityAttributes) {
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegSaveKeyA', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(file)), DynWinRtValue.pointer(securityAttributes)]);
    return { status: _ret.toNumber() };
}

/**
 * RegSaveKeyExA — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param file  [in] LPCSTR string
 * @param securityAttributes  [in/out pointer] pointer to Unknown
 * @param flags  [in] REG_SAVE_FORMAT enum
 * @returns { status: number }
 */
export function regSaveKeyExA(hKey, file, securityAttributes, flags) {
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegSaveKeyExA', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(file)), DynWinRtValue.pointer(securityAttributes), DynWinRtValue.i32(flags)]);
    return { status: _ret.toNumber() };
}

/**
 * RegSaveKeyExW — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param file  [in] LPCWSTR string
 * @param securityAttributes  [in/out pointer] pointer to Unknown
 * @param flags  [in] REG_SAVE_FORMAT enum
 * @returns { status: number }
 */
export function regSaveKeyExW(hKey, file, securityAttributes, flags) {
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegSaveKeyExW', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(file)), DynWinRtValue.pointer(securityAttributes), DynWinRtValue.i32(flags)]);
    return { status: _ret.toNumber() };
}

/**
 * RegSaveKeyW — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param file  [in] LPCWSTR string
 * @param securityAttributes  [in/out pointer] pointer to Unknown
 * @returns { status: number }
 */
export function regSaveKeyW(hKey, file, securityAttributes) {
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegSaveKeyW', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(file)), DynWinRtValue.pointer(securityAttributes)]);
    return { status: _ret.toNumber() };
}

/**
 * RegSetKeySecurity — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param securityInformation  [in] OBJECT_SECURITY_INFORMATION enum
 * @param pSecurityDescriptor  [in] PSECURITY_DESCRIPTOR handle
 * @returns { status: number }
 */
export function regSetKeySecurity(hKey, securityInformation, pSecurityDescriptor) {
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegSetKeySecurity', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.i32(securityInformation), DynWinRtValue.pointer(pSecurityDescriptor)]);
    return { status: _ret.toNumber() };
}

/**
 * RegSetKeyValueA — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param subKey  [in] LPCSTR string
 * @param valueName  [in] LPCSTR string
 * @param type  [in] U32
 * @param data  [in/out pointer] opaque pointer
 * @param data_2  [in] U32
 * @returns { status: number }
 */
export function regSetKeyValueA(hKey, subKey, valueName, type, data, data_2) {
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegSetKeyValueA', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(subKey)), DynWinRtValue.pointer(_wideStringBuffer(valueName)), DynWinRtValue.u32(type), DynWinRtValue.pointer(data), DynWinRtValue.u32(data_2)]);
    return { status: _ret.toNumber() };
}

/**
 * RegSetKeyValueW — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param subKey  [in] LPCWSTR string
 * @param valueName  [in] LPCWSTR string
 * @param type  [in] U32
 * @param data  [in/out pointer] opaque pointer
 * @param data_2  [in] U32
 * @returns { status: number }
 */
export function regSetKeyValueW(hKey, subKey, valueName, type, data, data_2) {
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegSetKeyValueW', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(subKey)), DynWinRtValue.pointer(_wideStringBuffer(valueName)), DynWinRtValue.u32(type), DynWinRtValue.pointer(data), DynWinRtValue.u32(data_2)]);
    return { status: _ret.toNumber() };
}

/**
 * RegSetValueA — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param subKey  [in] LPCSTR string
 * @param type  [in] REG_VALUE_TYPE enum
 * @param data  [in] LPCSTR string
 * @param data_2  [in] U32
 * @returns { status: number }
 */
export function regSetValueA(hKey, subKey, type, data, data_2) {
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegSetValueA', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(subKey)), DynWinRtValue.i32(type), DynWinRtValue.pointer(_wideStringBuffer(data)), DynWinRtValue.u32(data_2)]);
    return { status: _ret.toNumber() };
}

/**
 * RegSetValueExA — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param valueName  [in] LPCSTR string
 * @param reserved  [in] U32
 * @param type  [in] REG_VALUE_TYPE enum
 * @param data  [in/out pointer] pointer to U8
 * @param data_2  [in] U32
 * @returns { status: number }
 */
export function regSetValueExA(hKey, valueName, reserved, type, data, data_2) {
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegSetValueExA', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(valueName)), DynWinRtValue.u32(reserved), DynWinRtValue.i32(type), DynWinRtValue.pointer(data), DynWinRtValue.u32(data_2)]);
    return { status: _ret.toNumber() };
}

/**
 * RegSetValueExW — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param valueName  [in] LPCWSTR string
 * @param reserved  [in] U32
 * @param type  [in] REG_VALUE_TYPE enum
 * @param data  [in/out pointer] pointer to U8
 * @param data_2  [in] U32
 * @returns { status: number }
 */
export function regSetValueExW(hKey, valueName, reserved, type, data, data_2) {
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegSetValueExW', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(valueName)), DynWinRtValue.u32(reserved), DynWinRtValue.i32(type), DynWinRtValue.pointer(data), DynWinRtValue.u32(data_2)]);
    return { status: _ret.toNumber() };
}

/**
 * RegSetValueW — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param subKey  [in] LPCWSTR string
 * @param type  [in] REG_VALUE_TYPE enum
 * @param data  [in] LPCWSTR string
 * @param data_2  [in] U32
 * @returns { status: number }
 */
export function regSetValueW(hKey, subKey, type, data, data_2) {
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegSetValueW', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(subKey)), DynWinRtValue.i32(type), DynWinRtValue.pointer(_wideStringBuffer(data)), DynWinRtValue.u32(data_2)]);
    return { status: _ret.toNumber() };
}

/**
 * RegUnLoadKeyA — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param subKey  [in] LPCSTR string
 * @returns { status: number }
 */
export function regUnLoadKeyA(hKey, subKey) {
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegUnLoadKeyA', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(subKey))]);
    return { status: _ret.toNumber() };
}

/**
 * RegUnLoadKeyW — ADVAPI32.dll export.
 *
 * @param hKey  [in] HKEY handle
 * @param subKey  [in] LPCWSTR string
 * @returns { status: number }
 */
export function regUnLoadKeyW(hKey, subKey) {
    const _ret = DynWinRtValue.flatInvoke('ADVAPI32.dll', 'RegUnLoadKeyW', 'I32', [DynWinRtValue.pointer(hKey), DynWinRtValue.pointer(_wideStringBuffer(subKey))]);
    return { status: _ret.toNumber() };
}

export const Apis = Object.freeze({
    getRegistryValueWithFallbackW,
    regCloseKey,
    regConnectRegistryA,
    regConnectRegistryExA,
    regConnectRegistryExW,
    regConnectRegistryW,
    regCopyTreeA,
    regCopyTreeW,
    regCreateKeyA,
    regCreateKeyExA,
    regCreateKeyExW,
    regCreateKeyTransactedA,
    regCreateKeyTransactedW,
    regCreateKeyW,
    regDeleteKeyA,
    regDeleteKeyExA,
    regDeleteKeyExW,
    regDeleteKeyTransactedA,
    regDeleteKeyTransactedW,
    regDeleteKeyValueA,
    regDeleteKeyValueW,
    regDeleteKeyW,
    regDeleteTreeA,
    regDeleteTreeW,
    regDeleteValueA,
    regDeleteValueW,
    regDisablePredefinedCache,
    regDisablePredefinedCacheEx,
    regDisableReflectionKey,
    regEnableReflectionKey,
    regEnumKeyA,
    regEnumKeyExA,
    regEnumKeyExW,
    regEnumKeyW,
    regEnumValueA,
    regEnumValueW,
    regFlushKey,
    regGetKeySecurity,
    regGetValueA,
    regGetValueW,
    regLoadAppKeyA,
    regLoadAppKeyW,
    regLoadKeyA,
    regLoadKeyW,
    regLoadMUIStringA,
    regLoadMUIStringW,
    regNotifyChangeKeyValue,
    regOpenCurrentUser,
    regOpenKeyA,
    regOpenKeyExA,
    regOpenKeyExW,
    regOpenKeyTransactedA,
    regOpenKeyTransactedW,
    regOpenKeyW,
    regOpenUserClassesRoot,
    regOverridePredefKey,
    regQueryInfoKeyA,
    regQueryInfoKeyW,
    regQueryMultipleValuesA,
    regQueryMultipleValuesW,
    regQueryReflectionKey,
    regQueryValueA,
    regQueryValueExA,
    regQueryValueExW,
    regQueryValueW,
    regRenameKey,
    regReplaceKeyA,
    regReplaceKeyW,
    regRestoreKeyA,
    regRestoreKeyW,
    regSaveKeyA,
    regSaveKeyExA,
    regSaveKeyExW,
    regSaveKeyW,
    regSetKeySecurity,
    regSetKeyValueA,
    regSetKeyValueW,
    regSetValueA,
    regSetValueExA,
    regSetValueExW,
    regSetValueW,
    regUnLoadKeyA,
    regUnLoadKeyW,
});

// Raw metadata for each export (dll, entry point).
export const FLAT_EXPORTS = Object.freeze({
    getRegistryValueWithFallbackW: { dll: 'api-ms-win-core-state-helpers-l1-1-0.dll', entry: 'GetRegistryValueWithFallbackW' },
    regCloseKey: { dll: 'ADVAPI32.dll', entry: 'RegCloseKey' },
    regConnectRegistryA: { dll: 'ADVAPI32.dll', entry: 'RegConnectRegistryA' },
    regConnectRegistryExA: { dll: 'ADVAPI32.dll', entry: 'RegConnectRegistryExA' },
    regConnectRegistryExW: { dll: 'ADVAPI32.dll', entry: 'RegConnectRegistryExW' },
    regConnectRegistryW: { dll: 'ADVAPI32.dll', entry: 'RegConnectRegistryW' },
    regCopyTreeA: { dll: 'ADVAPI32.dll', entry: 'RegCopyTreeA' },
    regCopyTreeW: { dll: 'ADVAPI32.dll', entry: 'RegCopyTreeW' },
    regCreateKeyA: { dll: 'ADVAPI32.dll', entry: 'RegCreateKeyA' },
    regCreateKeyExA: { dll: 'ADVAPI32.dll', entry: 'RegCreateKeyExA' },
    regCreateKeyExW: { dll: 'ADVAPI32.dll', entry: 'RegCreateKeyExW' },
    regCreateKeyTransactedA: { dll: 'ADVAPI32.dll', entry: 'RegCreateKeyTransactedA' },
    regCreateKeyTransactedW: { dll: 'ADVAPI32.dll', entry: 'RegCreateKeyTransactedW' },
    regCreateKeyW: { dll: 'ADVAPI32.dll', entry: 'RegCreateKeyW' },
    regDeleteKeyA: { dll: 'ADVAPI32.dll', entry: 'RegDeleteKeyA' },
    regDeleteKeyExA: { dll: 'ADVAPI32.dll', entry: 'RegDeleteKeyExA' },
    regDeleteKeyExW: { dll: 'ADVAPI32.dll', entry: 'RegDeleteKeyExW' },
    regDeleteKeyTransactedA: { dll: 'ADVAPI32.dll', entry: 'RegDeleteKeyTransactedA' },
    regDeleteKeyTransactedW: { dll: 'ADVAPI32.dll', entry: 'RegDeleteKeyTransactedW' },
    regDeleteKeyValueA: { dll: 'ADVAPI32.dll', entry: 'RegDeleteKeyValueA' },
    regDeleteKeyValueW: { dll: 'ADVAPI32.dll', entry: 'RegDeleteKeyValueW' },
    regDeleteKeyW: { dll: 'ADVAPI32.dll', entry: 'RegDeleteKeyW' },
    regDeleteTreeA: { dll: 'ADVAPI32.dll', entry: 'RegDeleteTreeA' },
    regDeleteTreeW: { dll: 'ADVAPI32.dll', entry: 'RegDeleteTreeW' },
    regDeleteValueA: { dll: 'ADVAPI32.dll', entry: 'RegDeleteValueA' },
    regDeleteValueW: { dll: 'ADVAPI32.dll', entry: 'RegDeleteValueW' },
    regDisablePredefinedCache: { dll: 'ADVAPI32.dll', entry: 'RegDisablePredefinedCache' },
    regDisablePredefinedCacheEx: { dll: 'ADVAPI32.dll', entry: 'RegDisablePredefinedCacheEx' },
    regDisableReflectionKey: { dll: 'ADVAPI32.dll', entry: 'RegDisableReflectionKey' },
    regEnableReflectionKey: { dll: 'ADVAPI32.dll', entry: 'RegEnableReflectionKey' },
    regEnumKeyA: { dll: 'ADVAPI32.dll', entry: 'RegEnumKeyA' },
    regEnumKeyExA: { dll: 'ADVAPI32.dll', entry: 'RegEnumKeyExA' },
    regEnumKeyExW: { dll: 'ADVAPI32.dll', entry: 'RegEnumKeyExW' },
    regEnumKeyW: { dll: 'ADVAPI32.dll', entry: 'RegEnumKeyW' },
    regEnumValueA: { dll: 'ADVAPI32.dll', entry: 'RegEnumValueA' },
    regEnumValueW: { dll: 'ADVAPI32.dll', entry: 'RegEnumValueW' },
    regFlushKey: { dll: 'ADVAPI32.dll', entry: 'RegFlushKey' },
    regGetKeySecurity: { dll: 'ADVAPI32.dll', entry: 'RegGetKeySecurity' },
    regGetValueA: { dll: 'ADVAPI32.dll', entry: 'RegGetValueA' },
    regGetValueW: { dll: 'ADVAPI32.dll', entry: 'RegGetValueW' },
    regLoadAppKeyA: { dll: 'ADVAPI32.dll', entry: 'RegLoadAppKeyA' },
    regLoadAppKeyW: { dll: 'ADVAPI32.dll', entry: 'RegLoadAppKeyW' },
    regLoadKeyA: { dll: 'ADVAPI32.dll', entry: 'RegLoadKeyA' },
    regLoadKeyW: { dll: 'ADVAPI32.dll', entry: 'RegLoadKeyW' },
    regLoadMUIStringA: { dll: 'ADVAPI32.dll', entry: 'RegLoadMUIStringA' },
    regLoadMUIStringW: { dll: 'ADVAPI32.dll', entry: 'RegLoadMUIStringW' },
    regNotifyChangeKeyValue: { dll: 'ADVAPI32.dll', entry: 'RegNotifyChangeKeyValue' },
    regOpenCurrentUser: { dll: 'ADVAPI32.dll', entry: 'RegOpenCurrentUser' },
    regOpenKeyA: { dll: 'ADVAPI32.dll', entry: 'RegOpenKeyA' },
    regOpenKeyExA: { dll: 'ADVAPI32.dll', entry: 'RegOpenKeyExA' },
    regOpenKeyExW: { dll: 'ADVAPI32.dll', entry: 'RegOpenKeyExW' },
    regOpenKeyTransactedA: { dll: 'ADVAPI32.dll', entry: 'RegOpenKeyTransactedA' },
    regOpenKeyTransactedW: { dll: 'ADVAPI32.dll', entry: 'RegOpenKeyTransactedW' },
    regOpenKeyW: { dll: 'ADVAPI32.dll', entry: 'RegOpenKeyW' },
    regOpenUserClassesRoot: { dll: 'ADVAPI32.dll', entry: 'RegOpenUserClassesRoot' },
    regOverridePredefKey: { dll: 'ADVAPI32.dll', entry: 'RegOverridePredefKey' },
    regQueryInfoKeyA: { dll: 'ADVAPI32.dll', entry: 'RegQueryInfoKeyA' },
    regQueryInfoKeyW: { dll: 'ADVAPI32.dll', entry: 'RegQueryInfoKeyW' },
    regQueryMultipleValuesA: { dll: 'ADVAPI32.dll', entry: 'RegQueryMultipleValuesA' },
    regQueryMultipleValuesW: { dll: 'ADVAPI32.dll', entry: 'RegQueryMultipleValuesW' },
    regQueryReflectionKey: { dll: 'ADVAPI32.dll', entry: 'RegQueryReflectionKey' },
    regQueryValueA: { dll: 'ADVAPI32.dll', entry: 'RegQueryValueA' },
    regQueryValueExA: { dll: 'ADVAPI32.dll', entry: 'RegQueryValueExA' },
    regQueryValueExW: { dll: 'ADVAPI32.dll', entry: 'RegQueryValueExW' },
    regQueryValueW: { dll: 'ADVAPI32.dll', entry: 'RegQueryValueW' },
    regRenameKey: { dll: 'ADVAPI32.dll', entry: 'RegRenameKey' },
    regReplaceKeyA: { dll: 'ADVAPI32.dll', entry: 'RegReplaceKeyA' },
    regReplaceKeyW: { dll: 'ADVAPI32.dll', entry: 'RegReplaceKeyW' },
    regRestoreKeyA: { dll: 'ADVAPI32.dll', entry: 'RegRestoreKeyA' },
    regRestoreKeyW: { dll: 'ADVAPI32.dll', entry: 'RegRestoreKeyW' },
    regSaveKeyA: { dll: 'ADVAPI32.dll', entry: 'RegSaveKeyA' },
    regSaveKeyExA: { dll: 'ADVAPI32.dll', entry: 'RegSaveKeyExA' },
    regSaveKeyExW: { dll: 'ADVAPI32.dll', entry: 'RegSaveKeyExW' },
    regSaveKeyW: { dll: 'ADVAPI32.dll', entry: 'RegSaveKeyW' },
    regSetKeySecurity: { dll: 'ADVAPI32.dll', entry: 'RegSetKeySecurity' },
    regSetKeyValueA: { dll: 'ADVAPI32.dll', entry: 'RegSetKeyValueA' },
    regSetKeyValueW: { dll: 'ADVAPI32.dll', entry: 'RegSetKeyValueW' },
    regSetValueA: { dll: 'ADVAPI32.dll', entry: 'RegSetValueA' },
    regSetValueExA: { dll: 'ADVAPI32.dll', entry: 'RegSetValueExA' },
    regSetValueExW: { dll: 'ADVAPI32.dll', entry: 'RegSetValueExW' },
    regSetValueW: { dll: 'ADVAPI32.dll', entry: 'RegSetValueW' },
    regUnLoadKeyA: { dll: 'ADVAPI32.dll', entry: 'RegUnLoadKeyA' },
    regUnLoadKeyW: { dll: 'ADVAPI32.dll', entry: 'RegUnLoadKeyW' },
});
