// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '@microsoft/dynwinrt';
import { IWwwFormUrlDecoderEntry } from '../IWwwFormUrlDecoderEntry.js';

export declare const IID_IIterator_WindowsFoundationIWwwFormUrlDecoderEntry_g498f64075ebd0fce: WinGuid;

export declare class IIterator_WindowsFoundationIWwwFormUrlDecoderEntry_g498f64075ebd0fce {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IIterator_WindowsFoundationIWwwFormUrlDecoderEntry_g498f64075ebd0fce;

    get current(): IWwwFormUrlDecoderEntry;

    get hasCurrent(): boolean;

    moveNext(): boolean;

    getMany(items: IWwwFormUrlDecoderEntry[]): IWwwFormUrlDecoderEntry[];


    next(): IteratorResult<IWwwFormUrlDecoderEntry>;


    [Symbol.iterator](): IterableIterator<IWwwFormUrlDecoderEntry>;
}
