// Generated by dynwinrt-codegen — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('@microsoft/dynwinrt');
let __m_collections_IIterator_WindowsFoundationIWwwFormUrlDecoderEntry_g498f64075ebd0fce_50108df6;
const __load_collections_IIterator_WindowsFoundationIWwwFormUrlDecoderEntry_g498f64075ebd0fce_50108df6 = () => (__m_collections_IIterator_WindowsFoundationIWwwFormUrlDecoderEntry_g498f64075ebd0fce_50108df6 ??= require('./collections/IIterator_WindowsFoundationIWwwFormUrlDecoderEntry_g498f64075ebd0fce.js'));
const __get_IIterator_WindowsFoundationIWwwFormUrlDecoderEntry_g498f64075ebd0fce = () => __load_collections_IIterator_WindowsFoundationIWwwFormUrlDecoderEntry_g498f64075ebd0fce_50108df6().IIterator_WindowsFoundationIWwwFormUrlDecoderEntry_g498f64075ebd0fce;
require('./IWwwFormUrlDecoderEntry.js');
let __m_IWwwFormUrlDecoderEntry;
const __load_IWwwFormUrlDecoderEntry = () => (__m_IWwwFormUrlDecoderEntry ??= require('./IWwwFormUrlDecoderEntry.js'));
const __get_IWwwFormUrlDecoderEntry = () => __load_IWwwFormUrlDecoderEntry().IWwwFormUrlDecoderEntry;
let __m_lifetime;
const __load_lifetime = () => (__m_lifetime ??= require('../../lifetime.js'));
const __get_castProjectedValueBorrowed = () => __load_lifetime().castProjectedValueBorrowed;
const __get_castProjectedValueOwned = () => __load_lifetime().castProjectedValueOwned;
const __get_trackProjectedValue = () => __load_lifetime().trackProjectedValue;

const _unwrap = (x) => x?._obj ?? x;

const IID_IWwwFormUrlDecoderRuntimeClass = WinGuid.parse('d45a0451-f225-4542-9296-0e1df5d254df');
const IID_IWwwFormUrlDecoderRuntimeClassFactory = WinGuid.parse('5b8c6b3d-24ae-41b5-a1bf-f0c3d544845b');
const IID_IVectorView_WindowsFoundationIWwwFormUrlDecoderEntry_g58829236a97a8635 = DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.interface(WinGuid.parse('125e7431-f678-4e8e-b670-20a9b06c512d'))]).iid();
const IID_IIterable_WindowsFoundationIWwwFormUrlDecoderEntry_gd13025e9604dbcdb = DynWinRtType.parameterized(WinGuid.parse('faa585ea-6214-4217-afda-7f46de5869b3'), [DynWinRtType.interface(WinGuid.parse('125e7431-f678-4e8e-b670-20a9b06c512d'))]).iid();
const IID_WwwFormUrlDecoder = WinGuid.parse('d45a0451-f225-4542-9296-0e1df5d254df');

let _IWwwFormUrlDecoderRuntimeClassCache;
const _IWwwFormUrlDecoderRuntimeClass = new Proxy({}, {
    get(_target, prop) {
        _IWwwFormUrlDecoderRuntimeClassCache ??= DynWinRtType.registerInterface(
        "IWwwFormUrlDecoderRuntimeClass", IID_IWwwFormUrlDecoderRuntimeClass)
        .addMethod("GetFirstValueByName", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.hstring()));
        const value = _IWwwFormUrlDecoderRuntimeClassCache[prop];
        return typeof value === 'function' ? value.bind(_IWwwFormUrlDecoderRuntimeClassCache) : value;
    }
});

let _IWwwFormUrlDecoderRuntimeClassFactoryCache;
const _IWwwFormUrlDecoderRuntimeClassFactory = new Proxy({}, {
    get(_target, prop) {
        _IWwwFormUrlDecoderRuntimeClassFactoryCache ??= DynWinRtType.registerInterface(
        "IWwwFormUrlDecoderRuntimeClassFactory", IID_IWwwFormUrlDecoderRuntimeClassFactory)
        .addMethod("CreateWwwFormUrlDecoder", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.runtimeClass('Windows.Foundation.WwwFormUrlDecoder', DynWinRtType.interface(WinGuid.parse('d45a0451-f225-4542-9296-0e1df5d254df')))));
        const value = _IWwwFormUrlDecoderRuntimeClassFactoryCache[prop];
        return typeof value === 'function' ? value.bind(_IWwwFormUrlDecoderRuntimeClassFactoryCache) : value;
    }
});

let _IVectorView_WindowsFoundationIWwwFormUrlDecoderEntry_g58829236a97a8635Cache;
const _IVectorView_WindowsFoundationIWwwFormUrlDecoderEntry_g58829236a97a8635 = new Proxy({}, {
    get(_target, prop) {
        _IVectorView_WindowsFoundationIWwwFormUrlDecoderEntry_g58829236a97a8635Cache ??= DynWinRtType.registerInterface(
        "IVectorView_WindowsFoundationIWwwFormUrlDecoderEntry_g58829236a97a8635", IID_IVectorView_WindowsFoundationIWwwFormUrlDecoderEntry_g58829236a97a8635)
        .addMethod("GetAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addOut(DynWinRtType.interface(WinGuid.parse('125e7431-f678-4e8e-b670-20a9b06c512d'))))
        .addMethod("get_Size", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
        .addMethod("IndexOf", new DynWinRtMethodSig().addIn(DynWinRtType.interface(WinGuid.parse('125e7431-f678-4e8e-b670-20a9b06c512d'))).addOut(DynWinRtType.u32()).addOut(DynWinRtType.boolType()))
        .addMethod("GetMany", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addOutFill(DynWinRtType.arrayType(DynWinRtType.interface(WinGuid.parse('125e7431-f678-4e8e-b670-20a9b06c512d')))).addOut(DynWinRtType.u32()));
        const value = _IVectorView_WindowsFoundationIWwwFormUrlDecoderEntry_g58829236a97a8635Cache[prop];
        return typeof value === 'function' ? value.bind(_IVectorView_WindowsFoundationIWwwFormUrlDecoderEntry_g58829236a97a8635Cache) : value;
    }
});

let _IIterable_WindowsFoundationIWwwFormUrlDecoderEntry_gd13025e9604dbcdbCache;
const _IIterable_WindowsFoundationIWwwFormUrlDecoderEntry_gd13025e9604dbcdb = new Proxy({}, {
    get(_target, prop) {
        _IIterable_WindowsFoundationIWwwFormUrlDecoderEntry_gd13025e9604dbcdbCache ??= DynWinRtType.registerInterface(
        "IIterable_WindowsFoundationIWwwFormUrlDecoderEntry_gd13025e9604dbcdb", IID_IIterable_WindowsFoundationIWwwFormUrlDecoderEntry_gd13025e9604dbcdb)
        .addMethod("First", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('6a79e863-4300-459a-9966-cbb660963ee1'), [DynWinRtType.interface(WinGuid.parse('125e7431-f678-4e8e-b670-20a9b06c512d'))])));
        const value = _IIterable_WindowsFoundationIWwwFormUrlDecoderEntry_gd13025e9604dbcdbCache[prop];
        return typeof value === 'function' ? value.bind(_IIterable_WindowsFoundationIWwwFormUrlDecoderEntry_gd13025e9604dbcdbCache) : value;
    }
});

class WwwFormUrlDecoder {
    _obj;
    static _f_IWwwFormUrlDecoderRuntimeClassFactory;
    static f_IWwwFormUrlDecoderRuntimeClassFactory() { return WwwFormUrlDecoder._f_IWwwFormUrlDecoderRuntimeClassFactory ??= DynWinRtValue.activationFactory('Windows.Foundation.WwwFormUrlDecoder').cast(IID_IWwwFormUrlDecoderRuntimeClassFactory); }

    constructor(...args) {
        if (args.length === 1) {
            this._obj = WwwFormUrlDecoder.createWwwFormUrlDecoder(args[0])._obj;
            return;
        }
        throw new TypeError('No matching constructor for WwwFormUrlDecoder.');
    }
    static _fromNative(obj) {
        return Object.assign(Object.create(WwwFormUrlDecoder.prototype), { _obj: (__get_castProjectedValueOwned())(obj, IID_IWwwFormUrlDecoderRuntimeClass, 'WwwFormUrlDecoder') });
    }
    static _fromNativeBorrowed(obj) {
        return Object.assign(Object.create(WwwFormUrlDecoder.prototype), { _obj: (__get_castProjectedValueBorrowed())(obj, IID_IWwwFormUrlDecoderRuntimeClass, 'WwwFormUrlDecoder') });
    }
    static createWwwFormUrlDecoder(query) {
        return WwwFormUrlDecoder._fromNative(_IWwwFormUrlDecoderRuntimeClassFactory.method(6).invoke(WwwFormUrlDecoder.f_IWwwFormUrlDecoderRuntimeClassFactory(), [DynWinRtValue.hstring(query)]));
    }
    getFirstValueByName(name) {
        return _IWwwFormUrlDecoderRuntimeClass.method(6).invoke(this._obj, [DynWinRtValue.hstring(name)]).toString();
    }
    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
    getAt(index) {
        return ((v) => v.isNull() ? null : new (__get_IWwwFormUrlDecoderEntry())(v))(_IVectorView_WindowsFoundationIWwwFormUrlDecoderEntry_g58829236a97a8635.method(6).invoke(this._obj.cast(IID_IVectorView_WindowsFoundationIWwwFormUrlDecoderEntry_g58829236a97a8635), [DynWinRtValue.u32(index)]));
    }
    get size() {
        return _IVectorView_WindowsFoundationIWwwFormUrlDecoderEntry_g58829236a97a8635.method(7).invoke(this._obj.cast(IID_IVectorView_WindowsFoundationIWwwFormUrlDecoderEntry_g58829236a97a8635), []).toNumber();
    }
    getMany(startIndex, items) {
        return (() => { const _r = _IVectorView_WindowsFoundationIWwwFormUrlDecoderEntry_g58829236a97a8635.method(9).invokeAll(this._obj.cast(IID_IVectorView_WindowsFoundationIWwwFormUrlDecoderEntry_g58829236a97a8635), [DynWinRtValue.u32(startIndex), (Array.isArray(items) ? DynWinRtArray.fromObjectValues(items.map(_i => _unwrap(_i)), DynWinRtType.interface(WinGuid.parse('125e7431-f678-4e8e-b670-20a9b06c512d'))).toValue() : _unwrap(items))]); return _r[0].asArray().toValues().map(v => v.isNull() ? null : new (__get_IWwwFormUrlDecoderEntry())(v)).slice(0, _r[1].toNumber()); })();
    }
    /** Alias for {@link size}; matches Array.length / TypedArray.length. */
    get length() { return this.size; }
    /** Element at `index`. Negative indices count from the end (Array.prototype.at semantics). */
    at(index) {
        const n = this.size;
        const i = index < 0 ? n + index : index;
        if (i < 0 || i >= n) return undefined;
        return this.getAt(i);
    }
    /** Materialize as a plain JS array. */
    toArray() {
        const n = this.size;
        const out = new Array(n);
        for (let i = 0; i < n; i++) out[i] = this.getAt(i);
        return out;
    }
    *[Symbol.iterator]() {
        const n = this.size;
        for (let i = 0; i < n; i++) yield this.getAt(i);
    }
    /**
     * Return the index of `value`, or -1 if not found.
     */
    indexOf(value) {
        return (() => { const _r = _IVectorView_WindowsFoundationIWwwFormUrlDecoderEntry_g58829236a97a8635.method(8).invokeAll(this._obj.cast(IID_IVectorView_WindowsFoundationIWwwFormUrlDecoderEntry_g58829236a97a8635), [(value == null ? DynWinRtValue.nullValue() : _unwrap(value))]); return _r[1].toBool() ? _r[0].toNumber() : -1; })();
    }
    first() {
        return ((v) => v.isNull() ? null : new (__get_IIterator_WindowsFoundationIWwwFormUrlDecoderEntry_g498f64075ebd0fce())(v))(_IIterable_WindowsFoundationIWwwFormUrlDecoderEntry_gd13025e9604dbcdb.method(6).invoke(this._obj.cast(IID_IIterable_WindowsFoundationIWwwFormUrlDecoderEntry_gd13025e9604dbcdb), []));
    }
}

class IVectorView_WindowsFoundationIWwwFormUrlDecoderEntry_g58829236a97a8635 {
    _obj;

    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IVectorView_WindowsFoundationIWwwFormUrlDecoderEntry_g58829236a97a8635(obj.cast(IID_IVectorView_WindowsFoundationIWwwFormUrlDecoderEntry_g58829236a97a8635));
    }

    getAt(index) {
        return ((v) => v.isNull() ? null : new (__get_IWwwFormUrlDecoderEntry())(v))(_IVectorView_WindowsFoundationIWwwFormUrlDecoderEntry_g58829236a97a8635.method(6).invoke(this._obj, [DynWinRtValue.u32(index)]));
    }

    get size() {
        return _IVectorView_WindowsFoundationIWwwFormUrlDecoderEntry_g58829236a97a8635.method(7).invoke(this._obj, []).toNumber();
    }

    getMany(startIndex, items) {
        return (() => { const _r = _IVectorView_WindowsFoundationIWwwFormUrlDecoderEntry_g58829236a97a8635.method(9).invokeAll(this._obj, [DynWinRtValue.u32(startIndex), (Array.isArray(items) ? DynWinRtArray.fromObjectValues(items.map(_i => _unwrap(_i)), DynWinRtType.interface(WinGuid.parse('125e7431-f678-4e8e-b670-20a9b06c512d'))).toValue() : _unwrap(items))]); return _r[0].asArray().toValues().map(v => v.isNull() ? null : new (__get_IWwwFormUrlDecoderEntry())(v)).slice(0, _r[1].toNumber()); })();
    }

    /** Alias for {@link size}; matches Array.length / TypedArray.length. */
    get length() { return this.size; }

    /** Element at `index`. Negative indices count from the end (Array.prototype.at semantics). */
    at(index) {
        const n = this.size;
        const i = index < 0 ? n + index : index;
        if (i < 0 || i >= n) return undefined;
        return this.getAt(i);
    }

    /** Materialize as a plain JS array. */
    toArray() {
        const n = this.size;
        const out = new Array(n);
        for (let i = 0; i < n; i++) out[i] = this.getAt(i);
        return out;
    }

    *[Symbol.iterator]() {
        const n = this.size;
        for (let i = 0; i < n; i++) yield this.getAt(i);
    }

    /**
     * Return the index of `value`, or -1 if not found.
     */
    indexOf(value) {
        return (() => { const _r = _IVectorView_WindowsFoundationIWwwFormUrlDecoderEntry_g58829236a97a8635.method(8).invokeAll(this._obj, [(value == null ? DynWinRtValue.nullValue() : _unwrap(value))]); return _r[1].toBool() ? _r[0].toNumber() : -1; })();
    }
}

class IIterable_WindowsFoundationIWwwFormUrlDecoderEntry_gd13025e9604dbcdb {
    _obj;

    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IIterable_WindowsFoundationIWwwFormUrlDecoderEntry_gd13025e9604dbcdb(obj.cast(IID_IIterable_WindowsFoundationIWwwFormUrlDecoderEntry_gd13025e9604dbcdb));
    }

    first() {
        return ((v) => v.isNull() ? null : new (__get_IIterator_WindowsFoundationIWwwFormUrlDecoderEntry_g498f64075ebd0fce())(v))(_IIterable_WindowsFoundationIWwwFormUrlDecoderEntry_gd13025e9604dbcdb.method(6).invoke(this._obj, []));
    }

    [Symbol.iterator]() { return this.first(); }
}
exports.IID_WwwFormUrlDecoder = IID_WwwFormUrlDecoder;
exports.WwwFormUrlDecoder = WwwFormUrlDecoder;
exports.IVectorView_WindowsFoundationIWwwFormUrlDecoderEntry_g58829236a97a8635 = IVectorView_WindowsFoundationIWwwFormUrlDecoderEntry_g58829236a97a8635;
exports.IIterable_WindowsFoundationIWwwFormUrlDecoderEntry_gd13025e9604dbcdb = IIterable_WindowsFoundationIWwwFormUrlDecoderEntry_gd13025e9604dbcdb;
